### ISSUE TITLE
Sample Project?

### ISSUE THREAD

**Issue by SalmanTKhan** [davideas/FlexibleAdapter#1]
A working example would be greatly appreciated? The ExampleAdapter is not really clear since you renamed ManageLabelsAdapter to it, along with a plethora of "missing" classes associated with it. Thank you for the library.

**Comment by davideas** [comment]
Yeah I know that, I will prepare an example App and clean that class as well.

**Comment by davideas** [comment]
I think now you should be very happy :-)
The example was a thing that I wanted to make, and finally I made it.

**Comment by SalmanTKhan** [comment]
Thank you, looks like a pretty good example at that too.
