### ISSUE TITLE
Add item swipe implementation that will not require snackbar

### ISSUE THREAD

**Issue by vverbitskyy** [davideas/FlexibleAdapter#100]
Can you, please, add some other way to communicate with swiped items, cause now,
needs to inplicit call "remove" method to remove items from adapter after some delay.
Think there is good implementation like [here](https://github.com/daimajia/AndroidSwipeLayoutrl)

**Comment by davideas** [comment]
Please, see closed issue #98.

**Comment by davideas** [comment]
Another nice alternative could be https://github.com/chthai64/SwipeRevealLayout.
