### ISSUE TITLE
Whether ViewHolder can be separated from the Item？

### ISSUE THREAD

**Issue by JakeWoki** [davideas/FlexibleAdapter#101]

**Comment by davideas** [comment]
Hello @JakeWoki, I use IHolder item interface in one of my personal project, if you need to Serialize the object you can do it on your model object.
If you mean that you want to keep your model object separated from the ViewHolder, than IHolder is the solution.
You can check documentation (I still need to complete, I know), but something on it there is already.
In the demo App also you can find 2 examples of IHolder under package `eu.davidea.samples.flexibleadapter.showcase`

**Comment by JakeWoki** [comment]
But it's not really separate.If use[GsonFormat](https://github.com/zzz40500/GsonFormat),I hope Item only Item

**Comment by davideas** [comment]
@JakeWoki, `IHolder<Model>` _adapterItem_ has internally the model object of your type. with getModel() is returned the bean of your type.

**Comment by JakeWoki** [comment]
@davideas thanks

**Comment by JakeWoki** [comment]
@davideas Today, I try to use,but I still would not use.Help me

**Comment by davideas** [comment]
@JakeWoki might the documentation helped you?
https://github.com/davideas/FlexibleAdapter/wiki/5.x-%7C-Item-Interfaces#iholder

**Note:** `equals()` and `filter()` methods should take into account the fields of Model class.

**Comment by JakeWoki** [comment]
`public class Test {

    private String id;
    private String title;
    private String subtitle;

    public Test(String id) {
        this.id = id;
    }

    @Override
    public boolean equals(Object inObject) {
        if (inObject instanceof Test) {
            Test inItem = (Test) inObject;
            return this.id.equals(inItem.id);
        }
        return false;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getSubtitle() {
        return subtitle;
    }

    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle;
    }

    @Override
    public String toString() {
        return "id=" + id +
                ", title=" + title;
    }

}`

`public class TestHolder extends FlexibleItemHolderExample<Test> {

    public TestHolder(Test modelData, HeaderItem header) {
        super(modelData, header);
    }

    @Override
    public void bindViewHolder(final FlexibleAdapter adapter, ViewHolder holder, int position, List payloads) {
        holder.titleTextView.setText(modelData.getTitle());
    }

}`


`public class TestAdapter extends FlexibleAdapter<TestHolder> {

    public TestAdapter(@NonNull List<TestHolder> items, Activity activity) {
        super(items, activity);
    }

}`


`public class TestExample extends AbstractFragment
        implements FlexibleAdapter.OnItemClickListener {

    TestAdapter mAdapter;

    @Override
    public void onActivityCreated(Bundle savedInstanceState) {
        super.onActivityCreated(savedInstanceState);
        //Settings for FlipView
        FlipView.resetLayoutAnimationDelay(true, 1000L);

        //Create New Database and Initialize RecyclerView
        DatabaseService.getInstance().createEndlessDatabase();
        initializeRecyclerView(savedInstanceState);

        //Settings for FlipView
        FlipView.stopLayoutAnimation();
    }

    @SuppressWarnings({"ConstantConditions", "NullableProblems"})
    private void initializeRecyclerView(Bundle savedInstanceState) {
        List<TestHolder> list = new ArrayList<>();
        for (int i=0; i<10; i++) {
            Test test = new Test(""+i);
            test.setTitle("qq"+i);
            test.setSubtitle("ww"+i);
            list.add(new TestHolder(test, null));
        }
        mAdapter = new TestAdapter(list, getActivity());
        mAdapter.setMode(SelectableAdapter.MODE_SINGLE);

        //Experimenting NEW features (v5.0.0)
        mAdapter.setAnimationOnScrolling(true);
        mAdapter.setAnimationOnReverseScrolling(true);
        mRecyclerView = (RecyclerView) getView().findViewById(R.id.recycler_view);
        mRecyclerView.setLayoutManager(createNewLinearLayoutManager());
        mRecyclerView.setAdapter(mAdapter);
        mRecyclerView.setHasFixedSize(true); //Size of RV will not change
        mRecyclerView.setItemAnimator(new DefaultItemAnimator() {
            @Override
            public boolean canReuseUpdatedViewHolder(RecyclerView.ViewHolder viewHolder) {
                //NOTE: This allows to receive Payload objects on notifyItemChanged called by the Adapter!!!
                return true;
            }
        });
        //mRecyclerView.setItemAnimator(new SlideInRightAnimator());
        mRecyclerView.addItemDecoration(new DividerItemDecoration(getActivity(), R.drawable.divider).setDrawOver(true));
        mRecyclerView.postDelayed(new Runnable() {
            @Override
            public void run() {
                Snackbar.make(getView(), "Selection MODE_SINGLE is enabled", Snackbar.LENGTH_SHORT).show();
            }
        }, 1500L);
        //Add FastScroll to the RecyclerView, after the Adapter has been attached the RecyclerView!!!
        mAdapter.setFastScroller((FastScroller) getActivity().findViewById(R.id.fast_scroller),
                Utils.getColorAccent(getActivity()), (MainActivity) getActivity());

        SwipeRefreshLayout swipeRefreshLayout = (SwipeRefreshLayout) getView().findViewById(R.id.swipeRefreshLayout);
        mListener.onFragmentChange(swipeRefreshLayout, mRecyclerView, SelectableAdapter.MODE_SINGLE);
    }

    @Override
    public boolean onItemClick(int position) {
        return false;
    }

}`

Example

**Comment by davideas** [comment]
@JakeWoki yes that's good, you can even make `FlexibleItemHolderExample` abstract. 
It depends if you want another level of abstraction so you can use another `Test2` model class extending the same abstract class.
Also you can assign the `FlexibleItemHolderExample` to the `TestAdapter`, then you need something to distinguish `Test` from `Test2` model classes, when you `getItem(position).getModel()`.

**Comment by JakeWoki** [comment]
@davideas sometime,Test is a List.How add List<Test> to List<TestHolder> or TestAdapter?don't use for()

**Comment by davideas** [comment]
@JakeWoki, if Test represent a list it means that it represent a group, so it has a name. In this case you can use `AbstractExpandableItem` or `AbstractExpandableHeaderItem` which contain a list of subItems. If you don't want expandable feature you can disable it in 2 ways:
- `setEnabled(false)` in the constructor of this item, all clicks are disabled too!
- override the method `isViewExpandableOnClick()`, collapsing remain disabled but clicks and long clicks work.

**Comment by JakeWoki** [comment]
That was not what I meant. See the example above. If has a group `List<Test>`,  don't use for() how to add the group inside `List<TestHolder>` or TestAdapter?It has nothing to do with expandable

**Comment by davideas** [comment]
Ahh ok, this has something to do with Java, you need a converter **however**, where you must create the `TestHolder` object and you are obliged to use for().

- In Java7 you can create a private function `toTestHolder()` to convert the Test to TestHolder in a cycle for().
- In Java8 you still need that function but you can do:
``` java
List<Test> models = get list from database;
List<TestHolder> holders = models.stream().map(this::toTestHolder).collect(Collectors.toList());
```

**Comment by JakeWoki** [comment]
@davideas no,no,no.
I hope do like this:

`public abstract class SimpleBaseAdapter<T> extends BaseAdapter {

    protected Context mContext;

    protected List<T> mList;

    public SimpleBaseAdapter(Context mContext) {
        this.mContext = mContext;
        mList = new ArrayList<>();
    }


    @Override
    public int getCount() {
        return mList.size();
    }

    @Override
    public T getItem(int position) {
        return mList.get(position);
    }

    @Override
    public long getItemId(int position) {
        return position;
    }

    public void addAll(List<T> elem) {
        mList.addAll(elem);
        notifyDataSetChanged();
    }

    public List<T> getList() {
        return mList;
    }

    public void remove(T elem) {
        mList.remove(elem);
        notifyDataSetChanged();
    }

    public void remove(int index) {
        mList.remove(index);
        notifyDataSetChanged();
    }

    public void replaceAll(List<T> elem) {
        mList.clear();
        mList.addAll(elem);
        notifyDataSetChanged();
    }

    public void add(T elem) {
        mList.add(elem);
        notifyDataSetChanged();
    }

    public void add(int index, T elem) {
        mList.add(index, elem);
        notifyDataSetChanged();
    }

    public void clear() {
        mList.clear();
        notifyDataSetChanged();
    }

    /**
     * 
     * @param position
     * @param convertView
     * @param holder
     * @return
     */
    public abstract View getView(int position, View convertView, ViewHolder holder);


    /**
     *
     * @return
     */
    public abstract int getItemResource();

    @SuppressWarnings("unchecked")
    @Override
    public View getView(int position, View convertView, ViewGroup parent) {
        ViewHolder holder;
        if (null == convertView) {
            convertView = getConvertView(mContext, parent);
            holder = new ViewHolder(convertView);
            convertView.setTag(holder);
        } else {
            holder = (ViewHolder) convertView.getTag();
        }
        return getView(position, convertView, holder);
    }

    public View getConvertView(Context mContext, ViewGroup parent) {
        return View.inflate(mContext, getItemResource(), null);
    }


    public static class ViewHolder {
        private SparseArray<View> views = new SparseArray<View>();
        private View convertView;

        public ViewHolder(View convertView) {
            this.convertView = convertView;
        }

        @SuppressWarnings("unchecked")
        public <T extends View> T getView(int resId) {
            View v = views.get(resId);
            if (null == v) {
                v = convertView.findViewById(resId);
                views.put(resId, v);
            }
            return (T) v;
        }
    }

}`

**Comment by davideas** [comment]
@JakeWoki, what's that?
Forget BaseAdapter, you have RecyclerView and my library as Adapter. Why you posted it?

**Comment by JakeWoki** [comment]
@davideas I know.I said I hope do like that for use `list<T>`

**Comment by davideas** [comment]
I still don't see the relevant code and the idea you want to implement.
Explain me better, so maybe I can help you.

**Comment by JakeWoki** [comment]
@davideas 
`public class ViewHolder extends FlexibleViewHolder {

    public ViewHolder(View view, FlexibleAdapter adapter) {
        super(view, adapter);
        ButterKnife.bind(this, view);
        view.setTag(this);
    }

}`
`public abstract class RecyclerBaseHolder<Model, VH extends ViewHolder> extends AbstractFlexibleItem<VH>
		implements IFilterable, IHolder<Model> {
	/**
	 * Your complex data model object
	 */
	Model modelData;

	public RecyclerBaseHolder(Model modelData) {
		this.modelData = modelData;
	}

	@Override
	public Model getModel() {
		return modelData;
	}

	@Override
	public boolean equals(Object o) {
		if (modelData != null && o instanceof RecyclerBaseHolder) {
			final RecyclerBaseHolder inItem = (RecyclerBaseHolder) o;
			return modelData.equals(inItem.getModel());
		}
		return false;
	}

	@Override
	public VH createViewHolder(FlexibleAdapter adapter, LayoutInflater inflater, ViewGroup parent) {
		return super.createViewHolder(adapter, inflater, parent);
	}

	@Override
	public void bindViewHolder(final FlexibleAdapter adapter, VH holder, int position, List payloads) {
	}

	@Override
	public boolean filter(String constraint) {
		return true;
	}

}`
`public abstract class BaseRecyclerAdapter<M, H extends RecyclerBaseHolder<M, V>, V extends ViewHolder> extends FlexibleAdapter<H> {

    protected Context context;
    private List<M> models;

    public BaseRecyclerAdapter(@NonNull Context context, @NonNull List<M> models) {
        super(new ArrayList<H>(models.size()));
        this.context = context;
        this.models = models;
    }

    @Override
    public void onBindViewHolder(final RecyclerView.ViewHolder holder, final int position, final List payloads) {
        //When user scrolls, this line binds the correct selection status
        holder.itemView.setActivated(isSelected(position));
        //Bind the item
        H item = createHolder(context, getModel(position));
        if (item != null) {
            holder.itemView.setEnabled(item.isEnabled());
            item.bindViewHolder(this, (V) holder, position, payloads);
        }
        //Endless Scroll
        onLoadMore(position);
    }

    protected abstract H createHolder(@NonNull Context context, @Nullable M model);

    public M getModel(@IntRange(from = 0) int position) {
        if (position < 0 || position >= models.size()) return null;
        return models.get(position);
    }

    public void addAll(List<M> elem) {
        models.addAll(new ArrayList<>(elem));
        updateDataSet(new ArrayList<H>(models.size()));
        notifyDataSetChanged();
    }

    public List<M> getList() {
        return models;
    }

    public void remove(M elem) {
        models.remove(elem);
        updateData();
    }

    public void remove(int index) {
        models.remove(index);
        updateData();
    }

    public void replaceAll(List<M> elem) {
        models.clear();
        models.addAll(new ArrayList<>(elem));
        updateData();
    }

    public void add(M elem) {
        models.add(elem);
        updateData();
    }

    public void add(int index, M elem) {
        models.add(index, elem);
        updateData();
    }

    public void clear() {
        models.clear();
        updateData();
    }

    private void updateData() {
        final List<H> list = new ArrayList<>();
        for (M model : models) {
            H item = createHolder(context, model);
            list.add(item);
        }
        updateDataSet(list);
    }

}`
`public abstract class BaseFragment extends Fragment {

    public abstract int getLayoutResource();

    private Unbinder unbinder;

    @Override
    public final View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        int resLayoutId = getLayoutResource();
        if (resLayoutId != 0) {
            View view = inflater.inflate(resLayoutId, container, false);
            unbinder = ButterKnife.bind(this, view);
            return view;
        }
        return null;
    }


    @Override
    public void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
    }

    @Override
    public void onActivityCreated(@Nullable Bundle savedInstanceState) {
        super.onActivityCreated(savedInstanceState);
    }


    @Override
    public void onDestroy() {
        if (unbinder != null) {
            unbinder.unbind();
        }
        super.onDestroy();
    }

    protected boolean isUsable() {
        return getActivity() != null && !getActivity().isFinishing();
    }

}`
`public abstract class BaseRecyclerViewFragment<M, B extends BaseRecyclerAdapter> extends BaseFragment implements SwipeRefreshLayout.OnRefreshListener {

    public static final String TAG = "BaseRecyclerViewFragment";
    protected static final String ARG_COLUMN_COUNT = "column_count";

    public static final int[] swipColorResIds = new int[]{R.color.colorAccent};

    protected int mColumnCount = 2;
    @Nullable
    @BindView(R.id.swiprefresh)
    protected SwipeRefreshLayout swiprefresh;
    @BindView(R.id.recyclerView)
    protected RecyclerView recyclerView;
    @BindView(android.R.id.empty)
    protected EmptyView emptyView;
    @BindView(R.id.progressBar)
    protected View loading;

    private List<M> items = new ArrayList<>();

    protected B adapter;

    protected boolean recyclerShown;

    @Override
    public int getLayoutResource() {
        return R.layout.fragment_recyclerview;
    }

    @Override
    public void onActivityCreated(Bundle savedInstanceState) {
        super.onActivityCreated(savedInstanceState);
        if (swiprefresh != null) {
            swiprefresh.setColorSchemeResources(swipColorResIds);
            swiprefresh.setOnRefreshListener(this);
        }
        if (!items.isEmpty()) {
            setListShown(true, false);
        } else {
            if (isLoadData()) {
                loadData();
            }
        }
    }

    @Override
    public void onSaveInstanceState(Bundle outState) {
        adapter.onSaveInstanceState(outState);
        super.onSaveInstanceState(outState);
    }

    @Override
    public void onViewStateRestored(@Nullable Bundle savedInstanceState) {
        super.onViewStateRestored(savedInstanceState);
        if (savedInstanceState != null && adapter != null) {
            adapter.onRestoreInstanceState(savedInstanceState);
        }
    }

    @Override
    public void onDestroyView() {
        recyclerShown = false;
        super.onDestroyView();
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        initializeRecyclerView(savedInstanceState);
    }

    protected void initializeRecyclerView(Bundle savedInstanceState) {
        adapter = createAdapter();
        recyclerView.setLayoutManager(createNewLinearLayoutManager());
        recyclerView.setAdapter(adapter);
        recyclerView.setHasFixedSize(true);
        recyclerView.addItemDecoration(new DividerItemDecoration(getActivity(), R.drawable.divider).setDrawOver(true));
    }

    protected boolean isLoadData() {
        return true;
    }

    protected abstract void loadData();

    @Override
    public void onRefresh() {
        loadData();
    }

    public void refresh() {
        refresh(null);
    }

    private void refresh(final Bundle args) {
        if (!isUsable())
            return;
        loadData();
    }

    /**
     * @deprecated
     * @param exception
     * @param message
     * @param items
     */
    protected void onLoadFinished(Exception exception, String message, List<M> items) {
        if (!isUsable())
            return;
        hide(loading);
        if (exception != null) {
            showError(message);
            showList();
            return;
        }

        onLoadFinished(items);
    }

    protected void onLoadFinished(List<M> items) {
        this.items = items;
        adapter.replaceAll(items);
        hide(loading);
        showList();
    }

    protected B createAdapter() {
        B wrapped = createAdapter(items);
        return wrapped;
    }

    @NonNull
    protected abstract B createAdapter(final List<M> items);

    protected void showError(String message) {
        refreshFinish();
        ToastUtils.show(getActivity(), message);
    }

    protected void refreshFinish() {
        hide(loading);
        setRefreshing(false);
    }

    protected void showList() {
        if (swiprefresh != null)
            swiprefresh.setRefreshing(false);
        setListShown(true, isResumed());
    }

    protected void refreshWithSwipe() {
        items.clear();
    }

    protected void refreshWithProgress() {
        items.clear();
        setRecyclerShown(false);
        refresh();
    }

    protected void refreshWithDialog() {
        items.clear();
        show(loading);
        refresh();
    }

    public final RecyclerView getListView() {
        return recyclerView;
    }

    protected B getListAdapter() {
        return adapter;
    }

    protected BaseRecyclerViewFragment<M, B> notifyDataSetChanged() {
        if (getListAdapter() != null)
            getListAdapter().notifyDataSetChanged();
        return this;
    }

    protected BaseRecyclerViewFragment<M, B> setRefreshing(boolean refreshing) {
        return this;
    }

    protected BaseRecyclerViewFragment<M, B> setListAdapter(final RecyclerView.Adapter adapter) {
        if (recyclerView != null)
            recyclerView.setAdapter(adapter);
        return this;
    }

    protected BaseRecyclerViewFragment<M, B> fadeIn(final View view, final boolean animate) {
        if (view != null)
            if (animate)
                view.startAnimation(AnimationUtils.loadAnimation(getActivity(),
                        android.R.anim.fade_in));
            else
                view.clearAnimation();
        return this;
    }

    protected BaseRecyclerViewFragment<M, B> show(final View view) {
        view.setVisibility(View.VISIBLE);
        return this;
    }

    protected BaseRecyclerViewFragment<M, B> hide(final View view) {
        view.setVisibility(View.GONE);
        return this;
    }

    protected void hide() {
        if (emptyView != null) {
            hide(emptyView);
        }
    }

    public BaseRecyclerViewFragment<M, B> setEnabled(boolean enabled) {
        return this;
    }

    public BaseRecyclerViewFragment<M, B> setRecyclerShown(final boolean shown) {
        return setListShown(shown, true);
    }

    public BaseRecyclerViewFragment<M, B> setListShown(final boolean shown,
                                               final boolean animate) {
        if (!isUsable())
            return this;

        if (shown == recyclerShown) {
            if (shown)
                if (items.isEmpty())
                    hide(recyclerView).show(emptyView);
                else
                    hide(emptyView).show(recyclerView);
            return this;
        }

        recyclerShown = shown;

        if (shown)
            if (!items.isEmpty())
                hide(loading).hide(emptyView).fadeIn(recyclerView, animate)
                        .show(recyclerView);
            else
                hide(loading).hide(recyclerView).fadeIn(emptyView, animate).show(emptyView);
        else
            hide(recyclerView).hide(emptyView).fadeIn(loading, animate)
                    .show(loading);

        return this;
    }

    protected LinearLayoutManager createNewLinearLayoutManager() {
        return new SmoothScrollLinearLayoutManager(getActivity());
    }

    protected GridLayoutManager createNewGridLayoutManager() {
        return new SmoothScrollGridLayoutManager(getActivity(), mColumnCount);
    }

    protected StaggeredGridLayoutManager createNewStaggeredGridLayoutManager() {
        return new StaggeredGridLayoutManager(mColumnCount, StaggeredGridLayoutManager.VERTICAL);
    }

}`
`public class DemoAdapter extends BaseRecyclerAdapter<ViolateModel, DemoAdapter.DemoHolder, DemoAdapter.DemoHolder.ViewH> {

    public DemoAdapter(@NonNull Context context, @NonNull List<ViolateModel> items) {
        super(context, items);
    }

    @Override
    protected DemoHolder createHolder(@NonNull Context context, @Nullable ViolateModel model) {
        return new DemoHolder(context, model);
    }

    public static final class DemoHolder extends RecyclerBaseHolder<Test, DemoHolder.ViewH> {
        Context context;
        public DemoHolder(Context context, ViolateModel modelData) {
            super(modelData);
            this.context = context;
        }

        @Override
        public ViewH createViewHolder(FlexibleAdapter adapter, LayoutInflater inflater, ViewGroup parent) {
            return new ViewH(inflater.inflate(getLayoutRes(), parent, false), adapter);
        }

        @Override
        public void bindViewHolder(final FlexibleAdapter adapter, ViewH holder, int position, List payloads) {
            holder.title.setText(getModel().getTitle());
        }

        @Override
        public int getLayoutRes() {
            return R.layout.recycler_expandable_item;
        }

        public static final class ViewH extends ViewHolder {
            @BindView(R.id.title)
            TextView title;
            public ViewH(View view, FlexibleAdapter adapter) {
                super(view, adapter);
            }
        }
    }

}`
`public class DemoFragment extends BaseRecyclerViewFragment<Test, DemoAdapter> {

    @Override
    protected DemoAdapter createAdapter(List<Test> items) {
        return new DemoAdapter(getActivity(), items);
    }

    @Override
    protected void loadData() {
        final List<Test> list = new ArrayList<>();
        for (int i=0; i<10; i++) {
            final Test test = new Test(""+i);
            test.setTitle("qq"+i);
            test.setSubtitle("ww"+i);
            list.add(test);
        }
        onLoadFinished(list);
    }

}`
============================
 if has a better suggestion?in particular,this method:
BaseRecyclerAdapter:
`private void updateData() {
        final List<H> list = new ArrayList<>();
        for (M model : models) {
            H item = createHolder(context, model);
            list.add(item);
        }
        updateDataSet(list);
    }`

**Comment by davideas** [comment]
You can create the list of List<H> instead of creating the list of List<Model> so you can avoid the List conversion.

**Comment by JakeWoki** [comment]
@davideas Can you give an example?Thanks

**Comment by davideas** [comment]
Well, I cannot give you an example, it depends how you get/compose initially that list. If you already have the list of models, you have to make the conversion anyway.
What's the problem to not scan the list? how many items you have usually?

**Comment by JakeWoki** [comment]
api return List, it may have a lot of. If getItem/mItems.size()(FlexibleAdapter) can be constructed, i think List don't need conversion.

**Comment by davideas** [comment]
To the Adapter you need to pass a list of type `IFlexible`, or you extend/implement the model class from from API with that type directly in the repository layer) or you box it by creating a new List for the presentation layer. I do the last option because it is more organized and decoupled.

**Comment by JakeWoki** [comment]
@davideas page load, conversion doesn‘t necessarily affect performance

**Comment by davideas** [comment]
So I do not see any problem having list conversion.
