### ISSUE TITLE
Using dev branch with lastest SNAPSHOT

### ISSUE THREAD

**Issue by carmas123** [davideas/FlexibleAdapter#105]
Ciao Davide come faccio ad utilizzare l'ultimo snapshot con Gradle?

**Comment by davideas** [comment]
Ciao, nel task #39, che lascio aperto per questa lunga fase di sviluppo, c'è scritto tutto. Leggi il primo post, mentre le release note sono nell'ultimo messaggio.

Semplicemente quando rilascio questa speciale versione, non cambio numero, non c'è numero, sono fatte di frequente per distribuire le ultimissime modifiche e per dare maggior stabilità possibile nel più breve tempo possibile. Lo sviluppatore quindi non deve cambiare numero di versione, ma riceve automaticamente un aggiornamento quando il tuo Gradle aggiorna la sessione e la cache, ogni 24 ore.
Quando scrivo in quel task allora una nuova SNAPSHOT build è pronta, ma non è ancora matura per una [pre-]release.

**Comment by carmas123** [comment]
Io avevo gia provato con:
```
    compile ('eu.davidea:flexible-adapter:5.0.0-SNAPSHOT') {
        changing = true;
    }

```

ma mi da sempre 
Error:(104, 14) Failed to resolve: eu.davidea:flexible-adapter:5.0.0-SNAPSHOT

forse non è sul mavenCentral?

**Comment by davideas** [comment]
Infatti no, le SNAPSHOT sono su 

```
maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
```

**Comment by carmas123** [comment]
Tutto ok grazie, risolto
