### ISSUE TITLE
DividerItemDecorator should be configured to be drawn OVER or UNDERNEATH the items

### ISSUE THREAD

**Issue by vverbitskyy** [davideas/FlexibleAdapter#106]
I don't know, maybe I am not right, but even in yours examples, item decorator is visible, only if
we using ?attr/selectableItemBackground for item. But if I add simple (white) color, divider become invisible after items add to view.

**Comment by davideas** [comment]
@vverbitskyy the reason because now it's drawn below, it's because when dragging, decorator remains on the top and the items shift below the decorator, I should add a parameter to draw on the top or normal as now.

It's an improvement very easy to do, I will it now.

**Comment by vverbitskyy** [comment]
good. thanks
