### ISSUE TITLE
Issue with smooth scrolling

### ISSUE THREAD

**Issue by vverbitskyy** [davideas/FlexibleAdapter#108]
I saw an issue, with smooth scrolling of linear layout manager.
Say I need to scroll from 15th element to 2nd.
Issue is that sometimes, smoothScrollToPosition scrolls to bottom instead of top

**Comment by davideas** [comment]
This is a known issue by me, but it depends by the current animations on going, I can try to increase the time of the delay, until now it was fine.

**Comment by davideas** [comment]
I thought it was my autoscroll, I've read wrong.
@vverbitskyy, please delay the action of the autoscroll if it is in combination of a recalculation and animation done by the LayoutManager.

**Comment by vverbitskyy** [comment]
Thanks. It is working well after adding delay before scrolling
