### ISSUE TITLE
Bug in highlightText

### ISSUE THREAD

**Issue by carmas123** [davideas/FlexibleAdapter#112]
Into Utils.java highlight find index of "constraint" into a lowercase string but if the contraint is uppercase it doesn't work!

`int i = originalText.toLowerCase(Locale.getDefault()).indexOf(constraint);`

must become

`int i = originalText.toLowerCase(Locale.getDefault()).indexOf(constraint.toLowerCase(Locale.getDefault()));`

regards.

**Comment by davideas** [comment]
Thanks @carmas123, yes it's doesn't work if NOT used in combination with this Adapter.
If you use `getSearchText()` from this Adapter, the `searchText` is already lowered by `setSearchText()`. That's why it works.

But yes, I will fix it.

**Comment by carmas123** [comment]
I've found another bug into `highlightText`
Please add a check if `originalText` is null before create a Spannable otherwise I got an exception or add @NotNull annotation to originalText parameter.
