### ISSUE TITLE
[Help] Add sub item to the end of expandable item programmatically

### ISSUE THREAD

**Issue by r0b0t3d** [davideas/FlexibleAdapter#118]
Hi @davideas,

This library is wonderful. I'm trying to use it in my app.
I got some problem when implement and expandable list.

__HeaderItem__
```java
public class HeaderItem extends AbstractExpandableHeaderItem<HeaderItem.HeaderViewHolder, ChildItem> {
    private String id;

    public HeaderItem(String id) {
        this.id = id;

        setHidden(false);
        setExpanded(true);
        setSelectable(false);
    }

    @Override
    public boolean equals(Object inObject) {
        if (inObject instanceof HeaderItem) {
            HeaderItem inItem = (HeaderItem) inObject;
            return this.getId().equals(inItem.getId());
        }
        return false;
    }
}
```
__ChildItem__
```java
public class ChildItem extends AbstractSectionableItem<ChildItem.PlaceItemViewHolder, HeaderItem> {
    public ChildItem(HeaderItem header) {
        super(header);
    }

   static class PlaceItemViewHolder extends FlexibleViewHolder implements {
        public PlaceItemViewHolder(View view, FlexibleAdapter adapter) {
            super(view, adapter);
        }

        public void onButtonClick(View view) {
            // Add new child to the end of header
        }
    }
}
```
In first initialization, I created 1 header and 1 child.
In the view holder of child item. I would like to add new child to header when clicking on the button.
I tried many ways but can't archive this.

Please help!

**Comment by davideas** [comment]
Hello @r0b0t3d, I would like understand if you need help for the Adapter methods to call or how to put a callback responsible in adding new items or both.

I understood that you don't need item click listener. I think it's better to delegate the adding to the Activity/Fragment, in this case it's better to create a custom interface (callback) named `OnChildAddListener` with `addChild(headerObject?)` to call from inside the `onButtonClick()`, you can have the instance `mOnChildAddListener` in your custom Adapter.
``` java
static class PlaceItemViewHolder extends FlexibleViewHolder {

    private CustomAdapter mAdapter;

    public PlaceItemViewHolder(View view, CustomAdapter adapter) {
        super(view, adapter);
    }

    public void onButtonClick(View view) {
        // Add new child to the end of header
        mAdapter.mOnChildAddListener.addChild(
    }
}
```
Activity will implement the method interface. Here you call `mAdapter.addSubItem(parentPosition, subPosition, item)`. The effect of adding is performed if the expandable item is expanded, If you need more control, there are more _addSubItem methods_.
Actually there are many solutions to identify the correct subPosition, this is just one:
``` java
public void addChild(IExpandable header) {
    ChildItem childItem = ...
    header.addSubItem(childItem);
    mAdapter.addSubItem(mAdapter.getGlobalPositionOf(header),
            header.getSubItemPosition(childItem),
            childItem);
}
```
Another one is to calculate the position with a `Comparator` object, then call the appropriate adapter methods for sections.

In the future I will try to simply all this.
_Expandable_ items born before the _Headers and Sections_ and now they look similar.

**Comment by r0b0t3d** [comment]
Thanks @davideas, 

I can solve my problem with this method
```java
public void addChild(AbstractExpandableHeaderItem header) {
    ChildItem childItem = ...
    //Add the child item to the end of the section
    //Note: you don't need this if childItem is already part of the sublist
    header.addSubItem(childItem);
    //Synchronize the Adapter
    mAdapter.addSubItem(mAdapter.getGlobalPositionOf(header),
            header.getSubItemPosition(childItem),
            childItem);
}
```
I was confused by the object calls:
```java
child.setHeader(header);
header.adSubItem(child);
```
Does it cause a reference loop here?

**Comment by davideas** [comment]
@r0b0t3d, actually the instances of these objects are referenced into each others, but there's no loop because inside those methods, no calls to the other method is done.

We need a list of subItems because, when we collapse the section, their instances have to exist somewhere because when expansions occurs the Adapter picks them up from that list.
And the child needs the header instance otherwise we loose the information of which object is the parent, without it, it doesn't work.

Glad I helped you.
