### ISSUE TITLE
[5.0.0-b7] Issue with a sticky headers

### ISSUE THREAD

**Issue by vverbitskyy** [davideas/FlexibleAdapter#119]
Hey @davideas . Latest beta version is very good. But today, I have an issue with sticky headers.
I used new mechanism
```java
public CommentsHeaderViewHolder(View view, FlexibleAdapter adapter) {
            super(view, adapter, true);
        }
```
In my app, I have 1 header and many items below it.
So when header shown at the top of the screen (become sticky), I am scrolling first item below header in the way, that half of an item is below header and half of the item is behind header, I an trying to remove it.
The issue is, when item become removed, an item after it gain it's own copy of header. So i see 2 headers (on top of the screen and at the first item), but when I scroll up to the top header, it dismissing and gets normal behaviour.

**Comment by davideas** [comment]
I tried in the demo app (Headers and Section), if i did correctly the steps (put the item half behind the header, deleting this item) i don't see any double header. How can I reproduce it?

**Comment by Stratosfionda** [comment]
I've had the same issue and I solved my problem, so maybe you can try this solution.
In recycler_example_header_item.xml I've had a FrameLayout with this dimensions:

`android:layout_width="match_parent"
	android:layout_height="wrap_content"`

since I've changed my height to a fixed size my problem was solved!

**Comment by davideas** [comment]
@Stratosfionda could you please verify that with the latest Snapshot release everything works fine with `wrap_content`?

@vverbitskyy, can you please explain better your situation of duplicated headers? In the adapter, headers are not added when sectionable items are removed... You can enable logs and evaluate why header is displayed again.

**Comment by Stratosfionda** [comment]
I've used this in my gradle:
`compile 'eu.davidea:flexible-adapter:5.0.0-b7'
   compile 'eu.davidea:flexible-adapter:5.0.0-SNAPSHOT'`
but nothing changed. It's not possible to use `wrap_content` instead of a fixed height.

**Comment by davideas** [comment]
@Stratosfionda, I do not see any problems with `wrap_content` if you rotate it. So it's ok.
