### ISSUE TITLE
Populate list of items

### ISSUE THREAD

**Issue by danielpassos** [davideas/FlexibleAdapter#12]
It is not so clear only looking for the API or reading the wiki, you need populate the list of items in `FlexibleAdapter` using the method `filterItems`. If you don't do that you will get a RuntimeException.

IMHO populate the list of items should be a construction responsabilite. Wdyt?.

**Comment by davideas** [comment]
@danielpassos how do you get RuntimeException? In my example if I remove the call from _updateDataset_ (the only point where is called) it simply doesn't filter anymore.

_filterItems_ is a new function, but it's an option for the developer to call it if he wants to use the search, but being _protected_ it cannot be called from the Activity and it must be called from the adapter implementation.

You also say that the construction should accept the list and assign it to _mItems_?

**Comment by danielpassos** [comment]
> how do you get RuntimeException? In my example if I remove the call from updateDataset (the only point where is called) it simply doesn't filter anymore.

I mean if you don't call `updateDataset` nor `filterItems` you got a NPE. I'll create a new blank project to show you the problem.

> You also say that the constructor should accept the list and assign it to mItems?

Yes. I think it's more natural/intuitive/commons for developer. In 100% of adapters, we pass the list of data in constructor. It make sure we always will have the data set

**Comment by davideas** [comment]
The reason the constructor doesn't accept the list, it's that _updateDataset_ is called often in the Activity, so it's nice to centralize the point where the data is loaded and I've identified that method.
I can try but I need some time to apply the changes in a convenient way.

PS. Better if you keep tabulation to indent the code.

**Comment by davideas** [comment]
For the moment I added a constructor that accept the list and initialize _mItems_.
Then, it's always the developer that should call _super(List)_ or still initialize _mItems_ by himself in his Adapter implementation.
