### ISSUE TITLE
can i use GridLayoutManager to make stickyheader ?

### ISSUE THREAD

**Issue by 54binge** [davideas/FlexibleAdapter#129]
hi, @davideas ,is it must set StaggeredGridLayoutManager to make header sticky?

**Comment by davideas** [comment]
No @54binge, you can use all layouts.

**Comment by 54binge** [comment]
@davideas 
when i use GridLayoutManager header width become same with normal item,just like
![20160702144456](https://cloud.githubusercontent.com/assets/4814206/16538916/542fa504-4064-11e6-8990-b8c55faee343.png)

**Comment by davideas** [comment]
You have to set the colspan for the viewtype header. See the example App for the GridLayout.

**Comment by 54binge** [comment]
Resolved, Sorry to bother you on the weekend,thank you very much!
