### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by danielpassos** [davideas/FlexibleAdapter#13]
The project need to have some unit tests to help us to refactor/introduce new features.

**Comment by davideas** [comment]
@danielpassos, maybe, if you desire to collaborate, I will ask to you to add unit tests :-) but not now: let me first merge and commit changes in dev branch.
It will be interesting.

**Comment by danielpassos** [comment]
Sure. it's in my queue

**Comment by davideas** [comment]
@danielpassos, do you want to add unit tests in 4.2 or in 5.0?
Because I think 4.2 is ready to be published as it is in _dev_ branch.

**Comment by danielpassos** [comment]
I've started that, but I think `5.0` is better :)

**Comment by davideas** [comment]
Many unit tests have been added, even if some features still don't have.
However, I can now consider closed this issue.
