### ISSUE TITLE
Can i remove all the items under one section by passing position or an IHeader instance ?

### ISSUE THREAD

**Issue by naveenvenkannagari** [davideas/FlexibleAdapter#132]
I'm using the FlexibleAdapter to show sectioned data. Initially I have 2 sections, and on scroll, I'm making a network call after which I need to add some data in the middle. Is it possible to do that? or remove my last section including the header and items.

**Comment by davideas** [comment]
Well, no direct method to delete items in a section, I can add a method to return the item positions in a section, that is missing. For now you have to do:

``` java
adapter.setPermanentDelete(true);
List<ISectionable> list = adapter.getSectionItems(IHeader);
for (ISectionable item : list) {
	int position = adapter.getGlobalPositionOf(item);
	adapter.removeitem(position);
}
```
After the new method you can change with the following (but i will have to test it and publish):
``` java
adapter.removeitems(adapter.getSectionItemPositions(IHeader));
```

If instead you have created sections with Expandable that is much easier: you just delete the header item, it will be collapsed and all items will be then automatically removed.

_That's why (one of the reason) I suggested to use Expandables in the documentation for adding/removal as use case._
