### ISSUE TITLE
NullPointer when filtering list to empty

### ISSUE THREAD

**Issue by cordeveloper** [davideas/FlexibleAdapter#135]
After entering a filter to my list which removes all views, I hit the following exception:

Attempt to invoke interface method 'void eu.davidea.flexibleadapter.FlexibleAdapter$OnUpdateListener.onUpdateEmptyView(int)' on a null object reference

I believe this is just an issue of operator precedence; we need to add parentheses around the or statement here:

```
        if (mUpdateListener != null &&
                (initialCount == 0 && getItemCount() > 0) ||
                (initialCount > 0 && getItemCount() == 0))
            mUpdateListener.onUpdateEmptyView(getItemCount());
```

If the last condition is true, we proceed even if the listener is null. For now I'll sidestep it by providing a listener.

**Comment by davideas** [comment]
Thanks, yes it looks like operator precedence, missing a parenthesis. However as you already know that part has been completely modified in **experiments** branch. I will fix for current SNAPSHOT release.
