### ISSUE TITLE
[Question] How to change layout when move from list to grid.

### ISSUE THREAD

**Issue by mdtuyen** [davideas/FlexibleAdapter#137]
I want to change from list to grid with other layout. What is solution in your library ?

**Comment by davideas** [comment]
Hi @mdtuyen, it uses the normal way:
``` java
mRecyclerView.setLayoutManager(createNewGridLayoutManager());
```

Check the demo app, class [`AbstractFragment`](https://github.com/davideas/FlexibleAdapter/blob/master/flexible-adapter-app/src/main/java/eu/davidea/samples/flexibleadapter/fragments/AbstractFragment.java)

**Comment by mdtuyen** [comment]
Hi, @davideas  I want to change layout view of item not only list<->grid

**Comment by davideas** [comment]
Well, instead of providing a view type you give a new one.
But those items are completely different from the previous, new view type etc... it's not the same list!
Probably you also need to swap the adapter.

**Comment by davideas** [comment]
But, if the views have same IDs, you just provide a new layout id with an `if` statement, in getViewType or getLayoutRes if you implemented the new method A to bind items.

**Comment by mdtuyen** [comment]
That mean I can use:

```
	@Override
	public int getLayoutRes() {
              if(list){
	            return list_layout;
             }
             return grid_layout;
        }
```

**Comment by davideas** [comment]
Yes, but don't use local variable, use a static variable a general object, or if you use settings service, use for preferred layout.

**Comment by mdtuyen** [comment]
Ok I need your confirm to sure that reuse feature active. Thanks.
