### ISSUE TITLE
[5.0.0-b7] Sticky headers and android.support.v4.widget.SwipeRefreshLayout

### ISSUE THREAD

**Issue by tprochazka** [davideas/FlexibleAdapter#138]
I have this layout

```
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
	android:layout_width="match_parent"
	android:layout_height="match_parent">

	<android.support.v4.widget.SwipeRefreshLayout

		android:id="@+id/refresh"
		android:layout_width="match_parent"
		android:layout_height="match_parent">

		<android.support.v7.widget.RecyclerView
			android:id="@+id/list"
			style="@style/ListView"
			android:layout_width="match_parent"
			android:layout_height="match_parent"
			android:clipToPadding="false"
			android:overScrollMode="never" />

	</android.support.v4.widget.SwipeRefreshLayout>

	<include layout="@layout/sticky_header_layout" />


</FrameLayout>

```
It works correctly until I want to refresh list.
Problem is that refresh circle is under first header. 
If I move `sticky_header_leayout` inside of `SwipeRefreshLayout `after `RecyclerView `sticky header are gone.

But why sticky header is displayed when I'm on the top of list? If you simply hide it, it will be much better, but not ideal, when user initialize refresh and will scroll during refreshing sticky header must display and it will be over progress circle again.

**Comment by tprochazka** [comment]
This could work

```
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
	android:layout_width="match_parent"
	android:layout_height="match_parent">

	<android.support.v4.widget.SwipeRefreshLayout

		android:id="@+id/refresh"
		android:layout_width="match_parent"
		android:layout_height="match_parent">

		<FrameLayout android:id="@+id/sticky_header_container"
			android:layout_width="match_parent"
			android:layout_height="wrap_content"
			android:clipToPadding="false">

			<android.support.v7.widget.RecyclerView
				android:id="@+id/list"
				style="@style/ListView"
				android:layout_width="match_parent"
				android:layout_height="match_parent"
				android:clipToPadding="false"
				android:overScrollMode="never" />

		</FrameLayout>

	</android.support.v4.widget.SwipeRefreshLayout>

	<include layout="@layout/sticky_header_layout" />

</FrameLayout>
```

But just until I scroll to the end of the first section.
It looks that you are moving with whole sticky_header_container and whole recyclerView start moving out of the screen in top direction.

**Comment by davideas** [comment]
Please check issues #83 and #104 and release notes.

**Comment by davideas** [comment]
@tprochazka what do you mean with _moving with whole sticky_header_container and whole recyclerView start moving out of the screen in top direction_ ?

**Comment by tprochazka** [comment]
I added one more FrameLayout as you have it [here](https://github.com/davideas/FlexibleAdapter/blob/71b2d56b81c36805a766451f7f926a1b5729d86b/flexible-adapter-app/src/main/res/layout/fragment_recycler_view.xml) and it works as expected. I did it according the wiki https://github.com/davideas/FlexibleAdapter/wiki/5.x-%7C-Headers-and-Sections and I didn't know about the right solution for the SwipeRefreshLayout. Thanks
