### ISSUE TITLE
[5.0.0-b7] Sticky header is not resized on automatic configuration change

### ISSUE THREAD

**Issue by tprochazka** [davideas/FlexibleAdapter#139]
I have activity with `android:configChanges="orientation|screenSize"` because I need very fast rotation and I don't need layout changes after rotate.

But library probably set exact size for sticky header inside of `<include layout="@layout/sticky_header_layout" />`. Because header has the same size after rotate, he don't react on new layout() cycle when width of original header is changed properly.

Original header has `match_parent `as width, why not use the same also on virtual header inside of `sticky_header_layout`? Then it will be automatically changed during re-layouting.

**Comment by davideas** [comment]
Currently, the view transfer the information to the sticky layout as following:
``` java
private void ensureHeaderParent() {
	final View view = mStickyHeaderViewHolder.getContentView();
	//Make sure the item params are kept if WRAP_CONTENT has been set for the Header View
	mStickyHeaderViewHolder.itemView.getLayoutParams().width = view.getMeasuredWidth();
	mStickyHeaderViewHolder.itemView.getLayoutParams().height = view.getMeasuredHeight();
	//Now make sure the params are transferred to the StickyHolderLayout
	ViewGroup.LayoutParams params = mStickyHolderLayout.getLayoutParams();
	params.width = view.getMeasuredWidth();
	params.height = view.getMeasuredHeight();
	removeViewFromParent(view);
	mStickyHolderLayout.setClipToPadding(false);
	mStickyHolderLayout.addView(view);
}
```
Maybe I should do:
``` java
params.width = view.getLayoutParams().width;
params.height = view.getLayoutParams().height;
```
But I need to check together with your configuration.

**Comment by davideas** [comment]
I've reproduced it, it could be fixed, need to do some more tests.

**Comment by tprochazka** [comment]
It's should be part of current 5.0.0-SNAPSHOT or not yet?
I tested it with this version and it look that it is not working yet.

**Comment by davideas** [comment]
@tprochazka, so what I tested wasn't your issue? :-/
I added `android:configChanges="orientation|screenSize"` on the activity [here](https://github.com/davideas/FlexibleAdapter/blob/dev/flexible-adapter-app/src/main/AndroidManifest.xml), `match_parent` was already present, i used this [layout/recycler_header_item.xml](https://github.com/davideas/FlexibleAdapter/blob/dev/flexible-adapter-app/src/main/res/layout/recycler_header_item.xml).

In the [`StickyHeaderHelper`](https://github.com/davideas/FlexibleAdapter/blob/dev/flexible-adapter/src/main/java/eu/davidea/flexibleadapter/helpers/StickyHeaderHelper.java) the `view.getLayoutParams().width` was -1 = match_parent, by rotating the screen the method is indeed not called and the header got larger width and filled the screen. with old code, the size was until the half of the screen.

Now, for me it is fixed, until it is something else and you have to tell me how to reproduce your issue :-)

**Comment by tprochazka** [comment]
Sorry for delay I was on holiday.
I tested it again with SNAPSHOT and it works as expected.
Thanks you very much!
