### ISSUE TITLE
Crash after filtering and getting empty result.

### ISSUE THREAD

**Issue by ReinaldLee** [davideas/FlexibleAdapter#149]
- [ ] When using the FlexibleAdapter's filter function, the app will crash after no filter results come out.

- [ ] The library I use is v5.0.0-b7.
- [ ] Here is the problem. 
```
		//Call listener to update EmptyView
		if (mUpdateListener != null &&
				(initialCount == 0 && getItemCount() > 0) ||
				(initialCount > 0 && getItemCount() == 0))
			mUpdateListener.onUpdateEmptyView(getItemCount());
```
This is the source code in FlexibleAdapter#filterItems() where the crash happened. If the mUpdateListener is null, obviously mUpdateListener.onUpdateEmptyView(getItemCount()); shouldn't be executed. But in fact it will run this code and NullPointerException occurs. The reason is a pair of brackets is missed and the condition turns out true.
- [ ] I suppose that the code may be
```
		//Call listener to update EmptyView
		if (mUpdateListener != null &&
				( (initialCount == 0 && getItemCount() > 0) ||
				(initialCount > 0 && getItemCount() == 0) ) )
			mUpdateListener.onUpdateEmptyView(getItemCount());
```

**Comment by davideas** [comment]
Hello @ReinaldLee, please see issue #135, then use _Snapshot_ release of yesterday with more others fix and improvements.
