### ISSUE TITLE
Add item animation when RecyclerView is firstly loaded

### ISSUE THREAD

**Issue by davideas** [davideas/FlexibleAdapter#15]
Optionally activate a custom animation to the items when RecyclerView is firstly loaded and shown.
I will add this feature on next major release 5.0.0

**Comment by danielpassos** [comment]
Tip: Instead of comment on issue the version schedule for that. Create a _Milestone_ and assign to that. It make easily to you/community filter issues by release/milestone ;)

**Comment by davideas** [comment]
**To anyone!**

I've implemented this nice feature, it works good with LinearLayout, need to fix something with GridLayout, The feature is now available in **dev** only as java code with commit [1173a2b](https://github.com/davideas/FlexibleAdapter/commit/1173a2b4c87d3e446efb4b0016368c9a0563c3c8), 

Now a suggestion from more developers would be appreciated. There are 2 ways to insert this feature, you can say yours by commenting after me:
 1. (Current code) A developer can choose to extend his adapter from the usual `FlexibleAdapter` or from `FlexibleAnimatorAdapter` that internally extends `FlexibleAdapter`. Advantage of this separation is a lighter adapter if one doesn't want animations (_RecyclerView reference_ is in the new adapter only).
 2. Having only one adapter (`FlexibleAdapter`) that already extends `FlexibleAnimationAdapter` which advantage is that, animations are immediately available to anybody without modifying the class signature but 1 new method must be of course overridden and it's bit heavier in memory if one doesn't want animations.

Just a note: I already applied this kind of animations in one of my project but I also took inspiration from others 2 libraries ([RecyclerViewItemAnimators](https://github.com/gabrielemariotti/RecyclerViewItemAnimators) and [recyclerview-animators](https://github.com/wasabeef/recyclerview-animators)). All features from them and my previews project are now in my new class!
During development I've decided to use methods instead of more class extensions as they have done by adding adapter animation class as wrapper for the main adapter. Instead, my way has 3 immediate advantages:
 * Just one method to override to build custom _Animator_ list without modifying the existing code in the Activity and a much lighter library.
 * The most cool: different animations for items depends on _position - view type - active selection_.
 * (I did not test so I'm not sure but) doing their way, probably methods added in my FlexibleAdapter could not be available anymore.

**Comment by davideas** [comment]
It will be available from 5.0.0-b2.

**Comment by davideas** [comment]
In 5.0.0-b2 I opted for point 2: `FlexibleAdapter` extends `FlexibleAnimatorAdapter`.
