### ISSUE TITLE
scrollToPositionWithOffset scrolls only header but not section items

### ISSUE THREAD

**Issue by yamelkaya** [davideas/FlexibleAdapter#150]
I use FlexibleAdapter with sticky header - latest SNAPSHOT version. 

I need to scroll to particular list position. So, I use `SmoothScrollLinearLayoutManager` and `scrollToPositionWithOffset`. 

In most cases scrolling work as expected but sometimes manager scrolls to header position but does not scroll items below (please see [screenshot](http://screencast.com/t/g7UJUCz7JZ) - items grouped by date and you can see that "July 7" header is on top now but items for that date don't change position).

Unfortunately I can't provide certain steps that reproduce the issue but I am still testing the case. Maybe you have some ideas about the reason?

**Comment by davideas** [comment]
Nope, what you say sounds strage.

Do you need the "offset" or just a simple scroll?
https://developer.android.com/reference/android/support/v7/widget/LinearLayoutManager.html#scrollToPositionWithOffset(int,int)

**Comment by yamelkaya** [comment]
I've tried `scrollToPosition(position)` first but for some reasons this method does not work. When I scroll to some position it scrolls to absolutely another (I've checked it in debug - position is OK). So, I decided switch to `scrollToPositionWithOffset(position,0)` and it works as expected but with issue I mentioned above.

**Comment by yamelkaya** [comment]
I prepared [example](https://github.com/yamelkaya/FlexibleAdapterWithStickyHeadersDemo) for you. I use `scrollToPosition(position)` here. 

So, when you select date in DatePicker you should be scrolled to this date in list. I've noticed that when you try to scroll backward everything works but when you scroll forward it doesn't work as expected.

_Note:_ I generate dates with interval - e.g. 1st 3rd 5th etc. , for gaps I insert empty item with empty header.

**Comment by davideas** [comment]
Hi @yamelkaya, I tried your example, that is normal, because scrollTo displays the position you indicated, nothing to complain about it, even if is the last visible item in the RV...

Maybe you need a function like mine (check code), or maybe you need that function (now private):
``` java
private void autoScrollWithDelay(final int position, final int subItemsCount, final long delay);
```

**Comment by yamelkaya** [comment]
I see. `scrollToPosition(position)` is not my case. I need element at the top when I scroll to it. I think `scrollToPositionWithOffset(position,0)` should do what I need. 

So, I'll try to reproduce issue with incorrect scrolling (which I mention at the first [post](http://screencast.com/t/g7UJUCz7JZ)) in my example. 

Checked your method `autoScrollWithDelay`. It uses `smoothScrollToPosition(position)` . I will do experiments with this method too.

**Comment by davideas** [comment]
Smooth might not be good for many many items to scroll, it's nice for few items.
However I wanted to point out the calculation. You need the header to be scrolled as first visible position, so you need to calculate the position to scrollTo, you don't need ...WithOffset().

**Comment by yamelkaya** [comment]
> Smooth might not be good for many many items to scroll, it's nice for few items.

Yes, with smooth scroll it looks really strange. Are there any good solutions for fast scrolling to item?

**Comment by davideas** [comment]
Hi @yamelkaya, as said you need to calculate the top position to scrollTo.
