### ISSUE TITLE
GridLayout with Sections: GetSectionIndex return wrong value when dragging upwards

### ISSUE THREAD

**Issue by maltebucksch** [davideas/FlexibleAdapter#152]
Using a Gridlayout with sections that seperate your items (best represented by the "headers and sections example"):

While you drag, and get the value of `getSectionIndex(draggedItemPosition)` in `shouldMove(from,to)`
->` getSectionIndex` will return the wrong index if dragged from  screenBottom direction to screenTop direction

Let's say you have the following situation, 1 item, 1 header/section:
[ item1 ]                            <- "area1"
------Header-----
[ item2 ]                            <- "area2"

**Correct behavior** from screenTop direction to screenBottom (down):
1. You drag item1 to area2 
2. in the called method `shouldMove` you call and print `getSectionIndex(toPosition)`
3. You will get 0 **(which is fine)**

--- Starting again with the normal situation shown above ---
**Wrong behavior** from screenBottom direction to screenTop direction (up):
1. You drag item2 to area1 
2. in the called method `shouldMove` you call and print `getSectionIndex(toPosition)`
3. You will get 1
---> which is **not correct** since the target position does not have any headers before it anymore

If you check after dragging  `getSectionIndex(item1Position)` again -> you see that it's correct (it's 0)
So while dragging the index is not calculated correctly (it does not consider the header that just moved above the dragged item)

As with the last bug, I am using your library extensively, so I am quite happy over quick feedback or even a fix. Thanks in advance

I need this to work correctly in order to prohibit the dragging of items above a particular header. i want to limit the range in which the user can drag items by two headers (above and below) . Between these two border headers are a lot of sections/headers where the user can organize stuff.
If you have an alternative solution to get my intended behavior (in order to avoid the bug), I am also open to that alternatively
I hope you understand what I mean. I tried to make my description as accurate and easy to understand as possible

**Comment by davideas** [comment]
Hi @maltebucksch, well, if you see the code of getSectionIndex(toPosition), it takes the current item on that position, so `getSectionIndex(1)` gives you `1`, the move is not done yet... and that is correct: position `1` is covered by the header.
I think you obtain `0`, because you actually allow the move: position `0` is already covered by the header.
I don't know what is your condition that returns true/false.

More or less I understood what you want, try others methods `*Header*()` series OR try to simulate the fact that the `toPosition` has the correct value.
In any case, enable logs after try to debug as well.

Note that, I am not even sure to keep the functions `getSectionIndex()` series.

**Comment by maltebucksch** [comment]
That's pretty much my code in a subclass of flexibleadapter:
```
@Override
public boolean shouldMove(int fromPosition, int toPosition) {
        Log.d(LOG_TAG,"Section-from: "+getSectionIndex(fromPosition)+ "  Section-to: "+getSectionIndex(toPosition));
        return onModuleShouldMoveListener == null || onModuleShouldMoveListener.shouldMove(fromPosition, toPosition);
}
```

So it does not have to do anything with the fact that I allow or not allow the move. This part was not even executed yet when I check or log. I want allow or not allow the move based on the sectionIndex I am dragging to.

It's not correct like it is right now. If I drag item1 to area2, then the section of `fromPosition ` is n and section of `toPosition` is n+1.
If I drag item2 to area1, then the section of `fromPosition ` is n+1 and section of `toPosition` is also n+1. `getSectionIndex(toPosition) `should be n there.

So the method didn't yet take into account the move above the header, but when I drag from above to below the header, it does take it into account (which is great).

This happens for every move of an item over a header. If drag from above the header TO below the the header. It's certainly a bug. I can try to make a workaround but I just wanted to let you know about it before since it might be useful to know. If you have any question let me know.

**Comment by davideas** [comment]
@maltebucksch OK there's no code, but what I said remains true: the item is still not moved and `getSectionIndex(toPosition)` cannot know that you are dragging(!): in `toPosition` there's still the header so it is counted in.
You have to adapt to your use case with a super simple `if` statement:
``` java
@Override
public boolean shouldMove(int fromPosition, int toPosition) {
        Log.d(TAG, "Section-from: " + getSectionIndex(fromPosition) +
                   " Section-to: " + getSectionIndex((fromPosition > toPosition ? toPosition - 1 : toPosition));
        return onModuleShouldMoveListener == null || onModuleShouldMoveListener.shouldMove(fromPosition, toPosition);
}
```

With beta8 I can activate the `shouldMove` for the listener, I see that you use it.

**Comment by maltebucksch** [comment]
I see what you mean. It works, thanks a lot @davideas.

**Comment by maltebucksch** [comment]
I have another short question. I browsed through your wiki a lot but could not find a sufficient answer.
Is there a "best practice" for your library to update my local Realm/SQLLite database with changes I made in the UI?

It's only about reordering elements in different database lists:
The approach I intend to use is to just listen for "onMove" events and accordingly swap items in my database list. But because onMove is called for all items, not only the dragged one, I would need to add some code to filter other events out. That would be no problem but I asked myself if you would suggest a better way?

**Comment by davideas** [comment]
Unfortunately I do not see any magic code that does that.
Maybe, what you can do is to wait to move items in your DB until it is finally dropped, on that moment you check where it was dropped (which section) and the previous section in your DB, so that you "touch" the DB once.

To know when the item is released, I see that the callback method `onActionStateChanged()` is called with correct status, but it's called _before_ the `ViewHolder` receives the instruction to clear the view.

**Comment by maltebucksch** [comment]
Alright, that's fine then. I will make use of `onActionStateChanged` and `onMove`. Should't be too hard.
Thanks.
