### ISSUE TITLE
[Request] Lower minSdk

### ISSUE THREAD

**Issue by F43nd1r** [davideas/FlexibleAdapter#154]
I think it would be a good idea to lower the minSdk value. 
I tried with 11, because that is what my app used before, and the library had no problem with it.
(The sample app requires 14, but that shouldn't impact the library).
I'd like to keep support for Versions 11-13 for the moment, but that would require a minSdk <=11 in this library.

**Comment by davideas** [comment]
I'm sorry, too much effort to maintain versions no body uses.

**Comment by davideas** [comment]
Supporting the decision, soon we should all target API19:
https://developer.android.com/about/dashboards/index.html

**Comment by F43nd1r** [comment]
As long as I have active users on any version I will continue to support that version. I don't care that they are a minority, they are there. That's all what counts to me.
But it doesn't matter anymore. I have abandoned this library for now anyways. I will eventually check back when 5.0 becomes stable.
