### ISSUE TITLE
Updating datastructure after move

### ISSUE THREAD

**Issue by F43nd1r** [davideas/FlexibleAdapter#155]
I want to implement move from one section to another via drag, but items inside a section should stay sorted alphabetically. This almost works. The problem is, after moving the item, I need to update my internal datastructure to reflect the change, but I am unable to get the sections I am moving from & to.

```java
        adapter.initializeListeners(new FlexibleAdapter.OnItemMoveListener() {
            ScriptItem t;
            @Override
            public void onActionStateChanged(RecyclerView.ViewHolder viewHolder, int actionState) {
            }

            @Override
            public boolean shouldMoveItem(int i, int i1) {
                t = adapter.getItem(i);
                Log.d("pos",i+" "+i1);
                return !adapter.getExpandableOf(i).equals(adapter.getExpandableOf(i1));
            }

            @Override
            public void onItemMove(int fromPosition, int toPosition) {
                Log.d("move",fromPosition+" "+toPosition);
                if(t instanceof Script) {
                    Script move = (Script) t;
                    ScriptGroup fromGroup = (ScriptGroup) adapter.getExpandableOf(fromPosition);
                    ScriptGroup toGroup = (ScriptGroup) adapter.getExpandableOf(toPosition);
                    fromGroup.remove(move);
                    toGroup.add(move);
                }
            }
        });
```
src: https://github.com/F43nd1r/Multitool/blob/flexadapter/app/src/main/java/com/faendir/lightning_launcher/multitool/scriptmanager/DoubleBackedList.java#L29

This is what I tried, but `fromGroup` and `toGroup` are both the same group, so it doesn't work. I also had to capture the moving item in `shouldMove`, because in `onItemMove` `swapItems` has already been called and the item cannot be retrieved anymore.

What can I do here?

**Comment by davideas** [comment]
Might the issue #152 help you?

**Comment by F43nd1r** [comment]
Not really. #152 targets an issue in `shouldMoveItem`, while my problem is that I don't know how to interpret the information in `onItemMove`, because it seems to be called in between changes (If I analysed that correctly. At least the parameters do not represent what I would expect them to represent).

**Comment by davideas** [comment]
@F43nd1r since `shouldMoveItem` and `onItemMove` are callbacks, maybe you want override the methods from your custom Adapter and handle yourself the call to these callbacks.
But since you have read the comments on all those methods, you already know that `onItemMove` is called everytime the item is shifted and not when it is released.
So issue 152, still helps you because in there I suggested to use the state in `onActionStateChanged`, so that you know when it is released by the user.

`onItemMove` already does a lot of things for you, you can check the code too.
