### ISSUE TITLE
Drag range ,shouldMoveItem doesn't work!

### ISSUE THREAD

**Issue by PaperHS** [davideas/FlexibleAdapter#156]
When can I try to use shouldMoveItem,or is there another method to limit drag range?

**Comment by davideas** [comment]
`shouldMoveItem()` is a method for the developer to implement how he desires the logic, depending by his use case.
Actually this feature already existed, but it was necessary to extend the adapter to override the `shouldMove()` method.

**Comment by PaperHS** [comment]
@davideas thank u!I got it
