### ISSUE TITLE
How implement item update on swipe? 

### ISSUE THREAD

**Issue by yamelkaya** [davideas/FlexibleAdapter#158]
Hi @davideas, I am trying to implement swipe items (swipe **left - delete**, swipe **right - update**). 

Example: 

swipe left (delete) flow: 
- item disappears
- snackbar with "UNDO" appears
- item returned back if user clicks "UNDO"
- snackbar disappears if no action from user and item deleted from DB

swipe right (update) flow: 
- item changes color (cross line appears etc.)
- snackbar with "UNDO" appears
- item changes to its previous state back if user clicks "UNDO"
- snackbar disappears if no action from user and item updated in DB

I don't have problems with delete but don't understand how item update work. I look at your example (e.g. Endless scrolling) and it has some unclear points for me: 

1. I don't understand how to update items in DB and on UI in RecyclerView (e.g. updated items should have another color). 
_By the way, [orange region](http://screencast.com/t/owV0SnBiv) (which appears after swiping left in your example) is not scrollable. I mean that it's not possible to scroll list when I drag this item up or down. This region becomes inactive and only Snackbar appears again and again on clicks. Is it expected behavior?_ 

2. How implement "UNDO" with update? It is not implemented in your example now and not clear for me how to "swipe" archived items back when "UNDO" clicked.

3. Is it possible swipe item which has been swiped before (swipe left -> swipe left -> swipe left ...)? 

I am sorry in advance if my questions are stupid but I really don't see how achieve what I need. Thanks.

**Comment by yamelkaya** [comment]
So, I found suitable solution for my problem. When I work with `UndoHelper.ACTION_UPDATE` use custom list for updated items and `notifyItemChanged(position)` method to inform adapter that item updated 

update item -> notifyItemChanged -> add to list -> 1) update in db when confirmed or 2) revert item back when undo 

I think you may close the issue if there is no problems with this solution.

**Comment by davideas** [comment]
Hi @yamelkaya, if you have seen the GMail app, ideally when you implement the "archive" feature, as soon as it is swiped a dialog comes up to confirm what the user wants to do, so the action is delayed for the user who has to decide the operation.

You can close the item swiped with a new swipe in the opposite direction, the only thing is that the click in the _orange region_ doesn't work, need to work on it. Also the touch is horizontal because you swiped it, so the list cannot be scrolled vertically, I think it's normal because it not supposed to be scrolled vertically since an action is expected by the user with a dialog in front of everything.

**Comment by yamelkaya** [comment]
Ok, now I understand. I this case issues I mentioned are not a problem. But there is some cases when confirmation from user is not required (e.g. - we have task list and we swipe to complete item). In this case list item expected to be "normal" (clickable) just after swiping. For now I resolved this problem with `notifyItemChanged(position)`.

**Comment by yamelkaya** [comment]
Btw, I have one more question related to edit on swipe. When I swipe item to complete it should move to the bottom of section. I mean the following: 

**section 1**
item b
item c
item d
~~item a~~
~~item e~~

swipe(complete) `item c `

**section 1**
item b
item d
~~item a~~
~~item c~~
~~item e~~

I've updated the comparator (it compares `completed` property first now) but it's not enough. I need to refresh list somehow to inform that in section something changed (item crossed and moved to another position). Do you have any thoughts how to achieve that? Thanks in advance.

**Comment by davideas** [comment]
Use `moveItem`, it has the `notifyXXX*()` inside so that it will reflect the new position.

**Comment by yamelkaya** [comment]
Thanks, @davideas! `moveItem()` + `calculatePositionFor()` that's what I need. Everything works as expected.
