### ISSUE TITLE
Can I use this adapter to implement a chat list which is seen in many messenger app?

### ISSUE THREAD

**Issue by techadroit** [davideas/FlexibleAdapter#160]
Hi,

I want to know if this adapter can be used to implement a chat list like the one in the chat window of the whatsapp. (i.e, section and sticky header, multiple layouts, ripple effect, bubble backgrounds, fast scrolling, loading images). Everything a chat list would require.

Thanks

**Comment by davideas** [comment]
Hi @techadroit, basically this Adapter can do everything you listed, you just need to verify that the sticky header works when the keyboard is displayed. I do not know which solution you will adopt, I give you an hint by pointing issue #90.
If you in the end decide to publish your app with this Adapter let me know :-)

**Comment by techadroit** [comment]
Hi @davideas Thanks for the reply. I am creating a demo using this adapter and if everything goes well I might end up using this adapter in my app and will sure let you know.
