### ISSUE TITLE
NullPointerException when filtering items

### ISSUE THREAD

**Issue by RenatKaitmazov** [davideas/FlexibleAdapter#165]
I got `NullPointerException` when searching for an item that does not exist in the adapter.
I suspect it happens due to `&&` operator having precedence over `||` in the following snippet of code:
```
if (mUpdateListener != null &&
				(initialCount == 0 && getItemCount() > 0) ||
				(initialCount > 0 && getItemCount() == 0))
			mUpdateListener.onUpdateEmptyView(getItemCount());
```
This snippet of code is in `filterItems()` method.

I didn't set an update listener when initializing my adapter but still it tried to call `onUpdateEmptyView` because `(initialCount > 0 && getItemCount() == 0)` evaluates to true and it is enough for the whole condition to be true.

**Comment by davideas** [comment]
Hello @RenatKaitmazov, please see issue #135, then use _Snapshot_ release with more others fix and improvements. Until new beta will be deployed, please use the _Snapshot_.
I didn't have time to complete the content for next beta, I hope to finish the modifications I have in mind soon.

Alternatively you can implement the listener.
