### ISSUE TITLE
Add single or multiple selection for each section or expandable list separately

### ISSUE THREAD

**Issue by ahmadalibaloch** [davideas/FlexibleAdapter#169]
I don't know is this possible or not, I did not check the code thoroughly. I need to have many sections, each one handling the grouped radio buttons of itself. Is this possible or not?

**Comment by davideas** [comment]
@ahmadalibaloch, I think it is possible, but you need to customize the selection and override some functions.
You will need subitems under an expandable object (it is just a name, think it as section with expandable disabled), so that you can check if one of them is already selected.
