### ISSUE TITLE
For better implements

### ISSUE THREAD

**Issue by NewdBe** [davideas/FlexibleAdapter#172]
@Override
    public RecyclerView.ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        return getItem(viewType).createViewHolder(this, mInflater, parent);
    }

    @SuppressWarnings("unchecked")
    @Override
    public void onBindViewHolder(RecyclerView.ViewHolder holder, int position, List payloads) {
        getItem(position).bindViewHolder(this, holder, position, payloads);
    }

    @Override
    public int getItemViewType(int position) {
        return position;
    }

**Comment by davideas** [comment]
@NewdBe, why did you propose this implementation? It is super basic and it is not good for my new advanced features.
