### ISSUE TITLE
Inconsistency detected on beta8 with asynchronous item update

### ISSUE THREAD

**Issue by llDavidll** [davideas/FlexibleAdapter#173]
Hi,

I started using your library with beta7, and it worked very well. Since the update to beta8, I am having crashes like this one : 
>java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{dd3598b position=7 id=-1, oldPos=0, pLpos:0 scrap [attachedScrap] tmpDetached no parent}

After some debugging, I think I found the cause of the problem. I use "updateDataSet" function with animations enabled, which internally calls "animateTo" function of the FlexibleAdapter, which does this :

    List<T> tempItems = new ArrayList<>(mItems);
    applyAndAnimateRemovals(tempItems, newItems);
    applyAndAnimateAdditions(tempItems, newItems);
    if (notifyMoveOfFilteredItems)
        applyAndAnimateMovedItems(tempItems, newItems);
    mItems = tempItems;

The problem is that the notifications created with all the "applyAndAnimate" functions are executed asynchronously some time after mItems is set. If a layout pass occurs after mItems = tempItems and before the notifications are executed, the exception will be thrown. 
This is because the RecycleView checks for the itemCount in the adapter during its layout, and prepare the views.
For example, in an adapter without items, if you want to add 5 items :

- You change mItems
- The layout pass occurs : the recycler view checks the itemCount and think they are 5 items, so it prepares 5 view holders.
- The adapter makes the notify calls : the recycler view is notified of 5 pending adds.
- The next layout pass occurs : the recycler thinks it has 5 items + 5 pending items, so 10 items. The exception is thrown.

I activated the debug mode of the FlexibleAdapter, which makes it appear.

When it works :
>I/FlexibleAdapter: Performing 7 notifications
>I/FlexibleAdapter: Mapped viewType 2130903232 from NavigationAdapterItem
>V/FlexibleAdapter: onViewBound>Holder=ViewHolder position=0 itemId=-1 layoutPosition=0
>I/FlexibleAdapter: Mapped viewType 2130903173 from NavigationAdapterItem
>V/FlexibleAdapter: onViewBound>Holder=ViewHolder position=1 itemId=-1 layoutPosition=1
>V/FlexibleAdapter: onViewBound>Holder=ViewHolder position=2 itemId=-1 layoutPosition=2
>V/FlexibleAdapter: onViewBound>Holder=ViewHolder position=3 itemId=-1 layoutPosition=3
>V/FlexibleAdapter: onViewBound>Holder=ViewHolder position=4 itemId=-1 layoutPosition=4
>V/FlexibleAdapter: onViewBound>Holder=ViewHolder position=5 itemId=-1 layoutPosition=5
>V/FlexibleAdapter: onViewBound>Holder=ViewHolder position=6 itemId=-1 layoutPosition=6

When it crashes :
>I/FlexibleAdapter: Mapped viewType 2130903232 from NavigationAdapterItem
>V/FlexibleAdapter: onViewBound>Holder=ViewHolder position=0 itemId=-1 layoutPosition=0
>I/FlexibleAdapter: Mapped viewType 2130903173 from NavigationAdapterItem
>V/FlexibleAdapter: onViewBound>Holder=ViewHolder position=1 itemId=-1 layoutPosition=1
>V/FlexibleAdapter: onViewBound>Holder=ViewHolder position=2 itemId=-1 layoutPosition=2
>V/FlexibleAdapter: onViewBound>Holder=ViewHolder position=3 itemId=-1 layoutPosition=3
>V/FlexibleAdapter: onViewBound>Holder=ViewHolder position=4 itemId=-1 layoutPosition=4
>V/FlexibleAdapter: onViewBound>Holder=ViewHolder position=5 itemId=-1 layoutPosition=5
>V/FlexibleAdapter: onViewBound>Holder=ViewHolder position=6 itemId=-1 layoutPosition=6
>I/FlexibleAdapter: Performing 7 notifications

As you can see, when it crashes, views are bound before the notifications are executed.

I think you can try to postpone "mItems = ..." to the same place where you make the notifications. You would probably have to keep a "pendingItems" list and maybe use it internally if you need to know what is currently loading.

To test this I think you can add a delay in the `doInBackground` function of the `FilterAsyncTask`. Something like :

>switch (what) {
>...
>}
>try {
>    Thread.sleep(500);
>} catch (InterruptedException e) {
>    e.printStackTrace();
>}
> return null;

Then you open an empty list and set the items using `updateDataSet(items, true);`
This should postpone the notifications by 500ms, time during which the RecyclerView should make a layout pass.

Hope I was clear enough !

**Comment by davideas** [comment]
@llDavidll, thanks for the issue reported, let's try to figure out when and what really happens. However I did not well understood the solution proposed. I have some questions:
- Does this happens systematically or do you have a way to reproduce it all the times?
- I need more logs, in both cases: before background starts, until the end of the operations, with the timestamp too. Can past them here?
- I remind you that background task is cancelled every time it is requested a new one.

The notifications are always executed after the background process finishes (they have to) because is in `onPostExecute()` so `mItems` is assigned always in the background. You propose to assign the new items out of the background process?
- I do not understand why you have new view bounds between the background task and the notifications. The view are bounds only if there's a notification requested, how RV can have a layout pass without notifications or scroll?
- Also, why do you have "_Mapped viewType_" after an `updateDataSet()`?

Please send the the full log.

**Comment by llDavidll** [comment]
I am currently not at work so I wont be able to test/ give you logs until Monday. I will try to answer your questions :
- This happens randomly, because this is related to threads. I think that adding the little sample using Thread.sleep() at the end of `doInBackground` function would "force the bad luck" by giving more time to the RecyclerView to do its thing between the end of `animateTo` and the sending of the notifications. If you set this delay, it should also make scrolling during item adding/removing almost impossible.
- For the logs, it will have to wait but I will give them to you.
- I just need one call to `updateDataSet()` to make this happen.

I understand that the notifications must be executed on the main thread, but I think that mItems should also be modified on the main thread. The exception I got can be thrown one at least two cases : if you send the wrong notifications (which you don't), and if you modify the items without notifying the recycler view. You do notify it, but with some delay due to the multiple thread. Check this stackoverflow answer for example : [](http://stackoverflow.com/a/26832214). 
"...make sure you're updating your Adapter data source only from the main thread and calling appropriate adapter notify method after it."

- That's the thing : I have view bounds because the recycler view ask for them (from what I saw, its some kind of prelayout). The reycler view ask for the itemCount and prepare the views according to this. Then the notifications are executed, and the RecyclerView is "lost" From what I saw in debug the recycler view tries to create 14 items (the 7 it found during its layout pass, and the 7 added via the notifications).  Maybe I set my items before the first layout pass, and the notifications are executed after the first layout pass.
- I have Mapped viewType because the crash occured at startup (when I set my items). The adapter was empty, so no viewType are mapped. Then I set my items, and it crashes. I really think it could happen any time items are modified, especially when scrolling (but also at startup or when the view must do a layout pass).

One solution would be to have `mItems `and `mTemporaryItems`. On the async task you only modify mTemporaryItems, and just before executing the notifications : `mItems = mTemporaryItems`.

**Comment by davideas** [comment]
@llDavidll, I am able to reproduce it, thank you for your explanation, I now understand better your solution.
I can publish this fix, but I have a question. You call `uploadDataSet()` after you assign the adapter to the RV and not at start/up, because you receive the items remotely?
Ideally, you should create the Adapter and initialize it from constructor, this because you can animate items when they are loaded the first time (use scroll animations only at start up), not a big thing but nice to have.

Also if you need, be sure to implement `hashCode()` in the items, you might need this. It allows to have _stableIds_ to increase performance, also during the filter.

**Comment by davideas** [comment]
The fix is already available in beta8. If your Gradle doesn't update it, clean your `eu.davidea` cache manually. For me works, but I would like your code works too, let me know on Monday.

**Comment by llDavidll** [comment]
That was quick ! Thank you, I will let you know if it works. Also thanks for the suggestions, I will try to activate "stableIds" since all my items already implement the `hashCode()` function. About the items assignment, I use rxjava to retrieve asynchronously a lot of data from the database and file system which is why the data is not available when I create the adapter and the view.

**Comment by llDavidll** [comment]
I tested it and wasn't able to reproduce this bug, so thank you for the fix !
