### ISSUE TITLE
Skip null object (draw nothing) in grid view

### ISSUE THREAD

**Issue by longnguyencmg** [davideas/FlexibleAdapter#175]
First of all, thank you for the excellent lib. I just tried to use it 3 days ago. As my understanding, you draw grid from left to right. However, I want to show as columns.  I tried to add null object into the list, but it didn't work. Please have a look at the screenshot below. "Shift 3" should below "Shift 2" 🎯 . Can you help with that? Cheers!

![screen shot 2016-09-25 at 10 43 01 am](https://cloud.githubusercontent.com/assets/4001695/18814419/dbc9143a-833c-11e6-825d-0f742be55041.png)

**Comment by davideas** [comment]
@longnguyencmg, thank you for your message.
Well, I have no idea, this is not related with the library, rather with the RV itself, I don't think it's possible in easy way, there's no function that does that. It's something very customized, you have to create your self.

Adding null doesn't help, you **probably** need a filler element that displays nothing (an empty view), but it is difficult to manage inasmuch elements can change positions.
So you have to insert 2 filler elements after Shift 2 position in the Adapter, but the columns must be hard coded at 3 and elements should not change positions. If they change position you need to recalculate everything.

**Comment by longnguyencmg** [comment]
@davideas Thank you for your reply, I just found the solution for this. Using fake objects and setHidden, then hide them on bindViewHolder :D

**Comment by davideas** [comment]
Hidden property is used in the Filter process, if you use the Filter, you will have that property changed.

**Comment by longnguyencmg** [comment]
Hello, I got issue when trying to use collapse and expandable. This is the stack trace:

java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{2a1c4c84 position=3 id=-1, oldPos=12, pLpos:12 scrap [attachedScrap] tmpDetached no parent}.

I debug and see all data was okay. View looks good but when I click on header to collapse, error occurred.

![screen shot 2016-09-28 at 3 21 56 pm](https://cloud.githubusercontent.com/assets/4001695/18905869/5925648e-858f-11e6-97a5-9bf76a683fb2.png)

**Comment by davideas** [comment]
Well, I don't know what you are doing in your code. Could you please describe the steps to reproduce it?
What are the actions you do before the exception occurs, and also can you please paste the logs of the Adapter?

**Comment by longnguyencmg** [comment]
Thank you for your reply, my thought is about the data. These are steps to reproduce:

I initialized data in fragment and pass into adapter -> view looks good -> click on Header -> **Crashed**

When I used data in the same way in your DatabaseService to initialize data and get data for ExpandableSection. Then collapse and expand works but still have issue. Please have a look at the screenshot below.

![screen shot 2016-09-28 at 4 25 03 pm](https://cloud.githubusercontent.com/assets/4001695/18908129/9aea11ea-8598-11e6-8cff-9ecb0cd63b37.png)

And this is full stacktrace:
![screen shot 2016-09-28 at 4 50 29 pm](https://cloud.githubusercontent.com/assets/4001695/18908911/b6da66ae-859b-11e6-9d99-2ea8a429237d.png)

**Comment by longnguyencmg** [comment]
I don't think it's about empty items because they're full object with "hidden" attribute :D

**Comment by davideas** [comment]
Can you please enable the Adapter logs and paste them here as text, not as image?
Also can you show me how you initialize the Adapter in your fragment?

**Comment by longnguyencmg** [comment]
This is the logs:

09-28 23:51:08.685 8270-8270/com.planday.ninetofiveapp I/FlexibleAdapter: Initially expanded 9 subItems on position=0
09-28 23:51:08.685 8270-8270/com.planday.ninetofiveapp I/FlexibleAdapter: Initially expanded 5 subItems on position=10
09-28 23:51:08.685 8270-8270/com.planday.ninetofiveapp I/FlexibleAdapter: Initially expanded 5 subItems on position=16
09-28 23:51:08.714 8270-8270/com.planday.ninetofiveapp I/FlexibleAdapter: Mapped viewType 2130968919 from SCategory
09-28 23:51:08.715 8270-8270/com.planday.ninetofiveapp V/FlexibleAdapter: onViewBound    Holder=ExpandableHeaderViewHolder position=0 itemId=-1 layoutPosition=0
09-28 23:51:08.717 8270-8270/com.planday.ninetofiveapp I/FlexibleAdapter: Mapped viewType 2130968917 from SShift
09-28 23:51:08.719 8270-8270/com.planday.ninetofiveapp V/FlexibleAdapter: onViewBound    Holder=ChildViewHolder position=1 itemId=-1 layoutPosition=1
09-28 23:51:08.725 8270-8270/com.planday.ninetofiveapp V/FlexibleAdapter: onViewBound    Holder=ChildViewHolder position=2 itemId=-1 layoutPosition=2
09-28 23:51:08.727 8270-8270/com.planday.ninetofiveapp V/FlexibleAdapter: onViewBound    Holder=ChildViewHolder position=3 itemId=-1 layoutPosition=3
09-28 23:51:08.732 8270-8270/com.planday.ninetofiveapp V/FlexibleAdapter: onViewBound    Holder=ChildViewHolder position=4 itemId=-1 layoutPosition=4
09-28 23:51:08.733 8270-8270/com.planday.ninetofiveapp V/FlexibleAdapter: onViewBound    Holder=ChildViewHolder position=5 itemId=-1 layoutPosition=5
09-28 23:51:08.735 8270-8270/com.planday.ninetofiveapp V/FlexibleAdapter: onViewBound    Holder=ChildViewHolder position=6 itemId=-1 layoutPosition=6
09-28 23:51:08.738 8270-8270/com.planday.ninetofiveapp V/FlexibleAdapter: onViewBound    Holder=ChildViewHolder position=7 itemId=-1 layoutPosition=7
09-28 23:51:08.739 8270-8270/com.planday.ninetofiveapp V/FlexibleAdapter: onViewBound    Holder=ChildViewHolder position=8 itemId=-1 layoutPosition=8
09-28 23:51:08.742 8270-8270/com.planday.ninetofiveapp V/FlexibleAdapter: onViewBound    Holder=ChildViewHolder position=9 itemId=-1 layoutPosition=9
09-28 23:51:08.745 8270-8270/com.planday.ninetofiveapp V/FlexibleAdapter: onViewBound    Holder=ExpandableHeaderViewHolder position=10 itemId=-1 layoutPosition=10
09-28 23:51:08.747 8270-8270/com.planday.ninetofiveapp V/FlexibleAdapter: onViewBound    Holder=ChildViewHolder position=11 itemId=-1 layoutPosition=11
09-28 23:51:08.749 8270-8270/com.planday.ninetofiveapp V/FlexibleAdapter: onViewBound    Holder=ChildViewHolder position=12 itemId=-1 layoutPosition=12
09-28 23:51:08.751 8270-8270/com.planday.ninetofiveapp V/FlexibleAdapter: onViewBound    Holder=ChildViewHolder position=13 itemId=-1 layoutPosition=13
09-28 23:51:08.753 8270-8270/com.planday.ninetofiveapp V/FlexibleAdapter: onViewBound    Holder=ChildViewHolder position=14 itemId=-1 layoutPosition=14
09-28 23:51:08.755 8270-8270/com.planday.ninetofiveapp V/FlexibleAdapter: onViewBound    Holder=ChildViewHolder position=15 itemId=-1 layoutPosition=15
09-28 23:51:08.757 8270-8270/com.planday.ninetofiveapp V/FlexibleAdapter: onViewBound    Holder=ExpandableHeaderViewHolder position=16 itemId=-1 layoutPosition=16

And this is my code in fragment:

@Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        if (!EventBus.getDefault().isRegistered(this)) {
            EventBus.getDefault().register(this);
        }
        mHandler = new Handler();
        FlexibleAdapter.enableLogs(true);
        DatabaseService.getInstance().createExpandableSectionsDatabase(3);
        if (getArguments() != null) {
        }
    }

    @Override
    public void onResume() {
        super.onResume();
        requestGetListDepartmentForSchedule();
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        this.inflater = inflater;
        this.bundle = savedInstanceState;
        View view = inflater.inflate(R.layout.week_fragment_schedule, container, false);

        verticalPager = (ViewPager) view.findViewById(R.id.weekPager);
        verticalPager.setAdapter(new InfiniteHorizontalPagerAdapter(this, 0));
        verticalPager.setCurrentItem(Constants.START_INDEX);

        monthAndYear = (TextView) view.findViewById(R.id.monthYear);
        departmentSelection = (TextView) view.findViewById(R.id.departmentSelection);
        filterButton = (ImageView) view.findViewById(R.id.btn_filter);

        monthAndYear.setOnClickListener(mOnMonthTitleClickListener);
        departmentSelection.setOnClickListener(mOnMonthTitleClickListener);
        wireControls();
        return view;
    }

    @Override
    protected void wireControls() {
        BasicInfo bi = BasicInfo.getInstance(mContext);
        isEditShift = bi.isAllowedToEditDaySchedule();

        //use selected department for schedule.
        selectedDepartment = new Department();
        if (bi.getSelectedDepartmentId() != -1) {
            departmentSelection.setText(bi.getSelectedDepartmentName());
            selectedDepartment.setId(bi.getSelectedDepartmentId());
            selectedDepartment.setName(bi.getSelectedDepartmentName());
        }
    }

    @Override
    public void onAttach(Context context) {
        super.onAttach(context);
    }

    @Override
    public void onDetach() {
        super.onDetach();
    }

    @Override
    public View makeView(int vertical, int horizontal) {
        View view = inflater.inflate(R.layout.fragment_week_schedule, null);
        FlipView.resetLayoutAnimationDelay(true, 1000L);
        //Create New Database and Initialize RecyclerView
        if (horizontal == 0) {
        initData3Days();
        initializeRecyclerView(bundle, view, new ArrayList<AbstractFlexibleItem>(listCategory));
        }
        //Settings for FlipView
        FlipView.stopLayoutAnimation();
        return view;
    }

    private void initializeRecyclerView(Bundle savedInstanceState, View view, List<AbstractFlexibleItem> list) {
        //Initialize Adapter and RecyclerView
        //ExampleAdapter makes use of stableIds, I strongly suggest to implement 'item.hashCode()'
        mAdapter = new BPScheduleAdapter(list, this);
        //Experimenting NEW features (v5.0.0)
        mAdapter.expandItemsAtStartUp()
                .setAutoCollapseOnExpand(false)
                .setAutoScrollOnExpand(true)
                .setAnimateToLimit(Integer.MAX_VALUE)//Size limit = MAX_VALUE will always animate the changes
                .setNotifyMoveOfFilteredItems(false)//When true, filtering on big list is very slow!
                .setNotifyChangeOfUnfilteredItems(true)//We have highlighted text while filtering, so let's enable this feature to be consistent with the active filter
                .setRemoveOrphanHeaders(false)
                .setAnimationOnScrolling(true)
                .setAnimationOnReverseScrolling(true);
        mRecyclerView = (RecyclerView) view.findViewById(R.id.recycler_view);
        mRecyclerView.setLayoutManager(createNewGridLayoutManager());
        mRecyclerView.setAdapter(mAdapter);
        mRecyclerView.setHasFixedSize(true); //Size of RV will not change
        //NOTE: Use default item animator 'canReuseUpdatedViewHolder()' will return true if
        // a Payload is provided. FlexibleAdapter is actually sending Payloads onItemChange.
        mRecyclerView.setItemAnimator(new DefaultItemAnimator());
        //Custom divider item decorator
//        mRecyclerView.addItemDecoration(new DividerItemDecoration(this,
//                R.drawable.divider, 0));//Increase to add gap between sections (Works only with LinearLayout!)

        //Add FastScroll to the RecyclerView, after the Adapter has been attached the RecyclerView!!!
//        mAdapter.setFastScroller((FastScroller) this.findViewById(R.id.fast_scroller),
//                Utils.getColorAccent(getActivity()), (MainActivity) getActivity());
        //Experimenting NEW features (v5.0.0)
        mAdapter.setLongPressDragEnabled(false)//Enable long press to drag items
                .setHandleDragEnabled(false);//Enable handle drag
        //.setDisplayHeadersAtStartUp(true);//Show Headers at startUp! (not necessary if Headers are also Expandable)

        SwipeRefreshLayout swipeRefreshLayout = (SwipeRefreshLayout) view.findViewById(R.id.swipeRefreshLayout);
        swipeRefreshLayout.setEnabled(true);
        //mListener.onFragmentChange(swipeRefreshLayout, mRecyclerView, SelectableAdapter.MODE_IDLE);

        //Add sample HeaderView items on the top (not belongs to the library)
        //mAdapter.showLayoutInfo(savedInstanceState == null);
    }

    protected GridLayoutManager createNewGridLayoutManager() {
        GridLayoutManager gridLayoutManager = new SmoothScrollGridLayoutManager(getActivity(), mColumnCount);
        gridLayoutManager.setSpanSizeLookup(new GridLayoutManager.SpanSizeLookup() {
            @Override
            public int getSpanSize(int position) {
                //NOTE: If you use simple integer to identify the ViewType,
                //here, you should use them and not Layout integers
                switch (mAdapter.getItemViewType(position)) {
                    case R.layout.week_header_item:
                        return mColumnCount;
                    default:
                        return 1;
                }
            }
        });
        return gridLayoutManager;
    }

    protected LinearLayoutManager createNewLinearLayoutManager() {
        return new SmoothScrollLinearLayoutManager(getActivity());
    }

    public void initData3Days() {
        listCategory = new ArrayList<>();
        listCategory.clear();
        cal = Calendar.getInstance();

        SCategory cat1 = new SCategory("B 1");
        cat1.setmName("Bobby Kim");
        for (int i= 1; i<= 9; i ++) {
            SShift shift = new SShift("BK " + i);
            shift.setmName("shift " + i);
            shift.setHeader(cat1);
            shift.setHidden(false);
            shift.setmCategory("Bobby Kim");
            shift.setmType(1);
            shift.setmStartTime(cal);
            shift.setmEndTime(cal);
            shift.setmId(i);
            cat1.addSubItem(shift);
        }
        listCategory.add(cat1);

        SCategory cat2 = new SCategory("K 1");
        cat2.setmName("Katherine Bell");
        for (int i= 1; i<= 5; i ++) {
            SShift shift = new SShift("KB " + i);
            shift.setmName("shift " + i);
            shift.setHeader(cat1);
            shift.setHidden(false);
            shift.setmCategory("Katherine Bell");
            shift.setmType(2);
            shift.setmStartTime(cal);
            shift.setmEndTime(cal);
            shift.setmId(i);
            cat2.addSubItem(shift);
        }
        listCategory.add(cat2);

        SCategory cat3 = new SCategory("O 1");
        cat3.setmName("Oliver Twist");
        for (int i= 1; i<= 5; i ++) {
            SShift shift = new SShift("OT " + i);
            shift.setmName("shift " + i);
            shift.setHeader(cat1);
            shift.setHidden(false);
            shift.setmCategory("Oliver Twist");
            shift.setmType(3);
            shift.setmStartTime(cal);
            shift.setmEndTime(cal);
            shift.setmId(i);
            cat3.addSubItem(shift);
        }
        listCategory.add(cat3);
    }

**Comment by davideas** [comment]
Sorry @longnguyencmg, log is not completed with your actions of collapsing and expanding that triggers the exception, what you gave me is only the initialization only which works...

**Comment by longnguyencmg** [comment]
Sorry, log is not enough. Actually, when I click on any header to collapse then it crashed. This is the log:

09-30 23:26:22.314 3108-3108/com.planday.ninetofiveapp I/FlexibleAdapter: Initially expanded 9 subItems on position=0
09-30 23:26:22.314 3108-3108/com.planday.ninetofiveapp I/FlexibleAdapter: Initially expanded 5 subItems on position=10
09-30 23:26:22.314 3108-3108/com.planday.ninetofiveapp I/FlexibleAdapter: Initially expanded 5 subItems on position=16
09-30 23:26:22.316 3108-3108/com.planday.ninetofiveapp I/FlexibleAdapter: Mapped viewType 2130968920 from SCategory
09-30 23:26:22.318 3108-3108/com.planday.ninetofiveapp V/FlexibleAdapter: onViewBound    Holder=ExpandableHeaderViewHolder position=0 itemId=-1 layoutPosition=0
09-30 23:26:22.318 3108-3108/com.planday.ninetofiveapp I/FlexibleAdapter: Mapped viewType 2130968918 from SShift
09-30 23:26:22.320 3108-3108/com.planday.ninetofiveapp V/FlexibleAdapter: onViewBound    Holder=ChildViewHolder position=1 itemId=-1 layoutPosition=1
09-30 23:26:22.322 3108-3108/com.planday.ninetofiveapp V/FlexibleAdapter: onViewBound    Holder=ChildViewHolder position=2 itemId=-1 layoutPosition=2
09-30 23:26:22.324 3108-3108/com.planday.ninetofiveapp V/FlexibleAdapter: onViewBound    Holder=ChildViewHolder position=3 itemId=-1 layoutPosition=3
09-30 23:26:22.327 3108-3108/com.planday.ninetofiveapp V/FlexibleAdapter: onViewBound    Holder=ChildViewHolder position=4 itemId=-1 layoutPosition=4
09-30 23:26:22.329 3108-3108/com.planday.ninetofiveapp V/FlexibleAdapter: onViewBound    Holder=ChildViewHolder position=5 itemId=-1 layoutPosition=5
09-30 23:26:22.331 3108-3108/com.planday.ninetofiveapp V/FlexibleAdapter: onViewBound    Holder=ChildViewHolder position=6 itemId=-1 layoutPosition=6
09-30 23:26:22.333 3108-3108/com.planday.ninetofiveapp V/FlexibleAdapter: onViewBound    Holder=ChildViewHolder position=7 itemId=-1 layoutPosition=7
09-30 23:26:22.334 3108-3108/com.planday.ninetofiveapp V/FlexibleAdapter: onViewBound    Holder=ChildViewHolder position=8 itemId=-1 layoutPosition=8
09-30 23:26:22.336 3108-3108/com.planday.ninetofiveapp V/FlexibleAdapter: onViewBound    Holder=ChildViewHolder position=9 itemId=-1 layoutPosition=9
09-30 23:26:22.338 3108-3108/com.planday.ninetofiveapp V/FlexibleAdapter: onViewBound    Holder=ExpandableHeaderViewHolder position=10 itemId=-1 layoutPosition=10
09-30 23:26:22.341 3108-3108/com.planday.ninetofiveapp V/FlexibleAdapter: onViewBound    Holder=ChildViewHolder position=11 itemId=-1 layoutPosition=11
09-30 23:26:22.342 3108-3108/com.planday.ninetofiveapp V/FlexibleAdapter: onViewBound    Holder=ChildViewHolder position=12 itemId=-1 layoutPosition=12
09-30 23:26:22.345 3108-3108/com.planday.ninetofiveapp V/FlexibleAdapter: onViewBound    Holder=ChildViewHolder position=13 itemId=-1 layoutPosition=13
09-30 23:26:22.348 3108-3108/com.planday.ninetofiveapp V/FlexibleAdapter: onViewBound    Holder=ChildViewHolder position=14 itemId=-1 layoutPosition=14
09-30 23:26:22.350 3108-3108/com.planday.ninetofiveapp V/FlexibleAdapter: onViewBound    Holder=ChildViewHolder position=15 itemId=-1 layoutPosition=15
09-30 23:26:22.351 3108-3108/com.planday.ninetofiveapp V/FlexibleAdapter: onViewBound    Holder=ExpandableHeaderViewHolder position=16 itemId=-1 layoutPosition=16
09-30 23:26:24.480 3108-3108/com.planday.ninetofiveapp V/FlexibleAdapter: Request to Collapse on position=0 expanded=true hasSubItemsSelected=false
**09-30 23:26:24.481 3108-3108/com.planday.ninetofiveapp V/FlexibleAdapter: Collapsed 9 subItems on position 0**

**Comment by longnguyencmg** [comment]
One more question, I tried to set the grid view from 3 columns to 5 columns dynamically but it's didn't work. For example, gridview is showing 3 columns then I click on a button to make it show 5 columns by setting "setLayoutManager(createNewGridLayoutManager())" again and notifydatachange. There was no luck for me. Can you help with this? Thank you very much.

**Comment by davideas** [comment]
@longnguyencmg, sorry for the late answer, and sorry again because I can't see the problem from the information you gave me. Therefore, I kindly ask you to share your project, so I can compile it and execute myself. You can create a temporary project in your account so I can clone it.

**Comment by davideas** [comment]
Closed for inactivity from user.
