### ISSUE TITLE
Drop event, without swapItems on move

### ISSUE THREAD

**Issue by volser** [davideas/FlexibleAdapter#176]
How to implement drop event without swapItems on drag?
I want to drag item into another item, not swap

**Comment by volser** [comment]
I have folders and files.

I want:
- Drag and drop files onto each other to create a folder 
- Drag and drop files into an already created folder to add to that folder

But:
1. Then Folder collapsed onMove don't work over folder
I guess, because
```
	@Override
	public boolean canDropOver(RecyclerView recyclerView, RecyclerView.ViewHolder current, RecyclerView.ViewHolder target) {
		return current.getItemViewType() == target.getItemViewType();
	}
```

2. I don't want swap items on drag, but
```
	@Override
	@CallSuper
	public boolean onItemMove(int fromPosition, int toPosition) {
		swapItems(mItems, fromPosition, toPosition);
		//After the swap, delegate further actions to the user
		if (mItemMoveListener != null) {
			mItemMoveListener.onItemMove(fromPosition, toPosition);
		}
		return true;
	}

```


How to implement what I need? Thanks

**Comment by davideas** [comment]
@volser, You can override the methods and write your own, so instead of move you delete the item you are dragging. But this library is not designed for tree views, you will have troubles.

**Comment by volser** [comment]
@davideas Thanks for feedback
I don't need treeview only 1 level

1. I can't override method in ItemTouchHelperCallback

2. I can override, but I should call super
@CallSuper

**Comment by volser** [comment]
3. And how catch Drop event?

**Comment by davideas** [comment]
@volser, I need to give the possibility to set a custom ItemTouchHelperCallback, where you can override everything, for moment you can't intercept everything but something.
It will take sometime to rewrite that part.

**Comment by volser** [comment]
Ok, thanks

**Comment by davideas** [comment]
@volser, with next SNAPSHOT, you can now set the `ItemTouchHelperCallback` and override `swipeItems()` with empty method.
`onItemMove()` is with `@CallSuper` because there's the call to the listener.
