### ISSUE TITLE
Sticky Headers above recyclerview's scrollbar

### ISSUE THREAD

**Issue by diman24** [davideas/FlexibleAdapter#177]
First of all thank you very much for the great library!
I am running into an issue of recyclerview's scrollbar being under the sticky header though.  When I just start the app the scrollbar is on top of the header, as it should be:

![1](https://cloud.githubusercontent.com/assets/20729338/18932408/360e4c90-859e-11e6-84e2-93c303b69e27.png)

but as soon as I start scrolling it goes under the header:

![2](https://cloud.githubusercontent.com/assets/20729338/18932407/360c03ae-859e-11e6-9757-88783951b342.png)

I am using beta 8.
What do you think?  Any suggestions?  
Thanks very much!

**Comment by davideas** [comment]
@diman24 , thanks for your message, you can check my Demo App here: [fragment_recycler_view.xml](https://github.com/davideas/FlexibleAdapter/blob/master/flexible-adapter-app/src/main/res/layout/fragment_recycler_view.xml).

The bottom layers are on top of everything else by default in Android.

**Comment by diman24** [comment]
@davideas, my apologies, I am trying to wrap my head around your reply but I am not fully understanding it.  Are you saying this is not possible to fix?
You said that bottom layers are on top of everything else in Android, this makes sense.  I just tried moving <include layout="@layout/sticky_header_layout"/> to the place above <RecyclerView> declaration, which actually worked, but now all moving cell are on top of the sticky header, not just the scrollbar, which is not much better..

**Comment by davideas** [comment]
@diman24, if you look the file I linked, you see that FastScrollbar is positioned at the bottom, and sticky header is below the RecyclerView, you need the FastScrollbar to be on the top of sticky header layout:
If you follow this order you will have Scrollbar over the StickyHeader that is over the RV.

**Comment by diman24** [comment]
That does not fix the original problem though, does it?  From what I can what you're offering is a workaround by using a custom built (and always visible!) scroll bar, which looks pretty alien to the RecycleView control.

**Comment by davideas** [comment]
It's not a work around, and many apps has fast scrollbar always visible, which is ok.
Finally, the fast scrollbar can be disabled.
Fast scrollbar is imported from another library, you can read in the wiki or readme.
