### ISSUE TITLE
How to handle additional click events

### ISSUE THREAD

**Issue by Aselox** [davideas/FlexibleAdapter#178]
FlexibleAdapter has a built-in onItemClick listener attachable to a class implementing the FlexibleAdapter.OnItemClickListener interface but what if each item in our recyclerview requires multiple onClick listeners?

In my case I have a list of items with a "follow" button on each one. I implemented the OnItemClickListener to open the detail view of the item but how am I supposed to handle the follow click event? I need to have the listener in the activity/fragment because the event should trigger a network call and I don't want to add additional dependencies to my model.

I'm sorry if this issue has already been addressed but I had the need to ask this here to find a better solution as currently I'm faking a longclick event in the bindviewholder method to pass the secondary click event to my fragment via the built-in OnItemClickListener interface.

Thank you

**Comment by davideas** [comment]
@Aselox, as the listeners instances are all in the Adapter, you can extend `FlexibleAdapter` and add your own listener, so that it is reachable from items view holders, by calling `mAdapter.listenerX` in the ViewHolder.

See what I did in the DemoApp with the FlipView click listener, you just need to create a new listener and use the extended Adapter instead of FlexibleAdapter.
Then you can implement the custom listener in your activity/fragment.

**Comment by Aselox** [comment]
Ok, thank you ;)

**Comment by nluetkemeyer** [comment]
@davideas Having some trouble with a similar issue. I have extended FlexibleAdapter and added my extra listeners, however, I am unsure how to make this adapter reachable from my (abstract sectionable) item's view holder. Could you clarify as to where exactly I should replace FlexibleAdapter with my own? Do I need to mess with FlexibleViewHolder at all? Let me know if you need any more clarification. Thanks!

**Comment by davideas** [comment]
@nluetkemeyer, you actually need a Cast of the adapter, you can apply it in the `ViewHolder` Constructor OR in the `createViewHolder()` before passing the adapter as parameter.
Suppose you have:
``` java
MyAdapter extends FlexibleAdapter  {
	public MyListener myListener;
}
```
In the item you should do:
``` java
@Override
MyViewHolder createViewHolder(FlexibleAdapter adapter, LayoutInflater inflater, ViewGroup parent) {
	return new MyViewHolder(inflater.inflate(getLayoutRes(), parent, false), (MyAdapter) adapter);
}
// ViewHolder Constructor
public MyViewHolder(View view, MyAdapter adapter) {
	super(view, adapter);
	adapter.myListener.onXXX();
}
// if you use the listener in the other VH methods you better create mAdapter field in the
// ViewHolder, so it is visible.
```

To avoid the cast, unfortunately, a deep refactoring is needed in the signature of the item interfaces and methods. Better to not add more generic types on the `IFlexible` class signature.

**Comment by yabee5566** [comment]
If the listener in the adapter trigger  the adapter to refresh, like calling API to get the newest data, it would cause a retain cycle. So I keep the adapter using WeakReference to fix it

 WeakReference<FlexibleAdapterExtend> adapterRef;
