### ISSUE TITLE
Enhancement: Setting the Selection to SINGLE or MULTI automatically works

### ISSUE THREAD

**Issue by pixis** [davideas/FlexibleAdapter#180]
It would be nice if calling mAdapter.setMode(SelectableAdapter.MODE_SINGLE); or multi would make selection work, without having to implement FlexibleAdapter.OnItemClickListener in the activity and calling actionModeHelper.onClick(position).

**Comment by davideas** [comment]
@pixis, well ActionMode is considered an extension so it cannot be part of the Adapter. There are functionalities that have to be controlled by the user in the Activity.
