### ISSUE TITLE
No animation, no actions, nothing

### ISSUE THREAD

**Issue by bloodcarter** [davideas/FlexibleAdapter#181]
Built sample app, everything works. Implemented custom item and other classes from https://github.com/davideas/FlexibleAdapter/wiki/5.x-%7C-Setting-Up. No effect. All items are displayed, but no animations, no actions, nothing works. Am I dumb or what?
``` java
public class ComplexJobFragment extends Fragment {

    @BindView(R.id.estimate_recycler_view) RecyclerView estimate;

    public ComplexJobFragment(){}

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {

        View rootView = inflater.inflate(R.layout.complex_order_fragment, container,
                false);
        ButterKnife.bind(this, rootView);

        List<IFlexible>  myItems = getDatabaseList();
        FlexibleAdapter<IFlexible> adapter = new FlexibleAdapter<>(myItems);//Experimenting NEW features (v5.0.0)
        adapter.setAnimationOnScrolling(true)
                .setAnimationOnReverseScrolling(true)
                .setAnimationInterpolator(new DecelerateInterpolator())
                .setAnimationInitialDelay(500L)
                .setAnimationDelay(150L)
                .setAnimationEntryStep(true);
        estimate.setItemViewCacheSize(0);//Setting ViewCache to 0 (default=2) will animate items better while scrolling down+up with LinearLayout
        estimate.setHasFixedSize(true);//Size of RV will not change
        estimate.setLayoutManager(new SmoothScrollLinearLayoutManager(getActivity()));
        estimate.setAdapter(adapter);
        adapter.setLongPressDragEnabled(true);
    //    estimate.setItemAnimator(new DefaultItemAnimator());


        return rootView;
    }

    public List<IFlexible> getDatabaseList() {
        List<IFlexible> list = new ArrayList<>();
        list.add(new EstimateItem("1", "Hello"));
        list.add(new EstimateItem("2", "World"));
        list.add(new EstimateItem("3", "World"));
        list.add(new EstimateItem("4", "World"));
        list.add(new EstimateItem("5", "World"));
        list.add(new EstimateItem("6", "World"));
        list.add(new EstimateItem("7", "World"));
        list.add(new EstimateItem("1", "Hello"));
        list.add(new EstimateItem("2", "World"));
        list.add(new EstimateItem("3", "World"));
        list.add(new EstimateItem("4", "World"));
        list.add(new EstimateItem("5", "World"));
        list.add(new EstimateItem("6", "World"));
        list.add(new EstimateItem("7", "World"));
        list.add(new EstimateItem("1", "Hello"));
        list.add(new EstimateItem("2", "World"));
        list.add(new EstimateItem("3", "World"));
        list.add(new EstimateItem("4", "World"));
        list.add(new EstimateItem("5", "World"));
        list.add(new EstimateItem("6", "World"));
        list.add(new EstimateItem("7", "World"));

        return list;
    }

}
```

**Comment by mdtuyen** [comment]
Now, animation need do with each item by implement AnimatedViewHolder for the holder. It is complex. I don't need special effects.

**Comment by davideas** [comment]
Hello, it's not more complicated than before. Now, the 2 types of animations as well separated, as I explained in the new WikiPage [Adapter Animations](https://github.com/davideas/FlexibleAdapter/wiki/5.x-%7C-Adapter-Animations), the wiki page is not completed (few time), but it's more than enough to understand how they work.

1. Scroll animations is part of the normal flow, the new method `scrollAnimators()` of `FlexibleViewHolder` deprecates the `getAnimators()` of the `FlexibleAdapter`, as before activation it not sufficient, it should be also implemented to set which animation you want. Read carefully the methods documentation in the Wiki page. **Note:** To have the scroll animation you need to initialize the adapter with a non-empty list in the constructor (as @bloodcarter is doing).
2. The Item Animation is instead executed when item is notified, therefore nothing to do with loading/scrolling, so I created the `AnimatedViewHolder`, that is optional. `DefaultItemAnimator` is the default from Android and doesn't extend the new `FlexibleItemAnimator`.

@bloodcarter, the id of `EstimateItem` is repetitive, you might have problems, depends how you implemented the `equals` method of the item.
You missed also `setAnimationOnScrolling()` activation.

**Comment by bloodcarter** [comment]
@davideas No, take a closer look. I'm calling setAnimationOnScrolling(true). I understood how sample app works, but it's VERY complex, is there some more simple tutorial out there? It's kinda tricky to learn all this stuff from your wiki. Where should I learn about AnimatedViewHolder, etc.??? And also you don't use it in your sample app. Instead, you override scrollAnimators(). I'm confused! :)

**Comment by davideas** [comment]
@bloodcarter, sorry, I missed it in your code :-)
However, you got the point that, you need to add which Animator will be executed.

For the rest, you are right that the demo is complex, but I am not going to change it, not soon. Maybe the wiki page for the demoApp might help you, please go to read it.
I preferred to use fragments instead of multiple activities, so many things are in common.

The `AnimatedViewHolder` is used. You can also learn it a little, from the Wiki page and from the javadoc in the classes. The Item Animator classes are not part of the library, only the base class `FlexibleItemAnimator`.

If you need specific help, you can write here.

**Comment by davideas** [comment]
@bloodcarter, need more help?

**Comment by bloodcarter** [comment]
@davideas Yes, but not now, I implemented adapter without bells and whistles for now and will go back to it a bit later.  Thanks.
