### ISSUE TITLE
Header item not created on onLoadMoreComplete

### ISSUE THREAD

**Issue by mithrann** [davideas/FlexibleAdapter#183]
1) For Bugs / Support

version 5.0.0-b8 android 6
Header Item not displaying for new Dataset on LoadMoreItem

I tried to use EndlessScrollListener with header and section. But the problem is when i update list using onLoadMoreComplete(items). List is updating but header section for the new data is not getting created.

To be more clear 
1. I am using flexible adapter to load data with header (alphabet character)& section
2. For a particular case i am using enlessScrolling. When i tried to append the adapter with new data using onLoadMoreComplete(Items).
3.List is getting updated fine but the section for the new data is coming.

**Comment by davideas** [comment]
@mithrann, you have to be more specific.....
For example the person, who opened the issue before yours, use the same way but he doesn't have your problem.

**Comment by mithrann** [comment]
@davideas Is it fine now? Thanks.

**Comment by davideas** [comment]
@mithrann, need more help?

**Comment by mithrann** [comment]
@davideas  Yes. How do i create header sections while i append data to list using onLoadMoreComplete()

**Comment by davideas** [comment]
@mithrann, if it's a new section, the header item will be automatically displayed:
`onLoadMoreComplete()` internally calls `addItems()`, which will take care of the new headers.

Then, there are 2 use cases for Sections, you can read the Wiki page [Headers & Sections](https://github.com/davideas/FlexibleAdapter/wiki/5.x-%7C-Headers-and-Sections)

**Comment by CharuTulasyan** [comment]
@davideas setDisplayHeadersAtStartUp(true) is not working for me. I am still not able to add new headers in the list. Could you please elaborate how it will be fixed.

**Comment by davideas** [comment]
@CharuTulasyan, `setDisplayHeadersAtStartUp(true)` is only a startup configuration, then you need to prepare the list to pass to the Adapter, accordingly:

As explained in the Wiki and showed in the demoApp, the list you prepare should contain only the normal items without headers, when you set that configuration the adapter will display the headers too.
At the point of loading more, you add only the items which internally have an header object (i suppose new header object).
Enable logs to see what's the Adapter is doing, it may help you to understand the functioning.

PS. If you need specific help, better to open a new issue for your case.
