### ISSUE TITLE
I can't remove area between header and sampleItem

### ISSUE THREAD

**Issue by ulx** [davideas/FlexibleAdapter#186]
For Bugs / Support
- library version 5.0.0-b8 android 6
 - I can don't remove area between header and sampleItem
[https://s17.postimg.org/wnpydasvj/screenshot_2016_10_06_11_58_01_402.png](url)

- _I create adapter_ 

`private void initListView(){

        rvOperationsAdapter = new HistoryOperationAdapter(null);
        rvOperationsAdapter.setRemoveOrphanHeaders(false)
                .setNotifyChangeOfUnfilteredItems(true);
        rvOperations.setLayoutManager(createNewLinearLayoutManager());
        rvOperations.setAdapter(rvOperationsAdapter);
        rvOperations.setHasFixedSize(true);

        rvOperations.setItemAnimator(new DefaultItemAnimator());
        rvOperations.addItemDecoration(new DividerItemDecoration(getContext(), 0, 24));
        rvOperationsAdapter
                .setLongPressDragEnabled(true)
                .setHandleDragEnabled(true)
                .setSwipeEnabled(true)
                .setUnlinkAllItemsOnRemoveHeaders(true)
                //Show Headers at startUp, 1st call, correctly executed, no warning log message!
                .setDisplayHeadersAtStartUp(true)
                .enableStickyHeaders()
                //Simulate developer 2nd call mistake, now it's safe, not executed, no warning log message!
                .setDisplayHeadersAtStartUp(true)
                //Simulate developer 3rd call mistake, still safe, not executed, warning log message displayed!
                .showAllHeaders();

        rvOperationsAdapter.addUserLearnedSelection(filterItem, true);
        rvOperationsAdapter.setEndlessScrollListener(new LoadMoreListner(), new ProgressItem());
        rvOperationsAdapter.setEndlessScrollThreshold(1);

    }  `

- _add Items_

`   public void setListOperations(List<HistoryOperation> listOperations) {

        while (rvOperationsAdapter.getItemCount() > 1){
            rvOperationsAdapter.removeItem(1);
        }
        rvOperationsAdapter.onLoadMoreComplete(createItems(listOperations));
        rvOperationsAdapter.notifyDataSetChanged();
        Log.d(TAG, rvOperationsAdapter.getItemCount() + "");
        showData();
    } `

- _create items_

'
 private List<AbstractFlexibleItem> createItems(List<HistoryOperation> listOperations) {
        final List<AbstractFlexibleItem> newItems = new ArrayList<>(listOperations.size());
        String prev = "";
        HeaderItem header = null;
        for (HistoryOperation item : listOperations) {
            header = new HeaderItem(item.id + "");
            header.setTitle(DateUtils.parseDate(item.date));
            if (prev.equals(header.getTitle())) {
                header.setHidden(false);
            }else {
                newItems.add(header);
            }
            prev = header.getTitle();
            HistoryOperationItemView historyOperationItemView = new HistoryOperationItemView(item, null);
            String name = item.note != null ? item.note.name : item.id + "";
            historyOperationItemView.setTitle(name);
            newItems.add(historyOperationItemView);
        }
        return newItems;
    }

**Comment by davideas** [comment]
@ulx, it's very simple, it's the `DividerItemDecoration` constructor, check the javaDoc for the 3 constructors in this class. You can remove the sectionOffset.

**Comment by ulx** [comment]
Thanks!!!
How can I ever thank you?
