### ISSUE TITLE
Natural SwipeAnimationDuration

### ISSUE THREAD

**Issue by jeanpimentel** [davideas/FlexibleAdapter#188]
Hi! Thanks for this awesome library.

I have a question/suggestion on SwipeAnimationDuration.
It would be possible to calculate my swipe velocity, using _onActionStateChanged_ for example and then _onItemSwipe_, use this value to AnimationDuration?
My intention is that the animation should continue with the same velocity as my movement.

Thanks

**Comment by davideas** [comment]
@jeanpimentel, I don't think it's possible.
Thanks for the message.
