### ISSUE TITLE
Items placed under wrong header.

### ISSUE THREAD

**Issue by ferbeb** [davideas/FlexibleAdapter#189]
I am not able to find out why my items are placed under the wrong sticky header. I debugged it by setting the text of the SectionableItem to getHeader().getTitle() in it's onBindViewHolder. Every item has set the right HeaderItem, but is still placed under an entirely different header.

My Headeritem looks like this:

``` java
public class MyHeaderItem extends AbstractHeaderItem<HeaderViewHolder> {
	private String title;

	public MyHeaderItem (String title) {
		this.title = title;
		setSelectable(false);
	}

	@Override
	public int getLayoutRes() {
		return R.layout.item_my_header;
	}

	@Override
	public HeaderViewHolder createViewHolder(FlexibleAdapter adapter, LayoutInflater inflater, ViewGroup parent) {
		return new HeaderViewHolder(inflater.inflate(getLayoutRes(), parent, false), adapter, true);
	}

	@Override
	public void bindViewHolder(FlexibleAdapter adapter, HeaderViewHolder holder, int position, List payloads) {
		holder.title.setText(title);
	}

	@Override
	public boolean equals(Object o) {
		if(o instanceof  MyHeaderItem)
		{
			return ((MyHeaderItem)o).title.equals(title);
		}else
			return false;
	}

	public String getTitle() {
		return title;
	}
}
```
I call super(header) in the constructor of the SectionableItem, as I said, I verified the corret HeaderItems are set by calling getHeader in the Sectionables onBindViewHolder. 
Do you have any idea what could be wrong? Thanks!

**Comment by ferbeb** [comment]
A characteristic seems to be that correct items are placed in all headers but the last, which will contain way more items than it should. Those items are missing in the previous headers, but there don't seem to be wrong items in the non-last headers. So somehow most of the items end up in the last header regardless of what their getHeader() returns.

**Comment by davideas** [comment]
@ferbeb, what you can try is:
- enable Adapter logs
- see if when you create the list, before the Adapter receive it, the list is what you expect, considering the use case 1 and 2 in the wiki page. (Use debugging and some breakpoints).
- check if after the Adapter initialization (without any action), the list is the same
- enable properties one by one, and see if the list is the same.

I don't have enough elements to discover why you have that. Try to paste the logs here with the full list when it's fully scrolled.

**Comment by ferbeb** [comment]
@davideas 
Thanks for your help. 
I think I made a rather stupid mistake. The items are supposed to be sorted by header, right? 
I triple-checked that the correct header is set, but it never occured to me that it would make sense for the items to be sorted by header to have a consistent order of the headers.

**Comment by davideas** [comment]
@ferbeb, the items are not sorted, are shown as you create the list, so you are responsible to create it sorted.
Headers are shown on the top of the first item processed, if a header is already shown, and you have an item with that header not in order, then this item will appear under another section, even if the header is correct.

**Comment by ferbeb** [comment]
Yes, that makes sense. I don't know where I got the idea that they would automatically be sorted to the right header - that would not really make sense considering that you never specify any order for the headers. 

Thanks for this library and the fast responses! 👍
