### ISSUE TITLE
example based on Fragment instead of Activity

### ISSUE THREAD

**Issue by taiko000** [davideas/FlexibleAdapter#19]
if the example app would be based on a Fragment instead of an Activity it would be much easier to adapt it for simple projects.

**Comment by danielpassos** [comment]
@taiko000 Not sure if I got your point. How the `Fragment` instead of `Activity` could make the example easier to adapt . The library has no dependency on `Activity`. I mean you can use whatever class just need to implement the same methods/interface that `Activity` are implementing.

**Comment by Rainer-Lang** [comment]
Maybe some more docu (about internals) could be more helpful.

**Comment by davideas** [comment]
@taiko000, if the purpose is to have a RecyclerView and its adapter in a Fragment, then _danielpassos_ answered correctly: in the Fragment you just import the adapter and implement the interface you need on your Fragment, not more not less the example Activity does.

@Rainer-Lang, do you mean to describe the Adapter functions in the Wiki, similar to Javadoc?

**Comment by Rainer-Lang** [comment]
@davideas Not exactly. More schematic, how all work together and can be used.

**Comment by davideas** [comment]
@Rainer-Lang, I'm not sure to have well understood, can you be more specific? thanks.

**Comment by taiko000** [comment]
The sample application is pretty usable as a base for some simple projects since everything around the FlexibleAdapter is already implemented. That's why it would be even more usable if it used a Fragment.
