### ISSUE TITLE
Snackbar action color

### ISSUE THREAD

**Issue by jeanpimentel** [davideas/FlexibleAdapter#190]
At `UndoHelper`, method
`public Snackbar remove(List<Integer> positions, @NonNull View mainView,
                           CharSequence message, CharSequence actionText,
                           @IntRange(from = 0) int undoTime)` creates and shows a Snackbar, but I need to change the action color.

The method returns a snackbar instance, and I can call `setActionTextColor` but the method `show` was already called.

What are the alternatives here?
1. Create a new `remove` method with extra argument.
2. Create a new `remove?!?` method that returns snackbar but does not show.
3. ...?

What is your suggestion? I can make a PR with this.

**Comment by davideas** [comment]
Hello @jeanpimentel, why not. You can create a PR for branch **rc1**, create a method `withActionTextColor(int color)` and then in the method `remove()` use the field `mActionTextColor`.

I will publish it as SNAPSHOT, the it will be released for the rc1.
