### ISSUE TITLE
AsyncFilter fatal error

### ISSUE THREAD

**Issue by kasterlod** [davideas/FlexibleAdapter#191]
Hello =]

Your work is incredible! I've found error in async filter, I hope that it's not hard to repair it.
The app crash when I try to write space in the SearchView

java.lang.NullPointerException: null object reference size()
FlexibleAdapter.executeNotifications(FlexibleAdapter.java:3478)

lots of greetings =]

**Comment by davideas** [comment]
Hello @kasterlod, thanks for the message, yes it's a trivial bug, I will fix it in the next SNAPSHOT.
