### ISSUE TITLE
FastScroller inside the library

### ISSUE THREAD

**Issue by davideas** [davideas/FlexibleAdapter#20]
Evaluate if the external library _FastScroller_ should be included in this library.

**Comment by davideas** [comment]
**To everybody**

Please let me know if you desire this feature in my library.

_It's missing poll feature in Github_ :-/

**Comment by danielpassos** [comment]
FastScroller is always welcome :)

Maybe a way to enable/disable it is a good feature

**Comment by davideas** [comment]
It will be available from 5.0.0-b2.

**Comment by davideas** [comment]
This will probably change, in favor of [MaterialScrollBar](https://github.com/krimin-killr21/MaterialScrollBar).
