### ISSUE TITLE
Stick headers not working

### ISSUE THREAD

**Issue by Sifrazooy** [davideas/FlexibleAdapter#203]
Stick headers not working.

Last library version, Android version: 24
Expected: Stick headers to be working after setting the sticky header flag, adding the headers id's and include for the frame layout. Also, added the relevant items to the header.
Actual: Headers do show up in the right position but the headers is not sticky.

``` java
adapter = new FlexibleAdapter<>(items, this);
layoutManager = new ScrollLinearLayoutManager(getActivity(),LinearLayoutManager.VERTICAL, false);

recyclerview.setLayoutManager(timestampsLM);
recyclerview.setAdapter(timeTrackingAdapter);
recyclerview.setHasFixedSize(true);
adapter.setDisplayHeadersAtStartUp(true).enableStickyHeaders();
```

``` xml

<RelativeLayout
xmlns:android="http://schemas.android.com/apk/res/android"
android:layout_width="match_parent"
android:layout_height="wrap_content"
android:id="@+id/sticky_header_container">
```

`````` xml
<android.support.v7.widget.RecyclerView android:id="@+id/recycler_view" android:layout_width="match_parent" android:layout_height="match_parent"/> <include layout="@layout/sticky_header_layout"/>```

Thanks
``````

**Comment by davideas** [comment]
@Sifrazooy, please enable the logs before the creation of the Adapter (`FlexibleAdapter.enableLogs(true)`). So you can see what the Adapter is doing.

This calls are correct?
``` java
adapter = new FlexibleAdapter<>(items, this);
...
recyclerview.setAdapter(timeTrackingAdapter);
```

`IHeader` for items should also be implemented, I guess you already have read the Wiki pages.
