### ISSUE TITLE
[DemoApp] SwipeToRefresh, circle is white for the first refresh

### ISSUE THREAD

**Issue by kasterlod** [davideas/FlexibleAdapter#204]
When swiping to refresh for the first time then there is only white circle without arrow and fade animation. For the next times everything is ok.

greetings~~

**Comment by davideas** [comment]
@kasterlod, please be more clear, maybe with a screenshot, I don't understand why you talk about `SwipeToResfresh` and the `FastScroller` together.

**Comment by kasterlod** [comment]
Oh my godness, I'm really sorry for my nonsense.  I am recently very distracted. Of course I meant about swipe to refresh. When you swipe for the first time then only white circle background is vosoble without any Arrow with fade and rotate animation. 

Greetings and thank you for your patience :)

**Comment by davideas** [comment]
Well, I see it only now and I don't know why, I think it's a bug of Support library, I'm still waiting a fix for setting false the enabled flag in the layout. Recently they have made a change on this component, but sincerely I don't know why.
I don't think it is related to this library anyway.

**Comment by davideas** [comment]
If you want to investigate, you are welcome, but it's not a worth to spend time on it.

**Comment by davideas** [comment]
@kasterlod, with support library v25, circle animation is back.
