### ISSUE TITLE
FlexibleAdapter with Cursor support

### ISSUE THREAD

**Issue by kumarswamy-repo** [davideas/FlexibleAdapter#208]
There are constructors in FlexibleAdapter which will take List of Items. But is there any other way to work with Cursor directly

**Comment by davideas** [comment]
@kumarswamy-repo, short answer is no. Long answer is:

- Cursor does not give detailed information on what has changed, it is harder to animate changes properly.
- I think, most of the functionalities I added recently would not be possible using the cursor. I think the expandable, or the headers: I often make a check of existence of a specific item in the list, calling the Cursor it will make it impossible to manage, also from the performance point of view!
- And indeed, reading around, some people complain about the performance for big list as well.
- The only advantage I see is that, it loads in memory only the items that are currently displayed, but if you scroll or swing or fastscroll, it must pull the row 1 by 1? how often a user scroll a lot or until the end?
- Items are very often loaded from a network, managing them in a List is much better.

I think you can change the Cursor with the _LoadingMore_ feature, and using an ORM library will make it easier for you to decouple the presentation layer from the model layer.

There are libraries that support the Cursor, the point is: only that is supported.
