### ISSUE TITLE
Problem with handle drag

### ISSUE THREAD

**Issue by bejibx** [davideas/FlexibleAdapter#211]
Library version v5.0.0-b7.

I found a problem with handle drag functionality. First drag not being handled correctly. I made a [gif illustrated this issue](http://giphy.com/gifs/3oz8xDhOCixFJDg4N2). The problem is ```ItemTouchHelper``` firstly gets initiallized in ```FlexibleViewHolder#onTouch(View, MotionEvent)```, so helper don't register initial touch event and first drag gets messed up. For now workaround is to call ```FlexibleAdapter#getItemTouchHelper()``` once right after setting adapter on ```RecyclerView```.

**Comment by davideas** [comment]
@bejibx thanks again, but I already changed approach after the improvement of issue #176, however in b7 you have `setHandleDragEnabled()`, that in the new code it becomes mandatory, so if not activated before, the handle drag should not work.

Already available in the Snapshot.
