### ISSUE TITLE
when add a new Item,how to make it default is to expand?

### ISSUE THREAD

**Issue by JakeWoki** [davideas/FlexibleAdapter#212]
`eu.davidea.samples.flexibleadapter.fragments.FragmentExpandableSections`

``` Java
mAdapter.setEndlessScrollListener(this, new ProgressItem())
				.setEndlessScrollThreshold(1);
```

``` Java
@Override
	public void onLoadMore() {
		new Handler().postDelayed(new Runnable() {
			@SuppressWarnings("unchecked")
			@Override
			public void run() {
				final List<AbstractFlexibleItem> newItems = new ArrayList<>();
				for (int i=0; i<10; i++) {
					newItems.add(DatabaseService.newExpandableSectionItem(1));
				}
				mAdapter.onLoadMoreComplete(newItems);
			}
		}, 2000);
	}
```
It is collapse.throw exception when click ExpandableHeaderItem
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 51(offset:-1).state:58

**Comment by davideas** [comment]
@JakeWoki, from the demoApp you can expand the items in 2 ways:

``` java
//Callback the Adapter to notify the change:
//- New items will be added to the end of the list
//- When list is null or empty, ProgressItem will be hidden
mAdapter.onLoadMoreComplete(newItems);
DatabaseService.getInstance().addAll(newItems);

//Expand all Expandable items: Not Expandable items are automatically skipped/ignored!
for (AbstractFlexibleItem item : newItems) {
	//Simple expansion is performed:
	// - Automatic scroll is performed
	//mAdapter.expand(item);

	//Initialization is performed:
	// - Expanded status is ignored(WARNING: possible subItem duplication
	//   if called twice for the same item)
	// - Automatic scroll is skipped
	mAdapter.expand(item, true);
}
```

**Comment by JakeWoki** [comment]
@davideas 
``` Java
@Override
	public void onLoadMore() {
		new Handler().postDelayed(new Runnable() {
			@SuppressWarnings("unchecked")
			@Override
			public void run() {
				final List<AbstractFlexibleItem> newItems = new ArrayList<>();
				AbstractFlexibleItem newItem = DatabaseService.newExpandableSectionItem(1);
				newItems.add(newItem);

				mAdapter.onLoadMoreComplete(newItems);
				DatabaseService.getInstance().addAll(newItems);
				for (AbstractFlexibleItem item : newItems) {
					mAdapter.expand(item, true);
				}
			}
		}, 1000);
	}
```
It is also collapse.

**Comment by davideas** [comment]
@JakeWoki, I'm sure it works, the demoApp is ok.
You, that are experimenting this library, should keep **always** the log of this library enabled, until you deploy your app. Also reading more the wiki pages will help you a lot: many questions you asked are already answered in the wiki. (I know that some pages are not done nor finished or not so clear: I need more tranquility and time to complete that part).

In this case you should see _"Initially expanded Y subItems on position=X"_. In other cases you will see other logs and the possible reason why something doesn't happen. The boolean `true` is an initialization, and skip every additional check to add the subItems anyway.

As last instance, you can always debug and see the reason/reasons.

**Comment by JakeWoki** [comment]
I used Beta version: v5.0.0-b8,It not works.Can you commit it?

**Comment by davideas** [comment]
Beta8 is ok for that. What you see in the logs?

**Comment by JakeWoki** [comment]
@davideas SubItem Adds to the first position of the ExpandableHeaderItem

**Comment by davideas** [comment]
The expandable is expanded with sutItems, so what doesn't work? i don't understands, explain better and be more specific also with logs.

**Comment by JakeWoki** [comment]
I find the problem

**Comment by davideas** [comment]
What was?

**Comment by JakeWoki** [comment]
id are the same,so SubItem Adds to the first position of the ExpandableHeaderItem.sorry
