### ISSUE TITLE
Header with expandable as subItem

### ISSUE THREAD

**Issue by JakeWoki** [davideas/FlexibleAdapter#213]
![-1](https://cloud.githubusercontent.com/assets/6948411/19620568/e0cbc140-98b2-11e6-8283-51e1faa8d796.png)

View may have more.

``` Java
public interface IExpandable<VH extends ExpandableViewHolder, S extends IFlexible>
		extends IFlexible<VH>
```
`S` only allows one type,how can I do?

**Comment by davideas** [comment]
@JakeWoki, see issue #209, only one can be of type `IHeader`, otherwise it doesn't work.

**Comment by JakeWoki** [comment]
I drew a picture again.
![qq 20161023104356](https://cloud.githubusercontent.com/assets/6948411/19623797/e197ed0a-990d-11e6-8b2d-ac49ab2786d7.png)

**Comment by davideas** [comment]
@JakeWoki. Yes, this doesn't change what I wrote you before.
TextView or Other + View are in the same expandable item.
