### ISSUE TITLE
Simple example question

### ISSUE THREAD

**Issue by stargie** [davideas/FlexibleAdapter#216]
HI,

I created testing app with 1 main activity, 1 fragment with recycler view and simple item with like 1 label. I managed to set up recycler view and display items but after reading documentation and checking sample app i cant find out how to setup selecting an item. I have no idea how to handle onClick and OnLongClick in fragment for clicng in item or selecting it for deletion or reordering.
Is there any simple example how to use it ?

**Comment by davideas** [comment]
@stargie, are you looking only the single selection when user clicks on the full item (but also an internal view)?
If yes, you can enable the selection mode `SINGLE`, follow the docs [here](https://github.com/davideas/FlexibleAdapter/wiki/5.x-%7C-Selection-Modes#single-selection-single).

If you also need the multi selection, I've simplified with ActionModeHelper, follow the docs [here](https://github.com/davideas/FlexibleAdapter/wiki/5.x-%7C-ActionModeHelper#configuration--initialization).
The demo App has selectionMode example, where usually, the action mode is for the Activity.

If something of these docs is not clear, please be more specific.

**Comment by stargie** [comment]
Hey,
i was reading docs and looking at selectionMode example. LIstenners for clicks are defined in that fragment but htey are not fired on clicks. After few hours i noticed they are forwarded to activity by adapter configuration. That part is confusing and unclear.
Now i managed to selection working but now i have 2 toolbars visible. Probably something i am missing again. Any idea what ?

**Comment by davideas** [comment]
The listeners are usually initialized through the Adapter constructor. It's in the advanced part of "Setting Up" wiki page. I'm sorry you didn't see it.
The Adapter receives the listeners and the event is automatically propagated from the `FlexibleViewHolder` to the Activity that implements all of them not iin the fragment. But you can apply to the fragment as you wish, just initialize them by calling the constructor or the proper method.

About the double toolbar: it is the configuration of the styles and layout, _Overflow_ something... Watch what I did in the demoApp or search in Stackoverflow.com.

**Comment by stargie** [comment]
Thanks. I found out that i can change click receiver from activity to fragment and there handle clicks :)
Double toolbar - i copied styles from demo app and its working now but how to set up colors of new toolbar ? All i can see is that during action mode configuration i'am passing id of menu to show and then handle clicks in activity but how to set colors of that new toolbar ? I am assuming its created automatically with specific theme applied ?

**Comment by davideas** [comment]
Yes it's automatically generated by Android with the accent color. You can override the style but you have to search how to, in some blogs or stackoverflow.com.
