### ISSUE TITLE
How to create RecyclerView with multiple view type?

### ISSUE THREAD

**Issue by tsadoklf** [davideas/FlexibleAdapter#218]
Hi, 

Does FlexibleAdapter support multiple view types "out-of-the-box"?

I tried to set the adapter with a list of two types of items that each inherit from AbstractModelItem but I got ClassCastException (as id the library does not distinguish between the two types and their view holders). 

Thank you.

**Comment by davideas** [comment]
Hello @tsadoklf, there's `getLayoutRes()` in the item interfaces, I didn't create a second function `getViewType()` because every different view type have already a different layout, and they are integer as well.
ClassCast occurse because you have the same layout for 2 different classes.
Basically, I don't see the reason why 2 items should have the same layout.

**Comment by tsadoklf** [comment]
Hello @davideas, you're perfectly right. I used different types but the the same layout. When I changed the layout everything worked as expected. 

For me a good reason for supporting different types that use same layout is when I have a simple/complex generic layout that I'd like to implement differently without having to have multiple "copies" of the same layout. 

Another good reason for me is that it's more robust to my humble opinion to support types rather than just layouts.

I'd like to extend my appreciation to your very professional work. It's not a simple task to achieve the level of perfection that you've achieved. Keep on the good work. Thank you. 

Tsadok

**Comment by davideas** [comment]
@tsadoklf, thank you for the compliments! 👍 

Generic layouts and no copies as you say, for me, means that inside you have multiple views that you can use in different item. Well, still better to create different layouts, no? so, I believe it still belongs to a single item.

When Android will change the R.id as integer we will adapt the library too. As it is now, we have 1 method less to implement.
