### ISSUE TITLE
Expandable list with frame layout(+fragments).

### ISSUE THREAD

**Issue by shin2jhoon** [davideas/FlexibleAdapter#219]
Hello. I have curious question, so want to ask you.

I want to make expandable list and each child item has own frame layout.
in frame layout, i want to make a fragment and replace it under specific condition.

What i did is, just make frame layout in child item, and get its id in bindViewHolder, and just replace it. Like this.

 ```
 public static class PollViewHolder extends FlexibleViewHolder {
        private FrameLayout pollFrame;
        private RelativeLayout prevLayout;
        private RelativeLayout nextLayout;
...
        public PollViewHolder(View view, FlexibleAdapter adapter) {
            super(view, adapter);
            pollFrame = (FrameLayout) view.findViewById(R.id.stock_open_poll_container);
            prevLayout = (RelativeLayout) view.findViewById(R.id.poll_prev_layout);
            nextLayout = (RelativeLayout) view.findViewById(R.id.poll_next_layout);
...
        }
    }

```
and

```
`` @Override
    public void bindViewHolder(FlexibleAdapter adapter, final PollViewHolder holder,
                               int position, List payloads) {
...
        customAdapter = (FavorStockListAdapterTest) adapter;
...
 holder.prevLayout.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
getSupportFragmentManager().beginTransaction().replace(R.id.stock_open_poll_container, 
            }
        });

        holder.nextLayout.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
getSupportFragmentManager().beginTransaction().replace(R.id.stock_open_poll_container, 
            }
        });
``

```
But when i expand the multiple items, it doesn't work. Only one expanded item works well what i want to do.

i think, viewing only one frame layout is related with its layout Id, so changed the strategy. 
I set the frame layout Id dynamically, and passing its id, change the frame layout.
Like this.

```
@Override
    public void bindViewHolder(FlexibleAdapter adapter, final PollViewHolder holder,
                               int position, List payloads) {
...
        final int tempId = View.generateViewId();
        holder.pollContainer.setId(tempId);

 holder.prevLayout.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
getFragment(tempId);
            }
        });

        holder.nextLayout.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
getFragment(tempId);
            }
        });
}

public void getFragment(int layoutId){
customAdapter.getFragmentManager().beginTransaction().replace(layoutId, FavorPollDetailFragment.newInstance(stockInfo, currentDate, dateType, changeDate)).commit();
}

```
like this.

I can show multiple child item with fragment using this approach.
But this method also has problem.

That is duplicate its layout. I don't know why but no.1's child frame layout, still remains when i expand no.2 item.
Moreover when I scroll it bottom from top and getting recycled, layout id go crashed so app goes down.

I'm not certainly that i explained well.. if you need more description, i'll attach some picture to give you more detail.

Anyway, is there any other approaches that each child item has independent frame layout and its fragment ? 

Thanks!

**Comment by davideas** [comment]
@shin2jhoon, thanks for the message, yours is a strange question and approach.

I suppose you have a different view for each fragment, why don't you create a different item which display that specific view only?

Fragments are interchangeable parts of the screen, I never saw something like your layout, _RecyclerView_ manages lists of different items but once they scroll they are recycled for a new data binding, you loose all previous status of "that fragment".

So, I would not use fragments as items in this component: you should use different items/views and update the content of your expandable based on your status. To change view you can remove/add subitems and even update the subitems if they are currently displayed, so they can be rebound.

**Comment by shin2jhoon** [comment]
@davideas I think, I attempt to wrong approach as you said. Thank you for your reply. I'll considerate your advice and find other way !
