### ISSUE TITLE
GridLayoutManager with Custom Drag and Swipe Flags

### ISSUE THREAD

**Issue by DavidCorrado** [davideas/FlexibleAdapter#221]
I have a case that I would like to use a GridLayoutManager but be able to treat some of the headers the same as the way you handle LinearLayoutManager.  So it would be nice to be able to override swipeflags for grid layout like we could with the linearlayoutmanager.  So the default can be 0 but I can override the swipe flags.  

Also since I want to have something like a linearlayoutmanager I would like to override drag to allow just for left and right.

Below is the file and line of code that I would be interested to change.  If you are not interested in this then do you have any way I can do this without copying all of your files into my repo?

ItemTouchHelperCallback.java
`

     @Override
	public int getMovementFlags(RecyclerView recyclerView, RecyclerView.ViewHolder viewHolder) {
		RecyclerView.LayoutManager layoutManager = recyclerView.getLayoutManager();
		int dragFlags;
		int swipeFlags;
		//Set movement flags based on the Layout Manager and Orientation
		if (layoutManager instanceof GridLayoutManager || layoutManager instanceof StaggeredGridLayoutManager) {
			dragFlags = ItemTouchHelper.UP | ItemTouchHelper.DOWN | ItemTouchHelper.LEFT | ItemTouchHelper.RIGHT;
			swipeFlags = 0;
		} else if (Utils.getOrientation(layoutManager) == LinearLayoutManager.VERTICAL) {
			dragFlags = ItemTouchHelper.UP | ItemTouchHelper.DOWN;
			swipeFlags = mSwipeFlags > 0 ? mSwipeFlags : ItemTouchHelper.LEFT | ItemTouchHelper.RIGHT;
		} else {
			dragFlags = ItemTouchHelper.LEFT | ItemTouchHelper.RIGHT;
			swipeFlags = mSwipeFlags > 0 ? mSwipeFlags : ItemTouchHelper.UP | ItemTouchHelper.DOWN;
	}
`

**Comment by davideas** [comment]
@DavidCorrado, you can override and customize the ItemTouchHelper, please check the issue #176, then you will have to use the Snapshot version until next official pre-release. Check also the issue 39 for all the modifications on top of beta8.

**Comment by DavidCorrado** [comment]
Thanks!
