### ISSUE TITLE
moveItem() for the first visible item cause scrolling

### ISSUE THREAD

**Issue by yamelkaya** [davideas/FlexibleAdapter#222]
Hi @davideas! Seems like I found the issue in moving item. Steps to reproduce: 

1. Scroll to some item (make it first but not fully visible)
2. Call `moveItem(firstVisibleItemPosition, anyPosition)`
3. Item moved to proper position and scrolled to it (but excepted to be moved only)

In my original code I try to move item when some property changed. So `anyPosition` is calculated. 

```
        updateItem(itemVM,null);
        int oldPosition = getGlobalPositionOf(itemVM);
        int newPosition = calculatePositionFor(itemVM);
        if (oldPosition != newPosition){
            moveItem(oldPosition,newPosition,null);
        }
```
Here is log when I `moveItem()`:

```
V/FlexibleAdapter: moveItem fromPosition=1 toPosition=4
V/FlexibleAdapter: onViewBound    Holder=ItemViewHolder position=4 itemId=-1 layoutPosition=4
V/FlexibleAdapter: onViewBound    Holder=ItemViewHolder position=16 itemId=-1 layoutPosition=16
V/FlexibleAdapter: onViewBound    Holder=ItemViewHolder position=17 itemId=-1 layoutPosition=17
V/AnimatorAdapter: Clear notified for scrolling Animations

```
Please checkout an example https://github.com/yamelkaya/FlexibleAdapterMoveItem.

**Comment by davideas** [comment]
@yamelkaya, sadly I can't fix that behavior because is not caused by my implementation :-(

Please read this original issue: https://code.google.com/p/android/issues/detail?id=99047.

Try to add `recyclerView.scrollToPosition(fromPosition);` but that is **only** for the fromPosition as first visible position, it doesn't occur if you move another position.

**Comment by yamelkaya** [comment]
@davideas, I see now... Thanks a lot for reply anyway. I am closing the issue.
