### ISSUE TITLE
How to load data from a Json API with FlexibleAdapter?

### ISSUE THREAD

**Issue by izzamedia** [davideas/FlexibleAdapter#232]
I'am using GSON Library to load json from API, but with this library i can't apply.
I'am always return freze in Android Monitor with info 'Alloc concurrent mark sweep GC freed'.

Please give a example it can be applied?
Thank you

**Comment by izzamedia** [comment]
I'am using GSON Library to load json from API, but with this library i can't apply.
I'am always return freze in Android Monitor with info 'Alloc concurrent mark sweep GC freed'.

Please give a example it can be applied?
Thanks you

**Comment by davideas** [comment]
@izzamedia, objects from Json are simple pojos, named Model objects, then you need an Adapter item.
So you encapsulate the Model object into the Adapter item with `IHolder` interface.
You have **Wiki pages** and the demo app (for now only in `rc1` branch you can see the IHolder example).

**Comment by izzamedia** [comment]
@davideas, I have Read Wiki pages and the demo app rc1 branch, but I am confused and I don't know how to implement a model with IHolder interface in my model pojos.

My JSON File:
` [
  {
    "id": "1",
    "title": "Tes 1",
    "description": "description 1",
    "icon" : "file:///android_asset/images/1.jpg"
  },
  {
    "id": "2",
    "title": "Tes 2",
    "description": "description 2",
    "icon" : "file:///android_asset/images/1.jpg"
  }
]`
 
Class to handle JSON:
`public class LoadProduct {
    public final String TAG = LoadProduct.class.getSimpleName();
    public static List<OverallItem> data;
    public Random randomGenerator;
    public final String JSONFILE = 'product.json';`

    `public LoadProduct(Activity activity){
        data = new ArrayList<>();
        randomGenerator = new Random();
        String jsonString = loadJson(activity);
        data = getListFromJson(jsonString);
    }
    public String loadJson(Activity activity) {
        String jsonString;
        try {
            InputStream is = activity.getAssets().open(JSONFILE);
            int size = is.available();
            byte[] buffer = new byte[size];
            is.read(buffer);
            is.close();
            jsonString = new String(buffer, "UTF-8");
        } catch (IOException ex) {
            ex.printStackTrace();
            return null;
        }
        return jsonString;
    }

    public List<OverallItem> getListFromJson(String jsonString) {
        Gson gson = new Gson();
        Type collectionType = new TypeToken<List<OverallItem>>() {}.getType();
        return gson.fromJson(jsonString, collectionType);
    }

    public  OverallItem getItemRandom(){
        int index = randomGenerator.nextInt(data.size());
        OverallItem item = data.get(index);
        System.out.println("Data Random: "+ item);
        return item;
    }
    public  OverallItem getItemIndex(Long id){
        OverallItem item = data.get(id.intValue());
        Log.d("notif terpilih:", String.valueOf(item));
        return item;
    }
    public List<OverallItem> getDataProduct() {
        return data;
    }}`
I have edited examples 
`public class DatabaseService {
//I have added this to handle json
public void createRandomProduct(Activity activity){
   databaseType = DatabaseType.OVERALL;
   mItems.clear();	
   loadProduct = new LoadProduct(activity); //I've created this class with GSON lib to handle JSON from Assets Folder
    listku = loadProduct.getDataProduct(); //get array list from JSON
    Log.d(TAG,listku.toString());
     mItems.addAll(1,listku); //I am confused with this and I don't know how to implement IHolder with my model pojos
	}
}`

I use OverallAdapter to implement that, how can I make a model with it?

**Comment by davideas** [comment]
@izzamedia, the OverallItem in the demo app, doesn't implement _IHolder_ interface.
There's a specific sample for IHolder items, please have a look at that one.

packages:
```
eu.davidea.samples.flexibleadapter.holders
eu.davidea.samples.flexibleadapter.models
```

Once you have the list of models loaded from Gson, then you have to convert them for the Adapter: you should provide the model to the constructor of the Adapter holder item.
Check function `createHolderSectionsDatabase()`.

**Comment by izzamedia** [comment]
@davideas , I have modified OverallItem class to implement IHolder interface and successfully. 
This library is awesome but complex in the sample so it is not easy to understand.

Hopefully in the future there is also a more simple example.
btw, Thank you very much for the explanation.

**Comment by davideas** [comment]
I know, you are not the first one who says that, unfortunately I'm focusing more on the library for the rest I added wiki pages (usually people don't see them).

There's a [Wiki page](https://github.com/davideas/FlexibleAdapter/wiki/5.x-%7C-Demo-App) also for the demo.

**Comment by izzamedia** [comment]
@davideas , I have modified OverallItem class to implement IHolder interface and successfully. 
This library is awesome but complex in the sample so it is not easy to understand.

Hopefully in the future there is also a more simple example.
btw, Thank you very much for the explanation.
