### ISSUE TITLE
Drag 'N Drop inside expandable items

### ISSUE THREAD

**Issue by ayzenquwe** [davideas/FlexibleAdapter#234]
Hi.

I have a question regarding drag 'n drop functionality in expandable items. It seems (according to my experience and your demo application) that after dragging an item from one position to another, within one expandable item, this modification vanishes if I collapse/expand a parent expandable item. So any modifications I make through dragndrop are rollbacked to the original state after collapsing/expanding an expandable item where those modifications were.

I found an easy way to fix this by swapping items in the inner subitems list of a parent expandable item in onItemMove of OnItemMoveListener. This worked fine for situations where items are moved only inside their parent item.

```java
List list = fromHeader.getSubItems();
int fromSubIndex = list.indexOf(fromItem);
int toSubIndex = list.indexOf(toItem);
Collections.swap(list, fromSubIndex, toSubIndex);
```

Now I need to add an ability to move an item from one expandable item to another and I'm stuck. I tried to manipulate inner subitems lists of these parent items like I did before, but after that collapse/expand mechanics become broken for these two expandable items.

So what am I doing wrong? Maybe I have to modify those subitems list in a different way and not directly? Also, am I correct in my understanding that library doesn't make any changes to subitems lists, so I need to do it by myself?

**Comment by davideas** [comment]
@ayzenquwe, exactly: the demoApp in case of expandable doesn't modify the database list and the subitems of those expandables, you have to implement the logic yourself.

The library does the work of switching the elements between 2 sections (changing the header), but not the subItems of 2 expandables. It was quite complex to achieve that, I believe there's a better way.

However in case of subItems, the logic can be applied to any situation as well, so you may try to add this feature in the library too, once you find how to.

You can start to check if the `fromPosition` is a child (has a parent) and the `toPosition` is an Expandable, in that case you need to remove the child from the old parent and add it to the new Parent that you will retrieve. Then you need to handle the exceptions: like the the edges of the list and if no expandable is present when you get the new parent (subItem is moved outside of any expandable always toward the top).
Much more complicated is when you probably want to expand a collapsed Parent (the receiver) to insert the new child.

For the case when you start to drag a parent, the library already support the swapping by collapsing the parent automatically.
Check the `swapItems()` method in the `FlexibleAdapter` class.

**Comment by ayzenquwe** [comment]
Thanks for the quick response.

As I told, I've implemented a code that was able to remove an item from one expandable and to add it to another directly in their SubItems lists. But this broke expand/collapse mechanics of these two expandables. So, clicks on expandable didn't collapse it, it just did nothing. Is it okay to modify those lists directly? Maybe I should somehow tell the library that I changed subitems lists afterwards?

**Comment by davideas** [comment]
The subItems lists are already manipulated by the Adapter, so it's ok to modify those sub lists.
You may want to enable logs and see what the Adapter receives when collapsing is requested. You should be sure that the numbers of sub lists corresponds to what the collapse method is actually collapsing.

**Comment by ayzenquwe** [comment]
Okay, I'll check that out when I have free time. Thanks for the support.

**Comment by davideas** [comment]
Very important is when you move those items, you also notify about the removal and insertion with the proprer notifyItemXXX, I suspect that the position you clicked doesn't corresponds to expandable.

**Comment by ayzenquwe** [comment]
Important information. Thanks. :)
