### ISSUE TITLE
Flexible Adapter FilterItems() duplication issue

### ISSUE THREAD

**Issue by victorileaf** [davideas/FlexibleAdapter#235]
Hi Sir,
I have used your Example adapter from Demo app to implement filter ,fast scroller and everything. Im using th same object to call filterItems() method. filter works fine, but when i backspace and reach empty text. the items in recyclerview is doubled / tripled .
Headers will be double/ triple same as items.

Eg: 
A
Arya
B
Ben

becomes
A
A
Arya
Arya
B
B
Ben
Ben

What could be the problem?

    public void searchText(String text){
        if(mAdapter!=null) {
                mAdapter.setSearchText(text);
                //Fill and Filter mItems with your custom list and automatically animate the changes
                //Watch out! The original list must be a copy
                mAdapter.filterItems(mCopyContactItems,200);
        }
    }

    public void initData(){
        mAdapter = new ExampleAdapter(mContactItems, getActivity());
        //Experimenting NEW features (v5.0.0)
        mAdapter.setRemoveOrphanHeaders(false)
                .setNotifyChangeOfUnfilteredItems(true)//We have highlighted text while filtering, so let's enable this feature to be consistent with the active filter
                .setAnimationOnScrolling(false);
        rvContacts.setLayoutManager(new SmoothScrollLinearLayoutManager(getActivity()));
        rvContacts.setAdapter(mAdapter);
        rvContacts.setHasFixedSize(true); //Size of RV will not change
        //NOTE: Use default item animator 'canReuseUpdatedViewHolder()' will return true if
        // a Payload is provided. FlexibleAdapter is actually sending Payloads onItemChange.
        rvContacts.setItemAnimator(new DefaultItemAnimator());

        if(mContactItems.size()>7) {
            //Add FastScroll to the RecyclerView, after the Adapter has been attached the RecyclerView!!!
            mAdapter.setFastScroller(fastScroller,
                    R.color.peteriver, new eu.davidea.fastscroller.FastScroller.OnScrollStateChangeListener() {
                        @Override
                        public void onFastScrollerStateChange(boolean scrolling) {

                        }
                    });
        }
        mAdapter.setLongPressDragEnabled(false)
                .setHandleDragEnabled(false)
                .setSwipeEnabled(false)
                .setUnlinkAllItemsOnRemoveHeaders(true)
                //Show Headers at startUp, 1st call, correctly executed, no warning log message!
                .setDisplayHeadersAtStartUp(true)
                .enableStickyHeaders()
                //Simulate developer 2nd call mistake, now it's safe, not executed, no warning log message!
                .setDisplayHeadersAtStartUp(true)
                //Simulate developer 3rd call mistake, still safe, not executed, warning log message displayed!
                .showAllHeaders();
    }

Please help i actually spent more than 3-4 days to get this library integrated . Thanks in advance and Hats off to building such a high performance adapter.

**Comment by davideas** [comment]
@victorileaf, difficult to say from that code, try to enable logs and see what the adapter is doing.
I don't know what others methods are calling `searchText()`, who triggers it, who modifies the `mCopyContactItems`, so check yours and library logs.
In case you need more help and you don't understand the cause paste them here (use a little list) by providing good execution cases with and without filter, etc.,.

PS. Please remove the simulation calls mistakes for sticky headers from your code!

**Comment by victorileaf** [comment]
TextWatcher textWatcher = new TextWatcher() {
        @Override
        public void beforeTextChanged(CharSequence s, int start, int count, int after) {
            
        }

        @Override
        public void onTextChanged(CharSequence s, int start, int before, int count) {

        }

        @Override
        public void afterTextChanged(Editable s) {
         searchText(editable.toString());

        }
    };

mCopyContactItems is a copy of mContactItems which i used to set adapter filterItems() method .

can i use the same object that i used for setting the adpater for filter() method??

**Comment by victorileaf** [comment]
Using filter and then backspacing to empty text

11-22 21:03:58.042 31460-31460/co.helo.android W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
11-22 21:03:59.082 31460-609/co.helo.android D/FilterAsyncTask: doInBackground - started FILTER
11-22 21:03:59.082 31460-609/co.helo.android I/FlexibleAdapter: filterItems with searchText=a
11-22 21:03:59.128 31460-609/co.helo.android V/FlexibleAdapter: Animate changes! oldSize=757 newSize=573 limit=600
11-22 21:03:59.133 31460-609/co.helo.android V/FlexibleAdapter: calculateRemovals total out=184
11-22 21:03:59.135 31460-609/co.helo.android V/FlexibleAdapter: calculateAdditions total new=0
11-22 21:03:59.135 31460-609/co.helo.android D/FilterAsyncTask: doInBackground - ended FILTER
11-22 21:03:59.135 31460-31460/co.helo.android I/FlexibleAdapter: Performing 757 notifications
11-22 21:03:59.224 31460-31460/co.helo.android V/FlexibleAdapter: onViewBound    Holder=HeaderViewHolder position=2 itemId=65 layoutPosition=2
11-22 21:03:59.226 31460-31460/co.helo.android V/FlexibleAdapter: onViewBound    Holder=ParentViewHolder position=3 itemId=55 layoutPosition=3
11-22 21:03:59.228 31460-31460/co.helo.android V/FlexibleAdapter: onViewBound    Holder=ParentViewHolder position=4 itemId=56 layoutPosition=4
11-22 21:03:59.230 31460-31460/co.helo.android V/FlexibleAdapter: onViewBound    Holder=ParentViewHolder position=5 itemId=57 layoutPosition=5
11-22 21:03:59.233 31460-31460/co.helo.android V/FlexibleAdapter: onViewBound    Holder=HeaderViewHolder position=0 itemId=64 layoutPosition=0
11-22 21:03:59.233 31460-31460/co.helo.android I/HeaderItem: HeaderItem @ Payload [FILTER]
11-22 21:03:59.233 31460-31460/co.helo.android V/FlexibleAdapter: onViewBound    Holder=ParentViewHolder position=1 itemId=48 layoutPosition=1
11-22 21:03:59.431 31460-31460/co.helo.android V/AnimatorAdapter: Clear notified for binding Animations
11-22 21:04:01.495 31460-31460/co.helo.android E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
11-22 21:04:01.495 31460-31460/co.helo.android E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
11-22 21:04:01.698 31460-619/co.helo.android D/FilterAsyncTask: doInBackground - started FILTER
11-22 21:04:01.698 31460-619/co.helo.android I/FlexibleAdapter: filterItems with searchText=
11-22 21:04:01.702 31460-619/co.helo.android V/FlexibleAdapter: NotifyDataSetChanged! oldSize=573 newSize=757 limit=600
11-22 21:04:01.702 31460-619/co.helo.android D/FilterAsyncTask: doInBackground - ended FILTER
11-22 21:04:01.702 31460-31460/co.helo.android I/FlexibleAdapter: Performing 1 notifications
11-22 21:04:01.702 31460-31460/co.helo.android W/FlexibleAdapter: notifyDataSetChanged!
11-22 21:04:01.708 31460-31460/co.helo.android V/FlexibleAdapter: Showing header at position 1 header=HeaderItem[id=@, title=]
11-22 21:04:01.708 31460-31460/co.helo.android V/FlexibleAdapter: addItem delegates addition to addItems!
11-22 21:04:01.708 31460-31460/co.helo.android D/FlexibleAdapter: addItems on position=1 itemCount=1
11-22 21:04:01.708 31460-31460/co.helo.android V/FlexibleAdapter: Showing header at position 4 header=HeaderItem[id=*, title=]
11-22 21:04:01.708 31460-31460/co.helo.android V/FlexibleAdapter: addItem delegates addition to addItems!
11-22 21:04:01.708 31460-31460/co.helo.android D/FlexibleAdapter: addItems on position=4 itemCount=1
11-22 21:04:01.708 31460-31460/co.helo.android V/FlexibleAdapter: Showing header at position 7 header=HeaderItem[id=+, title=]
11-22 21:04:01.708 31460-31460/co.helo.android V/FlexibleAdapter: addItem delegates addition to addItems!
11-22 21:04:01.708 31460-31460/co.helo.android D/FlexibleAdapter: addItems on position=7 itemCount=1
11-22 21:04:01.709 31460-31460/co.helo.android V/FlexibleAdapter: Showing header at position 12 header=HeaderItem[id=5, title=]
11-22 21:04:01.709 31460-31460/co.helo.android V/FlexibleAdapter: addItem delegates addition to addItems!
11-22 21:04:01.709 31460-31460/co.helo.android D/FlexibleAdapter: addItems on position=12 itemCount=1
11-22 21:04:01.709 31460-31460/co.helo.android V/FlexibleAdapter: Showing header at position 15 header=HeaderItem[id=9, title=]
11-22 21:04:01.709 31460-31460/co.helo.android V/FlexibleAdapter: addItem delegates addition to addItems!
11-22 21:04:01.709 31460-31460/co.helo.android D/FlexibleAdapter: addItems on position=15 itemCount=1
11-22 21:04:01.709 31460-31460/co.helo.android V/FlexibleAdapter: Showing header at position 18 header=HeaderItem[id=A, title=]
11-22 21:04:01.709 31460-31460/co.helo.android V/FlexibleAdapter: addItem delegates addition to addItems!
11-22 21:04:01.709 31460-31460/co.helo.android D/FlexibleAdapter: addItems on position=18 itemCount=1
11-22 21:04:01.710 31460-31460/co.helo.android V/FlexibleAdapter: Showing header at position 113 header=HeaderItem[id=B, title=]
11-22 21:04:01.710 31460-31460/co.helo.android V/FlexibleAdapter: addItem delegates addition to addItems!
11-22 21:04:01.710 31460-31460/co.helo.android D/FlexibleAdapter: addItems on position=113 itemCount=1
11-22 21:04:01.711 31460-31460/co.helo.android V/FlexibleAdapter: Showing header at position 141 header=HeaderItem[id=C, title=]
11-22 21:04:01.711 31460-31460/co.helo.android V/FlexibleAdapter: addItem delegates addition to addItems!
11-22 21:04:01.711 31460-31460/co.helo.android D/FlexibleAdapter: addItems on position=141 itemCount=1
11-22 21:04:01.711 31460-31460/co.helo.android V/FlexibleAdapter: Showing header at position 163 header=HeaderItem[id=D, title=]
11-22 21:04:01.712 31460-31460/co.helo.android V/FlexibleAdapter: addItem delegates addition to addItems!
11-22 21:04:01.712 31460-31460/co.helo.android D/FlexibleAdapter: addItems on position=163 itemCount=1
11-22 21:04:01.712 31460-31460/co.helo.android V/FlexibleAdapter: Showing header at position 193 header=HeaderItem[id=E, title=]
11-22 21:04:01.712 31460-31460/co.helo.android V/FlexibleAdapter: addItem delegates addition to addItems!
11-22 21:04:01.712 31460-31460/co.helo.android D/FlexibleAdapter: addItems on position=193 itemCount=1
11-22 21:04:01.713 31460-31460/co.helo.android V/FlexibleAdapter: Showing header at position 206 header=HeaderItem[id=F, title=]
11-22 21:04:01.713 31460-31460/co.helo.android V/FlexibleAdapter: addItem delegates addition to addItems!
11-22 21:04:01.713 31460-31460/co.helo.android D/FlexibleAdapter: addItems on position=206 itemCount=1
11-22 21:04:01.714 31460-31460/co.helo.android V/FlexibleAdapter: Showing header at position 236 header=HeaderItem[id=G, title=]
11-22 21:04:01.714 31460-31460/co.helo.android V/FlexibleAdapter: addItem delegates addition to addItems!
11-22 21:04:01.714 31460-31460/co.helo.android D/FlexibleAdapter: addItems on position=236 itemCount=1
11-22 21:04:01.715 31460-31460/co.helo.android V/FlexibleAdapter: Showing header at position 265 header=HeaderItem[id=H, title=]
11-22 21:04:01.715 31460-31460/co.helo.android V/FlexibleAdapter: addItem delegates addition to addItems!
11-22 21:04:01.715 31460-31460/co.helo.android D/FlexibleAdapter: addItems on position=265 itemCount=1
11-22 21:04:01.715 31460-31460/co.helo.android V/FlexibleAdapter: Showing header at position 283 header=HeaderItem[id=I, title=]
11-22 21:04:01.715 31460-31460/co.helo.android V/FlexibleAdapter: addItem delegates addition to addItems!
11-22 21:04:01.715 31460-31460/co.helo.android D/FlexibleAdapter: addItems on position=283 itemCount=1
11-22 21:04:01.716 31460-31460/co.helo.android V/FlexibleAdapter: Showing header at position 295 header=HeaderItem[id=J, title=]
11-22 21:04:01.716 31460-31460/co.helo.android V/FlexibleAdapter: addItem delegates addition to addItems!
11-22 21:04:01.716 31460-31460/co.helo.android D/FlexibleAdapter: addItems on position=295 itemCount=1
11-22 21:04:01.717 31460-31460/co.helo.android V/FlexibleAdapter: Showing header at position 331 header=HeaderItem[id=k, title=]
11-22 21:04:01.717 31460-31460/co.helo.android V/FlexibleAdapter: addItem delegates addition to addItems!
11-22 21:04:01.717 31460-31460/co.helo.android D/FlexibleAdapter: addItems on position=331 itemCount=1
11-22 21:04:01.718 31460-31460/co.helo.android V/FlexibleAdapter: Showing header at position 373 header=HeaderItem[id=L, title=]
11-22 21:04:01.718 31460-31460/co.helo.android V/FlexibleAdapter: addItem delegates addition to addItems!
11-22 21:04:01.718 31460-31460/co.helo.android D/FlexibleAdapter: addItems on position=373 itemCount=1
11-22 21:04:01.719 31460-31460/co.helo.android V/FlexibleAdapter: Showing header at position 386 header=HeaderItem[id=M, title=]
11-22 21:04:01.719 31460-31460/co.helo.android V/FlexibleAdapter: addItem delegates addition to addItems!
11-22 21:04:01.719 31460-31460/co.helo.android D/FlexibleAdapter: addItems on position=386 itemCount=1
11-22 21:04:01.720 31460-31460/co.helo.android V/FlexibleAdapter: Showing header at position 438 header=HeaderItem[id=N, title=]
11-22 21:04:01.720 31460-31460/co.helo.android V/FlexibleAdapter: addItem delegates addition to addItems!
11-22 21:04:01.721 31460-31460/co.helo.android D/FlexibleAdapter: addItems on position=438 itemCount=1
11-22 21:04:01.722 31460-31460/co.helo.android V/FlexibleAdapter: Showing header at position 503 header=HeaderItem[id=O, title=]
11-22 21:04:01.722 31460-31460/co.helo.android V/FlexibleAdapter: addItem delegates addition to addItems!
11-22 21:04:01.722 31460-31460/co.helo.android D/FlexibleAdapter: addItems on position=503 itemCount=1
11-22 21:04:01.723 31460-31460/co.helo.android V/FlexibleAdapter: Showing header at position 512 header=HeaderItem[id=p, title=]
11-22 21:04:01.723 31460-31460/co.helo.android V/FlexibleAdapter: addItem delegates addition to addItems!
11-22 21:04:01.723 31460-31460/co.helo.android D/FlexibleAdapter: addItems on position=512 itemCount=1
11-22 21:04:01.724 31460-31460/co.helo.android V/FlexibleAdapter: Showing header at position 552 header=HeaderItem[id=Q, title=]
11-22 21:04:01.724 31460-31460/co.helo.android V/FlexibleAdapter: addItem delegates addition to addItems!
11-22 21:04:01.724 31460-31460/co.helo.android D/FlexibleAdapter: addItems on position=552 itemCount=1
11-22 21:04:01.725 31460-31460/co.helo.android V/FlexibleAdapter: Showing header at position 560 header=HeaderItem[id=R, title=]
11-22 21:04:01.725 31460-31460/co.helo.android V/FlexibleAdapter: addItem delegates addition to addItems!
11-22 21:04:01.726 31460-31460/co.helo.android D/FlexibleAdapter: addItems on position=560 itemCount=1
11-22 21:04:01.727 31460-31460/co.helo.android V/FlexibleAdapter: Showing header at position 620 header=HeaderItem[id=S, title=]
11-22 21:04:01.727 31460-31460/co.helo.android V/FlexibleAdapter: addItem delegates addition to addItems!
11-22 21:04:01.727 31460-31460/co.helo.android D/FlexibleAdapter: addItems on position=620 itemCount=1
11-22 21:04:01.729 31460-31460/co.helo.android V/FlexibleAdapter: Showing header at position 708 header=HeaderItem[id=t, title=]
11-22 21:04:01.729 31460-31460/co.helo.android V/FlexibleAdapter: addItem delegates addition to addItems!
11-22 21:04:01.729 31460-31460/co.helo.android D/FlexibleAdapter: addItems on position=708 itemCount=1
11-22 21:04:01.730 31460-31460/co.helo.android V/FlexibleAdapter: Showing header at position 729 header=HeaderItem[id=U, title=]
11-22 21:04:01.731 31460-31460/co.helo.android V/FlexibleAdapter: addItem delegates addition to addItems!
11-22 21:04:01.731 31460-31460/co.helo.android D/FlexibleAdapter: addItems on position=729 itemCount=1
11-22 21:04:01.732 31460-31460/co.helo.android V/FlexibleAdapter: Showing header at position 734 header=HeaderItem[id=V, title=]
11-22 21:04:01.732 31460-31460/co.helo.android V/FlexibleAdapter: addItem delegates addition to addItems!
11-22 21:04:01.732 31460-31460/co.helo.android D/FlexibleAdapter: addItems on position=734 itemCount=1
11-22 21:04:01.733 31460-31460/co.helo.android V/FlexibleAdapter: Showing header at position 780 header=HeaderItem[id=W, title=]
11-22 21:04:01.733 31460-31460/co.helo.android V/FlexibleAdapter: addItem delegates addition to addItems!
11-22 21:04:01.733 31460-31460/co.helo.android D/FlexibleAdapter: addItems on position=780 itemCount=1
11-22 21:04:01.735 31460-31460/co.helo.android V/FlexibleAdapter: Showing header at position 783 header=HeaderItem[id=x, title=]
11-22 21:04:01.735 31460-31460/co.helo.android V/FlexibleAdapter: addItem delegates addition to addItems!
11-22 21:04:01.735 31460-31460/co.helo.android D/FlexibleAdapter: addItems on position=783 itemCount=1
11-22 21:04:01.739 31460-31460/co.helo.android V/FlexibleAdapter: onViewBound    Holder=HeaderViewHolder position=0 itemId=64 layoutPosition=0
11-22 21:04:01.740 31460-31460/co.helo.android V/FlexibleAdapter: onViewBound    Holder=HeaderViewHolder position=1 itemId=64 layoutPosition=1
11-22 21:04:01.741 31460-31460/co.helo.android V/FlexibleAdapter: onViewBound    Holder=ParentViewHolder position=2 itemId=48 layoutPosition=2
11-22 21:04:01.742 31460-31460/co.helo.android V/FlexibleAdapter: onViewBound    Holder=HeaderViewHolder position=3 itemId=42 layoutPosition=3
11-22 21:04:01.746 31460-31460/co.helo.android V/FlexibleAdapter: onViewBound    Holder=HeaderViewHolder position=4 itemId=42 layoutPosition=4
11-22 21:04:01.946 31460-31460/co.helo.android V/AnimatorAdapter: Clear notified for binding Animations

**Comment by davideas** [comment]
Are you providing the copied list with headers already? The concept of adding only sectionable items when you initially create the adapter, is valid also for filtering items, so this list should contain only the sectionable items.

**Comment by victorileaf** [comment]
ok , im adding item after create simple item which uses header items inside

[ 
//in a loop
HeaderItem header = null;
                                if(previousName!=null){
                                    if(!previousName.substring(0,1).equalsIgnoreCase(displayName.substring(0,1))){
                                        mContactItems.add(
                                                new SimpleItem(pos+"",newHeader(contactItem.getName().substring(0,1)),contactItem));
                                    }
                                    else {
                                        mContactItems.add(
                                                new SimpleItem(pos+"",null,contactItem));
                                    }

                                }
](url)

**Comment by davideas** [comment]
@victorileaf, In that code there's a big mistake, you are setting a `null` header, shouldn't be `header` instance?? you should save the newHeader instance as well...
However, I think you have all the elements to provide the copy of the original list only with the `SimpleItem`.

**Comment by victorileaf** [comment]
im actually adding contacts to the list . simple item represents a contact 
and its in ascending order .. when first character is new i will set it as a header and for other items i will set header as null.

**Comment by davideas** [comment]
In the demo app, the header, of the others items, is not null.

**Comment by victorileaf** [comment]
```

	/*
	 * List of Simple Items with Header attached. Only Simple Items will be added to the list.
	 */
	public void createHeadersSectionsDatabase(int size, int headers) {
		databaseType = DatabaseType.HEADERS_SECTIONS;
		HeaderItem header = null;
		mItems.clear();
		int lastHeaderId = 0;
		for (int i = 0; i < size; i++) {
			header = i % Math.round(size / headers) == 0 ? newHeader(++lastHeaderId) : header;
			mItems.add(newSimpleItem(i + 1, header));
		}
	}
```

header will be null for  i % Math.round(size / headers) != 0

**Comment by davideas** [comment]
If you didn't resolve your issues, could please check how you implemented the `equals` methods of all items? A wrong implementation will lead to strange behaviors very difficult to find the cause.

**Comment by victorileaf** [comment]
@davideas  : I dumped the code started from scratch again .. i think its working fine now :)
I'm using your rc1 source code.
Thanks for the support.

**Comment by davideas** [comment]
@victorileaf, did you discovered what was?

**Comment by victorileaf** [comment]
@davideas  no . how can i disable animation when adapter is set (all times)?
I was able to disable on update

**Comment by davideas** [comment]
@victorileaf, which animations are you talking about, _scrolling_ animations or _notification_ animations?

**Comment by victorileaf** [comment]
when i first time loads the recylerview there is an drop down like animation to show all items.

Im also getting this error sometimes
 java.lang.IllegalStateException: ViewGroup for Sticky Headers unspecified! You must either include @layout/sticky_header_layout OR set a custom StickyHeaderContainer
Whats should i do to avoid these?

**Comment by davideas** [comment]
@victorileaf, for animations you probably have enabled them with `setAnimationOnScrolling(true)`. Please check this Wiki page: [Adapter Animations](https://github.com/davideas/FlexibleAdapter/wiki/5.x-%7C-Adapter-Animations).

To resolve the new illegal state in **rc1** branch, please follow the 4 steps here: [Headers and Sections#sticky-headers](https://github.com/davideas/FlexibleAdapter/wiki/5.x-%7C-Headers-and-Sections#sticky-headers).

- Please be aware that I'm actively working every day on a different branch and when I complete new code I will transfer everything in **rc1**.
- Please, be aware also that, I'm changing the way to activate the sticky headers to avoid xml configuration. I'm working to make it automatic when sticky headers are enabled at runtime.
- Also, I'm refactoring and deprecating many methods.

In general I'm following the milestones visible in the issue 224, refactoring and deprecation are visible in issue 200.
