### ISSUE TITLE
Section1_SubItem1's ViewHoder1 cannot be cast to Section2_SubItem2's ViewHolder2

### ISSUE THREAD

**Issue by lxdyglt** [davideas/FlexibleAdapter#238]
I have a `FlexibleAdapter` with expandable Sticky Headers (two headers in my case and expandable = false). 

Header1 contains one or more `SubItem1`, Header2 contains one or more `SubItem2` ((`SubItem1` and `SubItem2` are classes extends `AbstractListItem` respectively).

Because my `SubItem1` and `SubItem2` have different layout so I use different ViewHolder in each class (`VH1` & `VH2`).

Whenever the screen shows both subItems I got the list it crashes with the message:
"SubItem1$VH1 cannot be cast to SubItem2$VH2"

I would expect it to support different layout (view holder) for subitem which belongs to different sections(headers).

**Comment by davideas** [comment]
@lxdyglt, did you check the others issues closed? I believe you have configured the same layout in the 2 subItems classes, please check `getLayoutRes()`.

**Comment by lxdyglt** [comment]
Thanks davideas, that is exactly the case!
