### ISSUE TITLE
Not able to acomplish Sticky header

### ISSUE THREAD

**Issue by leodeleon22** [davideas/FlexibleAdapter#241]
I did all the steps according to the wiki and the demo but the headers are not sticking at all. The sections are fine but the header scrolls out of the page
@davideas  What else I should try?

Obs: 
- 'eu.davidea:flexible-adapter:5.0.0-b8'

- Using the same fragment_recycler_view.xml

- HeaderItem extends AbstractHeaderItem<HeaderItem.HeaderViewHolder> 

- Item extends AbstractFlexibleItem<Item.ItemViewHolder>  implements ISectionable<Item.ItemViewHolder, HeaderItem>

```
    adapter = new FlexibleAdapter<>(items);
    recycler.setLayoutManager(new SmoothScrollLinearLayoutManager(getContext()));
    adapter.setDisplayHeadersAtStartUp(true);
    adapter.enableStickyHeaders();
    recycler.setAdapter(adapter);
    recycler.setHasFixedSize(true);
    recycler.setItemAnimator(new DefaultItemAnimator());
```

**Comment by davideas** [comment]
@leodeleon22, have the items linked to the header when you build your list?
Do you add only the items to that list?

**Comment by leodeleon22** [comment]
My item has the header on the constructor


```
private HeaderItem header;

  Item(String id, HeaderItem header) {
    this.id = id;
    this.header = header;
  }
```

and I add the items like that

```
private List<AbstractFlexibleItem> items = new ArrayList<>();

items.add( new Item(getId(), header));
```

**Comment by davideas** [comment]
@leodeleon22, I see now that, you enable the headers before setting the Adapter. Move the assignment after. The layout needs the RV attached (means not null) before creating inflating the sticky container.

Be aware that I'm going to change this configuration, in the next pre-release.

**Comment by leodeleon22** [comment]
Hey @davideas thanks for the fast responses,

I actually moved the ssignment up because it was not working. I moved it down and the header is still scrolling out of the page. What else I should check?

**Comment by leodeleon22** [comment]
@davideas Found it! I was implementing this method wrong. Now it works!

```
@Override
  public boolean equals(Object inObject) {
    if (inObject instanceof HeaderItem) {
      HeaderItem inItem = (HeaderItem) inObject;
      return this.getId().equals(inItem.getId());
    }
    return false;
  }
```
