### ISSUE TITLE
keep/save the new dragged state

### ISSUE THREAD

**Issue by TheLoyalCruel** [davideas/FlexibleAdapter#245]
Hello
Thanks for this strong library...
Is it possible to keep/save the new position of items after dragging?
for example in OverallAdapter in your sample app.

thanks in advance...

**Comment by davideas** [comment]
@TheLoyalCruel, the position of the elements should be reflected in your original list at each move. So when user refreshes, the list is already with the new order.

**Comment by TheLoyalCruel** [comment]
is there any method the get the element new position?

**Comment by davideas** [comment]
``` java
OnItemMoveListener {
    shouldMoveItem(int fromPosition, int toPosition);
    onItemMove(int fromPosition, int toPosition);
}
```

**Comment by TheLoyalCruel** [comment]
thanks a million :)
