### ISSUE TITLE
Sticky Headers issue with three adapters when switching between them through check boxes.

### ISSUE THREAD

**Issue by aaru25kumar** [davideas/FlexibleAdapter#247]
I am trying to achieve the sticky headers with 3 adapters with 3 recyclerview and 3 check boxes. When you choose one check box, it will be checked and that recyclerview will be visible whereas the other two recyclerview visibility will be gone. 

The issue that I am facing is that when I scroll down the list and then switch to the other recyclerview through the check box then the header item for the previous recycler view is shown. I am also using one sticky_header_layout for all three recyclerview. Your help will be really appreciated here. Thank you.

**Comment by davideas** [comment]
@aaru25kumar, that is a particular situation.
Since I reworked the logic of the sticky header in the last month, could you please check the new Snapshot that I just released.
If doesn't resolve your situation, then I can think some solutions, but maybe it is not necessary anymore.

> Pay attention that, this snapshot brings a lot of changes to the whole library, it includes my last 2 months of development. Please read the release notes for this snapshot in issue #39.

**Comment by aaru25kumar** [comment]
I am actually using the version 5.0.0-b8 and I was looking into migrations where you have mentioned that we can use setStickyHeaders(boolean) instead of enableStickyHeaders(boolean) and not to use the sticky_header_layout. But I am haven't seen those changes in the library at all.

**Comment by davideas** [comment]
I can't change b8 content. That is published as it is for ever. In this phase of development, please use the snapshot version that receives continuous update from my dev.

**Comment by aaru25kumar** [comment]
I just switched from b8 to the snapshot and I am using the setStickyHeaders(true) to all the three adapters and also removed the include sitcky_header_layout in my xml file. But the issue is still present.

**Comment by davideas** [comment]
@aaru25kumar, depends what you show and hide when you switch RV, probably you have all in one Activity, I suggest to disable the sticky header and enable again for the new one RV. This cannot be done by the library because you are not detaching anything, just showing and hide something.

Most probably you don't need at all, to triplicate the RV widget, you only need to switch adapter!

**Comment by aaru25kumar** [comment]
I got it working as per your suggestion. I apologize for not leaving a comment sooner.
