### ISSUE TITLE
Transparent headers became white

### ISSUE THREAD

**Issue by yamelkaya** [davideas/FlexibleAdapter#248]
Hi @davideas, 
I've launched app today and noticed that headers became white (but they where **transparent** before). 
I am sure that I don't make any changes in header and item layout files. Maybe I am missing some important changes? 

My header markup: 

```
<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android">
    <data>
        <import type="android.view.View"/>
        <variable name="item" type="io.centaurea.cnzr.ViewModels.AgendaListHeaderVM"/>
    </data>
    <RelativeLayout android:layout_width="match_parent"
        android:layout_height="@dimen/agenda_header_height"
        android:gravity="center_vertical"
        android:paddingLeft="@dimen/agenda_item_padding_horizontal"
        android:paddingRight="@dimen/agenda_item_padding_horizontal">

        <TextView
            android:id="@+id/agenda_list_item_header"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_centerInParent="true"
            android:textColor="@color/colorSecondaryText"
            android:textSize="@dimen/font_small"
            android:text="@{item.label}"/>

    </RelativeLayout>
</layout>
```

**Comment by yamelkaya** [comment]
I am using flexible-adapter:5.0.0-SNAPSHOT

**Comment by davideas** [comment]
@yamelkaya, yes the new snapshot sets a white background for elevation, but I need to add possibility to set a custom one for transparency.

**Comment by yamelkaya** [comment]
Ok. Waiting for your changes. Transparent headers are very important in my case. I want to avoid any borders between items and headers in list and because of multi color background I can not set solid (white, black, red etc.). Transparency is only possible way I think.

**Comment by davideas** [comment]
@yamelkaya, I've adapted the code for transparency, now it has surgery precision :-)

- It super easy to implement the transparency and the elevation: all values are taken from the header item layout
- Double background is not visible anymore on swapping, if transparency is set.
- Elevation is still available with a transparent background.

**Comment by yamelkaya** [comment]
It's great! Thanks a lot for the quick fix.
Am I right that now I can set `android:background` for root element of header layout (in my case it is RelativeLayout)? I've tried it and it didn't help. 
By the way, I am using usual (not sticky) headers now.

**Comment by davideas** [comment]
Yes, you modify `android:background="#aa7e57c2"` and `android:elevation="Xdp"` to the root element of the item layout. Probably you need to clean manually the Gradle cache for my library.

**Comment by yamelkaya** [comment]
Yes, after cleaning the cache everything works. Thanks again!
