### ISSUE TITLE
Animated (scaled height) Sticky Headers

### ISSUE THREAD

**Issue by jczerski** [davideas/FlexibleAdapter#249]
Hello,

I would like to ask that is it possible to achieve for every sticky header collapsing layout when user is scrolling?
I'm mean  when there is a sticky header with height 200dp, after scrolling it changes it's height to 80dp. When next header arrives (with height 200dp) it moves earlier header. After after next scrolling it started scaling like this earlier.

If yes how to do this?:)

Thank you for the answer in advance.

Best regards,
Jack

**Comment by davideas** [comment]
@jczerski, thanks for the question, but it is not possible with the current calculation.
Basically, it is a brand new helper class, but you have to create one yourself and try to insert into the library.
