### ISSUE TITLE
getGlobalPositionOf always return -1

### ISSUE THREAD

**Issue by wankey** [davideas/FlexibleAdapter#250]
![1](https://cloud.githubusercontent.com/assets/1932886/21302728/3a92c49e-c5f4-11e6-9694-391dbeb6b95d.jpeg)

I had added 3 sectionableItem to adapter,but cannot see the header.when I debug the source ,I found getGlobalPositionOf always return -1.BUT according to the debug info , this method should return correct position。

**Comment by davideas** [comment]
@wankey, this seems one of the weird behaviour when equals method (of the item) is not well implemented. Could you check?

**Comment by wankey** [comment]
thanks for your answer,It's my fault.
