### ISSUE TITLE
How do i pass objects to adapter class 

### ISSUE THREAD

**Issue by SheikhZayed** [davideas/FlexibleAdapter#253]
what approach can i use to pass custom objects(List/Set/Map) while setting adapter,so that i can use inside my bindviewholder() method for some processing.?

**Comment by davideas** [comment]
@SheikhZayed, you will have to pass a List.
When `item.bindViewHolder` is automatically invoked you don't need the list, the data content is already inside the item itself.

**Comment by SheikhZayed** [comment]
no,i didnt mean that list which needs to be populated,in my last application i had a situation where i passed a set to the adapter class to do some processing before populating the view inside bindViewHolder();

I have passed this set while setting the adapter from the activity.

I like your library,but if i were to use something like that,what could be the best way ?

**Comment by davideas** [comment]
The constructor accepts only List collection.
If you have a Set, you have to transform it to List: `new ArrayList(setOfItems)`.

**Comment by SheikhZayed** [comment]
So,Basically can i have like this .. 

FlexibleAdapter<IFlexible> adapter = new FlexibleAdapter<>(firstList,secondList,andSomeOther);
recyclerView.setAdapter(adapter);

**Comment by davideas** [comment]
Not directly, you have to extend my `FlexibleAdapter` and to create a custom constructor to accept an array of lists/sets. In this constructor you build a List object to pass to the super() constructor.

**Comment by SheikhZayed** [comment]
Ok,this was the solution that struck my mind..
Anyway,thanks for addressing my issue :+1:

**Comment by davideas** [comment]
Sorry, what I wrote is not valid.
Since you must call `super` as first line, you have to map your Sets to a List before creating the Adapter. At this point you don't need to extend my Adapter. Just create a private method somewhere where you build the List object.

**Comment by SheikhZayed** [comment]
can u pls elaborate your point ?

**Comment by davideas** [comment]
Sure, since you need some line of code to map sets to the List object adding all sets in a cycle for before passing the list to the final adapter, you need to do this operation outside the constructor.

Java wants the call to `super()` as first statement, so you can't write any code before invoking `super()` in the constructor.

**Comment by SheikhZayed** [comment]
Ok,thanks
