### ISSUE TITLE
Header below items in ReverseLayout

### ISSUE THREAD

**Issue by tsadoklf** [davideas/FlexibleAdapter#255]
Hi, 

The sticky header is showed **below** "its" corresponding list  items. Any ideas of what's wrong?

I added - 

`<include layout="@layout/sticky_header_layout"/>`

after the recycler view and also tried to put it before the recycler view, but still got the header below the items.

The corresponding code is - `

         //Size of RV will not change
         recyclerView.setHasFixedSize(true); 
         
         // Set up Layout Manager, reverse layout
         LinearLayoutManager linearLayoutManager = new LinearLayoutManager(getContext());

         linearLayoutManager.setOrientation(LinearLayoutManager.VERTICAL);
         linearLayoutManager.setReverseLayout(true);
         linearLayoutManager.setStackFromEnd(true);
         
         recyclerView.setLayoutManager(linearLayoutManager);
         //
         // set item animator
         //
         recyclerView.setItemAnimator(new DefaultItemAnimator());
         //
         // set adapter
         //
         mAdapter = new FlexibleAdapter<>(new ArrayList<AbstractFlexibleItem>());

         recyclerView.setAdapter(mAdapter);

         mAdapter
            .setLongPressDragEnabled(true)
            .setHandleDragEnabled(false)
             .setSwipeEnabled(false)
             .setUnlinkAllItemsOnRemoveHeaders(true)
             .enableStickyHeaders()
             .setDisplayHeadersAtStartUp(true);`

**Comment by davideas** [comment]
@tsadoklf, do you need assistance on something? if yes edit your previous message, since your issue description was my template content, I removed it.

**Comment by davideas** [comment]
@tsadoklf, uhm... I never tested with `setReverseLayout(true);` indeed it is **not** supported at the moment since the position matters, while everything is inverted the sticky layout remains for headers, not footers.

I would like to understand why you use both settings: `reverseLayout` and `stackFromEnd`. I'm quite sure you just need `stackFromEnd`, it will behave like a chat app with headers, very well too.

If you really need reversing the content, you can achieve it by reverse sorting the items in your list, not the layout.

**Comment by tsadoklf** [comment]
@davideas thank you. I removed both settings and the headers are now in the right position, but I have another issue - I can't make them stick! I followed the sample app creating the header list item, header view holder, placing the layout after the recycler view but the header won't stick!

Any ideas?

**Comment by davideas** [comment]
Can you try to `enableStickyHeaders()` after `setDisplayHeadersAtStartUp()` ?

**Comment by tsadoklf** [comment]
Tried using this command and followed the WIKI but still it's not working. 

My code is - 

`  mAdapter
                .setLongPressDragEnabled(false)
                .setHandleDragEnabled(false)
                .setSwipeEnabled(false)
                .setUnlinkAllItemsOnRemoveHeaders(true)
                .setDisplayHeadersAtStartUp(true)
                .enableStickyHeaders();`

**Comment by davideas** [comment]
It could be `equals()` method not properly implemented or section items don't have the header object linked inside of them. Could you please check the initialization?

**Comment by tsadoklf** [comment]
@davideas thank you very much. 

The `equals` method was not implemented. I implemented it and it works fine. Almost...

The problem now is with fragments but I think that this deserves a new issue.
