### ISSUE TITLE
Sticky Headers and Fragments and ViewPager

### ISSUE THREAD

**Issue by tsadoklf** [davideas/FlexibleAdapter#258]
Hi, 

I have several fragments that are switched using view pager (ViewPager + TabLayout). 

Each fragment has a recycler view and stickey header layout. 

When I start the activity, the sticky headers work fine in the first tab but on the other tabs they do not stick anymore (they behave like "regular" list items). 

Tried several settings combinations like `setDisplayHeadersAtStartUp(true)` or `setDisplayHeadersAtStartUp(false)` with `showAllHeaders()` after updating the adapter and nothing gives the desired outcome.

Any ideas?

**Comment by davideas** [comment]
@tsadoklf, this is a known configuration, there are closed issues already, search "ViewPager".

Or if you really want try today the new release, you can use the existent Snapshot version (which is the rc1 that I will publish this evening anyway), which has a new automatic system in place for sticky headers, especially in ViewPager.
