### ISSUE TITLE
Endless scrolling in both directions

### ISSUE THREAD

**Issue by magneticflux-** [davideas/FlexibleAdapter#259]
How may I implement an adapter that starts loading data when the user approaches the top _or_ the bottom? I currently am able to load data at the bottom, but I don't see any way to add to the top. Is that something currently possible?

**Comment by davideas** [comment]
@magneticflux-, the top endless is not supported yet. It must be developed.
Unfortunately, I do not have time for the next month. but you can try a pull request if you want.

**Comment by jamiehiggins** [comment]
This would be a great addition

**Comment by volser** [comment]
@davideas Do you have any info about this feature? I saw your ToDo comments in code

I think this feature required some interface changes, so better to do this changes before release.

For, example onLoadMoreComplete required some direction param.
And what about progressItem? It's should be one or two items? How to set endless directions?

**Comment by davideas** [comment]
@volser, I will keep the progressItem to be the same, just inserted at the top instead of the bottom.
Direction could be set as additional property or as parameter to an existing function.

Unfortunately, I'm focusing on something else (also in private life). It will take a while to analyse this mod.

**Comment by davideas** [comment]
Available in the current snapshot: If activated with setTopEndless(), items can only be inserted at the top of the list, top endless is complementary to the bottom endless.
