### ISSUE TITLE
getLayoutRes() works incorrect after moveItem

### ISSUE THREAD

**Issue by yamelkaya** [davideas/FlexibleAdapter#260]
Hi @davideas, 
I use `FlexibleAdapter` with headers and I have 2 different types of layout for item: **active** and **completed** item (groupped by day header). All completed items move to the bottom of day.

`getLayoutRes()` code: 

```
 @Override
    public int getLayoutRes() {
        return !this.completed ? R.layout.list_item : R.layout.list_item_completed;
    }

@Override
    public ItemViewHolder createViewHolder(FlexibleAdapter adapter, LayoutInflater inflater, ViewGroup parent) {
        View view = inflater.inflate(getLayoutRes(), parent, false);
        return new ItemViewHolder(view, adapter,true);
    }
```
both active and completed items have the same layout but only different color of text for `title`:
```

<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content">
    <TextView
        android:id="@+id/title"
        android:textColor="@color/colorPrimary"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:paddingTop="10dp"
        android:paddingBottom="10dp"
        android:gravity="center"/>
</FrameLayout>
```
in `bindViewHolder` I just refresh item title: 
```

public void refresh(ListItem listItem, int position) {
            ((TextView) itemView.findViewById(R.id.title)).setText(listItem.getItem() + " at position " + position);
        }
```

So, the problem occurs when I move item some positions down after complete:

```
int oldPosition = adapter.getGlobalPositionOf(item);
int newPosition = adapter.calculatePositionFor(item, comparator);
adapter.moveItem(oldPosition,newPosition,null);

```
Item moved and its text color updated but when I scroll down I see that some other items also changed their color but they don't have any changes. Any ideas about this issue? 

Note: To reproduce the issue you don't need comparator (it's only to explain the real use case). You just need to update item property which affect `getLayoutRes()` and call `moveItem()`

**Comment by davideas** [comment]
@yamelkaya, yes it is perfectly normal that behavior.
You can't use different layout when changing status, because that RV is recycled for others elements too.

What you need to do is use same layout, then, you bind different color based on the status of that specific item. RV won't be recreated if the layout is the same, for this reason they named Recycler View the list.
