### ISSUE TITLE
Filter bug for expendable items

### ISSUE THREAD

**Issue by volser** [davideas/FlexibleAdapter#261]
Version: 5.0.0-SNAPSHOT built on 2016.12.20

I have 2 levels list:

For example:
Level1A
  -Level2A
  -Level2B
  -Level2C
  -Level2D
Level1B
...

I tries to filter items (for example search text = "B"). If "Level1A" collapsed before search - all ok
Result:
Level1
  -Level2B

But if "Level1A" expanded before search then:
Level1A
  **-Level2A
  -Level2B
  -Level2C
  -Level2D**
  -Level2B

on collapse with active filter - got crash

java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{1ea9c4 position=1 id=-1, oldPos=5, pLpos:5 no parent}

**Comment by davideas** [comment]
@volser, if you filter with "B" how comes that you have that second list?
I tried with the demoApp, it doesn't occur what you say.

**Comment by volser** [comment]
I understand.
I used for filterItems() the same list as for the adapter, but after expanding, this list is mutated (added subitems )

**Comment by davideas** [comment]
Oh I see, you need to pass always the original unfiltered list to `filterItems()`, this because if reduce the filter, the adapter needs to show again all the original items previously filtered out, it takes the items from the original source of information.

PS. You can already use the rc1 version.

**Comment by davideas** [comment]
In your case the original list, is still without subItems.

**Comment by volser** [comment]
I made copy of original list:
List<...> originalItems = new ArrayList<>(items);
adapter = new BaseAdapter<>(items);


and also set copy for unfiltered:
if (adapter.hasNewSearchText(newText)) {
                        adapter.setSearchText(newText);
                        adapter.filterItems(new ArrayList<>(originalItems));
                    }

and for "B" I got (header with all childs)
Level1A
-Level2A
-Level2B
-Level2C
-Level2D

why?

**Comment by volser** [comment]
"originalItems" contains only top level items (Level1A, Level1B)
What could be wrong?

**Comment by davideas** [comment]
The list you named `originalItems` and that you pass to the adapter, it's rather the one modified internally by the adapter, so it is not the original list. You probably want to name it `adapterItems`? It looks like the original list is the one named `items`.

it's ok if you pass a copy of the list to filterItems.
Can you try? `adapter.filterItems(new ArrayList<>(items));`

**Comment by davideas** [comment]
Sorry I read it wrong. let me see.

**Comment by volser** [comment]
Likely, I need "deep" copy of list , not only list, I need new items also.
It is not very useful if I want filter only local items (without some remote request)

**Comment by davideas** [comment]
Let's check if you properly implemented `equals` method of the items, can you post the 2 equals methods here?

PS. Deep copy not necessary.

**Comment by volser** [comment]
`    @Override
    public boolean equals(Object inObject) {
        if (inObject instanceof AbstractModelItem) {
            AbstractModelItem inItem = (AbstractModelItem) inObject;
            return this.id.equals(inItem.id);
        }
        return false;
    }
`

**Comment by davideas** [comment]
This equals method is inside the AbstractModelItem class?

**Comment by volser** [comment]
yes

**Comment by davideas** [comment]
Ok from here, I can't see so much. Please enable the logs with the static call `enableLogs()` before creating the adapter. Also try to debug the `filter()` method. You will be also able to see the mItems inside the adapter if you check filterItems method.
Maybe you can tell me more.

**Comment by davideas** [comment]
Use the rc1 version, so you can see the latest source code when debugging.

**Comment by volser** [comment]
here addFilteredSubItems() 

if (!subItem.isHidden())  -- always true

**Comment by volser** [comment]
I found issue, very strange

mSubItems = Lists.transform(...);

Lists.transform - it's from Guava

and mSubitems somehow changed all time

mSubItems = Lists.newArrayList(Lists.transform()) - works fine

**Comment by davideas** [comment]
Wow, so it now works as expected?

**Comment by volser** [comment]
yeah

**Comment by volser** [comment]
Thanks for help and cool library 👍

**Comment by davideas** [comment]
Thank you!
