### ISSUE TITLE
Some problem about use  Shared Element Transitions

### ISSUE THREAD

**Issue by JakeWoki** [davideas/FlexibleAdapter#263]
# [Video](https://github.com/JakeWoki/FlexibleDemo/blob/master/device-2017-01-09-155342.mp4)
![20170109155424](https://cloud.githubusercontent.com/assets/6948411/21760382/a6825a5a-d686-11e6-9f4c-b2745f501d3f.png)
![20170109155438](https://cloud.githubusercontent.com/assets/6948411/21760383/a6b1df28-d686-11e6-97a7-b421637f79c2.png)

# [FlexibleDemo](https://github.com/JakeWoki/FlexibleDemo)

can you give me some help?

**Comment by davideas** [comment]
I also encountered something similar, I did not resolve it yet. Might this help http://stackoverflow.com/questions/26567822/hiccups-in-activity-transitions-with-shared-elements ?
