### ISSUE TITLE
Is there a way to make a RecyclerView circular and center locked autoscroll using FlexibleAdapter?

### ISSUE THREAD

**Issue by DaLN** [davideas/FlexibleAdapter#264]
#Hi everyone, here is what i want to obtain.

> Default:
> View1 -> View2 -> View3 -> View4 -> View5
> 
> Selecting View2:
> View5 -> View1 -> View2 selected -> View3 -> View4

It seems we can't override getItemCount as it is final in FlexibleAdapter so i am not sure that there is a way to make the scroll circular.

Thanks for your answers.

**Comment by davideas** [comment]
Hello @DaLN, circular for sure not. but maybe centered yes.
Anyway, it's something not related with the adapter: Recently, a new version of Support Library was released with `LinearSnapHelper`. Good luck!
