### ISSUE TITLE
UndoHelper dismissed quickly with Snackbar predefined lengths.

### ISSUE THREAD

**Issue by inorichi** [davideas/FlexibleAdapter#265]
In [this line](https://github.com/davideas/FlexibleAdapter/blob/rc1/flexible-adapter/src/main/java/eu/davidea/flexibleadapter/helpers/UndoHelper.java#L159), 400ms are added  to `undoTime` to compensate animations.

When using `Snackbar#LENGTH_LONG` or `Snackbar#LENGTH_SHORT` (valid values according to the documentation), the snackbar is dismissed almost instantly because its values are 0 and -1.

This could be fixed by using `undoTime > 0 ? undoTime + 400 : undoTime` or directly comparing those two options. Maybe you could also make the `@IntRange` annotation start from -1.

**Comment by davideas** [comment]
@inorichi, yes!
