### ISSUE TITLE
Sticky headers don't work when all headers are initially collapsed

### ISSUE THREAD

**Issue by inorichi** [davideas/FlexibleAdapter#268]
As the title says, if all the headers of the adapter are collapsed when initially calling `updateDataSet`, sticky headers don't work after expanding them, but it works if I expand one and rotate the screen.

From my investigation, I think this is due to the `headersShown` property, which is always false if the initial state was collapsed.

I think the problem resides [in this line](https://github.com/davideas/FlexibleAdapter/blob/master/flexible-adapter/src/main/java/eu/davidea/flexibleadapter/FlexibleAdapter.java#L351). I don't know if there's a reason to initialize it there, but I think this condition should be outside `if (isExpanded(item))`, because AFAIK that property only controls whether the headers are visible, but here it also requires that at least one is expanded.

**Comment by inorichi** [comment]
Nevermind, it was my fault. I initially had `setDisplayHeadersAtStartUp(true)` but removed it trying to find another bug I had before and forgot to add it again. Calling this method make them work even if they are initially collapsed.

However, I don't know if the line I mentioned before could still cause another issue, it might be worth to check that just in case.

**Comment by davideas** [comment]
@inorichi, I marked this as bug and also fixed for next version, but since it is not a blocking I leave this issue closed. Thanks.
