### ISSUE TITLE
onLoadMoreComplete doesn't show headers

### ISSUE THREAD

**Issue by BoukhariAyoub** [davideas/FlexibleAdapter#271]
Hello, I'm trying to make a simple instagram like behaviour, but when I set the endless scroller the new Items are showing without headers and getting attached to the last Header.

I used the same code as the sample (instagram)

**Comment by davideas** [comment]
@BoukhariAyoub, items, that are still of type `ISectionable`, must have non-null header, same initialization at startup. So you don't have to add headers, but only items.
Concept, items and its implementation for sections don't change. Check `equals` method first!
