### ISSUE TITLE
ActionModeHelper does not replace Toolbar

### ISSUE THREAD

**Issue by rmunk** [davideas/FlexibleAdapter#272]
I am trying to use `ActionModeHelper` with `FlexibleAdapter` in my fragment which is inside standard `AppCompatActivity` with `AppBar` and `Toolbar`.

For some reason `ActionModeHelper` fails to replace the `Toolbar` like in the sample app but draws itself above it instead:
![device-2017-01-26-131815](https://cloud.githubusercontent.com/assets/1774159/22333648/80e4b67c-e3d7-11e6-9439-5519504dcefe.png)

Is it because I am using it in a fragment or did I miss something else? Here is how I initialize it from fragments `onCreateView`:
```
    private void initializeActionModeHelper(int mode) {
        mActionModeHelper = new ActionModeHelper(adapter, R.menu.menu_context, this) {
            @Override
            public void updateContextTitle(int count) {
                if (mActionMode != null) {
                    mActionMode.setTitle(count == 1 ?
                            getString(R.string.action_selected_one, String.valueOf(count)) :
                            getString(R.string.action_selected_many, String.valueOf(count)));
                }
            }
        }.withDefaultMode(mode);
    }
```
I bring it up like this:
```
    @Override
    public void onItemLongClick(int position) {
        mActionModeHelper.onLongClick((AppCompatActivity) getActivity(), position);
    }
```

**Comment by davideas** [comment]
@rmunk, please check your style as done [here](https://github.com/davideas/FlexibleAdapter/blob/master/flexible-adapter-app/src/main/res/values/styles.xml#L8).

**Comment by rmunk** [comment]
Thanks, I apologize for my stupidity.

**Comment by davideas** [comment]
@rmunk no problem.
