### ISSUE TITLE
Sticky headers not being recycled

### ISSUE THREAD

**Issue by allenchen1154** [davideas/FlexibleAdapter#273]
Library version: 5.0.0-rc1
Android API: 25
Support library version: 25.1.0
Hardware: x86-64 Emulator

It looks like the ViewHolder that corresponds to my sticky item (extends `AbstractHeaderItem`) is inflated every time you scroll past its position in the list. Is this intended behavior?

I am not using AutoMap - `android.support.v7.widget` is calling my adapter's `onCreateViewHolder()` method.

**Comment by davideas** [comment]
@allenchen1154, yes it is a intended behavior to have it sticky. If you check the code I make it not recyclable `setIsRecyclable(false)` when swapped.
