### ISSUE TITLE
How to put ExpandableHeader items list in accordion mode

### ISSUE THREAD

**Issue by a-nightcrawler** [davideas/FlexibleAdapter#275]
Hi guys, I was wondering if there is any way to make ExpandableHeader items list act like an accordion.
For example: I initially got all my items collapsed, then I tap on one to expand it, and then when I tap on another item the previous one collapse itself in a  way that every time only one item is expanded. I would really appreciate your help to achieve this :). Thanks so much.

**Comment by davideas** [comment]
@a-nightcrawler, you can call `setAutoCollapseOnExpand(true)`.

**Comment by a-nightcrawler** [comment]
Thanks, it works perfectly
