### ISSUE TITLE
DividerItemDecoration bug when using sticky headers

### ISSUE THREAD

**Issue by faridfor** [davideas/FlexibleAdapter#276]
Hi.
I am using version 5.0.0-rc1
I have a adapter with sticky headers:
`mAdapter.setStickyHeaders(true).setDisplayHeadersAtStartUp(true);`
and after adding a divider :
`mRecyclerView.addItemDecoration(new DividerItemDecoration(getContext(), R.drawable.post_list_divider).withOffset(false));`
i see this: (header view is semi-transparent)
![screenshot_20170205-190254](https://cloud.githubusercontent.com/assets/6500386/22627429/4a885850-ebd8-11e6-9995-a7430f31ddfe.png)

my divider resource:
``` xml
<shape xmlns:android="http://schemas.android.com/apk/res/android"
       android:shape="rectangle">
    <solid android:color="#F00"/>
    <size
        android:width="16dp"
        android:height="64dp"/>
</shape>
```
its buggy even when i set `whitOffset` to true
header and item height is fixed.

**Comment by davideas** [comment]
@faridfor, this seems more related to the header item background. How is it configured? Do you use any of the new features of transparency?

**Comment by faridfor** [comment]
this is my header, it has a transparent background

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              xmlns:app="http://schemas.android.com/apk/res-auto"
              xmlns:tools="http://schemas.android.com/tools"
              android:layout_width="match_parent"
              android:layout_height="wrap_content"
              android:background="#33121315"
              android:gravity="center_vertical"
              android:padding="4dp">

    <ImageView
        android:id="@+id/timeline_row_comment"
        android:layout_width="34dp"
        android:layout_height="34dp"
        android:layout_marginRight="8dp"
        android:clickable="true"
        app:srcCompat="@drawable/ic_comment_yellow_36dp"/>

    <ImageView
        android:id="@+id/timeline_row_like"
        android:layout_width="34dp"
        android:layout_height="34dp"
        android:clickable="true"
        app:srcCompat="@drawable/ic_favorite_border_light_gray_24dp"/>

    <com.robin.framework.components.ui.textview.RTextView
        android:id="@+id/timeline_row_name"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_weight="1"
        android:ellipsize="end"
        android:gravity="right"
        android:lines="1"
        android:maxLines="1"
        android:paddingRight="8dp"
        android:textSize="16sp"
        tools:text="Farid"/>

    <de.hdodenhof.circleimageview.CircleImageView
        android:id="@+id/timeline_row_avatar"
        android:layout_width="@dimen/profile_image_size_normal"
        android:layout_height="@dimen/profile_image_size_normal"
        android:src="@drawable/default_avatar"
        app:civ_fill_color="#2c323e"/>

</LinearLayout>

**Comment by davideas** [comment]
@faridfor, sorry but your post represents the content of the header, I asked the header container.

**Comment by faridfor** [comment]
sry github dose not show my layout :(
here is my layout:
`<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              xmlns:app="http://schemas.android.com/apk/res-auto"
              xmlns:tools="http://schemas.android.com/tools"
              android:layout_width="match_parent"
              android:layout_height="wrap_content"
              android:background="#33121315"
              android:gravity="center_vertical"
              android:padding="4dp">
`

**Comment by davideas** [comment]
@faridfor, I added your decorator with `offset=true` and added the transparency to the header item, I do not see it any problems, this is the result:

![screenshot_1486919488](https://cloud.githubusercontent.com/assets/12213847/22864296/0ae91028-f14f-11e6-9bcc-afdce9b05969.png)

You should have something particular in your code, because decorator must lay between items (see the red color), why in your case is under the header?!?

**Comment by davideas** [comment]
Maybe I understood!
Only when `offset=false` i reproduced your issue, fortunately I have entry animations enabled and I see the decorator under the items for a fraction of time, so the decorator is displayed under the transparent item.

I can say, your configuration is wrong in some concepts:
- The height of the decorator is too high.
- `Offset=true` leaves the space of the decorator between all items, `false` the decorator will be drawn over the items.
- If you want header with red background, just put it, do not have it transparent.
- You probably don't want decorator between the items, maybe?
