### ISSUE TITLE
How to merge new items with same Header

### ISSUE THREAD

**Issue by lemonboston** [davideas/FlexibleAdapter#277]
If I use FlexibleAdapter with sticky Headers, how can I add new List of items to the adapter which may contain Header that is already in the list?

Like:
```
List<ISectionable> originalItems = new ArrayList();

IHeader headerA1 = new Header(1);
ISectionable itemA1 = new Item(A1);
itemA1.setHeader(headerA1);
originalItems.add(itemA1);

ISectionable itemA2 = new Item(12);
itemA2.setHeader(headerA1);
originalItems.add(itemA2);
// ...originalItems contains more Headers and items as well

FlexibleAdapter adapter = new FlexibleAdapter(originalItems);
// .. setup

List<ISectionable> newItems = new ArrayList();

IHeader headerB1 = new Header(1);
ISectionable itemB1 = new Item(B1);
itemB1.setHeader(headerB1);
newItems.add(itemB1);
// ...newItems contains more headers and items


// How to add newItems to the list to have only one Header(1)?

// Even though headerA1.equals(headerB1) is true, addItems() will result in a second Header(1) added to the list:
adapter.addItems(0, newItems);

```
So does FlexibleAdapter support some automatic merging of the headers that are equal or do I have to do that manually by using the correct references of the actual header objects?
Either by using addItemToSection(), or with addItems() but with replacing headerB1 with headerA1 for the items in newItems before adding them.

Thanks.

**Comment by davideas** [comment]
@lemonboston, the new items should have already the destination header, and since the order of displaying depends a lot of the user content, then you need to create your own logic to automatically sort the new items within the section. To do that you have to pass your own `Comparator` object to the `addItemToSection()`. Check the Comparator I've done in my example to take some clues.

If you already know the adapter position then you can use `addItem[s]`, here new sections are automatically added and shown when adding section items.

**Comment by lemonboston** [comment]
I know the position, so I could use `addItems()` but that result in duplicate header.

So it's like this:

```
First load:

Feb 17 (header)
Event 3
Event 4

Loading previous page on top of it with `addItemToSection()`, it pushes down 3 an 4 if list is at scrolled to top, which is not good for us, it should stay at 3:

Feb 17 (Header)
Event 1
Event 2
Event 3
Event 4

Loading previous page on top with 'addItems()`, * are off screen (need to scroll up to see):

Feb 17 (Header)*
Event 1*
Event 2*
Feb 17 (Header)
Event 3
Event 4

```

Is there any way to solve this? Thanks.

**Comment by davideas** [comment]
@lemonboston, if you have duplication the answer is easy: the header is different, so it is different instance. To resolve logic duplication you have to take the same header instance.

**Comment by lemonboston** [comment]
I did try with updating the headers to the same instance in both ways.

So with update new items to have the same header as already in the list, this happens:

```
First load:

Feb 17 (header)
Event 17-3
Event 17-4

Loading previous page on top of with `addItems(0, newItems)`

Feb 16 (Header)*
Event 16-1*
Event 16-2*
Event 16-3*
Event 16-4*
Event 17-1*
Event 17-2*
Feb 17 (Header)
Event 17-3
Event 17-4
```

With the other way, so updating existing items to have the same header as in the incoming items:

```
First load:

Feb 17 (header)
Event 17-3
Event 17-4

Loading previous page on top of with `addItems(0, newItems)`

Feb 16 (Header)*
Event 16-1*
Event 16-2*
Event 16-3*
Event 16-4*
Feb 17 (Header)*
Event 17-1*
Event 17-2*
Feb 17 (Header)
Event 17-3
Event 17-4
```

**Comment by davideas** [comment]
I understand that you are adding items of different groups all together in an unique command. For how it is done, the adapter can't know the order/position of addition of all new items cross sections.

The sort algorithm is yours: every time you encounter a new header you take header position and add the new items that belongs to that section to the correct position.

I would do with a custom Comparator. it becomes useful to insert every new items at the right position inside each section.

**Comment by lemonboston** [comment]
We don't really need a sorting and comparison because the items are provided in correct order by our API and I think the Comparator wouldn't have helped, because as I come to understand the problem is simply that when adding items to a RecycerView to a postion which is visible, it of course shows them and pushes everything down. And because the IHeader was a visible item, adding anything under it naturally pushes the rest down. Only if items are added above it (at position 0), then RecyclerView adds them 'outside' of the screen.
During trying out different ways to solve this, I finally 'stumbled upon' one that worked: simply removing the IHeader item before adding the new items.

This is how I do it now and seems to work:
```
    private void mergeNewItemsTop(List<IFlexible> newItems)
    {
        IHeader firstDayInCurrent = getFirstHeaderCurrent();
        IHeader lastDayInNew = getLastHeader(newItems);

        if (Objects.equals(lastDayInNew, firstDayInCurrent))
        {
            mFlexibleAdapter.removeItem(mFlexibleAdapter.getGlobalPositionOf(firstDayInCurrent));
            int lastItemWithDistinctHeader = -1;
            for (int i = newItems.size() - 1; i >= 0; i--)
            {
                if (newItems.get(i) instanceof ISectionable)
                {
                    ISectionable item = ((ISectionable) newItems.get(i));
                    if (item.getHeader().equals(lastDayInNew))
                    {
                        item.setHeader(firstDayInCurrent);
                        mFlexibleAdapter.addItemToSection(item, firstDayInCurrent, 0);
                    }
                    else
                    {
                        lastItemWithDistinctHeader = i;
                        break;
                    }
                }
            }
            List<IFlexible> distinctItems = newItems.subList(0, ++lastItemWithDistinctHeader);
            mFlexibleAdapter.addItems(0, distinctItems);
        }
        else
        {
            mFlexibleAdapter.addItems(0, newItems);
        }
    }
```

**Comment by davideas** [comment]
@lemonboston, I see you have found a nice solution to add new items when header was already visible.

**Comment by lemonboston** [comment]
I don't know how nice it is but it worked :)

But we still have a problem: when the items are added on top without 'merging', so the `else` branch in the code above, simply using `addItems(0, newItems)` where `newItems` have distinct headers from the ones already in the list, then the current top header flashes.

Here are two screen videos:

merging, non-flashing:
https://drive.google.com/open?id=0Bzp0PP6UbK4lRzR4SEVDT1JreTg

non-merging, flashing:
https://drive.google.com/open?id=0Bzp0PP6UbK4lUk81V3BNaU9SR00

Do you have some idea why this happens? What can I try to fix this flash.
Thanks.

**Comment by davideas** [comment]
Well, you said that you remove it and when new items are added, it is displayed again. There are 2 notifications for this "flash". I am not sure you can do something about it.

**Comment by lemonboston** [comment]
This case I have problem with is the straightforward one when there is no 'merging' needed (no common header in the current list and incoming items).
So for example this:

```
Items added originally:
Event 16-1 (Header: Feb 16)
Event 16-2 (Header: Feb 16)

Displayed:
Feb 16 (Header)
Event 16-1
Event 16-2

New items arriving for adding to the top:
Event 15-1 (Header: Feb 15)
Event 15-2 (Header: Feb 15)

Using flexibleAdapter.addItems(0, newItems), the displayed result is correct:
Feb 15 (Header)*
Event 15-1*
Event 15-2*
Feb 16 (Header)
Event 16-1
Event 16-2

* outside of screen

But the Feb 16 (Header) flashes once.
```
So there is no removal here, I only call `addItems(0, newItems)`. So what are those 2 notifications?
If you have any hunch what is behind this, what is the mechanism that may cause the flash, please let me know, it may help me fix it on my side.
(I've found a fix actually, but it's a big hack, it involves adding one item twice and then removing in the end. I would be more content with a better solution.)

Thanks in advance.

**Comment by davideas** [comment]
@lemonboston, I need to investigate while you have that flash, I will try to reproduce it.
Did you try to disable temporary the sticky header in such situation? enable again after adding.

**Comment by lemonboston** [comment]
I just tried with disabling and enabling the sticky headers, like this:
```
mFlexibleAdapter.setStickyHeaders(false);
mFlexibleAdapter.addItems(0, newItems);
mFlexibleAdapter.setStickyHeaders(true);
```
It did solve the 'flash' when I haven't scrolled down before, the header is perfectly still in place. But it makes a small short glitch for the top header if I scrolled down already when adding the items on the top.

So maybe it could be combined with the hack I have currently, which is this by the way:
```
// firstDayInCurrent is the first header in the current list:
mFlexibleAdapter.removeItem(mFlexibleAdapter.getGlobalPositionOf(firstDayInCurrent));

ISectionable dummyItem = (ISectionable) newItems.get(newItems.size() - 1);
mFlexibleAdapter.addItemToSection(dummyItem, firstDayInCurrent, 0);
dummyItem.setHeader(lastDayInNew);

mFlexibleAdapter.addItems(0, newItems);

mFlexibleAdapter.removeItem(mFlexibleAdapter.getGlobalPositionOf(dummyItem) + 2);
```
So maybe checking for `firstVisibleItem` position and then choose based on that which hack to use..
Not nice anyway. If you don't happen to have any other tip, or maybe reproduced and solved it, then I will probably stay with this current hack.

**Comment by davideas** [comment]
@lemonboston, sorry, I need some time to reproduce, actually I do not have so much.

**Comment by lemonboston** [comment]
No problem, I understand of course, thanks anyway for the tips.
I've applied some of these hacky workarounds, they cover now almost all of our anomalies.
But if you think you may have time for it some time in the future so you would keep this open, that would be great, the proper solution might come useful that time, too.
(If we didn't need it any more, I try to keep in mind to come back here and comment.)

**Comment by davideas** [comment]
@lemonboston, there were several improvements related to sticky headers in the last release. Could you please try to remove your work-around?

**Comment by lemonboston** [comment]
I am afraid we don't have time for checking it now thoroughly so I wouldn't like to touch that code currently unless it's necessary, to avoid getting bogged down or causing any side effects.
But it's good to hear that there were improvements and thanks for letting me know. I'll keep in mind to update the version and check back on the workarounds when we need to touch that part of the code base again.

Feel free to close this issue of course, I will create a new one if I encounter anything later.
