### ISSUE TITLE
emptyview

### ISSUE THREAD

**Issue by Tiannuo** [davideas/FlexibleAdapter#279]
please add emptyview,thanks

**Comment by davideas** [comment]
@Tiannuo, emptyView is sub view in the layout where the RecyclerView lays, the Adapter has a listener you can implement, but it is useless for the adapter to invoke Visible/Invisible. The developer can customize the behavior if this choice is free for him.
You can check the demoApp to see how it should be implemented and controlled.

**Comment by Tiannuo** [comment]
thanks very much ,i got it.
