### ISSUE TITLE
Search & filtering

### ISSUE THREAD

**Issue by lostation** [davideas/FlexibleAdapter#280]
Hi folks,

I've added the searchable functionality and it works well just when I add input text and not when I remove text.

So I can make a search of word in my adapter dataset and the text is highlighting if matches -> nice ! ... but not on every showed items.

I'm pretty sure it's linked to a refresh problem cause I have UI troubles when I remove search text.
The refresh of the initial list seems to be done but visually there's also some old filtered items that remains. So It's like some super impose of two lists one on top of the other. 

Below is parts of search method in my adapter implementation

private boolean animate = false;
private List<AbstractFlexibleItem> items = get input data from model ...
private List<AbstractFlexibleItem> initialDataset = null;    -> initial data to adapter
private List<AbstractFlexibleItem> listToSearch = null;     -> copy for search

Can you just tell me if I missed something in initialization or filtered/unfiltered items ? 

-->So I do first a call to    updateDataSet(items, animate);   to get database data and make a first copy of items into initialDataset then set that as initial adapter content.

@Override
public void updateDataSet(List<AbstractFlexibleItem> dataset, boolean animate) {
        if (dataset != null && dataset.size() > 0) {
            initialDataset = new ArrayList<>(dataset);
            super.updateDataSet(initialDataset, animate);
        }
}

Then when I add text in my search field, it goes to this method

public void searchText(String search){

        if (StringUtils.isEmpty(search)) { 
           // run if search field is empty null to reset everything to initial state the adapter content
           // but I suppose the problem is there somewhere...

            setSearchText(null);
            if (listToSearch != null && listToSearch.size() > 0) listToSearch.clear();
            updateDataSet(items, animate);
            notifyDataSetChanged();
            return;
        }

        // otherwise it makes the search if there's something to search into from a search copy list !
        if (initialDataset != null && initialDataset.size() > 0) {
            listToSearch = new ArrayList<>(initialDataset);
            if (hasNewSearchText(search)) {
                setSearchText(search);
                filterItems(listToSearch, 200);
            }
        }
}

Thanks for help
Lo.

**Comment by lostation** [comment]
I simplify a bit 

        if (hasNewSearchText(search)
                && initialDataset != null && initialDataset.size() > 0) {
            setSearchText(search);
            filterItems(initialDataset, 200);
        }

    public void setChoiceList(List<ChoiceModel> choiceModelList){
        if (choiceModelList != null && choiceModelList.size() > 0){
            initiaChoiceModelList = new ArrayList<>(choiceModelList);
            updateChoiceList(initiaChoiceModelList);
        } else {
            updateChoiceList(null); // reset
        }
    }

@Override
    public void updateDataSet(List<AbstractFlexibleItem> dataset, boolean animate) {
        if (dataset != null && dataset.size() > 0) {
            initialDataset = new ArrayList<>(dataset);
            super.updateDataSet(initialDataset, animate);
        }
    }

but nothing better...

So in fact, remove/add char from search textfield will not correctly refreshing the content of recyclerView... The content and the highlighting... I need to scroll to recycle items and then I can see some highlighted text but I'm still facing with some duplicated ghosts items, a mix from initial list and filtered list. 

Seems also the sticky mechanism is goes below the "refreshed" list... the text content is moving above the sticky header.

I tried resetting with new dataset (i.e.... with other flexible object model with others id)
setSearchText(null or empty);
I tried using filters(with the same list of init of adapter) 
I tried using filters(with a copy of the same list of init of adapter) 
I tried using some notify* methods to rebind some stuffs  without success.

I do something wrong but I cannot figure it out where with your system of copies of model list copy hash and whatever... I'm pretty sure I don't need to reset and recreate all the adapter each times and let the search mechanism uses the hash storages to get fast access to data.

Please can you just send me an example "other than the demo app"... ?

Your help and advices will be really appreciated. 

I can't really spend more time working on trivial configuration... :-(

Thanks in advance.
Lo.

**Comment by davideas** [comment]
@lostation, I see that you are using the same instance `initialDataset` to initialize the Adapter **and** to filter the items, so the original list is not copied while filtering and the adapter already modified it when filtering it.
Internally, the Adapter deletes items while filtering, so if you remove chars in the search text it needs to find items from the original list, not from the original instance.

The Adapter to needs a copy when you _initialize_ it, when _updating_ the dataset and a new one when _filtering_. Basically, every time the **full** dataset changes.
Also you need to enable this option `setNotifyChangeOfUnfilteredItems`, everything is explained in the wiki page, but you can also check my demoApp and run the sample of the AsyncFilter.

> Why the copy? because the Adapter is on the presentation layer, while the Database is at lower layer. Normally, we should have this distinction and converting items from one layer to another to be more flexible to maintain the code.
Also, on presentation layer, displayed data can differ in format from the database data.

**Comment by lostation** [comment]
Ok it works...

I was misunderstanding the utility to recreate really each time a new dataset with fresh AbstractModelItem entity ID and new linked Hashcodes.

In fact, I was storing and always copy ( for search for instance) the initial dataset that I pushed to adapter on first step...  That was indeed wrong ! 

It NEEDS new ID and hashcodes ! So on every add/remove character it recreate a new copy from my models into a full Hashset in adapter. It's like recreate the adapter finally... 

So now all is pretty nice now ! THANKS for help and hints ! ;-)
