### ISSUE TITLE
how to set padding of sticky headers programmatically?

### ISSUE THREAD

**Issue by daquexian** [davideas/FlexibleAdapter#282]
Library version: 5.0.0-rc1

In ViewHolder, I used `itemView.setPadding` to set padding of `itemView` programmatically, but when the item gets sticky on top, the padding I set before doesn't work any more. And I couldn't find a method to set padding of sticky headers programmatically. How could I solve it?

Thanks in advance

**Comment by davideas** [comment]
@daquexian, can you try to call `getContentView()` in the constructor of the ViewHolder?
Read the comment on it.

**Comment by daquexian** [comment]
Thanks for you reply! It solved my problem.

I have another problem about padding. My RecyclerView has a padding, how
can I make the sticky header follow this padding without setting the
padding of outer FrameLayout instead?

**Comment by davideas** [comment]
@daquexian, you can create your own header container, and assign it to the Adapter.
The default header container is inside another FrameLayout for elevation effect.

Check the code here [StickyHeaderHelper](https://github.com/davideas/FlexibleAdapter/blob/master/flexible-adapter/src/main/java/eu/davidea/flexibleadapter/helpers/StickyHeaderHelper.java#L102) and here [setStickyHeader()](https://github.com/davideas/FlexibleAdapter/blob/master/flexible-adapter/src/main/java/eu/davidea/flexibleadapter/FlexibleAdapter.java#L1379).

**Comment by daquexian** [comment]
It works, thanks a lot
