### ISSUE TITLE
FlexibleAdapter#removeAllScrollableFooters() seems to notify incorrect item range

### ISSUE THREAD

**Issue by kvolkers** [davideas/FlexibleAdapter#284]
v5.0.0-rc1
https://github.com/davideas/FlexibleAdapter/blob/master/flexible-adapter/src/main/java/eu/davidea/flexibleadapter/FlexibleAdapter.java#L909

I think this line should be changed from:
`notifyItemRangeRemoved(getItemCount() - 1 - mScrollableHeaders.size(), mScrollableFooters.size());`
to:
`notifyItemRangeRemoved(getItemCount() - mScrollableFooters.size(), mScrollableFooters.size());`

Calling `removeAllScrollableFooters()` for these example items:
0 - Scrollable Header
1 - Scrollable Header
2 - Content Item
3 - Content Item
4 - Scrollable Footer

`notifyItemRangeRemoved(2, 1)` is called
getItemCount() => 5, minus 1 and minus 2 for mScrollableHeaders.size()

when I think it should be `notifyItemRangeRemoved(4, 1)`

**Comment by davideas** [comment]
@kvolkers, yes, you're right, I'll fix it asap and initially publish as snapshot version.
