### ISSUE TITLE
[QUESTION] Can we remove a AbstractSectionableItem from onBindViewHolder

### ISSUE THREAD

**Issue by ahmedkhan23** [davideas/FlexibleAdapter#285]
Just wondering if it is possible to remove an AbstractSectionableItem from onBindViewHolder callback within the same class ?

Basically I have a view within my ViewHolder that actions the delete right away.

When I do this using removeItem(position) from within onBindViewHolder I notice that the "removed view" appears stacked below the recyclerview in the same position ...

**Comment by davideas** [comment]
@ahmedkhan23, the question is applicable for any item type, and is more generic to all Adapters.
The event of removal is triggered by something external normally, you are removing the same view during the binding, so the LayoutManager wants to display it but you are actually removing the item, creating another notification for removal.
LayoutManager may not stays at your step for this specific case.

- Clarify if the removal should be done during the binding of itself.
- You can add a post delay or use the `removeItemWithDelay()` method, since the Adapter it is currently binding the view to display it.

General question, are you using the new binding from the items (item delegation) or the classic way to bind by extending the Adapter `onBindViewHolder()`?

**Comment by ahmedkhan23** [comment]
I am using the new method, binding from within the item.
Removal is not done during binding. What I have is a clicklistener on the "delete button" within the viewholder that will trigger the removal. So only when the button is clicked will this occur.

**Comment by davideas** [comment]
Ah ok, well, it normally works then, the demoApp if full of this use case. Maybe you can check it out.

**Comment by ahmedkhan23** [comment]
@davideas A hack that I am able to employ is I set the Visibility of the itemView in the ViewHolder to gone after calling removeItemWithDelay();
The adapter does remove the item but it for some reason appears "behind/below [z-axis]" the recyclerview in the same spot it originally was.

**Comment by ahmedkhan23** [comment]
@davideas actually that view appearing behind is causing issues -> this was caused by setting isRecyclable(false) on the ViewHolder.

The reason I set isReyclable(false) on the ViewHolder is because after I add a new Item in onSwap() and I scroll up and down in my list my ViewHolders are appearing in different positions.
I really don't know why that was happening but I set isRecyclable(false) and didn't get any error messages and my RecyclerView was fine.

So I have removed the line isRecyclable(false) now but my list items are appearing in different positions and different items are being deleted then the one I intended -> So that should be my question, how to fix recycling views appearing in random positions:

If you have a chance, here is my SectionItem, TestAdapter, MainActivity [small classes]
https://github.com/ahmedkhan23/android-samples/tree/master/FlexibleAdapterDemo/app/src/main/java/com/ahmed/flexibleadapterdemo

**Comment by davideas** [comment]
@ahmedkhan23, yes, it's the equals method not well implemented, actually returns false.
If you don't have an ID, use the classic java implementation `return this == o;`

**Comment by ahmedkhan23** [comment]
I have updated the "equals" method in both SectionItem and HeaderItem to use the standard java implementation and also something other than "return false".

I am still having the issue. My use case is before I remove an item from a section I check to see if the size of the section is "1". If the size is "1", removing this sole item would render the section empty and this is not what I want. So before I remove the item I add another "empty" SectionItem, and then I remove the original intended SectionItem. All this code is in onBindViewHolder of SectionItem. This works fine. However, on scrolling up and down twice, I see the "empty" SectionItem appearing at the bottom of the list.

I have navigated intensively throughout the sample app and any other issues on github and am really stumped. I am certainly missing something. My hunch is that it may have something to do with "payload" or setFixedSize(true/false) on RecyclerView.

**Comment by ahmedkhan23** [comment]
@davideas I believe it is my bindViewHolder() in my SectionItem that is causing issues. I can't seem to pinpoint it. What I do is in my bindViewHolder() I am changing visibility of views inside my holder based on certain user actions.

I have never used payload before. I read the Javadoc on it , and saw your implementation but still not clear on its use.

If my bindViewHolder() looks good, let me know I will look for a solution elsewhere.

**Comment by davideas** [comment]
@ahmedkhan23, can you try to use java implementation `return this == o;`? Title "empty" is not unique.

**Comment by ahmedkhan23** [comment]
@davideas yup, tried it. It was commented in code as I was toggling between that and the block of code above it.
Didn't work.

**Comment by davideas** [comment]
@ahmedkhan23, when you say "bottom of the list", you mean behind others items?
Can you make a screenshot?

**Comment by ahmedkhan23** [comment]
@davideas Yup, I was trying to do a screen record and paste it here but didn't work, maybe I will upload it to YouTube, I will find a way to demo it.

**Comment by davideas** [comment]
yes you can do it, just drag an drop in edit mode.

**Comment by ahmedkhan23** [comment]
I get the following when trying to upload a .mp4 here
<img width="687" alt="screen shot 2017-02-16 at 10 46 19 am" src="https://cloud.githubusercontent.com/assets/5214703/23028407/3bd9103c-f435-11e6-99c4-60d17011dc07.png">

**Comment by ahmedkhan23** [comment]
Here it is 
https://youtu.be/Ag1qRNllcW8

When I delete items from the section at the top, before the section will be completely empty, I add in another item [this is done in onBindViewHolder]

Scroll up and down twice, and I notice that the top item appears as the last item in the list.

The issue of "appearing behind" -> I will see if I can capture it again, but it went away with using
the standard java "this == o" for the equals method.

**Comment by davideas** [comment]
I saw the video, it appears the last item has the property `empty` same as the first item.
Can't say looking your code only, you need to debug, by checking what exactly is the last item.
Also more logs can help.

Just to avoid any further complication, also `hashCode()` must be coherent with `equals()`. So can you try to remove it for now? usually is a `return id.hashCode()` if you have an unique id. it will use the default java, since for now it's not mandatory to implement, only if you use special features, like filter or big lists.

**Comment by davideas** [comment]
I close for now, if you need more help, please reopen.
For me this is not an issue in the Adapter.

**Comment by ahmedkhan23** [comment]
@davideas actually I had to take a break from this issue, now I am back at it. Putting in breakpoints in my SectionItem I noticed my "equals()" method is never called.

Forgive me, I just don't know what I am missing.

Here is my repo again, adapter init code is in MainActivity

https://github.com/ahmedkhan23/android-samples/tree/master/FlexibleAdapterDemo/app/src/main/java/com/ahmed/flexibleadapterdemo
