### ISSUE TITLE
Hiding headers at startup

### ISSUE THREAD

**Issue by restor1** [davideas/FlexibleAdapter#286]
The docs of FlexibleAdapter's 'setDisplayHeadersAtStartUp' method says
"Default value is {@code false} (headers are <u>not</u> shown at startup)"
while it seems that headers are actually shown by default..
Trying to hide headers using 'hideAllHeaders' works but
the headers are first displayed and then hidden.
How can I hide headers at startup?

**Comment by davideas** [comment]
@restor1, they are hidden for sure, probably you are adding them to the list at start up along with others items, thing that you should not do it :-)

**Comment by restor1** [comment]
I add only items of type AbstractExpandableHeaderItem directly to the list at startup 
but they did have sub-items added to them.
However, even if I add the sub-items later or add nothing but the headers with no sub-items at all,
the header is still displayed by default

**Comment by davideas** [comment]
Ah ok, expandables items must be visible, since they holds others sub items that are added by reference of the father item. If you need expandables you don't have choice that displaying them.
When they are collapsed and you hide them you loose the reference, and cannot be added anymore.

**Comment by restor1** [comment]
The use case is that I have a list of expandable headers and whenever there is only one header at the top level, I would like it to be hidden(so only it's sub-items are displayed). It can be achieved by 'hideAlHeaders', but then this will not happen immediately at startup.

**Comment by restor1** [comment]
Never mind, in case when there's only one top level header, I add it's "sub-items" directly the adapter and skip it.
