### ISSUE TITLE
UndoHelper.remove(...) return type changed

### ISSUE THREAD

**Issue by maltebucksch** [davideas/FlexibleAdapter#288]
I was fetcching the Snackbar created by the Undo Helper by saving the return value of `UndoHelper.remove(...)`.
However it seems that you changed the return type to `void ` in a commit two days ago (SHA 37a304be45652624a274003c738e5bb208ed653b). That makes it impossible to access the Snackbar.
For some events I want to forcefully hide the snackbar (and execute deletion) *before* the undo time is over yet. That seems not  possible without accessing the Snackbar (snackbar.dismiss()). Please change return type back to "Snackbar" again.
Thanks in advance!

**Comment by davideas** [comment]
Yes, I can revert it back. It will be available in the Snapshot version soon.
