### ISSUE TITLE
How to get swiped item after filtering?

### ISSUE THREAD

**Issue by uxname** [davideas/FlexibleAdapter#289]
How to get object (item) in adapter's listener in onItemSwipe method?
When i try to use myObjects.get(position) - it returns object BY POSITION from ALL my collection, but i want to get object BY POSITION from FILTERED items.
```
adapter.addListener(new FlexibleAdapter.OnItemSwipeListener() {
            @Override
            public void onItemSwipe(int position, int direction) {
                    myObjects.get(position);
            }
```

**Comment by davideas** [comment]
@uxname, you should use mAdapter.getItem(position);
