### ISSUE TITLE
[5.0.0-rc1] Expandable header is not resized / redrawn on automatic configuration change when sticky headers are enabled

### ISSUE THREAD

**Issue by arciszewskim** [davideas/FlexibleAdapter#294]
I need activity with android:configChanges="orientation|screenSize" and list with sticky expandable headers. I verified flexible-adapter-app sample with 
`
<activity android:name=".MainActivity" android:configChanges="orientation|screenSize">`
but after orientation change there is problem with size / blank expandable header (not all, some of them). 

Expandable headers with disabled sticky headers are OK with automatic configuration change. Regular headers too. Problem happens only when we want to use expandable header with sticky.

Any idea how to fix it?

![device-2017-02-19-212206](https://cloud.githubusercontent.com/assets/21089684/23106400/54962014-f6ed-11e6-9042-81f8e49b4d5a.png)
![device-2017-02-19-212058](https://cloud.githubusercontent.com/assets/21089684/23106401/54c05bc2-f6ed-11e6-9b74-3714fb14d51e.png)
![device-2017-02-19-212042](https://cloud.githubusercontent.com/assets/21089684/23106402/54c21192-f6ed-11e6-91a6-60c9311e1f7c.png)

**Comment by davideas** [comment]
@arciszewskim, need more test on that, to see what's going on in the layout configuration.

**Comment by davideas** [comment]
@arciszewskim, can you try with the current version in master? I tried and I don't get your issue on rotation. (enable autoConfig).

**Comment by szynka** [comment]
Confirm issues still exists in master branch, try rotate and scroll several times (enable autoConfig, and open Expandable Sections + Sticky Headers), and You got it.

**Comment by davideas** [comment]
@arciszewskim, I did it but I cannot reproduce it. I'm using API 21 on SamsungS5 now, I will check with emulator on latest API.

**Comment by luweglinski** [comment]
@davideas I make video maybe this would help you:
[https://www.dropbox.com/sh/xgug4xk51nfji3b/AAD80UWSxC96dvvN5-ACms9ja?dl=0](url)

**Comment by davideas** [comment]
@luweglinski, I'm rotating, scrolling, expanding with sticky heeaders and autoConfig, but still nothing.
It seems a very exceptional case after consecutive rotation and expanding, which is not realistic for a normal user (I think). So it is not deterministic.

What I have is the drag handle that disappear sometimes when back to portrait view (probably the header gets bigger width).

**Comment by luweglinski** [comment]
The problem is more visible if title has gravity center. When I searching for solutions for issues, I commented out null check in getHeaderViewHolder so always create new one, and the issues disappeared, but then click on sticky header not notify in adapter.

**Comment by davideas** [comment]
@luweglinski, I've finally reproduced it, but still it occurs random.
However I've put a patch, could you check?

**Comment by luweglinski** [comment]
I think it's work good right now, i can't reproduce it anymore.
@davideas  Thanks for your time and help!
