### ISSUE TITLE
[5.0.0-rc1] Items not notified on auto collapse

### ISSUE THREAD

**Issue by ketain** [davideas/FlexibleAdapter#295]
**What is the version:**
5.0.0-rc1

**What is the goal:**
Adding down/up arrow icon to expandable headers to indicate the possible actions. The icons should alternate depending on the state of the header.

**The problem:**
Switching between these state is no problem as long as there autoCollapseOnExpand is deactivated.
If it is activated items are not notified when they are automatically collapsed.

**What was tried:**
I inherited fromFlexibleAdapter and overrode collapseAll(int) like this

    @Override
        public int collapseAll(int level) {
            if(isAutoCollapseOnExpand() && super.getExpandedItems().size() > 0){
                T item = super.getExpandedItems().get(0);
                super.updateItem(item, Payload.COLLAPSED);
            }
            return super.collapseAll(level);
        }

It did not work. I investigated and found that the payload was at some point in the method chain always disregarded. 

I then tried to call item.bindViewHolder() manually but was not able to find, where the view holder is actually stored.

Do I miss something here?

**Question**: Ho do I inform auto collapsed items about their change in state?

**Comment by davideas** [comment]
Hello @ketain, I'll look into that when got some time.

**Comment by davideas** [comment]
I've put a `notifyItemChanged(position)` but when collapsing all, 1 item doesn't receive the notification of collapsing that is for sure triggered at the right position. Any idea?

**Comment by ketain** [comment]
Sry for the late answer. I will be able to look into it tomorrow. Or maybe today late afternoon.

**Comment by davideas** [comment]
Actually, I'm receiving `java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position` only when sticky header is enabled.
