### ISSUE TITLE
AutoCollapseOnExpand(true) seems not notify the header

### ISSUE THREAD

**Issue by anaszakariyah** [davideas/FlexibleAdapter#296]
Using setAutoCollapseOnExpand(true) will collapse others than current selected header. But the problem in here seems like the header is not notified about the changes by the adapter.

Expected: The section header should also be notified on collapse so the view will rendered again
Actual: Section header not notified only the items belong to the section changed

This is the flexible adapter example app demo I record. You can see that the header does not seem to change on collapse when using auto collapse.

![ezgif com-gif-maker](https://cloud.githubusercontent.com/assets/9209302/23128604/181e7102-f7b2-11e6-99e4-872df4cbbbb0.gif)

Any Idea how I can make the header also get notified on collapse?

**Comment by anaszakariyah** [comment]
seems like the issue is similiar with #295

**Comment by davideas** [comment]
Hello @anaszakariyah, yes it's the same. I'll look into that when got some time.
