### ISSUE TITLE
[5.0.0-rc1] repeated ValueAnimation effect in long lists

### ISSUE THREAD

**Issue by ketain** [davideas/FlexibleAdapter#300]
**What was tried:**
Increasing the text size inside a textview by utilising ValueAnimation and decreasing it again. The former happens when expanding an expandableItem the latter when collapsing it again.

**What went wrong**
In a long list of items the effect of an increased text size was repeated by non expanded items. This is most likely an effect caused by the recycling of views. (My first guess)

**What was done**
In createViewBinder() the current textSize is stored within the ViewBinderClass of this item. It is used as a refference to increase from or decrease to respectively. To start the animations the methods expandView() and collapseView() of the ViewHolder were overriden.

**Question**
How can I reset the text size of items when they are recycled. Is there a method to override?

**Comment by davideas** [comment]
@ketain, yes Adapter has `onViewRecycled()` to override, but you must call `super()`.

**Comment by ketain** [comment]
Thanks for the fast answer :)

I didn't say so before but: This really is a great library! :)
Nahh I am bad at this but please feel complimented. 👍

**Comment by davideas** [comment]
Thank you @ketain!
