### ISSUE TITLE
[Question] Empty view

### ISSUE THREAD

**Issue by korest** [davideas/FlexibleAdapter#301]
Is it possible to set empty view while items are loading or error occurred ?

**Comment by davideas** [comment]
@korest, you have full control on your empty view, but if you implement the callback with the if condition, it will change visibility accordingly. It might be good anyway.

**Comment by korest** [comment]
Is there any example with it?

**Comment by davideas** [comment]
There's an example in the demoApp, the emptyView is visible when filter returns empty list.
