### ISSUE TITLE
Persistent Scrollable Header

### ISSUE THREAD

**Issue by alex-marochko** [davideas/FlexibleAdapter#304]
Hi. Thanks a lot for your lib!

Question: is it possible to add header that will be persistent, i.e. independent of main data updates?
I need a scrollable header containing MapFragment, so I'm adding it after every `updateDataSet()`. The problem is that header is resource expensive and it blinks when data is refreshing.

**Comment by davideas** [comment]
@alex-marochko, can you check properties in RV like: not recyclable and stable ids?
Are you using `updateDataSet()` with animation or without?

**Comment by alex-marochko** [comment]
@davideas , thanks! It works (changed stable IDs to true).

**Comment by davideas** [comment]
@alex-marochko, be sure you have unique ids everywhere for the items.
