### ISSUE TITLE
QUESTION: How to Add Multiple Item/View Types to RecyclerView?

### ISSUE THREAD

**Issue by searchy2** [davideas/FlexibleAdapter#305]
I am creating a notes application and would like to display text notes and image notes in the RecyclerView using Flexible Adapter. How should I pass multiple view types to Flexible Adapter?

My current implementation is as follows: 
1. I have a NoteItemViewHolder that extends AbstractFlexibleItem for text notes. 
2. I have a ImageItemViewHolder that extends AbstractFlexibleItem for image notes.
3. In the IFlexible getDatabaseList, I add each item separately to the List<IFlexible> sorted chronologically by time. 

Based on @davideas your other replies, I believe two ViewHolder/Layouts are necessary and/or recommended? 

For every item type I would like to add to RecyclerView, I should create another ViewHolder class that extends AbstractFlexibleItem? Then, I have to sort the items using my own custom logic when I add them to IFlexible right?

I think I am beginning to get the hang of the library :1st_place_medal:

**Comment by davideas** [comment]
@searchy2, in order.
Yes you need multiple types. I understood you don't need to regroup them.
- I would not call XXXViewHolder the item that extends AbstractFlexibleItem. That is the ViewHolder. Just call the items NoteItem, ImageItem, and create an inner class for ViewHolder with name NoteItemViewHolder etc.. Watch my demoApp.
- I remind you that those items are mainly designed for presentation only for Adapter, so if you have a real database or an external resource, it's much better to have a different object (Note, Image, etc.) then convert them to NoteItem... e viceversa.
- IFlexible is an interface for my Adapter extended by the adapter items.
- Pay attention at the equal method, if you don't have an unique id, then just use the default java implementation inside that method.
- Yes, you will need to add them to the list with a kind of your own logic.
- Finally, pass always a copy of that list to the Adapter.

**Comment by searchy2** [comment]
Thank you for this very helpful explanation. I have worked a bit more with the adapter and it is becoming easier for me to understand. Much thanks for the help!
