### ISSUE TITLE
get header size in expandable adapter

### ISSUE THREAD

**Issue by faridfor** [davideas/FlexibleAdapter#309]
Hi.
I need to check my HeaderItem (extended fromAbstractHeaderItem) is the last item or not (first item can be checked with position = 0 but for last one?)  I need to find Header items size (should I pass the size and save it my self or is there any way to get it from adapter?)
`

    @Override
    public void bindViewHolder(FlexibleAdapter adapter, ViewHolder holder, int position, List payloads) {
        if (position == 0) {
            //do sth with first item
        }
        if (position == adapter.getHeaderCount()) {
            // do sth else with last item
        }
    }
`

**Comment by davideas** [comment]
@faridfor, if you check `position = 0` you can also check the last position, that item binding is only for that item and not for anything else, so if you check `position = adapter.getItemCount() - 1`  you have the last position to check for that item.

Are you sure you don't want to use the new feature Scrollable Headers and Footers? check the Wiki.
