### ISSUE TITLE
Is there a way to get the topmost visible header?

### ISSUE THREAD

**Issue by rabipelais** [davideas/FlexibleAdapter#310]
Say the list looks like this:

**header 1**
item 1
item 2
**header 2**
item 3
\=====================
item 4
**header 3**
item 5
item 6
\=====================

and only things between the lines are currently visible on the screen. Is there a way to get the Header of the topmost visible section? In this case that would be header 2.

**Comment by davideas** [comment]
@rabipelais, you have few methods:
- `getHeaderOf(item)` if you know the item
- `getSectionHeader(position)` if you know the position.
For position you can call library `Utils` class `findFirstCompletelyVisibleItemPosition()`.
Also `isHeader` can help you understand if the item is a IHeader already or not.

**Comment by rabipelais** [comment]
Thank you, this works exactly as requested.
