### ISSUE TITLE
Header not sticky after using nested sections

### ISSUE THREAD

**Issue by Marc1510** [davideas/FlexibleAdapter#312]
Hi,

I'm trying to create a list with a single header and nested sections. The single header should always be on top of the contents. I used this library before, but for some reason it is not working right now.
Right now I have 3 viewtypes:
- AddProductItem which should be the sticky header
- HeaderItem which is a sectionheader
- DefaultItem which is just a default item.

The logs do say that a sticky item is being created, however no sticky items are shown.
I'm creating the simplified list with the following `code:java List<AbstractFlexibleItem> items = new ArrayList<>();
        AddProductItem header = new AddProductItem();
        items.add(header);

        for (int numberOfSections = 0; numberOfSections < 10; numberOfSections++) {
            HeaderItem sectionItem = new HeaderItem("Section: "+numberOfSections);
            sectionItem.setHeader(header);

            for (int itemsInSection = 0; itemsInSection < 10; itemsInSection++) {
                DefaultItem defaultItem = new DefaultItem("Section: "+numberOfSections + " item: "+itemsInSection);
                sectionItem.addSubItem(defaultItem);
                defaultItem.setHeader(sectionItem);
            }

            items.add(sectionItem);
        }

        FlexibleAdapter mAdapter = new FlexibleAdapter<>(items, null);
        mAdapter.enableLogs(true);
        mAdapter.setStickyHeaders(true)
                .setAutoCollapseOnExpand(true)
                .setAutoScrollOnExpand(true);
        mRecyclerView.setLayoutManager(new LinearLayoutManager(this));
        mRecyclerView.setAdapter(mAdapter);`

As you can see, a single sticky header is created and then 10 sections are created with each 10 sub items in them.

Here are also the other viewholders:
AddProductItem
`public class AddProductItem extends AbstractHeaderItem<AddProductItem.ViewHolder> {

    public long currentTime = System.nanoTime();

    @Override
    public int getLayoutRes() {
        return R.layout.layout_add_product;
    }

    @Override
    public boolean equals(Object o) {
        if (o instanceof AddProductItem) {
            AddProductItem inItem = (AddProductItem) o;
            return this.currentTime==inItem.currentTime;
        }
        return false;
    }

    @Override
    public int hashCode() {
        return (""+currentTime).hashCode();
    }

    @Override
    public AddProductItem.ViewHolder createViewHolder(FlexibleAdapter adapter, LayoutInflater inflater,
            ViewGroup parent) {
        return new AddProductItem.ViewHolder(inflater.inflate(getLayoutRes(), parent, false), adapter);
    }

    @Override
    public void bindViewHolder(FlexibleAdapter adapter, AddProductItem.ViewHolder holder, int position,
            List payloads) {
        holder.mTitle.setText("Sticky header");
    }

    static class ViewHolder extends ExpandableViewHolder {

        @BindView(R.id.facet_listitem_name) FontTextView mTitle;

        ViewHolder(View view, FlexibleAdapter adapter) {
            super(view, adapter, true);
            ButterKnife.bind(this, view);
        }
    }

}
`

HeaderItem
`public class HeaderItem extends AbstractFlexibleItem<HeaderItem.ViewHolder>
        implements IExpandable<HeaderItem.ViewHolder, AbstractFlexibleItem>,
        ISectionable<HeaderItem.ViewHolder, IHeader>, IHeader<HeaderItem.ViewHolder> {

    private boolean mExpanded = false;
    private List<AbstractFlexibleItem> mSubItems;

    private String mTitle;
    
    public HeaderItem(String title) {
        mTitle = title;
        setHidden(false);
        setExpanded(true);
    }

    @Override
    public int getLayoutRes() {
        return R.layout.facet_header;
    }

    @Override
    public boolean equals(Object o) {
        if (o instanceof HeaderItem) {
            HeaderItem inItem = (HeaderItem) o;
            return mTitle.equals(inItem.mTitle);
        }
        return false;
    }

    @Override
    public int hashCode() {
        return mTitle.hashCode();
    }

    @Override
    public ViewHolder createViewHolder(FlexibleAdapter adapter, LayoutInflater inflater,
            ViewGroup parent) {
        return new ViewHolder(inflater.inflate(getLayoutRes(), parent, false), adapter);
    }

    @Override
    public void bindViewHolder(FlexibleAdapter adapter, ViewHolder holder, int position,
            List payloads) {
        holder.mTitle.setText(mTitle);
    }

    @Override
    public boolean isExpanded() {
        return mExpanded;
    }

    @Override
    public final void setExpanded(boolean expanded) {
        mExpanded = expanded;
    }

    @Override
    public int getExpansionLevel() {
        return 0;
    }

    @Override
    public List<AbstractFlexibleItem> getSubItems() {
        return mSubItems;
    }

    public void addSubItem(AbstractFlexibleItem subItem) {
        if (mSubItems == null) {
            mSubItems = new ArrayList<>();
        }
        mSubItems.add(subItem);
    }

    private IHeader mHeader;

    @Override
    public IHeader getHeader() {
        return mHeader;
    }

    @Override
    public void setHeader(IHeader header) {
        mHeader = header;
    }

    static class ViewHolder extends ExpandableViewHolder {

        @BindView(R.id.facet_listitem_name) FontTextView mTitle;

        ViewHolder(View view, FlexibleAdapter adapter) {
            super(view, adapter);
            ButterKnife.bind(this, view);
        }
    }

}`

and last but not least the DefaultItem
`public class DefaultItem extends AbstractFlexibleItem<DefaultItem.ViewHolder>
        implements ISectionable<DefaultItem.ViewHolder, IHeader> {

    private String mTitle;
    private IHeader mHeader;

    public DefaultItem(String title) {
        mTitle = title;
    }

    @Override
    public boolean equals(Object o) {
        if (o instanceof DefaultItem) {
            DefaultItem inItem = (DefaultItem) o;
            return this.mTitle.equals(inItem.mTitle);
        }
        return false;
    }

    @Override
    public int hashCode() {
        return mTitle.hashCode() + mHeader.hashCode();
    }

    @Override
    public IHeader getHeader() {
        return mHeader;
    }

    @Override
    public void setHeader(IHeader header) {
        mHeader = header;
    }

    @Override
    public int getLayoutRes() {
        return R.layout.item_facet;
    }

    @Override
    public ViewHolder createViewHolder(FlexibleAdapter adapter, LayoutInflater inflater,
            ViewGroup parent) {
        return new ViewHolder(inflater.inflate(getLayoutRes(), parent, false), adapter);
    }

    @Override
    public void bindViewHolder(FlexibleAdapter adapter, ViewHolder holder, int position,
            List payloads) {
        holder.mTitle.setText(mTitle);
    }

    static class ViewHolder extends ExpandableViewHolder {

        @BindView(R.id.facet_listitem_name) FontTextView mTitle;

        ViewHolder(View view, FlexibleAdapter adapter) {
            super(view, adapter);
            ButterKnife.bind(this, view);
        }
    }

}`

The code is extremely simplified, however the sticky header does not yet work unfortunately. Is there anything obvious I'm missing? Or is a header with nested sections not possible?

**Comment by Marc1510** [comment]
And for completeness, also the log:
`03-06 16:44:15.521 20052-20052/nl.fleurametz.mobile.acc.dev I/FlexibleAdapter: Running version 5.0.0-rc1 built on 2017.01.14
03-06 16:44:15.521 20052-20052/nl.fleurametz.mobile.acc.dev I/FlexibleAdapter: Initialized with StableIds=false
03-06 16:44:15.521 20052-20052/nl.fleurametz.mobile.acc.dev I/FlexibleAdapter: Set stickyHeaders=true (in Post!)
03-06 16:44:15.521 20052-20052/nl.fleurametz.mobile.acc.dev I/FlexibleAdapter: Set autoCollapseOnExpand=true
03-06 16:44:15.521 20052-20052/nl.fleurametz.mobile.acc.dev I/FlexibleAdapter: Set setAutoScrollOnExpand=true
03-06 16:44:15.521 20052-20052/nl.fleurametz.mobile.acc.dev V/FlexibleAdapter: Collapsed 10 subItems on position 1
03-06 16:44:15.522 20052-20052/nl.fleurametz.mobile.acc.dev V/FlexibleAdapter: Collapsed 10 subItems on position 2
03-06 16:44:15.522 20052-20052/nl.fleurametz.mobile.acc.dev V/FlexibleAdapter: Collapsed 10 subItems on position 3
03-06 16:44:15.522 20052-20052/nl.fleurametz.mobile.acc.dev V/FlexibleAdapter: Collapsed 10 subItems on position 4
03-06 16:44:15.523 20052-20052/nl.fleurametz.mobile.acc.dev V/FlexibleAdapter: Collapsed 10 subItems on position 5
03-06 16:44:15.523 20052-20052/nl.fleurametz.mobile.acc.dev V/FlexibleAdapter: Collapsed 10 subItems on position 6
03-06 16:44:15.523 20052-20052/nl.fleurametz.mobile.acc.dev V/FlexibleAdapter: Collapsed 10 subItems on position 7
03-06 16:44:15.523 20052-20052/nl.fleurametz.mobile.acc.dev V/FlexibleAdapter: Collapsed 10 subItems on position 8
03-06 16:44:15.524 20052-20052/nl.fleurametz.mobile.acc.dev V/FlexibleAdapter: Collapsed 10 subItems on position 9
03-06 16:44:15.524 20052-20052/nl.fleurametz.mobile.acc.dev V/FlexibleAdapter: Collapsed 10 subItems on position 10
03-06 16:44:15.530 20052-20052/nl.fleurametz.mobile.acc.dev I/FlexibleAdapter: Mapped viewType 2130968670 from AddProductItem
03-06 16:44:15.535 20052-20052/nl.fleurametz.mobile.acc.dev V/FlexibleAdapter: onViewBound    Holder=ViewHolder position=0 itemId=-1 layoutPosition=0
03-06 16:44:15.536 20052-20052/nl.fleurametz.mobile.acc.dev I/FlexibleAdapter: Mapped viewType 2130968645 from HeaderItem
03-06 16:44:15.538 20052-20052/nl.fleurametz.mobile.acc.dev V/FlexibleAdapter: onViewBound    Holder=ViewHolder position=1 itemId=-1 layoutPosition=1
03-06 16:44:15.541 20052-20052/nl.fleurametz.mobile.acc.dev V/FlexibleAdapter: onViewBound    Holder=ViewHolder position=2 itemId=-1 layoutPosition=2
03-06 16:44:15.543 20052-20052/nl.fleurametz.mobile.acc.dev V/FlexibleAdapter: onViewBound    Holder=ViewHolder position=3 itemId=-1 layoutPosition=3
03-06 16:44:15.546 20052-20052/nl.fleurametz.mobile.acc.dev V/FlexibleAdapter: onViewBound    Holder=ViewHolder position=4 itemId=-1 layoutPosition=4
03-06 16:44:15.549 20052-20052/nl.fleurametz.mobile.acc.dev V/FlexibleAdapter: onViewBound    Holder=ViewHolder position=5 itemId=-1 layoutPosition=5
03-06 16:44:15.552 20052-20052/nl.fleurametz.mobile.acc.dev V/FlexibleAdapter: onViewBound    Holder=ViewHolder position=6 itemId=-1 layoutPosition=6
03-06 16:44:15.555 20052-20052/nl.fleurametz.mobile.acc.dev V/FlexibleAdapter: onViewBound    Holder=ViewHolder position=7 itemId=-1 layoutPosition=7
03-06 16:44:15.558 20052-20052/nl.fleurametz.mobile.acc.dev V/FlexibleAdapter: onViewBound    Holder=ViewHolder position=8 itemId=-1 layoutPosition=8
03-06 16:44:15.586 20052-20052/nl.fleurametz.mobile.acc.dev I/StickyHeaderHelper: Default StickyHolderLayout initialized
03-06 16:44:15.586 20052-20052/nl.fleurametz.mobile.acc.dev I/FlexibleAdapter: Sticky headers enabled
03-06 16:44:15.757 20052-20052/nl.fleurametz.mobile.acc.dev V/AnimatorAdapter: Clear notified for scrolling Animations`

At the end it clearly says 'Sticky headers enabled' however they are not visible. And yes, the RecyclerView is wrapped in a FrameLayout.

**Comment by davideas** [comment]
@Marc1510, can you try to remove the ISectionable interface from HeaderItem?

**Comment by Marc1510** [comment]
@davideas I just tried that, the objects are now as following:
HeaderItem extends AbstractExpandableItem<HeaderItem.ViewHolder, AbstractFlexibleItem>
public class DefaultItem extends AbstractSectionableItem<DefaultItem.ViewHolder, IHeader>
AddProductItem extends AbstractHeaderItem<AddProductItem.ViewHolder>

I saw these classes implemented some logic already so I didn't need to implement them myself. However the AddProductItem is still not sticky.

**Comment by davideas** [comment]
@Marc1510, can you make a list here to show which items contains what and which should be sticky and expandable?

**Comment by Marc1510** [comment]
@davideas of course I can!
The list should be:
- AddProductItem > always sticky on top of the list
- HeaderItem > should be a section which can expand/collapse with sub-items
- DefaultItem > Just a normal item which should be able collapse/expand under the header item above.
- DefaultItem (possibly more of these)
- HeaderItem > section which can expand/collapse the underlying DefaultItems
- DefaultItem (as many as you would like)

And so on. I just need one sticky item, and then multiple headers with subitems under that.

**Comment by davideas** [comment]
@Marc1510, so the types are:
AddProductItem: AbstractHeaderItem
HeaderItem: AbstractExpandableItem implements ISectionable
DefaultItem: AbstractSectionableItem
```
sectionItem.setHeader(header); //as you did it
defaultItem.setHeader(header); //and not sectionItem
```

But I would rename HeaderItem to SectionItem since it makes confusion which is the real header (AddProductItem) and which is the sub-section with the default items.

I think it should work, can you try?

**Comment by Marc1510** [comment]
@davideas that is correct indeed.
I just tried it, however it does not work. The sections can be expanded/collapsed, the DefaultItems are correctly shown, however the sticky header is not yet sticky.

Just for completeness I will add the adjusted viewholders/code to setup the adapter here as well.
StickyHeaderItem:
`public class StickyHeaderItem extends AbstractHeaderItem<StickyHeaderItem.ViewHolder> {

    private long currentTime = System.nanoTime();

    @Override
    public int getLayoutRes() {
        return R.layout.layout_add_product;
    }

    @Override
    public boolean equals(Object o) {
        if (o instanceof StickyHeaderItem) {
            StickyHeaderItem inItem = (StickyHeaderItem) o;
            return this.currentTime==inItem.currentTime;
        }
        return false;
    }

    @Override
    public int hashCode() {
        return (""+currentTime).hashCode();
    }

    @Override
    public StickyHeaderItem.ViewHolder createViewHolder(FlexibleAdapter adapter, LayoutInflater inflater,
            ViewGroup parent) {
        return new StickyHeaderItem.ViewHolder(inflater.inflate(getLayoutRes(), parent, false), adapter);
    }

    @Override
    public void bindViewHolder(FlexibleAdapter adapter, StickyHeaderItem.ViewHolder holder, int position,
            List payloads) {
        holder.mTitle.setText("Sticky header");
    }

    static class ViewHolder extends ExpandableViewHolder {

        @BindView(R.id.facet_listitem_name) FontTextView mTitle;

        ViewHolder(View view, FlexibleAdapter adapter) {
            super(view, adapter, true);
            ButterKnife.bind(this, view);
        }
    }

}`

SectionItem:
`public class SectionItem extends AbstractExpandableItem<SectionItem.ViewHolder, AbstractFlexibleItem> implements ISectionable<SectionItem.ViewHolder, IHeader> {

    private String mTitle;

    public SectionItem(String title) {
        mTitle = title;
    }

    @Override
    public int getLayoutRes() {
        return R.layout.facet_header;
    }

    @Override
    public boolean equals(Object o) {
        if (o instanceof SectionItem) {
            SectionItem inItem = (SectionItem) o;
            return mTitle.equals(inItem.mTitle);
        }
        return false;
    }

    @Override
    public int hashCode() {
        return mTitle.hashCode();
    }

    @Override
    public ViewHolder createViewHolder(FlexibleAdapter adapter, LayoutInflater inflater,
            ViewGroup parent) {
        return new ViewHolder(inflater.inflate(getLayoutRes(), parent, false), adapter);
    }

    @Override
    public void bindViewHolder(FlexibleAdapter adapter, ViewHolder holder, int position,
            List payloads) {
        holder.mTitle.setText(mTitle);
    }

    private IHeader mHeader;

    @Override
    public IHeader getHeader() {
        return mHeader;
    }

    @Override
    public void setHeader(IHeader header) {
        mHeader = header;
    }

    static class ViewHolder extends ExpandableViewHolder {

        @BindView(R.id.facet_listitem_name) FontTextView mTitle;

        ViewHolder(View view, FlexibleAdapter adapter) {
            super(view, adapter);
            ButterKnife.bind(this, view);
        }
    }

}
`
DefaultItem:
`public class DefaultItem extends AbstractSectionableItem<DefaultItem.ViewHolder, IHeader> {

    private String mTitle;

    public DefaultItem(String title, IHeader header) {
        super(header);
        mTitle = title;
    }

    @Override
    public boolean equals(Object o) {
        if (o instanceof DefaultItem) {
            DefaultItem inItem = (DefaultItem) o;
            return this.mTitle.equals(inItem.mTitle);
        }
        return false;
    }

    @Override
    public int hashCode() {
        return mTitle.hashCode();
    }

    @Override
    public int getLayoutRes() {
        return R.layout.item_facet;
    }

    @Override
    public ViewHolder createViewHolder(FlexibleAdapter adapter, LayoutInflater inflater,
            ViewGroup parent) {
        return new ViewHolder(inflater.inflate(getLayoutRes(), parent, false), adapter);
    }

    @Override
    public void bindViewHolder(FlexibleAdapter adapter, ViewHolder holder, int position,
            List payloads) {
        holder.mTitle.setText(mTitle);
    }

    static class ViewHolder extends ExpandableViewHolder {

        @BindView(R.id.facet_listitem_name) FontTextView mTitle;

        ViewHolder(View view, FlexibleAdapter adapter) {
            super(view, adapter);
            ButterKnife.bind(this, view);
        }
    }

}
`

And the code to create the objects and adds them to the adapter:
`List<AbstractFlexibleItem> items = new ArrayList<>();
        StickyHeaderItem header = new StickyHeaderItem();
        items.add(header);

        for (int numberOfSections = 0; numberOfSections < 10; numberOfSections++) {
            SectionItem sectionItem = new SectionItem("Section: "+numberOfSections);
            sectionItem.setHeader(header);

            for (int itemsInSection = 0; itemsInSection < 10; itemsInSection++) {
                DefaultItem defaultItem = new DefaultItem("Section: "+numberOfSections + " item: "+itemsInSection, header);
                sectionItem.addSubItem(defaultItem);
                defaultItem.setHeader(header);
            }

            items.add(sectionItem);
        }

        FlexibleAdapter mAdapter = new FlexibleAdapter<>(items);
        FlexibleAdapter.enableLogs(true);
        mAdapter.setStickyHeaders(true)
                .setAutoCollapseOnExpand(true)
                .setAutoScrollOnExpand(true);
        mRecyclerView.setLayoutManager(new LinearLayoutManager(this));
        mRecyclerView.setAdapter(mAdapter);
        mAdapter.collapseAll();`

**Comment by davideas** [comment]
@Marc1510,
``` java
// this should resolve the sticky header
// remove
items.add(header);
// add 
mAdapter.setDisplayHeadersAtStartUp(true);

// Some optimizations
// also this should be superfluous, by default they are collapsed.
mAdapter.collapseAll();

// also the signature for SectionItem
AbstractExpandableItem<SectionItem.ViewHolder, AbstractFlexibleItem> ...
// should be:
AbstractExpandableItem<SectionItem.ViewHolder, DefaultItem> ...

// and you don't need:
defaultItem.setHeader(header); // because you have it in the constructor
```

**Comment by Marc1510** [comment]
@davideas thanks! That did solve the issue. I do however have one question left, isn't it weird that the 'header item' would not be added to the items?

**Comment by davideas** [comment]
The header item normally is a logic item to group others main business items. True that you are using header as AddProductItem. probably you can add it to the layout directly on the top of the RecyclerView.

The logic items are managed all together by the Adapter, I had to find a way also to not duplicate items at the startup. Sticky helper checks if headers are displayed with the boolean headersShown that must be set `true` by calling display headers at startup: this speed up the process when they are hidden.

**Comment by Marc1510** [comment]
Unfortunately I do have to add it in the layout for some specific reasons. However the explanation does make sense. Thanks a lot!
