### ISSUE TITLE
Crash during filter

### ISSUE THREAD

**Issue by IHNEL** [davideas/FlexibleAdapter#316]
This is randomly crash and hard to duplicated, but I want to track here and hope you take a look.
It occurred while I typing the keyword to filter my long list.
```

Caused by java.util.ConcurrentModificationException
java.util.ArrayList$ArrayListIterator.next (ArrayList.java:573)
eu.davidea.flexibleadapter.FlexibleAdapter.filterItemsAsync (FlexibleAdapter.java:3924)
eu.davidea.flexibleadapter.FlexibleAdapter.access$2100 (FlexibleAdapter.java:98)
eu.davidea.flexibleadapter.FlexibleAdapter$FilterAsyncTask.doInBackground (FlexibleAdapter.java:5287)
eu.davidea.flexibleadapter.FlexibleAdapter$FilterAsyncTask.doInBackground (FlexibleAdapter.java:5253)
android.os.AsyncTask$2.call (AsyncTask.java:295)
java.util.concurrent.FutureTask.run (FutureTask.java:237)
android.os.AsyncTask$SerialExecutor$1.run (AsyncTask.java:234)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1113)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:588)
java.lang.Thread.run (Thread.java:818)
```

**Comment by davideas** [comment]
@IHNEL do you pass the copy of the original list to the filter method?

**Comment by IHNEL** [comment]
Yes of course. Now I have good understanding your lib and use it for fews screen. They work fine. Just crash 1 time and be tracked by crashlytics on my client's devices.

**Comment by IHNEL** [comment]
I am using feature `5.0.0-rc1`:
 `compile 'eu.davidea:flexible-adapter:5.0.0-rc1'`

**Comment by davideas** [comment]
@IHNEL, this is almost impossible to reproduce it. Let me know if you receive it often. Maybe it should be interesting to know if you also modify the List in your code, but also having more logs on what the user was doing...

**Comment by IHNEL** [comment]
Hi @davideas 
This happen many times and I found the root cause. While I was pulling down the data list and append to the adapter, if user type to filter it will crash.
Which I do to fix my side is block the filter feature until I got the whole data list. But I hope you got a better way.

Thanks.

**Comment by davideas** [comment]
Because I cannot test as you do, try to create the list as `Collections.synchronizedList(list);` and see if it resolves the issue?
If it works I will add it in the `FilterAsyncTask` class.

**Comment by davideas** [comment]
@IHNEL, sorry, can you try it anyway to wrap your list with synced list?

**Comment by davideas** [comment]
@IHNEL, I'm trying to reproduce this issue, I need your help. Can you provide me a way to reproduce it?

**Comment by IHNEL** [comment]
@davideas ,
I didn't got this crash in my phone also. but It occurred  in my client's Samsung Galaxy S6 very often. The log was catch by Crashlytics as above. 
I asked him and I guess the data list on his phone is very long ( The feature is load the phone contact list). It's need a while to read and append 1 by 1 to the recycler view. On the same time, he entered some words to filter the contact list and the app crash.

I already try to block the filter feature until all contacts loaded successful and he didn't receive any crash regarding this. 

I think this is because there are more than 1 process to alter same data List. is there anyway to only append the incoming data item to original list instead of filtered list? If yes, I guess the problem solved.

**Comment by IHNEL** [comment]
This is the class to load the Phone Contact in my app:
```
import android.content.ContentResolver;
import android.content.Context;
import android.database.Cursor;
import android.net.Uri;
import android.os.Build;
import android.provider.ContactsContract;

import com.makeit.domain.bean.PhoneContact;

import javax.inject.Inject;

import io.reactivex.Observable;
import io.reactivex.ObservableEmitter;
import io.reactivex.ObservableOnSubscribe;

public class PhoneContactProvider {
    private static final String[] PROJECTION =
            {
                    ContactsContract.Data._ID,
                    // The primary display name
                    Build.VERSION.SDK_INT >= Build.VERSION_CODES.HONEYCOMB ?
                            ContactsContract.Data.DISPLAY_NAME_PRIMARY :
                            ContactsContract.Data.DISPLAY_NAME
            };

    @Inject
    Context mContext;

    @Inject
    PhoneContactProvider() {
    }

    Observable<PhoneContact> getPhoneContactList() {

        return Observable.create(new ObservableOnSubscribe<PhoneContact>() {
            @Override
            public void subscribe(final ObservableEmitter<PhoneContact> e) throws Exception {
                ContentResolver cr = mContext.getContentResolver(); //Activity/Application android.content.Context
                Cursor cursor = cr.query(ContactsContract.Contacts.CONTENT_URI, PROJECTION, null, null,
                        ContactsContract.CommonDataKinds.Phone.DISPLAY_NAME + " ASC");

                if (cursor == null) {
                    e.onComplete();
                    return;
                }
                if (cursor.moveToFirst()) {
                    do {
                        PhoneContact contact = new PhoneContact();
                        contact.id = cursor.getString(cursor.getColumnIndex(PROJECTION[0]));
                        contact.name = cursor.getString(cursor.getColumnIndex(PROJECTION[1]));
                        contact.image = Uri.withAppendedPath(ContactsContract.Contacts.CONTENT_URI, String.valueOf(contact.id)).toString();
                        e.onNext(contact);

                    } while (cursor.moveToNext());
                }
                e.onComplete();
                cursor.close();
            }
        });
    }
}

```

I create my adapter, extend the `FlexibleAdapter` with below constructor:
```
    public ContactAdapter() {
        super(new ArrayList<>(), null, true);
    }
```
whenever I receive a contact from `PhoneContactProvider`, call `mContactAdapter.addItem(contactItem);` as well as `originalContactList.add(contactItem)`

When user enter the keyword to filter, 
```
 TextWatcherAdapter searchTextListener = new TextWatcherAdapter() {
        @Override
        public void onTextChanged(CharSequence charSequence, int i, int i1, int i2) {
              mContactAdapter.filter(originalContactList, key);
        }
    };
```
```
    @Override
    public void filter(List data, String key) {
        setSearchText(key);
        filterItems(data, 300);
    }
```

**Comment by davideas** [comment]
@IHNEL, it looks like same issue of a #323.
When _instantiating, updating, filtering_, you always need to pass a copy of the original list, just because the adapter modifies that list (for instance while expanding/collapsing, display headers, filter out items), while you shouldn't touch it anymore because normally you have your own original list in memory to rely.
``` java
filterItems(new ArrayList<>(data), 300);
```
As said in that issue, maybe it's better that I create the copy internally (I will evaluate the impact).

Which means in any case that, if you have the filter active, but not running, and you receive a new item, you need to check if this item is filtered by the current filter or not, if yes you add the item to your originalList anyway AND and with addItem(position) to the adapter, but only when filter is completed!

- You can override `onPostFilter()` and in there you add items from a temporary array, but you should filter yourself the items to know if you need to add or not!

- Another thing you can do is to wrap/create your ArrayList as Synchronized OR even better use `CopyOnWriteArrayList` (from Java 5) instead and add new items to it, I think my cast of List is transparent, just give a try.

**Comment by IHNEL** [comment]
@davideas Thank you so much.

**Comment by davideas** [comment]
@IHNEL, I'm optimizing the initialization, the update and filter processes, you can already start to have a look at the commits in the branch **list_copy**.
