### ISSUE TITLE
OnItemClick listener in a Fragment not working

### ISSUE THREAD

**Issue by mfarrukh** [davideas/FlexibleAdapter#317]
public class Favorite extends AbstractFlexibleItem<Favorite.FavoritesViewHolder> implements
        IFilterable, Serializable {

    private int id, age;
    private String name, email, gender, iconTxt, iconColor, distance, accountStatus, lastSeen;

    public Favorite(int id, String name, String email, int age, String gender, String iconTxt, String iconColor,
                  String distance, String accountStatus, String lastSeen) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.age = age;
        this.gender = gender;
        this.iconTxt = iconTxt;
        this.iconColor = iconColor;
        this.distance = distance;
        this.accountStatus = accountStatus;
        this.lastSeen = lastSeen;
    }

    public int getId() { return id; }

    public void setId(int id) { this.id = id; }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getIconTxt() {
        return iconTxt;
    }

    public void setIconTxt(String iconTxt) {
        this.iconTxt = iconTxt;
    }

    public String getIconColor() {
        return iconColor;
    }

    public void setIconColor(String iconColor) {
        this.iconColor = iconColor;
    }

    public String getDistance() {
        return distance;
    }

    public void setDistance(String distance) {
        this.distance = distance;
    }

    public String getAccountStatus() {
        return accountStatus;
    }

    public void setAccountStatus(String accountStatus) {
        this.accountStatus = accountStatus;
    }

    public String getLastSeen() {
        return lastSeen;
    }

    public void setLastSeen(String lastSeen) {
        this.lastSeen = lastSeen;
    }

    @Override
    public int getLayoutRes() {
        return R.layout.row_favorites;
    }

    @Override
    public int hashCode() {
        return String.valueOf(id).hashCode();
    }

    @Override
    public boolean equals(Object inObject) {
        if (inObject instanceof Favorite) {
            Favorite inItem = (Favorite) inObject;
            return this.id == inItem.id;
        }
        return false;
    }

    @Override
    public FavoritesViewHolder createViewHolder(FlexibleAdapter adapter, LayoutInflater inflater, ViewGroup parent) {
        return new FavoritesViewHolder(inflater.inflate(getLayoutRes(), parent, false), adapter);
    }

    @Override
    public void bindViewHolder(FlexibleAdapter adapter, FavoritesViewHolder holder, int position, List payloads) {
        ColorGenerator generator = ColorGenerator.MATERIAL;
        int color =  Integer.parseInt(getIconColor()); // generator.getRandomColor();
        Drawable drawable = TextDrawable.builder().beginConfig().fontSize(Constants.AVATAR_TEXT_SIZE).endConfig()
                .buildRound(getIconTxt(), color);
        holder.ivAvatar.setImageDrawable(drawable);
        holder.tvName.setText(getName());
        holder.tvAge.setText(String.valueOf(getAge()));
        holder.tvDistance.setText(getDistance());
        if (getGender().equalsIgnoreCase(Constants.GENDER_FEMALE)){
            holder.ivGender.setImageResource(R.mipmap.ic_female);
        }else{
            holder.ivGender.setImageResource(R.mipmap.ic_male);
        }
        if (Utils.isOnline(getLastSeen())){
            holder.vOnline.setVisibility(View.VISIBLE);
        }else{
            holder.vOnline.setVisibility(View.INVISIBLE);
        }
    }

    static final ButterKnife.Setter<View, Typeface> TYPEFACE = new ButterKnife.Setter<View, Typeface>() {
        @Override
        public void set(@NonNull View view, Typeface value, int index) {
            if(view instanceof TextView){
                ((TextView) view).setTypeface(value);
            }
        }
    };

    @Override
    public boolean filter(String constraint) {
        return getName() != null && getName().toLowerCase().trim().contains(constraint) ;
    }

    public static class FavoritesViewHolder extends FlexibleViewHolder {

        public final View mView;
        public Typeface tfVera;
        Context mContext;
        @BindViews({R.id.tvname, R.id.tvdistance, R.id.tvage})
        List<TextView> tvList;
        @BindView(R.id.ivavatar)
        ImageView ivAvatar;
        @BindView(R.id.ivgender) ImageView ivGender;
        @BindView(R.id.tvname) TextView tvName;
        @BindView(R.id.tvdistance) TextView tvDistance;
        @BindView(R.id.tvage) TextView tvAge;
        @BindView(R.id.vonline) View vOnline;
        @BindView(R.id.rlv) RelativeLayout rlOnclick;

        @BindString(R.string.font_vera) String FONT;

        public FavoritesViewHolder(View view, FlexibleAdapter adapter) {
            super(view, adapter);
            mView = view;
            mContext = mView.getContext();
            ButterKnife.bind(this, view);
            tfVera = Typefaces.get(mContext, FONT);
            ButterKnife.apply(tvList, TYPEFACE, tfVera);
        }
    }
}

In the Fragment 

    private FlexibleAdapter<Favorite> mFlexibleAdapter;
    private ProgressItem mProgressItem = new ProgressItem();
    private List<Favorite> mflexibleList;

In OnCreateView
    mFlexibleAdapter = new FlexibleAdapter<>(mflexibleList);
        mFlexibleAdapter
                .addListener(clickListenerAdapter1)
                .addListener(onItemLongClickListener)
                .setEndlessPageSize(30)
                .setEndlessScrollListener(this, mProgressItem);

    recyclerView.setAdapter(mFlexibleAdapter);

Where 
    private FlexibleAdapter.OnItemClickListener clickListenerAdapter1 =
            new FlexibleAdapter.OnItemClickListener() {
                @Override
                public boolean onItemClick(int position) {
                    // Action on elements are allowed if Mode is IDLE, otherwise selection has priority
                    if (mFlexibleAdapter.getMode() != FlexibleAdapter.MODE_IDLE && mActionModeHelper != null) {
                        boolean activate = mActionModeHelper.onClick(position);
                        return activate;
                    } else {

                        Bundle bundle = new Bundle();
                        bundle.putSerializable(KEY_USER, Utils.getUser(mFlexibleAdapter.getItem(position)));
                        ActivityStackManager.getInstance(mCurrentActivity).startChatActivityWithData(bundle);
                        return false;
                    }
                }
            };

    private FlexibleAdapter.OnItemLongClickListener onItemLongClickListener =
            new FlexibleAdapter.OnItemLongClickListener() {
                @Override
                public void onItemLongClick(int position) {
                    mActionModeHelper.onLongClick((AppCompatActivity) getActivity(), position);
                }
            };

**Comment by davideas** [comment]
@mfarrukh, can you explain a little bit?
You should try to override the click listener in the ViewHolder to put your logs. Also put logs in your listener implementation, finally enableLogs of the Adapter: try to check where is not propagated the listener.
