### ISSUE TITLE
[QUESTION] What would prompt "equals()" in AbstractItem to not be called ?

### ISSUE THREAD

**Issue by ahmedkhan23** [davideas/FlexibleAdapter#318]
Referencing #285 . 
I couldn't re-open the issue.

I noticed my "equals()" method in my SectionItem which extends AbstractSectionableItem<> is not being called and I am stumped as to what I am missing when initializing my adapter.

**Comment by davideas** [comment]
@ahmedkhan23, the `equals()` method is used everytime the object is compared to another one, so it happens all the time in a java.util.List when you get an item. If you don't have an unique ID value for your item, then you can use default java implementation: `return this == o`.

**Comment by ahmedkhan23** [comment]
@davideas in my implementation for my SectionItem it is never getting called

**Comment by davideas** [comment]
@ahmedkhan23, it's Java, so it is called. Read this article: https://www.sitepoint.com/implement-javas-equals-method-correctly:
Try to put some logs in it, but of course when you retrieve from a list you should search it correctly.
If you put log you will see it will be called tons of times!

**Comment by ahmedkhan23** [comment]
@davideas my equals method in SectionItem is not called when the adapter/recyclerview are being setup. It is only called when I remove an item from the adapter.

Is this expected ?

Put logs/breakpoints/ checked your sample app. In your sample app the equals method is indeed called when the recyclerview/adapter are first being setup - at least what I could gather by using breakpoints.

**Comment by davideas** [comment]
> Is this expected ?

Yes.
My sampleApp builds the initial list differently than yours I suppose.

**Comment by ahmedkhan23** [comment]
@davideas even when I do a proper implementation of equals() method, the regular Java implementation of "return this == o" - I am seeing the issue of my views being recycled in different positions as I scroll up and down my list. Can't pinpoint the error for the longest time.

**Comment by ahmedkhan23** [comment]
problem was in my bindView() ... I had an if clause but no "else", so the settings from the "if" were being applied to other view holders as I was scrolling up and down ...
