### ISSUE TITLE
Sample Sticky Header in Recyclerview

### ISSUE THREAD

**Issue by wiltonbarros** [davideas/FlexibleAdapter#319]
Hi there.
Congratulations for your continuous work.
I need a full sample how to implement a Sticky header in a recyclerview.
Today i have a recyclerview with header where i separate in two lists, i have two layouts, one for the header and other for the items.
I'm using the appcompat to implementation.
Thank you.

**Comment by davideas** [comment]
@wiltonbarros, thank you for the message!
A step by step example doesn't not exists (yet!), best way is to read first the wiki for _setting up_, _item interfaces_ and _sections and headers_.
Then you can take code snippets from the demoApp.

**Comment by davideas** [comment]
@wiltonbarros, which kind of sample you were thinking, because the demoApp has some already, plus there's a comprehensive guide here.

**Comment by wiltonbarros** [comment]
Hi @davideas, it is the classic sample, where the header scroll up and fix, then wait the next title scroll up too.

**Comment by davideas** [comment]
@wiltonbarros ah ok, so everything is covered then. I can close this issue.

**Comment by wiltonbarros** [comment]
@davideas  Yes, you can.
Thanks.
