### ISSUE TITLE
getSectionItemPositions()，Does it work ?

### ISSUE THREAD

**Issue by Sullen** [davideas/FlexibleAdapter#322]
@NonNull
	public List<Integer> getSectionItemPositions(@NonNull IHeader header) {
		List<Integer> sectionItemPositions = new ArrayList<>();
		int startPosition = getGlobalPositionOf(header);
		T item = getItem(++startPosition);
		while (hasSameHeader(item, header)) {
			sectionItemPositions.add(++startPosition);
		}
		return sectionItemPositions;
	}

This should be an infinite loop.

**Comment by davideas** [comment]
@Sullen, indeed it is in loop :-(
Not used, not tested. I'm going to fix it, since it is easy.
To use it you need to wait next Snapshot!
