### ISSUE TITLE
Is it possible to customize 'sticked' header layout?

### ISSUE THREAD

**Issue by lemonboston** [davideas/FlexibleAdapter#327]
Is it possible to change how the header item looks when it gets 'sticked'?
So we would like to make some transition, like changing the color and maybe layout arrangement as well when the header gets sticky.
Is there any callback that we could use to react when the item gets sticked/unsticked?

I know of the elevation, that's great actually, but we are exploring options to further change the look of the sticked header.

Thanks

**Comment by davideas** [comment]
@lemonboston, currently the layout of the header is translated to the sticky container, and the container takes the shape of the header item, unless is customized and provided at runtime with specific width/height.

There's a callback when it swaps and clear `OnStickyHeaderChangeListener`.

**Comment by lemonboston** [comment]
Thanks @davideas ! I missed that callback, we may be able to use that then, with I suppose also just finding the sticky layout by id.
cheers
