### ISSUE TITLE
Sticky header not drawn properly if scrolling down after pushing another sticky header up

### ISSUE THREAD

**Issue by kenyee** [davideas/FlexibleAdapter#330]
If you scroll the sticky header up and then scroll down immediately after you push another one out of the way, it looks like the sticky headers are drawing on top of themselves:

![image](https://cloud.githubusercontent.com/assets/586670/24590484/ec43afdc-17bb-11e7-8a68-108723317720.png)

Header is defined like this:
``` xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_marginBottom="16dp"
    android:orientation="vertical">

    <View
        android:layout_width="match_parent"
        android:layout_height="1dp"
        android:background="@color/colorAccent"/>
    <TextView
       android:layout_width="match_parent"
       android:layout_height="wrap_content"
       android:paddingLeft="16dp"
       android:paddingRight="16dp"
       android:paddingTop="8dp"
       android:paddingBottom="8dp"
       android:maxLines="1"
       android:ellipsize="end"
       android:textSize="20sp"
       android:fontFamily="sans-serif"
       android:textColor="@android:color/black"
       android:background="@color/colorBackground"
       android:id="@+id/header_text"
       tools:text="10:30am"/>
    <View
        android:layout_width="match_parent"
        android:layout_height="1dp"
        android:background="@color/colorAccent"/>
</LinearLayout>
```

**Comment by kenyee** [comment]
Ahh....adding this to the root LinearLayout causes that weird behavior:
    android:layout_marginBottom="16dp"
Probably should be documented...

**Comment by davideas** [comment]
@kenyee, thanks I will check it out.

**Comment by davideas** [comment]
@kenyee, I couldn't reproduce that issue. Which LinearLayout?

**Comment by kenyee** [comment]
Topmost linearlayout (included the layout in the bug report).

Scroll the 2nd header up over the first one and then scroll it slowly down...it's some overwrite issue where the first header is drawn over the 2nd even though the 2nd one should be over the first.

 ken



-----Original Message-----

**Comment by davideas** [comment]
@kenyee, still can't reproduce it. It should be how you initialize the list or the equals method not properly implemented.
Please use the Snapshot version, which contains the most advanced code. But read carefully the last 3 posts of issue 39 to adapt your code.

**Comment by kenyee** [comment]
Thanks for trying...I'll just close this then.  I should have written up a small sample project :-(
If you want way too much code, you can pull this project at this commit that was using 5.0.0-rc1:
https://github.com/Droidcon-Boston/conference-app-android/commit/e65b58777cc5fa797acc237de27967e05a6d22e3
That was before I restructured it to get rid of the marginBottom in the root header tag.
