### ISSUE TITLE
getStateListDrawable should set also the pressedColor on state_pressed for API < 21

### ISSUE THREAD

**Issue by marbat87** [davideas/FlexibleAdapter#333]
Hi,

I was trying to set a selectableBackroundCompat on a Item, but I noticed that using that mehtod, when you click on the view no effect is shown on API < 21

I saw that, for API < 21, you're calling the following utility method inside DrawableUtils:
<pre>
    public static Drawable getSelectableBackgroundCompat(@ColorInt int normalColor, @ColorInt int pressedColor, @ColorInt int rippleColor) {
        return (Drawable)(Utils.hasLollipop()?new RippleDrawable(ColorStateList.valueOf(rippleColor), getStateListDrawable(normalColor, pressedColor), getRippleMask(normalColor)):getStateListDrawable(normalColor, pressedColor));
    }

...

    private static StateListDrawable getStateListDrawable(@ColorInt int normalColor, @ColorInt int pressedColor) {
        StateListDrawable states = new StateListDrawable();
        states.addState(new int[]{16843518}, getColorDrawable(pressedColor));
        states.addState(new int[0], getColorDrawable(normalColor));
        if(!Utils.hasLollipop() || Utils.hasNougat()) {
            short duration = 200;
            states.setEnterFadeDuration(duration);
            states.setExitFadeDuration(duration);
        }

        return states;
    }
</pre>

I saw that 16843518 corresponds to state_activated.
I think that ONLY for API < 21 you should add also the state_pressed.
You could replace the call to getStateListDrawable, with a new getStateListDrawableLegacy, like this one:
<pre>
    public static Drawable getSelectableBackgroundCompat(@ColorInt int normalColor, @ColorInt int pressedColor, @ColorInt int rippleColor) {
        return (Drawable)(Utils.hasLollipop()?new RippleDrawable(ColorStateList.valueOf(rippleColor), getStateListDrawable(normalColor, pressedColor), getRippleMask(normalColor)):getStateListDrawableLegacy(normalColor, pressedColor));
    }

..

	private static StateListDrawable getStateListDrawableLegacy(@ColorInt int normalColor, @ColorInt int pressedColor) {
		StateListDrawable states = new StateListDrawable();
		states.addState(new int[]{16843518}, getColorDrawable(pressedColor));
		states.addState(new int[]{16842919}, getColorDrawable(pressedColor));
		states.addState(new int[0], getColorDrawable(normalColor));
		if(!Utils.hasLollipop() || Utils.hasNougat()) {
			short duration = 200;
			states.setEnterFadeDuration(duration);
			states.setExitFadeDuration(duration);
		}

		return states;
	}
</pre>

I tested it and it works fine ob both 6.0.1 or 4.1 Android versions.

Thanks & Regards

**Comment by davideas** [comment]
@marbat87, thanks for the improvement suggestion, I will check it out better, later.

**Comment by davideas** [comment]
@marbat87, what is the difference visually? I can't see it.
