### ISSUE TITLE
Header view drawn multiple time

### ISSUE THREAD

**Issue by IHNEL** [davideas/FlexibleAdapter#334]
Hi,
I implement my recycler-view using FlexibleAdapter within `AbstractHeaderItem` and `AbstractSectionableItem` to make sticky-header list.

There are 3 list items which assigned 3 header items. 3 these header items have same data, and of course I implemented the `equals` method to return whether they are same. The issue is the header items drawn multiple time as below screenshot

<img width="313" alt="screen shot 2017-04-07 at 11 46 41 am" src="https://cloud.githubusercontent.com/assets/698960/24785978/2e1f6f52-1b88-11e7-88b0-894c9b98fecf.png">

If I created unique header data item and then set to all 3 items, then it draw correctly. What I am expecting is I can create header data item dynamically based on given data-fields, and there is a way to group same headers into a section.

Did I make any mistake?

**Comment by davideas** [comment]
@IHNEL, well a mistake was done. Review your code to be sure the same header object is assigned to the 3 items, or maybe equals is not implemented properly. Read again the wiki for equals or simply read the method comments.

**Comment by IHNEL** [comment]
I created a new header object every time insert  new item. Each header object has a field`name`, and I wrote the `equals` like this (I'm using Kotlin) :

> override fun equals(other: Any?) 
> = other is HeaderView && other.name == this.name

I debug and see the equals method works fine.

**Comment by davideas** [comment]
@IHNEL, uhm theoretically it should work. Can you check which is the reference in memory for the 3 header items?
Debug and watch the list in the Adapter.
Possibly assign the same object so you see the difference between the 2 approaches.

**Comment by davideas** [comment]
I closed due to inactivity, but also the approach used should be refined.

**Comment by IHNEL** [comment]
@davideas sorry for quite lately reply. I didn't keep good notification in Github. 
Of course the memory references are difference cos I initialized 3 difference objects for header. But I think it should rely on the `equals` method to check that they should be on same group.

**Comment by davideas** [comment]
@IHNEL, the function getHeaderOf takes the header instance of the item, and on it is checked if it is hidden or not, then displayed, so it must be the same instance.

**Comment by IHNEL** [comment]
Ok, Got it. Seems I have to reconsider my data structure.
Thank you so much,

**Comment by IHNEL** [comment]
I debug and see that the method `equals` of header view didn't be call. I spent much of time to investigate but don't know why it runs into this case.
Any recommendation?

**Comment by davideas** [comment]
@IHNEL, the equals method is called when you get an item from the list or when it is explicity called.
With the last Snapshot I improved the calls on `equals` for managing Headers, check commits in issue #357.

**Comment by IHNEL** [comment]
Thank. Finally I found the cause.
The `equals()` method wasn't called if I set up the adapter like this:
`adapter.setDisplayHeadersAtStartUp(true).setStickyHeaders(true)`

And it works like a charm when I turn to this.
```      
       adapter.setStickyHeaders(true)
        adapter.setStickyHeaders(true)
```
