### ISSUE TITLE
Issue with grouping items when updateDataSet called after SNAPSHOT updated

### ISSUE THREAD

**Issue by yamelkaya** [davideas/FlexibleAdapter#335]
Hi @davideas, 

I use `StaggeredGridLayoutManager `with 3 columns:

`StaggeredGridLayoutManager layoutManager = new StaggeredGridLayoutManager(3, LinearLayoutManager.VERTICAL);`

On start everything is OK and looks like: 

![image](https://cloud.githubusercontent.com/assets/2253928/24829181/d79cd32e-1c75-11e7-805c-1e25f29cc19b.png)

When I click on item for details and return back I refresh list with  `adapter.updateDataSet(items,true);` and after that grouping is broken - first item goes out of first group

![image](https://cloud.githubusercontent.com/assets/2253928/24829201/43687658-1c76-11e7-8e7a-fa9f1882c5ee.png)

If I repeat these steps (1 - open details, 2 - go back to list) everything looks normally again. 

I haven't noticed this issue before. I suppose it's connected with latest updates.

**Comment by davideas** [comment]
@yamelkaya, please check the logs and see how many items are deleted / inserted / modified when using the async update. "Welcome on board" could be without header in that refresh.

As explained in the release note, headers and expanded items are now initially applied to the list provide in the update, then the calculation of the difference between new list and internal list is performed.
If he sees a change it will remove and insert at the position of the new list. So if the new list doesn't have the header, that is the result.

**Comment by yamelkaya** [comment]
I've checked first badge header - it's OK and equals to BETA badge header

![image](https://cloud.githubusercontent.com/assets/2253928/24851077/081443dc-1ddb-11e7-92fb-80874ea2f417.png)

Logs for `updateDataSet` below (call with `animate = false` now):
```

04-08 17:08:42.680 21096-21096/io.centaurea.cnzr W/FlexibleAdapter: updateDataSet with notifyDataSetChanged!
04-08 17:08:42.681 21096-21096/io.centaurea.cnzr V/FlexibleAdapter: onViewBound    Holder=ItemViewHolder position=0 itemId=-1 layoutPosition=0
04-08 17:08:42.684 21096-21096/io.centaurea.cnzr V/FlexibleAdapter: onViewBound    Holder=HeaderViewHolder position=1 itemId=-1 layoutPosition=1
04-08 17:08:42.684 21096-21096/io.centaurea.cnzr V/FlexibleAdapter: onViewBound    Holder=ItemViewHolder position=2 itemId=-1 layoutPosition=2
04-08 17:08:42.687 21096-21096/io.centaurea.cnzr V/FlexibleAdapter: onViewBound    Holder=ItemViewHolder position=3 itemId=-1 layoutPosition=3
04-08 17:08:42.688 21096-21096/io.centaurea.cnzr V/FlexibleAdapter: onViewBound    Holder=HeaderViewHolder position=4 itemId=-1 layoutPosition=4
04-08 17:08:42.688 21096-21096/io.centaurea.cnzr V/FlexibleAdapter: onViewBound    Holder=ItemViewHolder position=5 itemId=-1 layoutPosition=5
04-08 17:08:42.689 21096-21096/io.centaurea.cnzr V/FlexibleAdapter: onViewBound    Holder=ItemViewHolder position=6 itemId=-1 layoutPosition=6
04-08 17:08:42.692 21096-21096/io.centaurea.cnzr V/FlexibleAdapter: onViewBound    Holder=ItemViewHolder position=7 itemId=-1 layoutPosition=7
04-08 17:08:42.693 21096-21096/io.centaurea.cnzr V/FlexibleAdapter: onViewBound    Holder=HeaderViewHolder position=8 itemId=-1 layoutPosition=8
04-08 17:08:42.701 21096-21096/io.centaurea.cnzr V/FlexibleAdapter: onViewBound    Holder=ItemViewHolder position=9 itemId=-1 layoutPosition=9
04-08 17:08:42.703 21096-21096/io.centaurea.cnzr V/FlexibleAdapter: onViewBound    Holder=ItemViewHolder position=10 itemId=-1 layoutPosition=10
04-08 17:08:42.704 21096-21096/io.centaurea.cnzr V/FlexibleAdapter: onViewBound    Holder=ItemViewHolder position=11 itemId=-1 layoutPosition=11
04-08 17:08:42.704 21096-21096/io.centaurea.cnzr V/FlexibleAdapter: onViewBound    Holder=HeaderViewHolder position=12 itemId=-1 layoutPosition=12
04-08 17:08:42.905 21096-21096/io.centaurea.cnzr V/AnimatorAdapter: Clear notified for scrolling Animations
```
When I use `clear `+ `addItems `combination everything works perfectly. 

```
adapter.clear();
adapter.addItems(0, sortedGroupedBadges);

```

**Comment by davideas** [comment]
@yamelkaya, ok thanks for the logs, I think I've identified the point of the error.
Cannot create new snapshot from here, you need to wait for this evening/tomorrow.

**Comment by yamelkaya** [comment]
Ok. Thanks a lot.
