### ISSUE TITLE
Update a single item

### ISSUE THREAD

**Issue by Faisal0sal** [davideas/FlexibleAdapter#336]
Please check off the following points BEFORE submitting a new issue / asking support.
- [x] Write a self explanatory Subject.
- [x] Check if the issue has already been raised by someone else (see closed issue).

1) For Bugs / Support
- [x] What you've tried (If necessary, indicate library Version / Android version / hardware).
- [x] Expected behavior and actual behavior (problem encountered).
- [x] Steps to reproduce the problem (also include code snippets if you think will help).

2) For questions / new feature / improvement
- [x] Simply Erase all this text and ask your question;

3) To have your App added to the list
- [x] Simply Erase all this text and provide your app's name and link.

I can see in the Wiki how I can Update a dataset however, I can't see how will I update one single item in a recycle view?

I have tried `myCategoriesRecyclerViewAdapter.updateItem(new CategoryItem(), index);`

But this one creates a new item for some reason instead of updating an existing one in my recycle view?

How would I do that?

Thanks

**Comment by davideas** [comment]
@Faisal0sal, please read the comment of the methods, the index parameter is wrong. There are 2 methods overload of `updateItem()`.
