### ISSUE TITLE
Endless scroll enhancement

### ISSUE THREAD

**Issue by kvolkers** [davideas/FlexibleAdapter#340]
Current endless scroll supports pages that have an exact amount of items (for example loading 20 more items each time).

My suggestion is to add support for another type of endless scroll, for pages that don't have a pre-determined amount of items.

Example use case: an electronic program guide that lazy loads items per day. A page represents a date range from the start of a day to the end of that day. Page -1 -> yesterday, page 0 -> today, page 1 -> tomorrow etc.

A new criteria to disable the endless feature would be useful, based on the minimum page and maximum page to load.

**Comment by davideas** [comment]
@kvolkers, you can already change the page count every time. But, it is also up to you to call the Rest Api and return the correct number of items, by default page count is unlimited.

You can actually disable the endless by setting `null` the `progressItem` at the condition you desire.
