### ISSUE TITLE
Swipe does not properly work (animate) on android version below Lollipop

### ISSUE THREAD

**Issue by SolidScorpion** [davideas/FlexibleAdapter#346]
Hello! Long term library user here. Recently started working on a new project where I encountered the need for items to be swipe able and  show some kind of view behind them.
I examined example app provided in this repo and implemented an item with layout similar to recycler_expandable_item.xml (from sample project). I defined front view, rear right view and rear left view.
I've searched for similar open\closed issues and did not manage to find anything.

Adapter version I'm using:
5.0.0-rc1
I've tried swipe with rear view on Android versions below lollipop (16,17,19) here's the video of the issue (first part is showing issue using your sample app, second part - my app) https://www.youtube.com/watch?v=Wzs13nGb3cw
The issue is not present when using swipe on items with rear view on android version >= lollipop

As you can see - the moment swipe action starts the front view disappears and rear view is shown immediately. Does this have something to do with transparency on Android versions below lollipop?

**Comment by lxdyglt** [comment]
I'v got the same problem, can someone make an urgent release to fix it.

**Comment by davideas** [comment]
Dears, thank you for your messages.
I really do not have time to look into this issue, but be aware that the swiping really needs to be improved and restructured. The issue #315 is already in place.

**Comment by davideas** [comment]
Please use **exclusively** this view order in the layout:
``` xml
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout>
	<RelativeLayout
		android:id="@+id/rear_left_view"
		android:visibility="gone">
	</RelativeLayout>

	<RelativeLayout
		android:id="@+id/rear_right_view"
		android:visibility="gone">
	</RelativeLayout>

	<RelativeLayout
		android:id="@+id/front_view">
	</RelativeLayout>

</FrameLayout>
```

**Comment by davideas** [comment]
@SolidScorpion, @lxdyglt, if you don't have any remarks I will close this ticket.

**Comment by lxdyglt** [comment]
@davideas that solved this issue, thanks.

**Comment by SolidScorpion** [comment]
Thank you! it did
