### ISSUE TITLE
Fast scroller never shown in the current snapshot

### ISSUE THREAD

**Issue by inorichi** [davideas/FlexibleAdapter#348]
When the fast scroller is inflated with `View.GONE`, the scroller will never show until its visibility is manually set to `View.VISIBLE` .

I'm using `FragmentViewPager` from the sample app as example (which currently crashes in [this line](https://github.com/davideas/FlexibleAdapter/blob/current_snapshot/flexible-adapter-app/src/main/java/eu/davidea/samples/flexibleadapter/fragments/FragmentViewPager.java#L107), I commented it).

Expected behavior:
* Scroller is shown after the user begins to scroll.

Actual behavior:
* Scroller is never shown.

The example from `FragmentHeadersSection` is working because `MainActivity` enables the visibility of the scroller in `onUpdateEmptyView`. Shouldn't the visibility be handled internally?

I would like the scroller to be shown only when the user begins to scroll (in this fragment it's also shown at the start, but IMO that's too distracting).

**Comment by davideas** [comment]
@inorichi, since with the new FastScroller, AutoHide is enabled by default, we can remove the Visibility.GONE from the layout, this will fix your issue!

And, I added a new feature, if scrolled amount is small (< 120px), it is not shown.
Available with next snapshot.

**Comment by inorichi** [comment]
I think the scroll amount is not a good idea, the scroller can be hidden even when it's still scrolling. To reproduce, begin with a fast drag then continue slowly.

What I meant in my last sentence was something like this patch: https://github.com/inorichi/FlexibleAdapter/commit/0f0e88d14b96f17d9f5408fd81bfbd4edf865113 (I don't know if this solution introduces any issue)

When `autoHideEnabled` is set, you don't see the scroller for a few seconds when the view is created.

**Comment by davideas** [comment]
@inorichi, it is wanted that the scrollbar is shown for a small amount of time at startup, then, it auto-hides. It gives an hint to the user that fast scrollbar is available!

With my last commit, it is now better: if you set the minimum scroll threshold, by dragging the list slowly, it won't show the scrollbar. The fast scrollbar is always available on touch by the way. But when you start to fling the list (when scroll amount is bigger than threshold), the fast scrollbar is shown again and now remains visible if it is active. I think it's cool.
