### ISSUE TITLE
Footer alignment

### ISSUE THREAD

**Issue by larten** [davideas/FlexibleAdapter#351]
Hi,

Do you have any idea how can I align the footer in the adapter?
The footer view is working correctly, my problem is when the content of recyclerview lesser than the height of recyclerview, I would like to show the footer view at the bottom of the view.

So I would like to set the position of the footer view align to the bottom or below the the items if the content is scrollable.

Thanks for the help!

**Comment by davideas** [comment]
@larten, yes I understand, it could be interesting, it's doable with a ItemDecorator that is able to recognize if exists a Footer item, it can calculate the difference between the last item and the remaining space.

If you will do you will share the code.
