### ISSUE TITLE
onLoadMore currentPage != currentPage

### ISSUE THREAD

**Issue by es0329** [davideas/FlexibleAdapter#353]
When working with EndlessScrollListener, at the _initial_ [onLoadMore](https://github.com/davideas/FlexibleAdapter/blob/31852ca6326e4f1f082478bc1346054342384a08/flexible-adapter/src/main/java/eu/davidea/flexibleadapter/FlexibleAdapter.java#L5218), I expect currentPage == 1, however I'm observing currentPage == 20. It seems to contain a value equal to itemCount or lastPosition. Perhaps, I'm doing something wrong; any ideas?

**Comment by davideas** [comment]
@es0329, currentPage is a calculation of the following method:
``` java
/**
 * Provides the current endless page if the page size limit is set, if not set the returned
 * value is always 1.
 *
 * @return the current endless page
 */
public int getEndlessCurrentPage() {
	return Math.max(1, mEndlessPageSize > 0 ? getMainItemCount() / mEndlessPageSize : 0);
}
```
