### ISSUE TITLE
setRemoveOrphanHeaders(false) still available in any way?

### ISSUE THREAD

**Issue by maltebucksch** [davideas/FlexibleAdapter#354]
I am using the filter functions on a dataSet containing headers (`AbstractExpandableItem`) and `AbstractSectionableItems` as their child.
If no item matches the query I want to only show the headers. But if a header has no sub-items it vanishes automatically.
Any way to keep the headers even if they have no sub-items?
(Like the `setRemoveOrphanHeaders(false)` that was deprecated according to https://github.com/davideas/FlexibleAdapter/issues/200)

**Comment by davideas** [comment]
@maltebucksch, the feature will be removed before final release. If you remove all the sub-items, nothing happens to the expandable.

Headers that are not expandable will disappear at the next refresh, because they rely on the items below, while if they are expandable they are kept because the sub-items rely on the expandable.

**Comment by maltebucksch** [comment]
Thanks for your reply. My headers are 'expandable' since they are a subclass of "AbstractExpandableItem" and I even setExpandable(true) on them in addition. They are still vanishing once my search query filters out all of their sub items, am I missing something here?

**Comment by davideas** [comment]
Ah ok. Filter actually removes any item that do not match with the search text. So it's normal. If no subitems are filtered in then also the expandable of them is filtered out.

Your next question will be, can you keep the expandable in the filter with empty sub list? Is this what you want?

**Comment by maltebucksch** [comment]
Yep, exactly. If no sub-item matches the filter, I still want to show the header/expandable.

**Comment by davideas** [comment]
Let me check what I can do. In case it will be a property configuration to activate.

**Comment by maltebucksch** [comment]
Thank you

**Comment by davideas** [comment]
@maltebucksch, if you want the expandable always be filtered in, even when subItems are filtered out, implement the method `filter()` and `return true` for the Expandable item.

**Comment by maltebucksch** [comment]
Works! thanks for the tip Davidea
