### ISSUE TITLE
[FastScroller] Scrollbar/handle is temporarily hidden when handle is selected

### ISSUE THREAD

**Issue by arpinca** [davideas/FlexibleAdapter#359]
Cause: In ScrollbarAnimator.java, the bar and handle are set to visible only in onAnimationEnd.

Previously, it was before the animator set is created.
Why was it moved inside onAnimationEnd?

Note: I'm using current_snapshot

**Comment by davideas** [comment]
Ouch, I didn't notice, I will revert it back.

**Comment by arpinca** [comment]
Thanks! I can submit a PR if you want. But I'm not sure where to branch from. current_snapshot?

**Comment by davideas** [comment]
@arpinca, I already did it, I need to create a new Snapshot.

**Comment by davideas** [comment]
Snapshot is ready.

**Comment by thelong1EU** [comment]
Thanks!
