### ISSUE TITLE
Review the example App

### ISSUE THREAD

**Issue by davideas** [davideas/FlexibleAdapter#36]
Add configuration Dialog or load new Activity to show all the power the library has.
Separate example with new Activities/Fragments, Sections with sticky headers, Expandable items, Expandable headers (to evaluate),  Linear/Grid animations, Helpers use cases.

**Comment by zosocanuck** [comment]
Hi,

Nice set of interfaces.  I'm just getting started and was wondering if you have any sample code around working with sections?

**Comment by davideas** [comment]
Hello @zosocanuck, thanks for the message.
Actually the demo app has sections implemented, but until I don't release the final version always look in **dev** branch. Also, read the latest _change log, wiki page_ and _issues page_.
Keep in mind that, demo app is under continuous development and so you will find code not properly organized at the moment.

Feel free to ask for your specific use case by opening a new issue.
