### ISSUE TITLE
Simplify the method createViewHolder in IFlexible

### ISSUE THREAD

**Issue by davideas** [davideas/FlexibleAdapter#363]
This will have an impact of the current implementation.
Layout inflation will be done by the Adapter and the delegated method `createViewHolder()` will receive the inflated View and the Adapter. It will simplify the ViewHolder creation by the user.

**Comment by davideas** [comment]
From the next snapshot you will have to adapt the method `createViewHolder()` in ALL of your `IFlexible` implementation:
The `IFlexible` interface now wants you implement as following:
``` java
@Override
public MyViewHolder createViewHolder(View view, FlexibleAdapter adapter) {
	return new MyViewHolder(view, adapter);
}
```

**Comment by dozd** [comment]
How to support databinding in view holders now? In previous version i could inflate the view myselft creating databinding class and provide it to ViewHolder. Something like this:

```
@Override
public ViewHolder createViewHolder(FlexibleAdapter adapter, LayoutInflater inflater, ViewGroup parent) {
    ItemReminderBinding binding = DataBindingUtil.inflate(inflater, getLayoutRes(), parent, false);
    return new ViewHolder(binding, adapter);
}

@Override
public void bindViewHolder(FlexibleAdapter adapter, ViewHolder holder, int position, List payloads) {
    holder.getDataBinding().setVariable(BR.item, reminder);
    holder.getDataBinding().executePendingBindings();
}
```

It this possible after in current version?

**Comment by davideas** [comment]
@dozd, I believe https://developer.android.com/reference/android/databinding/DataBindingUtil.html has something with the View. Isn't it?

**Comment by dozd** [comment]
Ach, thx, i'll try it
