### ISSUE TITLE
How to disable expand/collapse animation?

### ISSUE THREAD

**Issue by volser** [davideas/FlexibleAdapter#364]
How to disable expand/collapse animation?

Thanks

**Comment by davideas** [comment]
@volser, could you please elaborate your question?
I would answer just don't add any animation. The default ItemAnimator make it appear or disappear, which specific animation are you talking about for expanding/collapsing?

**Comment by volser** [comment]
I mean this animation:
https://youtu.be/bz97fR8D-DM

**Comment by davideas** [comment]
@volser, ok, so it's the `DefaultItemAnimator`, if you set it null any change won't be animated anymore.

**Comment by volser** [comment]
@davideas cool, thanks

**Comment by davideas** [comment]
@volser, sorry, I reviewed your video, there's a glitch on the lower views, they move up and down once you click on the expandable, I mean the views of "Worked on recently". That shouldn't happen as you see from the demoApp those views nicely move up and down only the subItems appear and disappear.
Are those views part of the same list?

**Comment by volser** [comment]
@davideas  "Worked on recently" it's second recyclerview.

First recyclerview has height="wrap_content"

**Comment by davideas** [comment]
Ah ok, so you are aware of it.
