### ISSUE TITLE
[FastScroller] OnScrollListener removed onDetachedToWindow?

### ISSUE THREAD

**Issue by arpinca** [davideas/FlexibleAdapter#369]
Hi,

I'd like to ask why is `onScrollListener` removed in `FastScroller#onDetachedToWindow`? I mean, if it's for preventing leaks when the window is detached, why remove only the onScrollListener? How about the other listeners like OnLayoutChangeListener and OnPreDrawListener? Or how about adding it again in `FastScroller#onAttachedToWindow`?

For context, I use FastScroller in views on a ViewPager. Then, I change the PagerAdapter in runtime. This causes the `FastScroller#onDetachedToWindow`to be called. Eventually, `FastScroller#onAttachedToWindow` is called. But since the onScrollListener is not re-added, I no longer receive onScrolled callbacks. Hence, FastScroller will no longer be displayed (unless the view is recreated).

**Comment by davideas** [comment]
@arpinca, the first version was took from another project, changing the Adapter wasn't foreseen.
I will fix it.

**Comment by davideas** [comment]
Since I do not have example to swap the ViewPager Adapter at runtime and I  cannot publish a new Snapshot, could you please check if adding the following in your version resolves the issue, if you can?
``` java
@Override
protected void onAttachedToWindow() {
	super.onAttachedToWindow();
	if (recyclerView != null) {
		// Occurs only when a new ViewPager is changed at runtime
		recyclerView.addOnScrollListener(onScrollListener);
	}
}
```

**Comment by arpinca** [comment]
> Does your issue come only when you change the Adapter of the pager and not of the RecyclerView?

Yes. Thank you! This [snippet](https://github.com/davideas/FlexibleAdapter/issues/369#issuecomment-303049018) fixed it.
