### ISSUE TITLE
Adjust and improve Wiki pages

### ISSUE THREAD

**Issue by davideas** [davideas/FlexibleAdapter#37]
Add a Wiki page with all functionalities and quick description of what the library can do.
Add and adjust Wiki pages with tutorials for v5.0.0 to show the main functionalities.
Add a side menu for different versions.
#### The basics
- [x] Library structure
- [x] Setting Up
- [x] Setting Up Advanced
- [x] Item interfaces
- [x] ViewHolders
- [x] Callbacks
- [x] Migrations
#### Functionalities
- [x] Update Data Set
- [x] Selection modes
- [x] Headers and Sections
- [x] Scrollable Headers and Footers
- [x] Expandable items
- [x] Drag&Drop and Swipe
- [x] Search Filter
- [x] EndlessScroll / On Load More
- [x] Adapter Animations
#### Extensions
- [x] Smooth Layout Managers
- [x] Thirds Layout Managers
- [x] Flexible Item Decoration
- [x] FastScroller
- [x] Utils
- [x] ActionModeHelper
- [x] UndoHelper
- [x] AnimatorHelper
- [x] Payload
#### Demo App
- [x] Activity & Fragments

\* = Initiated / Not completed

**Comment by davideas** [comment]
Added structure description about how this library is designed. Link: [Library structure](https://github.com/davideas/FlexibleAdapter/wiki/5.x-%7C-library-structure).

**Comment by davideas** [comment]
Added a new Wiki page about how to implement sections with sticky headers and expandable sections. Direct link: [Headers and Sections](https://github.com/davideas/FlexibleAdapter/wiki/5.x-%7C-Headers-and-Sections).

**Comment by davideas** [comment]
Added new Wiki page about [How to use](https://github.com/davideas/FlexibleAdapter/wiki/5.x-%7C-How-to-use) and how to initialize the adapter.

**Comment by choxnox** [comment]
Documentation definitely needs improvement because I've just wasted the whole day trying to figure out why my initial list with headers isn't working and throwing ClassCastException only to find out it's because I was using the same layout resource. 

Not only that but it appears `getLayoutRes` function is internally called within adapter which means it's also mandatory to implement it and nothing of this is mentioned in the documentation.

**Comment by davideas** [comment]
@choxnox, I'm sorry if you got lost in the implementation, the page _How to use_, actually shows the 2 ways to implement the binding (normal way or with item interfaces). Also, you could read the comments of every single methods (to override) of the Adapter and of the item interfaces.

**Comment by davideas** [comment]
Added new Wiki page about [Drag&Drop and Swipe](https://github.com/davideas/FlexibleAdapter/wiki/5.x-%7C-Drag&Drop-and-Swipe).

**Comment by 54binge** [comment]
this lib is so powerful，so many functions, but the demo app and wiki is so diffcult to read,this may be a reason why so many stars but a little issules, i want to use it,after two days ,i gave up,but i still believe it is a great lib and i will still keep focus it

**Comment by davideas** [comment]
Hello @54binge, thank you.
The demo App is divided by fragments showing different use cases, they have callbacks to the main Activity where common views and objects are used, it can be done better but before it was much worst.

About the Wiki, I'm going to add new pages in these days, as planned. For the existent pages, what is not clear? I already modified the existent to support the beta7 features.

I'm open to any suggestions.
Thanks, Davide

**Comment by davideas** [comment]
Wiki pages tutorial has been completely reviewed
In the coming weeks, more pages will be completed as well.

**Comment by davideas** [comment]
Added [Demo App Wiki page](https://github.com/davideas/FlexibleAdapter/wiki/5.x-%7C-Demo-App).

**Comment by davideas** [comment]
Added [Setting Up Advanced](https://github.com/davideas/FlexibleAdapter/wiki/5.x-%7C-Setting-Up-Advanced) Wiki page.

**Comment by davideas** [comment]
Added [Scrollable Headers and Footers](https://github.com/davideas/FlexibleAdapter/wiki/5.x-%7C-Scrollable-Headers-and-Footers).

**Comment by davideas** [comment]
Added [Payload](https://github.com/davideas/FlexibleAdapter/wiki/5.x-%7C-Payload) & reviewed all existent pages.

**Comment by shymmq** [comment]
[Load more upon a user request](https://github.com/davideas/FlexibleAdapter/wiki/5.x-%7C-On-Load-More#load-more-upon-a-user-request) isn't really documented well. Should I call adapter.onLoadMore()? If yes, when? Will the items be added automatically or do I have to add them manually? Also, there is no example on this topic in the demo app, only automatic loading.

**Comment by davideas** [comment]
@shymmq, that part is indicative (without example yet), but the logic steps are described. I added another point to complete the loading once the items are received.

`onLoadMore()` is for automatic loading, so you **don't** have to call it. The items are loaded when user clicks on the button that you add in the layout of the progress bar. The callback of that remote call will invoke `onLoadMoreComplete(newItems)`.

**Comment by davideas** [comment]
With RC2 release many pages have been reviewed already, all the remaining will be updated soon.
