### ISSUE TITLE
Confusing behaviour of clearAllBut when called without specifying view types to retain

### ISSUE THREAD

**Issue by Kreiri** [davideas/FlexibleAdapter#372]
Javadoc comment for `clearAllBut` method of FlexibleAdapter says:

    /**
	 * Clears the Adapter list retaining Scrollable Headers and Footers and all items of the
	 * type provided as parameter.
	 * <p><b>Note:</b>- This method is opposite of {@link #removeItemsOfType(Integer...)}.
	 *
	 * @param viewTypes the viewTypes to retain
	 * @see #clear()
	 * @see #removeItems(List)
	 * @see #removeItemsOfType(Integer...)
	 * @since 5.0.0-rc1
	 */

Using `adapter.clearAllBut()`, I expected it to leave headers and footers but remove everything else, as list of view types to retain is empty. Instead, it simply cleared **everything**. 

I think either javadoc or code should be updated.

**Comment by davideas** [comment]
@Kreiri, thank you, it is certainly a bug, I will fix and publish for RC2 pre-release.
