### ISSUE TITLE
how to update head notifyDataSetChanged not work for head item

### ISSUE THREAD

**Issue by epwtrq** [davideas/FlexibleAdapter#374]
i use notifyDataSetChanged not work  to update head item

**Comment by davideas** [comment]
@epwtrq, which version are you using?
It should work if you use the Snapshot version, since it was fixed on 12/4 together with issue #320.
Try to use `updateItem()` function, it should trigger the update also the sticky layout if that header is sticky.

**Comment by epwtrq** [comment]
thanks ，I use your source code .sticky head use notifyDataSetChanged not work .i will try another way as your say updateItem()

**Comment by epwtrq** [comment]
updateItem(head)still not work for sticky head .is there a sample in demo

**Comment by davideas** [comment]
@epwtrq, it works in Snapshot version, I just tried. However, this version will be the RC2 very soon!
If you want to try it out, I just committed something in the demo app.

**Comment by epwtrq** [comment]
thanks
