### ISSUE TITLE
Sticky header doesn't maintain RecyclerView.ItemDecoration where getItemOffsets is used for GridLayoutManager

### ISSUE THREAD

**Issue by blitr** [davideas/FlexibleAdapter#376]
The following layout manager is being used: SmoothScrollGridLayoutManager
With the column count set to 2 and the spanSizeLookup being used to mark certain rows as headers.

The following item decoration is being used:
```
public class SpacesItemDecoration extends RecyclerView.ItemDecoration {
    private int mItemOffset;

    public SpacesItemDecoration(int itemOffset) {
        mItemOffset = itemOffset;
    }

    public SpacesItemDecoration(@NonNull Context context, @DimenRes int itemOffsetId) {
        this(context.getResources().getDimensionPixelSize(itemOffsetId));
    }

    @Override
    public void getItemOffsets(Rect outRect, View view, RecyclerView parent,
                               RecyclerView.State state) {
        super.getItemOffsets(outRect, view, parent, state);
        outRect.set(mItemOffset, mItemOffset, mItemOffset, mItemOffset);
    }
}
```

When the sticky header view holder is displayed at the top it looses the spacing decoration used by the recyclerview thus causing the content in the header to jump to the default offsets.

**Comment by davideas** [comment]
@blitr, yes, the offset is _not_ translated to the sticky layout.
This needs to be analyzed how to do. Any idea?

The `FlexibleItemDecorator` from the library needs to be enhanced as well to have the offset configurable that works for linear layout and the 2 grid layouts. It should also support equal distance at the edges of the items if used with grid layouts.
Now, it only supports the divider offset and the section gap offset.

**Comment by davideas** [comment]
@blitr, I highly improved the ItemDecoration (see #382) and implemented a possible solution for what you requested. Please could you run the demoApp with the emulator and check in Header and Sections example (use **current_snapshot** branch only)? Is that what you were looking for?

**Comment by blitr** [comment]
@davideas Cool, thanks. Any idea when rc2 will be available so I can sync with my project?

I'll try to find time to pull the branch and check it out.

**Comment by davideas** [comment]
@blitr, it would be better that you check it out before I publish the new pre-release that I foresee for this Saturday if something else doesn't come up.

**Comment by blitr** [comment]
@davideas, it certainly looks like it will solve the issue we had. I have a workaround in my code right now but once rc2 is released I'll get it working for our use case. 
Great job on the library! And thanks for the rapid turnaround.

**Comment by davideas** [comment]
Thank you @blitr ❗️
