### ISSUE TITLE
Calling FlexibleAdapter.clear() may cause NullPointerException

### ISSUE THREAD

**Issue by magneticflux-** [davideas/FlexibleAdapter#378]
Library Version: 5.0.0-rc1

All methods referenced are located in FlexibleAdapter.java

Expected outcome:
When `public IHeader getHeaderOf(@NonNull T item) { ... }` is overriden, `item` should never be null. I relied on that null checking, and it caused a NullPointerException unexpectedly.

Actual outcome:
`clear();`
calls
`removeRange(0, getItemCount(), null);`
which then assigns
`T item = getItem(positionStart);`
without checking if the `itemCount` argument is `0`.
Since the list is empty, `getItem(0);` returns null, which is then passed to `getHeaderOf(item);` without a null check.

**Comment by magneticflux-** [comment]
I'll make a pull request that fixes this and adds more `@Nullable` and `@NonNull` annotations in FlexibleAdapter to prevent future similar errors.

**Comment by davideas** [comment]
@magneticflux- thanks for your message. Actually the annotation is just an indication. But you are right that if overridden, that indication may mislead to not check the nullable value.
If you want you can also add a check of emptiness in `removeRange()`, to early return so it avoids to run through that method.

Maybe is better to check all the NotNull annotation that can be overridden too. Would you do it?

**Comment by magneticflux-** [comment]
@davideas I'll try looking through other overrideable methods with `@NonNull` annotations and see if any can be changed so they aren't violated.
