### ISSUE TITLE
Sticky item is invisible after replacing items below it

### ISSUE THREAD

**Issue by zoki-** [davideas/FlexibleAdapter#383]
The setup is as follows:
- there is a sticky item with a spinner for selecting
- the sticky item is sticked for the user to filter items using the spinner when scrolling down and browsing those items, that are positioned below the sticky item
- the user has scrolled down in the list, so the sticky view is sticked.

The action:
- when user selects something from spinner, I do the following: `adapter.removeItemsOfType(R.layout.my_layout);`
to remove the items below the sticky view in the list.
This is then immediately followed by
`adapter.onLoadMoreComplete(newItems);`
to add the new items user wants to see.

The result is:
- list is scrolled to the top
- sticky item is invisible, but still takes the space
- new items are visible below the invisible sticky view
- when scrolling a bit for the view to stick again to the top, the view becomes visible again

Expected result:
- the sticky view should be visible when list is scrolled to the top

**Comment by davideas** [comment]
@zoki- which version are you using?
I've fixed some bugs described in #320 and #347 and those fix are available in the Snapshot version and soon also in RC2.
Does that behaviour still occurs in the Snapshot version?

**Comment by zoki-** [comment]
I'm using the 5.0.0-SNAPSHOT version.
The behavior occurs with this version.

**Comment by davideas** [comment]
@zoki- well Ok, can you provide me the logs and parts of code?
If you can share the project even better.

**Comment by davideas** [comment]
@zoki-, without logs I can't be precise. I can only suspect that the layout manager didn't finish its work after the layout of removing and sticky header is not cleared, or is cleared but not scrolled to the top. Can you add the new items in post, delayed?
Separate the process: first delete and see if the header is still there without items, then, optionally you scroll to it, finally you add new items and see what happens.

**Comment by davideas** [comment]
Closing this issue: not reproducible.
