### ISSUE TITLE
get Item data 

### ISSUE THREAD

**Issue by ceddyb** [davideas/FlexibleAdapter#385]
How do i get the data from my IFlexible item?

i mean the private data fields, lets say for an item selected.

As i see it returns an IFlexible object which doesn't have my data.

Do i have to define my own setter and getter methods for my IFlexible item and manually add a duplicate Array for my data?

**Comment by davideas** [comment]
@ceddyb, you have 2 options:
- You can extend your [Adapter item](https://github.com/davideas/FlexibleAdapter/wiki/5.x-%7C-Setting-Up#implement-and-customize-the-item-myitem-and-myviewholder-classes) with your data from `AbstractFlexibleItems` and others.
- Create your adapter item with [IHolder](https://github.com/davideas/FlexibleAdapter/wiki/5.x-%7C-Item-Interfaces#iholder) and set your data item.

You have to pass the most common class to the FlexibleAdapter and eventual cast it to the expected specific item when you call `getItem(pos)`.
``` java
// If you have many view type you will have to cast to your expected specific item
FlexibleAdapter<YourCommonAbstractClass> adapter = new FlexibleAdapter<>(myItems);

// If you have only one view type you can avoid cast items because it is already of our type.
FlexibleAdapter<YourItemClass> adapter = new FlexibleAdapter<>(myItems);
```

**Comment by ceddyb** [comment]
I done made some casting of my class, but it took me like 2 to 3 builds to figure out what was happening. 

Awesome lib man!

**Comment by davideas** [comment]
The library is now quite big in terms of functionality, so the initialization has its complexity as well, but with Wiki, demo and javaDoc, it becomes easier.
