### ISSUE TITLE
Build problems

### ISSUE THREAD

**Issue by pavelkryl** [davideas/FlexibleAdapter#386]
Hello I am following:

https://github.com/davideas/FlexibleAdapter#setup

and I am still unable to build my project. 

build.gradle:

repositories {
    jcenter()
    maven { url 'https://maven.fabric.io/public' }
}

dependencies {
    ....
    // flexible adapter
    compile 'eu.davidea:flexible-adapter:5.0.0-rc1'
    compile 'eu.davidea:flexible-adapter-databinding:1.0.0-b1'
    .....
}

and it does NOT work. It's driving me crazy. The error message I am getting is:

Error:(95, 13) Failed to resolve: eu.davidea:flexible-adapter-databinding:1.0.0-b1

Seems that eu.davidea:flexible-adapter-databinding:1.0.0-b1 is not published in jcenter!

**Comment by davideas** [comment]
@pavelkryl, thank you for the message, actually I missed to request the pubblication in JCenter too, I did it now. Temporary, you can use `maven { url "http://dl.bintray.com/davideas/maven" }`.

But probably there's another issue of undefined version. Need to investigate.

**Comment by plastus** [comment]
I was having the same issue but even after changing the repository URL I still receive "failed to resolve: com.android.support:design:25.4.0"

**Comment by davideas** [comment]
For that you must add the new google maven repo url. Read support realease note.

**Comment by plastus** [comment]
@davideas Thank you; I've never run into that before so I guess it's a new change as of 25.4.0? I added the following line to my gradle file:

`compile 'eu.davidea:flexible-adapter-databinding:1.0.0-b1'`

but I'm receiving the following:

`Failed to resolve: FlexibleAdapter:flexible-adapter:unspecified`

I don't mean to sidetrack this discussion; thank you again for your help!

**Comment by davideas** [comment]
I should try to put `provided` and publish it again. Now I'm out, I will do it by tomorrow.

**Comment by davideas** [comment]
OK, I do not know why Gradle doesn't like, but the following line will make it compile successfully:
```
compile 'eu.davidea:flexible-adapter-databinding:1.0.0-b1@aar'
```

And for the moment, until it is not published to jCenter, add this repository as well:
```
maven { url "http://dl.bintray.com/davideas/maven" }
```

**Comment by davideas** [comment]
It is published.
