### ISSUE TITLE
Compile with design support library 25.4.0

### ISSUE THREAD

**Issue by kamisaberi** [davideas/FlexibleAdapter#391]
hi. i have problem with 25.4.0 design library with rc2 version. help please
in rc2 version said this problem fixed but i have this problem now 

Error:Failed to resolve: com.android.support:design:25.4.0
<a href="install.m2.repo">Install Repository and sync project</a><br><a href="openFile:F:/PROJECTS/ME/NarijApp/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by kamisaberi** [comment]
hi. i have problem with 25.4.0 design library with rc2 version. help please

**Comment by davideas** [comment]
@kamisaberi, with 25.4.0 Android team changed the way to load its support libraries dependencies.
For that you must add the new Google maven repo url. Read [support library release note](https://developer.android.com/topic/libraries/support-library/setup.html).

I will add this note to FlexibleAdapter release note and [Migrations](https://github.com/davideas/FlexibleAdapter/wiki/Migrations) as well.
Thanks.

**Comment by kamisaberi** [comment]
android studio and gradle version requirement?
