### ISSUE TITLE
5.0.0-rc2  StickyHeaderHelper BUG

### ISSUE THREAD

**Issue by pyt8756** [davideas/FlexibleAdapter#395]
StickyHeaderHelper  89 line ，
`frameLayout.setLayoutParams(new ViewGroup.LayoutParams(width, height));`
Lead to 261 line error ClassCastException，
`ViewGroup.MarginLayoutParams params = (ViewGroup.MarginLayoutParams) mStickyHolderLayout.getLayoutParams();`
No mistake after the change 89 line
`frameLayout.setLayoutParams(new ViewGroup.MarginLayoutParams(width, height));`

**Comment by davideas** [comment]
Thanks @pyt8756, it will be available from next Snapshot and in RC3 release as well.
