### ISSUE TITLE
Sticky headers when recyclerview is nested in android.support.v4.widget.NestedScrollView?

### ISSUE THREAD

**Issue by i-schuetz** [davideas/FlexibleAdapter#398]
A first test shows it's not working, but I may be missing something. I called `setStickyHeaders(true)`. 

Everything works as expected except that the headers are not sticky.

Edit:
I just found this issue: https://github.com/davideas/FlexibleAdapter/issues/164
The reason I need NestedScrollView is because I have multiple recyclerviews and some other views and need a special coordinated scrolling/animation behaviour.

Is there a hint to get the sticky headers working other than "you have to play with layouts"...? (I have no idea how to "play" atm...).

**Comment by davideas** [comment]
@i-schuetz, I didn't work with NestedScrollView so I can't really help you, just a hint, the sticky layout should stay in the same father layout, so the sticky layout is always on top of RV. As I shown in the wiki, a FrameLayout that wraps the RV is necessary. See migrations wiki page as well for latest changes.
