### ISSUE TITLE
How to get an item position by his hashCode()

### ISSUE THREAD

**Issue by jrcacd** [davideas/FlexibleAdapter#399]

**Comment by davideas** [comment]
Java works with `equals` in List collections and with `hashCode in Hash collections.
When you have unique IDs the item is automatically picked up when `getGlobalPositionOf(item)` is called.
If you have only hashCode you can create an empty object providing only the string id, which will provide also the hashCode of that id.

**Comment by jrcacd** [comment]
val notesAdapter = FlexibleAdapter(ArrayList<IFlexible<*>>())

Now, how do I. find an item by his hashcode?

FlexibleAdapter only has:
- getItem(int position)
- getItemId(int position)
- getCardinalPositionOf(IFlexible item)

Is there some;
- getItem(int hashcode) ?

**Comment by davideas** [comment]
Hi @jrcacd, if you have only the hash, which i don't believe, the only way, in Java7, is to scan the list and compare the item.hashCode() == your hashCode. Then you have your item.
But, if you have the ID and is unique, the best way is also to scan the entire list until you find it or you use the method I described in my first answer.

**Comment by jrcacd** [comment]
OK. answered. 
Thanks,

**Comment by davideas** [comment]
In Java8 you can use streams with filter, which will simplify and speed up a lot the search.
