### ISSUE TITLE
Force Close on flexible-adapter-v5.0.0-rc2.apk

### ISSUE THREAD

**Issue by henriquenfaria** [davideas/FlexibleAdapter#402]
The flexible-adapter-v5.0.0-rc2.apk app attached to the v5.0.0-rc2 release is not opening.
The app force closes just after opened. 
Reproduced on a Galaxy S8 (Android 7.0). The flexible-adapter-v5.0.0-rc1.apk appworks correctly in this same device.

Find below the FC stack trace:

07-04 07:54:48.240 31801 31801 E AndroidRuntime: FATAL EXCEPTION: main
07-04 07:54:48.240 31801 31801 E AndroidRuntime: Process: eu.davidea.samples.flexibleadapter, PID: 31801
07-04 07:54:48.240 31801 31801 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{eu.davidea.samples.flexibleadapter/eu.davidea.samples.flexibleadapter.SplashActivity}: java.lang.ClassNotFoundException: Didn't find class "eu.davidea.samples.flexibleadapter.SplashActivity" on path: DexPathList[[zip file "/data/app/eu.davidea.samples.flexibleadapter-2/base.apk"],nativeLibraryDirectories=[/data/app/eu.davidea.samples.flexibleadapter-2/lib/arm64, /system/lib64, /vendor/lib64]]
07-04 07:54:48.240 31801 31801 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2849)
07-04 07:54:48.240 31801 31801 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3018)
07-04 07:54:48.240 31801 31801 E AndroidRuntime: 	at android.app.ActivityThread.-wrap14(ActivityThread.java)
07-04 07:54:48.240 31801 31801 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1653)
07-04 07:54:48.240 31801 31801 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-04 07:54:48.240 31801 31801 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
07-04 07:54:48.240 31801 31801 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6724)
07-04 07:54:48.240 31801 31801 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-04 07:54:48.240 31801 31801 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
07-04 07:54:48.240 31801 31801 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
07-04 07:54:48.240 31801 31801 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "eu.davidea.samples.flexibleadapter.SplashActivity" on path: DexPathList[[zip file "/data/app/eu.davidea.samples.flexibleadapter-2/base.apk"],nativeLibraryDirectories=[/data/app/eu.davidea.samples.flexibleadapter-2/lib/arm64, /system/lib64, /vendor/lib64]]
07-04 07:54:48.240 31801 31801 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
07-04 07:54:48.240 31801 31801 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
07-04 07:54:48.240 31801 31801 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
07-04 07:54:48.240 31801 31801 E AndroidRuntime: 	at android.app.Instrumentation.newActivity(Instrumentation.java:1086)
07-04 07:54:48.240 31801 31801 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2839)
07-04 07:54:48.240 31801 31801 E AndroidRuntime: 	... 9 more

**Comment by davideas** [comment]
@henriquenfaria thanks! I analyzed the apk package, indeed it was missing the app :cry: I rebuilt the app now. Can you please uninstall the rc1 and install the rc2?

**Comment by henriquenfaria** [comment]
@davideas It's properly working now! :)
Thank you for such a great lib.

**Comment by davideas** [comment]
@henriquenfaria good. Thank you to have chosen it.
