### ISSUE TITLE
Unable add more than one element in RecyclerView

### ISSUE THREAD

**Issue by rusxakep** [davideas/FlexibleAdapter#403]
Hi David,

I can't understand "base logic" of FlexibleAdapter for add more than one element in recyclerview (with cardview):

Add item 1 and 2, but createViewHolder and bindViewHolder call once and my recycler view contain only one element:

Log:
I/FlexibleAdapter: Running version 5.0.0-rc2 built on 2017.06.10
I/FlexibleAdapter: Initialized with StableIds=true
D/FlexibleAdapter: addItems on position=0 itemCount=1
D/FlexibleAdapter: addItems on position=1 itemCount=1
I/FlexibleAdapter: Mapped viewType 2130968667 from ObjectItem

Source:
for (ObjectMarker objectMarker : cluster.getItems()) {
        objectAdapter.addItem(new ObjectItem(objectMarker.getClientObjectItem(), objectMarker.getClientObjectItem().getName()));
}
objectAdapter.notifyDataSetChanged();

What's wrong?

**Comment by davideas** [comment]
Hi @rusxakep, there's no strange logic to adding items.
First, did you read the documentation [Setting Up](https://github.com/davideas/FlexibleAdapter/wiki/5.x-%7C-Setting-Up)?
Then, normally you don't need to call `notifyXXX` methods anymore, unless you are in a particular case.

It could be a wrong implementation of your `equals` method in the item, because Java see it equals, so when Java search for the items the first one is always picked up and shown.

**Comment by rusxakep** [comment]
Remove any notifyXXX, thank you.

Tested now my equals implementation: 
1. new ObjectItem(new ClientObjectItem(100L, "ddd")).equals(new ObjectItem(new ClientObjectItem(100L, "ddd"))) : true
2. new ObjectItem(new ClientObjectItem(100L, "ddd")).equals(new ObjectItem(new ClientObjectItem(101L, "ddd"))) : false

What's else, I should be check?

**Comment by davideas** [comment]
@rusxakep, I have few information now, I can't see what could be your issue. 
Try to call `updateDataSet(cluster.getItems(), true)` for now.

For the rest you need to share something more, like ObjectItem, you could also debug and see what the adapter list contains after the second addItem.

**Comment by rusxakep** [comment]
ObjectAdapter contains correct mItems (ArrayList with 2 ObjectItem's) after next addItem ...

Call stacktrace (1,2,3 is unique id):
new Adapter(xxx)
Adapter.addItem(new ObjectItem(1))
Adapter.addItem(new ObjectItem(2))
Adapter.addItem(new ObjectItem(3))
ObjectItem.hashCode (1)
ObjectItem.createViewHolder(1)
ObjectItem.hashCode (1) <---- ??
ObjectItem.bindViewHolder(1)

That's all.

Where is 2 and 3 calls, I don't know.

**Comment by rusxakep** [comment]
updateDataSet(cluster.getItems(), true) worked more correct, I testing now and edit message later.

**Comment by rusxakep** [comment]
Call stacktrace with updateDataSet:

new Adapter(empty item list)
....
updateDataSet(items, true)
ObjectItem.hashCode (1)
ObjectItem.hashCode (2)
ObjectItem.hashCode (3)
ObjectItem.hashCode (1)
ObjectItem.hashCode (2)
ObjectItem.hashCode (3)
ObjectItem.hashCode (1)
ObjectItem.hashCode (2)
ObjectItem.hashCode (3)
ObjectItem.createViewHolder(1)
ObjectItem.hashCode (1)
ObjectItem.bindViewHolder(1)

**Comment by davideas** [comment]
Sorry @rusxakep, I do not understand your log, please share adapter logs, and `equals` and `hashCode` methods.

**Comment by rusxakep** [comment]
Ok @davideas, I debug flexible adapter by myself and edit this post after that.

Thank for reply

**Comment by rusxakep** [comment]
Simply test: 

[](https://github.com/rusxakep/FlexAdapterBug)

**Comment by davideas** [comment]
@rusxakep, LOL!! Please, scroll up the bottom sheet :bulb:
You are sorry, don't worry.

**Comment by rusxakep** [comment]
Yep, you are right.
