### ISSUE TITLE
Same header for different sections

### ISSUE THREAD

**Issue by preyesm** [davideas/FlexibleAdapter#406]
hi @davideas, I have a small query. I have two different kinds of section, but i also have a list with merged content. I need to show same header for section from both the lists. i am currently maintaining a map of headeritems and i keep appending the map after i create a section.

Event after using the same instance of the header item from the map, the lists are shown one after the other, with headers being replicated. Please let me know if there is any solution to this.

**Comment by davideas** [comment]
@preyesm, they have to be different instances and the `equals` method is complementary to each other (basically they are different objects, probably with different Id). Keep always in mind how List collection works in Java.
