### ISSUE TITLE
What else need for onClick's events?

### ISSUE THREAD

**Issue by rusxakep** [davideas/FlexibleAdapter#408]
Hello David,
I have some problem's with onClick events....

1. Created activity and implements `FlexibleAdapter.OnItemClickListener`, `FlexibleAdapter.OnItemLongClickListener`.

2. Created adapter like this:
``` java
public class Adapter extends FlexibleAdapter<AbstractFlexibleItem> {
    public Adapter(@Nullable List<AbstractFlexibleItem> items, @Nullable Object listeners) {
        super(items, listeners, true);
    }
}
```
3. Created simple Item object extending `AbstractFlexibleItem<Item.ViewHolder> ...`
4. Created instance of this adapter with empty items list like: `new Adapter(emptylist, this);`
4. Added some items

Try to fire onClick events, tapping items on the screen... Nothing :(

What's wrong?

Thank for help.

**Comment by davideas** [comment]
Hi @rusxakep, did you extend the ViewHolder from `FlexibleViewHolder`? What do you expect it happens in your implementation of the callback?
Also, remember that you have logs, to see if the event is fired in the FlexibleViewHolder you need VERBOSE level.

**Comment by rusxakep** [comment]
Sure, extend.

static class ViewHolder extends FlexibleViewHolder {
...
}

I expect Log.v("onClick"); :-)

Yes, log  with verbose:

I/FlexibleAdapter: Running version 5.0.0-rc2 built on 2017.07.11
I/FlexibleAdapter: Initialized with StableIds=true
I/FlexibleAdapter: Setting listener class Activity as:
I/FlexibleAdapter: - OnItemClickListener
I/FlexibleAdapter: - OnItemLongClickListener
V/FlexibleAdapter: Attached Adapter to RecyclerView
V/FlexibleAdapter: addItem delegates addition to addItems!
D/FlexibleAdapter: addItems on position=0 itemCount=1
V/FlexibleAdapter: addItem delegates addition to addItems!
D/FlexibleAdapter: addItems on position=1 itemCount=1
V/FlexibleAdapter: addItem delegates addition to addItems!
D/FlexibleAdapter: addItems on position=2 itemCount=1
I/FlexibleAdapter: Mapped viewType 2130968663 from TokenItem
V/FlexibleAdapter: onViewBound    Holder=ViewHolder position=0 itemId=4999
V/FlexibleAdapter: onViewBound    Holder=ViewHolder position=1 itemId=5220
V/FlexibleAdapter: onViewBound    Holder=ViewHolder position=2 itemId=6524

**Comment by davideas** [comment]
Ok @rusxakep, then the only reason I can see from there is the check for enabled state. If it isn't, you should debug and see why the callback is not called.

**Comment by rusxakep** [comment]
Items in default state, I do not use setEnabled() method...

Ok. If I made that's all correct, I'll be debug this. Thank you.

**Comment by rusxakep** [comment]
Hmm... Add onClick and onLongClick at ViewHolder item class and working only LongClick.

OnClick still don't fired. 

@davideas, where is problem?

**Comment by davideas** [comment]
@rusxakep, can you show me the ViewHolder and the Item classes?

**Comment by rusxakep** [comment]
I found my mistake. In onBindViewHolder:

        holder.cardview.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
            }
        });

Thank for fast answers. Close issue.
