### ISSUE TITLE
Sticky Headers clickable

### ISSUE THREAD

**Issue by davideas** [davideas/FlexibleAdapter#41]
Once a header is drawn over others elements, it should be clickable.
This is not a bug due to the different representation/implementation of the view in the RecyclerView.

**Comment by davideas** [comment]
I've analyzed such improvement.
To have called the the click listener on the item, **it is impossible** to achieve it since the `StickyHeaderDecoration` simply draws the header over the items and the header view is not anymore a view... :-1: 
However, I'm able to intercept the touch event and avoid the lower item to be clicked, even returning the Header item object, but we cannot use anymore the cache mechanism but also we loose the implementation of the ViewHolder and it is not properly what I wanted for the sticky header.

Probably a custom **LayoutManager** can help to make the current view "sticky", but I do not know where to start.

**Comment by 3mph4515** [comment]
Hi! Looks like an awesome multi-library. Can you provide some examples with sticky headers? And is it possible to add extra header to sticky headers in your implementation? 

Best wishes, Andrew

**Comment by davideas** [comment]
Hello @3mph4515, thanks!
What do you mean to add extra header to sticky headers?

With another person, we are trying to completely change how the current headers are displayed and handled. At the end we will be able to add a real view and so to add listeners on it. It will take some time.

**Comment by 3mph4515** [comment]
Thank you for the answer. 
I mean adding simple header view(like listview.addHeader) for padding.

**Comment by davideas** [comment]
I'm looking what Akylas is doing #44, he added headers/footer very recently. So the answer is yes, but:
I will need to review and metabolize his changes in order to merge his work, I don't know how much time it will take...

**Comment by BoldijarPaul** [comment]
Currently , is there any hack to achieve this ?

**Comment by pepitoria** [comment]
I also need to implement this behavior. Adding comment to get notifications.

Good job btw!

**Comment by davideas** [comment]
Almost done.

**Comment by pepitoria** [comment]
awesome. <3 xD

**Comment by davideas** [comment]
Already available in 5.0.0-SNAPSHOT of 2016.03.26.
This functionality will be also released from 5.0.0-b5.
