### ISSUE TITLE
cannot hide ProgressItem after load latest page 

### ISSUE THREAD

**Issue by wankey** [davideas/FlexibleAdapter#410]
``` java
  @Override protected void initializeView() {
    adapter = new ArenaFlexibleAdapter(this);

    adapter.setEndlessScrollListener(this, new ProgressItem());
    adapter.setEndlessPageSize(**20**);
    rvList.setAdapter(adapter);
    rvList.setLayoutManager(new SmoothScrollLinearLayoutManager(getContext()));
    rvList.addItemDecoration(RecycleViewDividerFactory.getDividerLine(getContext()));
  }
```

``` java
  @Override public void noMoreLoad(int i) {
  }

  @Override public void onLoadMore(int i, int i1) {
    mPresenter.loadMore();
  }

  @Override public void showData(List<? extends IFlexible> data) {
    adapter.onLoadMoreComplete(data);
  }
```

when the count of latest page is less then 20

> this.hideProgressItem(); 

won't be called. and ProgressItem was be shown 

I think the problem is when set null to progressItem( line 1274),endlessScrollEnabled will be set to false, and this.isEndlessScrollEnabled() (line 1283) will return false,then hideProgressItem won't call

**Comment by davideas** [comment]
@wankey, i see that you are not using delay so the check for `isEndlessScrollEnabled()` is skipped, it goes directly to hide the progress item:
``` java
// Check if features are enabled and the limits have been reached
if (mEndlessPageSize > 0 && newItemsSize < mEndlessPageSize || // Is feature enabled and Not enough items?
        mEndlessTargetCount > 0 && totalItemCount >= mEndlessTargetCount) { // Is feature enabled and Max limit has been reached?
    // Disable the EndlessScroll feature
    setEndlessProgressItem(null);
}
// Remove the progressItem if needed
if (delay > 0 && (newItemsSize == 0 || !isEndlessScrollEnabled())) {
    Log.v("onLoadMore     enqueued removing progressItem (%sms)", delay);
    mHandler.sendEmptyMessageDelayed(LOAD_MORE_COMPLETE, delay);
} else {
    hideProgressItem();
}
```
To double check, you can enable verbose logs and see if the log for removal is logged.

**Comment by wankey** [comment]
Thanks for your answer.

you can close this issue now.

I found that the source of rc1 which I used is different from the master.

in rc1:
` if(delay > 0L && (newItemsSize == 0 || !this.isEndlessScrollEnabled())) {
      if(DEBUG) {
        Log.v(TAG, "onLoadMore     enqueued removing progressItem (" + delay + "ms)");
      }

      this.mHandler.sendEmptyMessageDelayed(8, delay);
    } else if(this.isEndlessScrollEnabled()) {
      this.hideProgressItem();
    }`

in master:
`if (delay > 0 && (newItemsSize == 0 || !isEndlessScrollEnabled())) {
    Log.v("onLoadMore     enqueued removing progressItem (%sms)", delay);
    mHandler.sendEmptyMessageDelayed(LOAD_MORE_COMPLETE, delay);
} else {
    hideProgressItem();
}`

**Comment by wankey** [comment]
i will update to rc2
