### ISSUE TITLE
updateDataSet with animation very slow when header is sticking

### ISSUE THREAD

**Issue by allenchen1154** [davideas/FlexibleAdapter#413]
Library version: 5.0.0-RC1
Android version: Android 8.0.0
Hardware: Emulator

When a sticky header is being stuck to the top of the `RecyclerView`, calls to updateDataSet() with the `animate` parameter as `true` are very slow (4-5 seconds). This issue does not occur when the header is not being stuck to the top.

**Comment by davideas** [comment]
@allenchen1154, I execute the `updateDataSet` in Section and Headers example and current version (RC2 and Snapshot) in master branch. I do not have any lag on Android 8.0.
Also, it has no sense to test it against RC1 for me. Please update the library.

**Comment by davideas** [comment]
If you don't have any update, I will close this issue.
