### ISSUE TITLE
can i have endless recyclerview and  sticky header feature in one recyclerview

### ISSUE THREAD

**Issue by surindersinghbindra** [davideas/FlexibleAdapter#415]
can i have endless recyclerview and  sticky header feature in one recyclerview

**Comment by davideas** [comment]
@surindersinghbindra, yes, both features are provided by this Adapter.

**Comment by surindersinghbindra** [comment]
i want to add this feature on the same RecyclerView that can support Endless and Sticky header simultaneously.  Is that possible with the help of **Great Library FlexibleAdapter**
