### ISSUE TITLE
Items in multiple sections

### ISSUE THREAD

**Issue by de-Stan** [davideas/FlexibleAdapter#418]
Hello,
I have implemented a simple list with sticky headers without any problems. Our requirement now is that an item can be in multiple sections.
An item contains an Array which holds the names or ID's of the groups (headers) it belongs to. Imagine something simple as ["Header1", "Header2"].

Would this be possible to implement with FlexibleAdapter?
My main concern is how would we implement the equals method so it can return all headers from the list and how do we decide which one these names to pass to viewholder's text (of the header item).

Thank you.

**Comment by davideas** [comment]
@de-Stan, we are talking about the same item instance displayed twice (or more) in the list. This is simply impossible to pick up the correct item position if the equals are the same.
You need a discriminator to put in the `equals`, `hashCode` and in `getHeader`. Simpler to create a new instance with the new header, directly.

Why you would keep the same instance?
The adapter items should be intended as objects for presentation level, while you have a business entity at data layer.

**Comment by de-Stan** [comment]
@davideas yes the item would be shown in the list twice, or more times depending on how many groups it belongs to. 

> Simpler to create a new instance with the new header, directly.

So you mean to create a copy of the item with the only difference the Header, if i can understand it correct? Bad or good it's a requirement.

**Comment by davideas** [comment]
@de-Stan, I think you don't have so much options if that is the information to display. You need to organize the list in the way that is usable technically speaking too.

It might be in the future, you will want also switch how you display the list, for instance: only items and tags inside for headers (1 instance of this item) OR list of items grouped by headers (more instance of this item) as you want to do now.

**Comment by de-Stan** [comment]
Thanks @davideas i just wanted to discuss it first and find the best solution before i start the implementation.
