### ISSUE TITLE
ItemDecoration animation appears underneath other items in ExpandableSections

### ISSUE THREAD

**Issue by samcgarry** [davideas/FlexibleAdapter#419]
Hi,
I looked at the previous issues but couldn't find anything that quite addresses this problem.

In the demo app, if I change the item decoration from a custom divider to:

`mRecyclerView.addItemDecoration(new FlexibleItemDecoration(getActivity()).withDefaultDivider());
`

During the animation of the Expandable section the divider appears underneath the other items - i.e. it is rendered before the sub items appear or fade in. I tried with various combinations of DrawOver, and I'm wondering if there is something I missed in the code.

Is there a way to add an itemdecoration such that it will appear at the end of the expansion animation?

**Comment by davideas** [comment]
@samcgarry, defaultDivider is the Android drawable 1px line displayed between the items.
Unfortunately, I do not know any way to draw these lines in conjunction of the appearing of the item. The add animation is enough fast, but yes, the lines are visible first, I have tried too now. I have fear we cannot change this behaviour.

But...
- If the lines are not so important you can skip drawing the divider as I do in the demoApp OR you can simply leave a blank space: with this new component added in the last version you can do it very easily.
- If the lines are important, I can suggest to draw the line at bottom of the item layout by hiding the bottom line when is the main item is the last in the list. You can try and see if the effect is good for you.

**Comment by samcgarry** [comment]
Thanks for the feedback. I think I've managed to get the effect I wanted using the approach you suggested by adding a line at the bottom of the item/subitem layout.
