### ISSUE TITLE
Bug: demo is weird when searching

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [davideas/FlexibleAdapter#42]
1. The top-left corner has a "..." button which does nothing
2. Pressing the X button on the right closes the search, instead of just clearing the query
3. pressing the back button (of the nav buttons) doesn't close the search, but instead it closes the activity.

**Comment by davideas** [comment]
HI, thanks to check the demo app, actually I agree only for the point 3.
On my phone and on the virtual device, the first 2 points do something, which version of Android have you tried?

**Comment by AndroidDeveloperLB** [comment]
What do you mean they do something?
There shouldn't be a "..." button on the top-left corner. This place it used to close the search mode (collapse the search) and go to the normal mode instead , where the search becomes an action item.
On the top right, the X button should only clear the text.  

That's how it works on all apps...

Here's how it looks like (tested on HTC One M8 with Android 5.0.2 ) :

![device-2016-02-24-094436](https://cloud.githubusercontent.com/assets/5357526/13278754/8c0e5be4-dadb-11e5-87e9-079672d0c02e.png)

On Nexus 5 with Android 6.0.1 and on SGS4 with custom rom of Android 5.1.1, the "..." button is invisible, yet there is nothing there. And still the X button  on the right closes the search instead of only resetting the text:

![device-2016-02-24-094817](https://cloud.githubusercontent.com/assets/5357526/13278808/eb58a38e-dadb-11e5-90ff-d74bd29d1364.png)

**Comment by davideas** [comment]
Oh well, that was strange, I said "was" because, I've reviewed the demo for the new development, it is available here https://github.com/davideas/FlexibleAdapter/releases/download/5.0.0-b4/flexible-adapter-v5.0.0-b4.apk.
I am not able to go back to fix the demo for 4.2.0, but probably the horizontal dots "..." will be still there on your HTC One, I do not know what they are. In true, now on the new version, there are the 3 vertical dots on the top right because there's the menu, before there's wasn't.

Regarding, the X button, on the emulator it works as you mean, it clears the text if any searchText is entered and it closes the searchView when there's no searchText. I have no idea how it works on others phones.

**Comment by AndroidDeveloperLB** [comment]
About the "...", instead of it there should be a button that really closes the search.
About the X button, it isn't supposed to close the search. Try it on any Google app you know, for example the contacts app, and you will see. 

About the control of it, actually you do have, and I think you've customized it. The reason is that I have an app that has the search menu (here: https://play.google.com/store/apps/details?id=com.lb.app_manager ) , and I didn't customize it, and the X button only appear when the text isn't empty anyway, automatically (I didn't need to change anything about it).

**Comment by davideas** [comment]
I tried the "search use case" in Contacts app. I'm sure that is a custom view, while, in the default widget class `SearchView`, the implementation of the method that handles the click of the X button, is declared `private`, so we cannot have control on it, line 1171 `private void onCloseClicked()`.

There are very good search solutions in GitHub, they are starred in my page, maybe a day I will implement in the demo. For the moment it works just fine the default widget.

**Comment by AndroidDeveloperLB** [comment]
@davideas It doesn't matter. The basic one works the same, as I've written.
You can try for yourself. Create a new project, and set this as the menu:

    <item
        android:id="@+id/search"
        app:actionViewClass="android.support.v7.widget.SearchView"
        android:icon="@android:drawable/ic_menu_search"
        app:showAsAction="collapseActionView|always"
        android:title="search" />

This doesn't need any repo or third party library. Just try it. This is the default behavior. 
What you do isn't the default. There is no need to listen to anything special.

**Comment by davideas** [comment]
@AndroidDeveloperLB, the only difference was `collapseActionView`, so I have to thank you, now it works as you say. I've uploaded a new demo.
If there's nothing else related to this issue, I close it.

**Comment by AndroidDeveloperLB** [comment]
Was the "..." issue also fixed?
And, does it look now like an official new project?

**Comment by davideas** [comment]
@AndroidDeveloperLB, can you look for the 3 dots? I have only this rendering now:

![searchview](https://cloud.githubusercontent.com/assets/12213847/13390243/7e7a055a-decd-11e5-9f49-063bb07f38b9.png)

**Comment by AndroidDeveloperLB** [comment]
how can I check? I don't see any changes over the past few days:
https://github.com/davideas/FlexibleAdapter

**Comment by davideas** [comment]
@AndroidDeveloperLB , I made commits on dev, I don't touch master branch and also the old demo.
Please, try the dev branch version with the new demo app under release 5.0.0-b4.

**Comment by AndroidDeveloperLB** [comment]
please put link.

**Comment by davideas** [comment]
https://github.com/davideas/FlexibleAdapter/releases/download/5.0.0-b4/flexible-adapter-v5.0.0-b4.apk

**Comment by AndroidDeveloperLB** [comment]
seems to work fine.
