### ISSUE TITLE
set Section Background for ExpandableItem

### ISSUE THREAD

**Issue by wankey** [davideas/FlexibleAdapter#420]
Is there an easy way to set a background to ExpandableItem, then subItem be wrapped in this background.
For example, set a round corner rectangle to ExpandableItem.

**Comment by davideas** [comment]
@wankey, the library comes with some Utils, one of this is [DrawableUtils](https://github.com/davideas/FlexibleAdapter/wiki/5.x-%7C-Utils#drawableutils).

It the corners are in the Drawable xml you can assign it to the view conditionally.
