### ISSUE TITLE
How to notify change to a scrollable header?

### ISSUE THREAD

**Issue by dev-JE02** [davideas/FlexibleAdapter#421]
I have a scrollable header that has clickable views. They serve a some sort of toggle but they are not checkable image views or anything, just normal ImageViews and TextViews enclosed in a LinearLayout. I have an instance of the header inside my Fragment

I want to update the imageView when the LinearLayout enclosing them is clicked and I want it to kind of hold on to the change by means of a boolean. 

I tried calling FlexibleAdapter.updateItem(scrollableHeader) but it doesn't update the item. Even notifyItemChanged does not do anything

**Comment by dev-JE02** [comment]
I used `notifyDataSet()` and it successfully updates the state of the header. But I am still waiting if there is a better way to do this since notifyDataSet supposedly affects the whole list

**Comment by davideas** [comment]
@dev-JE02, sorry but the `updateItem(scrollableHeader)` works just fine, just verified again, it couldn't be otherwise since that item is in the list.

PS. You can modify the demoApp and test it as I did it.
