### ISSUE TITLE
Endless Scrolling both directions

### ISSUE THREAD

**Issue by samcgarry** [davideas/FlexibleAdapter#422]
Hi,

Is it possible to set up an endless scrolling feature which works in both directions? I'm looking for behaviour like this:
1) Pull down from top to trigger an asynchronous refresh of the adapter items.
2) Scroll down to view a certain number of items, then loading further items as required (e.g. a list of 200 items shows 50 initial items, then each time you scroll down you get the next 'page')

I've been able to get the pull to refresh to work but I can't see a way to implement scrolling in the opposite direction too.

**Comment by samcgarry** [comment]
I think I've found my own answer. In the demo app is a method initializeSwipeToRefresh, so I should be able to use something similar for my pull to refresh, and then use endless scroll to do the item paging.

**Comment by davideas** [comment]
@samcgarry, correct. Check the demoApp for code snippets.
