### ISSUE TITLE
ExpandableHeaderItem not taking into account mHidden parameter

### ISSUE THREAD

**Issue by LeMimit** [davideas/FlexibleAdapter#423]
Hello,

First I would like to thank you for this amazing library!

I am currently trying to use it in my project. I am using a list which is based on the FragmentExpandableSections example in the demoApp. I modified it to be able to use DataBinding.
So I am using ExpandableHeaderItem and SubItem.

In my application, it is possible to click on Subtems to change the color of the background.
I would like to filter the items of my list so it is easier to select specific items.
I got a problem on this part. Since I am using DataBinding the filtered list is autoBound. When we click on one filtered item, it is updated **BUT** all the ExpandableHeaderItem appear with no Subitems attached.

I tried to look the code. I saw all the items which are not in line with the filter constraint got mHidden set to true. Based on this observation I tried to modify the DemoApp by just setting mHidden to true for all the items when the database of the fragment is created. 

```java
public static ExpandableHeaderItem newExpandableSectionItem(int i) {
	ExpandableHeaderItem expandableItem = new ExpandableHeaderItem("EH" + i);
	expandableItem.setTitle("Expandable Header " + i);
	expandableItem.setHidden(true);
	for (int j = 1; j <= SUB_ITEMS; j++) {
		SubItem subItem = new SubItem(expandableItem.getId() + "-SB" + j);
		subItem.setTitle("Sub Item " + j);
		subItem.setHidden(true);
		//In this case the Header is the same parent: ExpandableHeaderItem instance
		subItem.setHeader(expandableItem);
		expandableItem.addSubItem(subItem);
	}
	return expandableItem;
}
```

Conclusion: All the Subitems are hidden but not the ExpandableHeaderItem which is a problem for me.

May be there are an option to solve this problem? Or Can you help me to fix this problem?

Hope this is clear. Tell me if you need more details.

Thanks a lot!

**Comment by davideas** [comment]
@LeMimit, thank you for compliments!

The hidden field is managed internally, the filter function modifies it to true/false if not found/found during the elaboration and read by others functions in order to respond correctly to the user actions.
Normally you shouldn't touch.

There are 2 ways to filter items:
- you let the Adapter doing it, internally it creates a copy of the original list and shows the filtered ones with those flags modified.
- you ask to the database to give you a filtered list from it, so you reset the current list and provide the new filtered list from db. Here you can also open a new Search page to show the filtered items.
Normally, you choose this approach if the list is not totally loaded, it happens when the Adapter cannot hold all the items.

**Comment by LeMimit** [comment]
@davideas Thank for the answer.

I am using the first way: I let the adapter doing the sorted list.
I think you didn't get my point. This is my fault, I will try to explain my problem step by step:

- I am using dataBinding to manage items in my list. I am using an internal attribute in SubItem to choose the color of the background.
- I am using `mAdapter.filterItems(200);` to filter the items. It is working good. 
  Let take an example: 
    - I got 5 ExpandableHeaderItem with 5 SubItems => With the filter constraint I got now the section 0 and 1 with 2 SubItems.
- When I click on one item let's take the first one of the section 0. I am changing the attribute of this item. Then with the Databinding the item is updated and the background color changes. All this treatment with the filtered list.
- Then comes the strange behavior when the list is updated with `public void updateDataSet(List<T> items, boolean animate) ` with the DataBinding. The first item of the section 0 is updated with the new background color BUT all the other ExpandableHeaderItem appear with no SubItem.
  - The sortered list becomes then section 0 and section 1 with 2 SubItems and the header of section 2, 3 and 4 with no SubItems.

I don't understand why I got the header of the other sections in the filtered list after the update since there are no item found in it ( mHidden = true).

**Comment by davideas** [comment]
@LeMimit, it looks like a complicated situation you entered. But maybe is very easy to resolve:
I didn't read you cleared the search text, you update with the search inside? can you try to clear it?
