### ISSUE TITLE
Shallow copy instead of Deep copy

### ISSUE THREAD

**Issue by LeMimit** [davideas/FlexibleAdapter#424]
Hello,

Sorry to open two posts at the same time :/ But I think I found a problem in the new internal filter process.

Since 5.0.0-rc2 no need to provide a copy of the list, FlexibleAdapter is doing it for us.
However there are a problem in the copy. A Shallow copy is performed instead of a Deep copy.

```java
public void filterItems(@IntRange(from = 0) long delay) {
    if (mOriginalList == null) mOriginalList = mItems;
    filterItems(mOriginalList, delay);
}
```
So for example with the following code:
```java
private synchronized void executeNotifications(Payload payloadChange) {
    Log.i("Performing %s notifications", mNotifications.size());
    mItems = mTempItems; //Update mItems in the UI Thread
```
Will also change the value of the objects stored in `mOriginalList `. So for example I have the following problem: 
-  If a `ExpandableHeaderItem` was collapsed before filter process, its status (mExpanded value) isn't restored well if it is expanded during the filter process. Indeed, when we set mExpanded to true in mList to change the UI it also change the value in mOriginalList. So we don't restore the good value after the filter process.

Thanks

**Comment by davideas** [comment]
@LeMimit, expanded status are saved and restored after search is cleared out.
Original list and filtered list represent different status of the information, so it's ok to do a shallow copy as you name it.
Deep copy is not in the requirements, it will make the filter much slower too.
