### ISSUE TITLE
I can't swipe after fragment transaction

### ISSUE THREAD

**Issue by thelong1EU** [davideas/FlexibleAdapter#426]
I think that I forgot something. When I return to the previous fragment I can't swipe anymore. Any idea?

![ezgif-1-43ef7f8f50](https://user-images.githubusercontent.com/9283414/29600810-cc41b1ee-87e0-11e7-9afa-0d05dd703c62.gif)

**Comment by thelong1EU** [comment]
This is the log that I get:
`08-23 10:28:01.565 8055-8055/eu.long1.jwnotes I/SelectableAdapter: Mode MULTI enabled
08-23 10:28:01.572 8055-8055/eu.long1.jwnotes D/ActionModeHelper: ActionMode is active!
08-23 10:28:01.572 8055-8055/eu.long1.jwnotes I/SelectableAdapter: Mode MULTI enabled
08-23 10:28:01.573 8055-8055/eu.long1.jwnotes I/FlexibleAdapter: Set swipeEnabled=false
08-23 10:28:01.583 8055-8055/eu.long1.jwnotes V/SelectableAdapter: toggleSelection added on position 0, current [0]
08-23 10:28:18.509 8055-8055/eu.long1.jwnotes D/ActionModeHelper: ActionMode is about to be destroyed! New mode will be 0
08-23 10:28:18.517 8055-8055/eu.long1.jwnotes I/SelectableAdapter: Mode IDLE enabled
08-23 10:28:18.518 8055-8055/eu.long1.jwnotes D/SelectableAdapter: clearSelection [0]
08-23 10:28:18.521 8055-8055/eu.long1.jwnotes I/FlexibleAdapter: Set swipeEnabled=true`

**Comment by davideas** [comment]
@thelong1EU, I see, thanks for sharing.

I tried in the demoApp by simply enabling/disabling the swiping feature when disabling/enabling ActionMode: everything seems to work fine :+1:  I can add this feature as a property settings for ActionModeHelper. I will create a new issue for this new feature.

Now, I do not know if changing fragment has an impact on the current status of the Adapter. In theory the `ItemTouchHelperCallback` instance is still the same in memory and the swipeable property is passed to it. But, it seems that it is still `false`, that's why you can't swipe.
Also, from your log I see something strange: 2 logs that enable mode `MULTI`, something is not ok there. Are you enabling action mode twice? Are you using `ActionModeHelper`? can you show those points?

**Comment by thelong1EU** [comment]
Yes! I was doing this:
```
adapter.mode = MULTI
mActionModeHelper.withDefaultMode(MULTI)
```

But still the swipe is not working. I'm navigating away from the adapter using swipe or click on the ActionMode icon. I'm going back using onBackPressed()

**Comment by thelong1EU** [comment]
I've tried to enter and leave AnctionMode without changing the fragment and this is the result:

```
08-23 13:03:26.620 3762-3762/eu.long1.jwnotes D/ActionModeHelper: ActionMode is active!
08-23 13:03:26.621 3762-3762/eu.long1.jwnotes I/SelectableAdapter: Mode MULTI enabled
08-23 13:03:26.621 3762-3762/eu.long1.jwnotes I/FlexibleAdapter: Set swipeEnabled=false
08-23 13:03:26.630 3762-3762/eu.long1.jwnotes V/SelectableAdapter: toggleSelection added on position 0, current [0]
08-23 13:03:36.271 3762-3762/eu.long1.jwnotes V/SelectableAdapter: toggleSelection added on position 2, current [0, 2]
08-23 13:03:36.879 3762-3762/eu.long1.jwnotes V/FlexibleViewHolder: onClick on position 3 mode=2
08-23 13:03:36.879 3762-3762/eu.long1.jwnotes V/SelectableAdapter: toggleSelection added on position 3, current [0, 2, 3]
08-23 13:03:37.348 3762-3762/eu.long1.jwnotes V/FlexibleViewHolder: onClick on position 4 mode=2
08-23 13:03:37.348 3762-3762/eu.long1.jwnotes V/SelectableAdapter: toggleSelection added on position 4, current [0, 2, 3, 4]
08-23 13:03:41.652 3762-3762/eu.long1.jwnotes D/ActionModeHelper: ActionMode is about to be destroyed! New mode will be 0
08-23 13:03:41.653 3762-3762/eu.long1.jwnotes I/SelectableAdapter: Mode IDLE enabled
08-23 13:03:41.654 3762-3762/eu.long1.jwnotes D/SelectableAdapter: clearSelection [0, 2, 3, 4]
08-23 13:03:41.659 3762-3762/eu.long1.jwnotes I/FlexibleAdapter: Set swipeEnabled=true
```

It sees like the problems is with the fragment transaction.

**Comment by davideas** [comment]
The default mode property settings normally is dedicated for `IDLE` and `SINGLE`. The mode `MULTI` is normally a temporary state. You can activate `MULTI` at start, but I see it as a permanent state where you can only select and never disable the mode `MULTI`.

**Comment by thelong1EU** [comment]
Can you read Kotlin?

**Comment by davideas** [comment]
@thelong1EU, I didn't study it, but it is very well readable because Java is similar and it is similar to Typescript too!

**Comment by thelong1EU** [comment]
I was thinking if you can take a look. It's driving me crazy. I've created this gist if you would.
https://gist.github.com/thelong1EU/db237146e93e0d8d0bf7cf327134c2df

**Comment by davideas** [comment]
@thelong1EU, so you have 2 layouts from the gif you posted, then I see 1 adapter and 1 fragment, with default mode MULTI (it means, when you finish ActionMode, the mode is `MULTI` (again)... even a simple click will trigger the item selection through ActionModeHelper).
Then, I don't know what ShareTalksEvent does when you invoke it, has relevant code related to ActionMode and that adapter instance?

I see that you implemented your own undo feature, FlexibleAdapter comes with it too with `UndoHelper`. I don't know if is easy to use, I still have to write documentation...

**Comment by thelong1EU** [comment]
Thanks for your time.
ShareTalksEvent just changes the fragment. The second screen fragment doesn't use FlexibleAdapter, just the MainFragment.

Ok so I deleted the startActionMode(), but still the same. I think that I will recreate the MainFragment and not pop it from the backStack.

**Comment by thelong1EU** [comment]
So it seems that it has nothing to do with the ActionMode, rather it is about FragmentTransactions. Still I didn't find the cause. When I go away from MainFragment replacing it with another and go back reverting the transaction the swipe doesn't work.

**Comment by davideas** [comment]
@thelong1EU, if you didn't resolve yet, please use 2 RecyclerView and 2 adapters, in the end they show different set of items one for each fragment. I think this should solve your case.

**Comment by thelong1EU** [comment]
I am using two 2 RecyclerViews and 2 Adapters. so I think that this is not it. If you want you can close the issue. I will try to solve it by myself.

**Comment by thelong1EU** [comment]
Did you ever seen anything like this?
D/TalkAdapter: onAttachedToRecyclerView
E/RecyclerView: No adapter attached; skipping layout

**Comment by thelong1EU** [comment]
It's from Kotter Knife :)))

**Comment by davideas** [comment]
@thelong1EU, that log is strange, since the attached callback is to indeed attach the Adapter to the RV.
Do you call super in that method?

**Comment by davideas** [comment]
Oh finally, bravo!

**Comment by thelong1EU** [comment]
I've migrated my whole base code to Kotlin and I'm still learning, so.. You should try it.
