### ISSUE TITLE
FlexibleAdapter assumes that different item types will not use the same layout resource ID

### ISSUE THREAD

**Issue by sandeep-voxer** [davideas/FlexibleAdapter#430]
There are some situations where we might want to use the same layout and thus the same layout resource ID for different item types. FlexibleAdapter assumes that multiple items will not use the same layout resource ID, which makes it inflexible ironically. Is there any chance you could fix this before releasing 5.0?

**Comment by davideas** [comment]
@sandeep-voxer, in which situation you might want same layout for different item types, so same ViewHolder and same type of info displayed?

**Comment by sandeep-voxer** [comment]
Think of an SMS app for example, where you can have text and picture messages. 

For any incoming message, the overall layout used is the same - i.e sender's profile picture, name, timestamp etc. are all fixed fields. The only thing that changes is the message content - so you could have the Views for both text and image in the message bubble, but as ViewStubs so that they are not rendered unnecessarily.

And based on the message type, you can expand either. For picture messages you expand only the image message container, and for text messages you expand only the text message container.

With FlexbileAdapter's current code, the text message and image message views are considered the same if the same layout resource is used for both, so the binding code must always make sure to hide the other message types' Views and only make sure it's own Views are visible. This requires a lot of layout changes in the binding stage, which will impact scroll performance (since the app is constantly changing layout and size of several views in each message cell while scrolling, instead of reusing as is, which is the whole purpose of recycling and ViewHolders).

Also, in onCreateViewHolder(), findView() has to be performed for every single message type View even if they will never be used.

**Comment by sandeep-voxer** [comment]
One easy way to fix this, is to create a new method (e.g) getItemViewType() in IFlexible, and then have a default implementation in AbstractFlexibleItem that returns the layout resource ID. And in FlexibleAdapter.getItemViewType(), return item.getItemViewType(), and in mapViewTypeFrom(), use item.getItemViewType() as the key in the map.

This way the current behaviour is preserved as long as your custom item class extends AbstractFlexibleItem, but there's a small bit of extra work if your custom item class implements IFlexible directly. It is a change in the interface, but not a big one.

**Comment by davideas** [comment]
@sandeep-voxer, thank you for your explanation. If you really desire to contribute you can create a pull request. Otherwise I will try your solution and come here once I made it. As you wish.

The `IFlexible` has already a new function for RC3 that differ from RC2, so it's not a problem to add a new one since the library is still in dev phase.
