### ISSUE TITLE
Different TAGs for each Adapter

### ISSUE THREAD

**Issue by thelong1EU** [davideas/FlexibleAdapter#431]
It will be very useful to set a tag for each adapter. This will make debugging a lot easier when you have multiple adapters.

**Comment by davideas** [comment]
@thelong1EU, I think this is possible in somehow, now the Log system is custom and static, I will probably need to add new custom functions to accept dynamic _TAG_ to the Log class.

Let's keep it aside for the moment.

**Comment by thelong1EU** [comment]
In can implement it if you want and make a fully request.

**Comment by davideas** [comment]
@thelong1EU, I couldn't find another "quick" solution than this:

**Log.java**
``` java
public static void setCustomTag(@Nullable String customTag) {
    Log.customTag = customTag;
}

private static String getTag() {
    if (customTag != null) return customTag;
    StackTraceElement traceElement = new Throwable().getStackTrace()[2];
    ......
}
```

Using static `instances` and non-static `instance` fields, it continues to increase no stop, every time you create an instance (opening/closing activities). By defining a custom tag you can set it in create phase and restore/clear at destroy phase. Usage from 2nd Activity:

``` java
onCreate() {
   Log.useTag("FlexibleAdapter2");
   mAdapter = new FlexibleAdapter();
}
onDestroy() {
   // Because it's static we need to restore previous value for 1st instance
   Log.useTag(null); or Log.useTag("FlexibleAdapter1");
}
```

Another solution would be to have non-static _internal_ Logger initialized inside with the default or from a static setter before creation. Like this:

``` java
FlexibleAdapter.useTag("FlexibleAdapter2");
mAdapter = new FlexibleAdapter();
```
Anyway, the others helper classes around the Adapter won't take the custom tag!

**Comment by davideas** [comment]
@thelong1EU, I opted for a mixed solution, please see the next commit in **CustomTags** branch.
You can also see the javaDoc description of the new `Logger` class that now works in collaboration with `Log`. Now FlexibleAdapter instances can have custom tag and the tag reset is automatic.

**Comment by thelong1EU** [comment]
Perfect, thanks!
