### ISSUE TITLE
restore the single item on undo and not the list of all items

### ISSUE THREAD

**Issue by YashMaharshi** [davideas/FlexibleAdapter#434]
I am using sticky header with section , where on swipe of item display the snack bar, and call the onDeleteConfirmed after the undo-time over.
But when I keep on swiping the list item quickly within the undo-time over time, and click on the UNDO button on the Snackbar, it restore all the item
I want to restore only the last item on click of UNDO button

Kindly provide me the appropriate solution

**Comment by davideas** [comment]
@YashMaharshi, that's on purpose.
But you will resolve your use case by emptying the bin `emptyBin()` before another swipe to delete.

**Comment by YashMaharshi** [comment]
Is there any way to restore the single swipe item? instead of restore all items

**Comment by davideas** [comment]
@YashMaharshi, not as single call, but I gave you already the solution.

**Comment by YashMaharshi** [comment]
@davideas

**Comment by davideas** [comment]
@YashMaharshi, sorry, emptying the bin is not enough. You need to do also the commit of the deletion:
``` java
onDeleteConfirmed(UndoHelper.ACTION_REMOVE);
mAdapter.emptyBin();
```

However I will improve this mechanism by providing a new function in UndoHelper that will commit the previous call:
``` java
.withConsecutive(true)
```

Please temporary use the workaround I gave you now. I'm also improving and simplify the UndoHelper, I will keep this issue number as reference for new code.
