### ISSUE TITLE
Does FlexibleAdapter supports Sticky Subheaders as well ?

### ISSUE THREAD

**Issue by debjitk** [davideas/FlexibleAdapter#435]
Does FlexibleAdapter supports Sticky Headers and Subheaders as well ?

**Comment by davideas** [comment]
@debjitk, unfortunately not fully, look this way:

- Expandable (can be unclickable)
  - HeaderA for subItems
    - subItem1
    - subItem2
  - HeaderB for subItems
    - subItem3
    - subItem4

The sticky behaviour will be applied only to SubHeaders, the expandable will scroll away!
Never, tried but it should work.
