### ISSUE TITLE
How can i use Realm with FlexibleAdapter ?

### ISSUE THREAD

**Issue by debjitk** [davideas/FlexibleAdapter#436]
How can i use Realm with FlexibleAdapter ?

**Comment by davideas** [comment]
@debjitk, this is a feature requested in #166, and it cannot be resolved soon.
I saw that, the Realm team will work in the next months on the integration of Inheritance / Polymorphism. Let's see what they will bring to us.

**Comment by debjitk** [comment]
Can I extend FlexibleAdapter and use Realm inside ?

**Comment by davideas** [comment]
@debjitk, yes, you will have to provide items for FlexibleAdapter, in this case the Adapter works as any others.
