### ISSUE TITLE
Update ExpandableSubItem not work

### ISSUE THREAD

**Issue by mdtuyen** [davideas/FlexibleAdapter#441]
Hi,
I need to implement GUI for comment screen of YOUTUBE. 
The first i load comment level 1, after scroll to comment have sub comment i load sub comment add add to it.

> public class ItemComment extends AbstractItem<ItemComment.ChildViewHolder> implements IExpandable<ItemComment.ChildViewHolder, ItemSubComment>, IHeader<ItemComment.ChildViewHolder>

> public class ItemSubComment extends AbstractItem<ItemSubComment.ChildViewHolder>
>         implements ISectionable<ItemSubComment.ChildViewHolder, IHeader>, IFilterable
> 
Here is my code in ItemComment to load ItemSubComment:

```
        YoutubeApi.getSubComments(commentThread.getId(), nextPageToken, new YoutubeApi.YouTubeVideoCommentReceiver() {
            @Override
            public void onVideosCommentReceived(List<Comment> youTubeComments, String currentPageToken, String nextPageToken) {
                ItemComment.this.nextPageToken = nextPageToken;
                DatabaseService.getInstance().createSubComments(ItemComment.this, youTubeComments);
                for (Comment c: youTubeComments) {
                    ItemSubComment subItem = new ItemSubComment(c.getId(), c);
                    subItem.setHeader(ItemComment.this);
                    addSubItem(subItem);
                }
                adapter.expand(ItemComment.this, true);
                adapter.updateItem(ItemComment.this);
            }
        });
```

Howerver, after load complete adapter.updateItem(ItemComment.this) not make change.

**Comment by davideas** [comment]
@mdtuyen, it could be: item not found in the internal list, due to the `equals` method not well implemented. The function works.

**Comment by mdtuyen** [comment]
@davideas Thanks for your support,
 I coppied to ItemComment so that equals method in this class not correct.
