### ISSUE TITLE
Divider only for specific ViewTypes

### ISSUE THREAD

**Issue by chrisonline** [davideas/FlexibleAdapter#442]
I use the default divider and have section headers:
```
recyclerView.addItemDecoration(new FlexibleItemDecoration(activity).withDefaultDivider()
                .withOffset(10)
                .withBottomEdge(true)
                .withTopEdge(true)

```
But how can I draw the divider only on subitems and not the header item?
Any hints how I can do this? Or is there already a function inside the library to hide dividers on headers?

**Comment by davideas** [comment]
@chrisonline, you will be able to specify a list of the view types directly in the 2 methods for dividers:
``` java
mRecyclerView.addItemDecoration(new FlexibleItemDecoration(getActivity())
        .withDefaultDivider(
                R.layout.recycler_simple_item,
                R.layout.recycler_scrollable_expandable_item));

// OR only 1 view type.
mRecyclerView.addItemDecoration(new FlexibleItemDecoration(getActivity())
        .withDivider(R.drawable.divider, R.layout.recycler_simple_item));
```

**Note:** From RC3, the view type, optionally, can be different from the layout resource id and can be customized by the developer.
