### ISSUE TITLE
FlexibleUtils.highlightText with multi-span, and multiple text for the spans

### ISSUE THREAD

**Issue by jrcacd** [davideas/FlexibleAdapter#444]
Another question.
How do I put multiple spans in the same string, but with 2 ou more searched text?

Example

Searched text to span: need, same 
If I **need** to put 2 ou more diferent spans in the **same** string.

**Comment by davideas** [comment]
This is not possible at all, with the current function. If you want you can create a pull request for another function: `highlightWords`

**Comment by davideas** [comment]
@jrcacd, I won't implement this feature, so if you want you can contribute to this library by a new pull request.

**Comment by jrcacd** [comment]
I have created the new funcion: how can I create a pull request?

**Comment by jrcacd** [comment]
Ok, found it.
Done
