### ISSUE TITLE
Duplicate header when make Recyclerview header session with no children 

### ISSUE THREAD

**Issue by mdtuyen** [davideas/FlexibleAdapter#445]
Hi,
I make an listview as youtube comment:
Level 0 of comment as an HeaderItem (- its name is ItemComment)
Level 1 of comment as an ExpandableHeaderItem (- its name is ItemMoreSubComment)
Level 2 of comment as an SubItem(- its name is ItemMoreSubComment)
if a comment have no subcomment it only have leve0, no level 1, 2
if a comment have subcomment  it have only one level 1 and one or more level 2

This code I init item with level 0 and 1:

```
    public List<AbstractFlexibleItem> createComments(List<CommentThread> data) {
        List<AbstractFlexibleItem> mItems = new ArrayList<>();
        for (CommentThread c: data) {
            ItemComment header = new ItemComment(c.getId(), c);
            if (c.getSnippet().getTotalReplyCount() > 0){
                ItemMoreSubComment subItem = new ItemMoreSubComment(c.getId() + "more", c);
                subItem.setHeader(header);
                mItems.add(subItem);
            }else {
                mItems.add(header);
            }
        }
        return mItems;
    }
```

I see that sometime ItemComment  have dupplicate (when ItemComment have subcomment: one have subcomment and one no subcomment)

**Comment by davideas** [comment]
Can you show the equals methods?

**Comment by mdtuyen** [comment]
Hi @davideas 
Here is my equals method:
  ```
  @Override
    public boolean equals(Object inObject) {
        if (inObject instanceof ItemComment) {
            ItemComment inItem = (ItemComment) inObject;
            return this.getId().equals(inItem.getId());
        }
        return false;
    }
```

Example Recycler that I want:
- LV01
   -  LV11
       -LV21
       -LV22

But it show:

- LV01
- LV01
   -  LV11
       -LV21
       -LV22

That mean duplicate LV01

**Comment by davideas** [comment]
@mdtuyen, as per documentation you shouldn't add the HeaderItem to the list. That is done when you invoke `setDisplayHeadersAtStartUp()`.

**Comment by mdtuyen** [comment]
How do I show a header if it does not already have an item?

**Comment by davideas** [comment]
@mdtuyen, you have to insert the header with the property `hidden = false` with the headers already set as `shown` from the adapter.

**Comment by mdtuyen** [comment]
That mean with header no item I need use addSection() function ? , I need pass Adapter to createComments ?

**Comment by davideas** [comment]
@mdtuyen, I do not know your code, I only gave you some methods.

**Comment by mdtuyen** [comment]
@davideas 
At the first comment, I gave you the code I convert tata to  Holder View.

**Comment by davideas** [comment]
@mdtuyen, it seems I have to write you exactly the lines of code you need, while you can just simply try the methods exposed by Api, and the suggestions i already gave to you.
You asked _I need pass Adapter to createComments?_ boo, how can I know your code? so do whatever you need. _I do not know your code_ means: all code, not simply that routine of the first comment, you have the global vision of your use case!

**Comment by pranavlathigara** [comment]
@mdtuyen Hi,
Do you get any solution as i also faced this issue?

Thank you
