### ISSUE TITLE
Can't get Endless Scroll to work

### ISSUE THREAD

**Issue by ACK19** [davideas/FlexibleAdapter#447]
Hi,

I have followed the documentation on how to setup endless scrolling. I've been able to create and populate a View Holder. From what I understand, endless scrolling is automatic when an ```EndlessScrollListener``` is specified by ```.setEndlessScrollListener()```. All of which I have implemented or defined respectively.

```public class EventFragment extends PagingFragment implements Callback<EventList>, FlexibleAdapter.EndlessScrollListener{```

My adapter has been setup with:

`eventAdapter
.setLoadingMoreAtStartUp(true)
.setEndlessTargetCount(15)
.setEndlessScrollThreshold(1)
.setEndlessScrollListener(this, progressItem)
.setTopEndless(false)`

Making use of the exact same ```ProgressItem``` used in the demo application.

I have setup a rest API, using Square's Retrofit. The API is tested and working. My problem sets in where on getting to the bottom of the RecyclerView after fetching Page 1, ```onLoadMore()``` isn't called by the adapter when the threshold is reached.

If it's any help, my environment is Windows 10, building to an Android Marshmallow(6.0.1). 

Thanks

**Comment by ACK19** [comment]
I have been able to figure out why more items aren't loaded. The function `setEndlessPageSize()` is a bit ambiguous to me. I believe the endless page size is the count of pages calculated by `totalNumberOfItems/(number of Items per page)`... This is calculated by my API, is this assumption correct?

I have read the documentation on the method `setEndlessPageSize()`  and it said 
`Sets the limit to automatically disable the endless feature when coming items size is less than the <i>page size</i>.`

I thought it should be 
`when (item size / perpage) is less than the <i>page size </i>` , 
so I ask, is there a way to set a number of items per page on the FlexibleAdapter?

**Comment by davideas** [comment]
@ACK19, your assumption is correct, but the page size is implicit in your query. If your query returns less then requested, then no more items are there to load, and these information are an input for the adapter, that will disable the loading more or trigger another call.

The call to `onLoadMore(totalMainItems, currentPage)` is triggered by the adapter, while, when you receive the new elements, you call `onLoadMoreComplete(newItems, [delay])`.

You can enable logs and analyse your calls.

**Comment by ACK19** [comment]
When the FlexibleAdapter calls `onLoadMore(totalMainItems, currentPage)`, the parameter `currentPage`, is always one, why is that? 

What I'm trying to say is, when the threshold is reached my adapter calls onLoadMore but the `currentPage` is always one, causing my API to endlessly load Page 1 and page 1 alone from my API.. My API accepts a parameter `page`, and I tell it which page (i.e 1, 2, 3...)  which I believe is the `currentPage` parameter on the function `onLoadMore`

**Comment by davideas** [comment]
@ACK19 the target count implicitly considers that the page is only 1, because it doesn't know the page size! Your API accept pages? but those pages have fixed item count and a starting point somewhere in the code. How do you know in advances how many pages the API provides then? you normally don't know this info.

Maybe you have to review your API, check _Twitter API_ for example.
It is much simpler to say: _give me the next 20 items since this ID_: page size is 20, target count is infinite (unless you know the total) and that's it, when you receive less then 20 you reached the limit.

Both limits can be used together, but normally is the page size the most adopted.

**Comment by ACK19** [comment]
I have gone over the twitter API as you've suggested, and it seems that would be a good use case for how the EndlessScroll on the FlexibleAdapter is implemented, in my case however, the count of items has been pre-calculated, so there's a JSON object like this (in every request): 

```"_meta": {```
           ```"totalCount": 50,```
            ```"pageCount": 5,``` // total number of pages (pageCount * perPage = totalCount)
            ```"currentPage": 2,```
            ```"perPage": 10``` // number of items on each page
    ```}```

This is how I know "what page?" or "how many pages?", so if I'm correct, by the explanation you just gave, `setEndlessPageSize(pageSize)` where `pageSize` maps to `_meta.perPage`, is that right? 

I also understand why (considering twitter's API) the end is reached when the count of Items added by `onLoadMoreComplete(list, delay)` is less than `pageSize`. So is my use case a feature to implement? I work with a team and as such, have no control over the API or it's design.

**Comment by davideas** [comment]
@ACK19, I imagined that you couldn't change it.
However, _perPage_ is the page size, as I can see. In theory you should receive your page number based on the total items in the adapter.

**Comment by ACK19** [comment]
Understood, I'd find a different resolve by extending `FlexibleAdapter`. Thanks for the clarification :-)
