### ISSUE TITLE
How do you check if an item is currently being dragged?

### ISSUE THREAD

**Issue by dev-JE02** [davideas/FlexibleAdapter#449]
I want to like show some sort of view in the item itself while it is being dragged. Is there any way to know it is currently being dragged inside the model?

**Comment by davideas** [comment]
@dev-JE02, you have `OnItemMoveListener extends OnActionStateListener` with the method `onActionStateChanged()` that you can implement in your activity OR if you don't need to implement move listener you can override `onActionStateChanged()` in `FlexibleViewHolder`, just call `super()` at first line.
