### ISSUE TITLE
Section Gap Offset added in front of freshly added item of the same section

### ISSUE THREAD

**Issue by pavelkryl** [davideas/FlexibleAdapter#451]
I have an application where there are multiple sectionable items. In total I have 3 sections. These sections are preceded with a single IFLexible item (title which scrolls away, not sticky). When I add a sectionable item into the third action (after the listview is already showing), it is added with extra padding equal to section gap offset.

I have a workaround like this:

                int pos = addItemToSection(flexibleItem, flexibleItem.getHeader(), ITEM_COMPARATOR_BY_TYPE);
                // workaround flexible list bug
                int prevPos = pos - 1;
                IFlexible prevListItem = getItem(prevPos);
                if (prevListItem instanceof DlFlexibleItem) {
                    if (item.type == ((DlFlexibleItem) prevListItem).item.type) {
                        // notify about the change
                        updateItem(pos - 1, prevListItem, null);
                    }
                }

Attaching image explaining the problem.
![gap](https://user-images.githubusercontent.com/362145/30433879-f39f602e-9965-11e7-8c40-0a50b1b1ca28.png)

**Comment by davideas** [comment]
@pavelkryl, I had a similar problem when test dragging around an item with the offsets, the offset at 4 margins were kept until I execute:
``` java
// When offset between item decorations have been set, we need to invalidate them
mAdapter.invalidateItemDecorations(100L);
```

Try to all this function, since the LayoutManager seems he wants to get notified. If you know another automatic method, please tell me.
