### ISSUE TITLE
Support for Paging Library 

### ISSUE THREAD

**Issue by pkoutsovasilis** [davideas/FlexibleAdapter#452]
Thank you for this library, it really comes handy with a great set of features. I was wondering if there are any plans for implementing an adapter like the newly introduced in Android Components [Paging Library](https://developer.android.com/topic/libraries/architecture/paging.html). 

Thanks in advance
Cheers

**Comment by davideas** [comment]
@pkoutsovasilis, I can't say anything on that library **yet**, but normally the `updateDataSet` with granular notifications/animations does the job for the differences, so you can use it.
Any library of this kind, will have a place in the extensions part on top of FlexibleAdapter to maintain the same features.

When you receive new list, using `updateDataSet`, the expected list will substitute the current one!
If you want to add new items and use pagination you should use the "loadingMore" pattern I have exposed.

**Comment by pkoutsovasilis** [comment]
Thank you @davideas for you response, i surely missed out the "loadingMore" pattern, so i guess the same logic of the Paging Library is sort of already implemented
