### ISSUE TITLE
Show divider after last item

### ISSUE THREAD

**Issue by de-Stan** [davideas/FlexibleAdapter#456]
Hello,
Is there a way to show a divider after the last item?
I'm using the default divider with `withDefaultDivider()` but it's not displayed beneath the last item.

Thank you.

**Comment by davideas** [comment]
Hello @de-Stan, the last line is removed on purpose:
``` java
for (int i = 0; i < itemCount - 1; i++) {
   ...
}
```

**Comment by de-Stan** [comment]
I see got it.
Just an idea should there be an option like `withDividerAfterLastItem()` or something similar to provide such functionality?

**Comment by de-Stan** [comment]
In our current project the client asked for it. There is a recyclerview that might contain just a couple of items so it would be better (**visual only**) if the divider was there. 
It's easy for me to clone and edit or just create the item layout to contain the divider and drop the ItemDecoration altogether. 
Also an idea if you want to include it in your library for such cases.

**Comment by davideas** [comment]
Well, we can always add it as feature.

**Comment by de-Stan** [comment]
Thought I could work on it after heading back from work and sending a PR.

Thanks for implementing it.

Στις 28 Σεπ 2017 17:22, ο χρήστης Davide Steduto <notifications@github.com> έγραψε:

Closed #456<https://github.com/davideas/FlexibleAdapter/issues/456> via 70a8bcb<https://github.com/davideas/FlexibleAdapter/commit/70a8bcbb809c4fc4840085926e19624115359d68>.

**Comment by davideas** [comment]
@de-Stan, sorry I was already there to fix a small bug in another class.
