### ISSUE TITLE
How to handle if subExpandable.getSubItems() are null?

### ISSUE THREAD

**Issue by kalvish** [davideas/FlexibleAdapter#458]
https://github.com/davideas/FlexibleAdapter/blob/595aa527b9dfa235d68490ae1a36411a266af2cd/flexible-adapter/src/main/java/eu/davidea/flexibleadapter/FlexibleAdapter.java#L3971

**Comment by davideas** [comment]
@kalvish, I see, it should skip the call, but actually you will receive a bad exception, I can fix it.

**Comment by kalvish** [comment]
Thanks @davideas !!!
