### ISSUE TITLE
FlexibleItemDecoration increate space when fragment return from backstack

### ISSUE THREAD

**Issue by mdtuyen** [davideas/FlexibleAdapter#459]
Here is my config for Decoration:

```
 mRecyclerView.addItemDecoration(new FlexibleItemDecoration(mActivity.get())
                .addItemViewType(R.layout.item_chanel, 8,8,8,8)
                .withDivider(hasDivider() ? R.drawable.divider : 0)
                .withSectionGapOffset(0)
                .withDrawOver(true)
                .withEdge(true));
```
After press back to return previous Fragment, it call oncreateView again and item: **item_chanel** have margin increate.

**Comment by davideas** [comment]
@mdtuyen, I understood that the space is added to each item everytime you go back from a Fragment? well, do you add decoration multiple times? I mean, what is the code executed when the fragment is resumed?

Please, always try with some logs and at least debugging.

**Comment by davideas** [comment]
@mdtuyen, in my example, I don't use backstack and the fragment is every time recreated with a replace.
Maybe, the issue 457, could be useful to you as well?
