### ISSUE TITLE
Hide the scroll bar

### ISSUE THREAD

**Issue by thelong1EU** [davideas/FlexibleAdapter#466]
Is it possible to hide the scrollbar when using fastscroller? Like you would do with the recyclerview using android:scrollbars="none"

**Comment by davideas** [comment]
@thelong1EU, sure! Please have a look at the `FastScroller` class, there are some methods that will do the job.

**Comment by thelong1EU** [comment]
I don't seem to find one method that hide the scrollbar. I'm not referring to the dragging handler. but to this
bar = findViewById(R.id.fast_scroller_bar);

**Comment by davideas** [comment]
`fastScroller.hideScrollbar();`

**Comment by thelong1EU** [comment]
That's what I thought at first. But it doesn't disable the bar. When you use this android:scrollbars="none" on a recycler view, the scroll bar never shows.

What I did was to copy the layout in my res folder and change the color of the fast_scroller_bar item to transparent.

**Comment by davideas** [comment]
You also have the overridden `setEnabled`, read the javaDoc of that method and see the implementation.

**Comment by thelong1EU** [comment]
Thanks!
Do you know the fast_scroller_bar view? This is handled in the ScrollbarAnimator. Here you are applying the animation to both the handler and the bar. I just want to make the bar disappear. The bar has the id fast_scroller_bar in the library_fast_scroller_layout.xml file. My dirty solution was to set a transparent background to the view, because I could not remove it from the layout.

`public void hideScrollbar() {
		if (bar == null || handle == null) {
			return;
		}

		if (isAnimating) {
			scrollbarAnimatorSet.cancel();
		}

		scrollbarAnimatorSet = createAnimator(bar, handle, false);
		scrollbarAnimatorSet.addListener(new AnimatorListenerAdapter() {
			@Override
			public void onAnimationEnd(Animator animation) {
				super.onAnimationEnd(animation);
				onHideAnimationStop(bar, handle);
				isAnimating = false;
			}

			@Override
			public void onAnimationCancel(Animator animation) {
				super.onAnimationCancel(animation);
				onHideAnimationStop(bar, handle);
				isAnimating = false;
			}
		});
		scrollbarAnimatorSet.start();
		isAnimating = true;
	}
`

`<?xml version="1.0" encoding="utf-8"?>
<merge xmlns:android="http://schemas.android.com/apk/res/android"
	xmlns:tools="http://schemas.android.com/tools"
	android:layout_width="wrap_content"
	android:layout_height="match_parent">

	<View
		android:id="@+id/fast_scroller_bar"
		android:layout_width="7dp"
		android:layout_height="wrap_content"
		android:layout_gravity="end"
		android:background="@android:color/darker_gray"/>

	<RelativeLayout
		android:layout_width="wrap_content"
		android:layout_height="wrap_content">

		<TextView
			android:id="@+id/fast_scroller_bubble"
			android:layout_width="wrap_content"
			android:layout_height="wrap_content"
			android:layout_gravity="end"
			android:layout_marginRight="0dp"
			android:layout_marginEnd="0dp"
			android:paddingLeft="16dp"
			android:paddingRight="16dp"
			android:layout_toLeftOf="@+id/fast_scroller_handle"
			android:background="@drawable/fast_scroller_bubble"
			android:gravity="center"
			android:textColor="?android:attr/textColorPrimaryInverse"
			android:textSize="38sp"
			android:visibility="gone"
			tools:visibility="visible"
			tools:text="A" />

		<ImageView
			android:id="@+id/fast_scroller_handle"
			android:layout_width="wrap_content"
			android:layout_height="wrap_content"
			android:layout_alignParentRight="true"
			android:paddingLeft="6dp"
			android:paddingStart="6dp"
			android:contentDescription="@null"
			android:src="@drawable/fast_scroller_handle"/>

	</RelativeLayout>

</merge>`
