### ISSUE TITLE
[Support] Enable endless if number element >= n 

### ISSUE THREAD

**Issue by funnymobiledev** [davideas/FlexibleAdapter#467]
Hi,
How to enable endless if number element >= n.

**Comment by davideas** [comment]
@funnymobiledev, what is _n_? and what the _number of element_ represents (current list, new items, ...)?

**Comment by funnymobiledev** [comment]
@davideas 
Yes, n is number current element.

**Comment by davideas** [comment]
@funnymobiledev, if you don't explain, I can't answer. Why you have number of element (what represents this number?) > number of current element? explain the situation.

**Comment by funnymobiledev** [comment]
Hi @davideas 
I have problem that my RecyclerView need add some element first then I will add normal element or I will init adapter with empty list first then I will add normal element.
If not support abover feature I need add element in onLoadMore function because onLoadMore function will call later.

**Comment by davideas** [comment]
@funnymobiledev, you have a setting function to trigger the first call, don't need to invoke `onLoadMore()` while you configure the adapter.
