### ISSUE TITLE
Sticky Headers Showing question

### ISSUE THREAD

**Issue by Null45** [davideas/FlexibleAdapter#469]
Hi there. I have couple questions about sticky header.
# 1) Sticky headers always blank when it's appears
   RecyclerView wrapped into FrameLayout, list's items are IHeader instances. Lib version: v5.0.0-rc2. Screenshot is below.  
# 2) How to make sticky only one header type not all subHeaders in RecyclerView?

![screenshot](https://gyazo.com/5921d86d8e7824632c6682e4bcae39b5)

**Comment by davideas** [comment]
@Null45, image link is not visible. Follow the wiki page you may have forgot something.

for the 2nd question, it is actually not possible out of the box, you can try to override the function `getSectionHeader` to decide which header to return.
There was also an idea to make sticky a ScrollableHeader, but still not done.

There's probably a simplest way, for the headers that are should not be sticky just don't implement IHeader, implement those headers as sectionable items as well with layout for header.

**Comment by Null45** [comment]
@davideas ty for explanation. 
Here's the screenshot 
![screenshow](https://user-images.githubusercontent.com/201536/31577808-8219aa9e-b13f-11e7-98e4-93d355c5975a.png)

**Comment by davideas** [comment]
@Null45 is it visible when not sticky?
At the moment I have few elements to understand the reason of the white.

I would recommend to implement equals method correctly, to set the sticky boolean true in the ViewHolder constructor. To have the FrameLayout that wraps RV.

And maybe to post some logs (from `enableLogs()`) of the Adapter startup and with the scroll for the sticky header.

**Comment by Null45** [comment]
Thanks for your advices. Overriding getSectionHeader helped.  I just retrun null to all headers except the  one. Code listing above. 

About second question i forgot to set true to sticky boolean in ViewHolder. Now it works like a charm. Thanks you 

```
 override fun getSectionHeader(position: Int): IHeader<*>? {
    if (!areHeadersShown()) {
      return null
    } else {
      (position downTo 0)
          .map { getItem(it) }
          .filter { isHeader(it) && it is DishTypeItem }
          .forEach { return it as IHeader<*>? }
      return null
    }
  }
```
