### ISSUE TITLE
How do you use the AutoValue framework with this library?

### ISSUE THREAD

**Issue by dev-JE02** [davideas/FlexibleAdapter#471]
I have recently learned how to use AutoValue for easier creation of POJOs. I would like to know how I would be able to use my AutoValue annotated classes for generating classes to be used by the FlexibleAdapter. 

I am thinking of extending the AutoValue annotated classes into another class that implements the Item Interfaces. But I got confused as to how the class would be structured? Could you help me shine a light here?

Thank you very much

**Comment by davideas** [comment]
Hi @dev-JE02 what is this AutoValue?
