### ISSUE TITLE
Crash with FlexibleItemAnimator

### ISSUE THREAD

**Issue by SamYStudiO** [davideas/FlexibleAdapter#474]
Using support 26+ when trying to add Animation to my list i  got this error
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/animation/AnimatorCompatHelper;
using
`mList.setItemAnimator( new FlexibleItemAnimator( ) );`

**Comment by davideas** [comment]
Duplicate of #437, will be part of RC3 release soon.

But thanks for notifying.
