### ISSUE TITLE
defaultDivider gone in rc3

### ISSUE THREAD

**Issue by 10erlosh** [davideas/FlexibleAdapter#475]
When moving from rc2 to rc3 the default item divider is no longer visible.
Previously working code:
```
// setup itemDecoration
recyclerView.addItemDecoration(new FlexibleItemDecoration(activity)
                .withDefaultDivider()
        // ...
);
```

**Comment by davideas** [comment]
Thanks @10erlosh!! I completely forgot to mention it, and I didn't see the bug before.
Now it is in the release notes #442.

The fix will be publish for final release, in the meantime if you want any divider (custom or default) you must specifies the viewTypes, for which you want it drawn, as parameter. That works.
