### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by zabi90** [davideas/FlexibleAdapter#476]
So far this lib is very helpful but i am little bit stuck with expandable item. I want to get notify my headerItem when subItem is expand or collapse so that i can change the arrow up and down that is exist in headerItem.
Thanks

**Comment by davideas** [comment]
@zabi90 thank you very much. 
If I understood well the header is the expandable item, so you have implemented `ExpandableViewHolder`, that provides the function `shouldNotifyParentOnClick()`. Make it return true so you will receive the call for a new binding and the payload `Payload.EXPANDED` or `Payload.COLLAPSED` (very important in this case) as well.

**Comment by zabi90** [comment]
Thanks! it's done.
