### ISSUE TITLE
ExpandableViewHolder#onClick should always call super

### ISSUE THREAD

**Issue by technicalflaw** [davideas/FlexibleAdapter#477]
Currently, `onClick` doesn't call super if the item isn't enabled or `isViewExpandableOnClick() == false`, but this stops any callbacks added to the adapter from being called, which should never be the case if the item is enabled. I think it should be the same as `onLongClick()`.

```
public void onClick(View view) {
  if (mAdapter.isEnabled(getFlexibleAdapterPosition()) && isViewExpandableOnClick()) {
    toggleExpansion();
  }
  super.onClick(view);
}
```

**Comment by davideas** [comment]
@technicalflaw, yes I agree. Thanks.
