### ISSUE TITLE
Loading and caching data.

### ISSUE THREAD

**Issue by pharma-vie** [davideas/FlexibleAdapter#478]
is there a library that supports the cache for loading and caching data for this excellent library.

**Comment by davideas** [comment]
@pharma-vie, thanks for the message, if I understood your question you search a library that caches and provides items to the Adapter. Recently Android team developed `LiveData` and `ViewModel` objects.
_ViewModel_ is the holder of the data in the memory instantiated once for the lifecycle of the App and that provides data to the "View" (Activity/Fragment) that in turn supplies the Adapter.

**Comment by pharma-vie** [comment]
yes, I want to memorize the data coming from the internet to use it later in offline mode.
I will try this method.. thinks davideas

**Comment by sandeep-voxer** [comment]
@pharma-vie  You should then store the data in some kind of persistent storage like database or files (e,g Sqlite, Realm etc.)
