### ISSUE TITLE
Expand/collapse on click doesn't seem to work in rc3

### ISSUE THREAD

**Issue by cioraneanu** [davideas/FlexibleAdapter#479]
First of all thank you for the awesome library.

After updating from rc2 to rc3, I'm struggling to get the collapse/expand on click behavior to work. (this worked as expected on rc2)

**Code:**
1. Expandable item
```
public class GroupItem extends AbstractExpandableItem<GroupItem.GroupViewHolder, SimpleItem> {

    private static final int LAYOUT_RESOURCE = R.layout.group_layout;
    String title;

    public GroupItem(String title) {
        this.title = title;
        setExpanded(true);
    }

    @Override
    public boolean equals(Object o) {
        GroupItem comparedItem = (GroupItem) o;
        return (comparedItem.title.equalsIgnoreCase(title));
    }

    @Override
    public int getLayoutRes() {
        return LAYOUT_RESOURCE;
    }



    @Override
    public GroupViewHolder createViewHolder(View view, FlexibleAdapter adapter) {
        return new GroupViewHolder(view, adapter);
    }

    @Override
    public void bindViewHolder(FlexibleAdapter adapter, GroupViewHolder holder, int position, List payloads) {
        holder.tvTitle.setText("----" + title);
    }

    // View holder class
    public static class GroupViewHolder extends ExpandableViewHolder {

        public TextView tvTitle;

        public GroupViewHolder(View view, FlexibleAdapter adapter) {
            super(view, adapter);
            this.tvTitle = view.findViewById(R.id.tvTitle);
        }

    }
}
```

2. Sub Item
```
public class SimpleItem extends AbstractFlexibleItem<SimpleItem.SimpleViewHolder> {

    private static final int LAYOUT_RESOURCE = R.layout.simple_layout;

    String title;

    public SimpleItem(String title) {
        this.title = title;
    }

    @Override
    public boolean equals(Object o) {
        SimpleItem comparedItem = (SimpleItem) o;
        return (comparedItem.title.equalsIgnoreCase(title));
    }

    @Override
    public int getLayoutRes() {
        return LAYOUT_RESOURCE;
    }

    @Override
    public SimpleViewHolder createViewHolder(View view, FlexibleAdapter adapter) {
        return new SimpleViewHolder(view, adapter);
    }

    @Override
    public void bindViewHolder(FlexibleAdapter adapter, SimpleViewHolder holder, int position, List payloads) {
        holder.tvTitle.setText(title);
    }

    // View holder class
    public static class SimpleViewHolder extends ExpandableViewHolder {

        public TextView tvTitle;

        public SimpleViewHolder(View view, FlexibleAdapter adapter) {
            super(view, adapter);
            this.tvTitle = view.findViewById(R.id.tvTitle);
        }

    }
}
```

3. Adapter with mock data
```
        List<GroupItem> groupList = new ArrayList<>();
        for (int i = 0; i < 5; i++) {
            GroupItem newGroup = new GroupItem("Group " + i);
            for (int j = 0; j < 6; j++) {
                SimpleItem simpleItem = new SimpleItem("Item" + i + " " + j);
                newGroup.addSubItem(simpleItem);
            }
            groupList.add(newGroup);
        }

        adapter = new FlexibleAdapter<GroupItem>(groupList);
        adapter.expandItemsAtStartUp();
        recyclerView.setLayoutManager(new SmoothScrollLinearLayoutManager(this));
        recyclerView.setAdapter(adapter);
```

**Result:**
 - Clicking the group items doesn't trigger any action
 - Calling setExpanded(true) and expandItemsAtStartUp() shows both expandable and subitems. Without these I only see the expandable items.

Am I missing anything here?

**Comment by davideas** [comment]
@cioraneanu, by declaring `setExpanded(true)` you are responsible to insert the subItems yourself, the adapter sees that element expanded he skips it. That property is for internal usage but can be modified by the user for advanced usage.

If you are sure that _title_ is unique in your set of data, then it's ok to have it in the `equals` method, if not use a better identifier or at the first double same title java can't grab your second element with that title.

**Comment by wildmelon** [comment]
I face the same question and add
`holder.itemView.setOnClickListener(holder);`
to solved it

**Comment by cioraneanu** [comment]
@wildmelon Your proposed solution works.
Adding a click listener on the adapter seems to do the job as well.
`adapter.addListener(new FlexibleAdapter.OnItemClickListener(){`

**Comment by davideas** [comment]
@wildmelon, the correct way to link the listener to an item view is by adding the listener to the adapter as @cioraneanu does or in the Constructor, the difference as new feature is that now when added and removed separately at runtime, there's a routine that identifies all the already bound view holders and link the listener to them. You can read more here (#427 - Dynamically add and remove listeners).

@cioraneanu, please review my previous answer (now edited) since it was wrong.

**Comment by cioraneanu** [comment]
@davideas Regarding your first answer, I only used `setExpanded(true)` to test if the sub-items where correctly added to the expandable ones.(without that i only saw the expandable items and click event didn't provide any change).

Double checked and the ids are unique.

I do understand your reasoning but it's a bit weird that an internal functionality doesn't work without an external (possibly unwanted) listener attached. I think a warning on the wiki "Expandable items" page regarding the importance a click listener would be helpful.

**Comment by shannonlo** [comment]
I used r3 and faced the same problem...

**Comment by davideas** [comment]
Regarding the click listener to assign to the Adapter I gave it for implicit fact, since without it, the list is in read only mode.
There's an alternative to expand and collapse an item by implementing a click listener to an inner view of the item and call `toggleExpansion()` method as done in the overridden `onClick` in the `ExpandableViewHolder`.

> PS. Documentation has been adapted, thanks.

**Comment by khalid-mahmood** [comment]
@davideas Please provide Complete Collapse and Expand example. can't find where is implemented in sample App. Thanks in Advnace.

**Comment by davideas** [comment]
@khalid-mahmood, even if I want to make a new demo App simpler to understand (only lack of time), you can find more instructions in the Wiki page for [Expandable items](https://github.com/davideas/FlexibleAdapter/wiki/5.x-%7C-Expandable-items). From docs:
> **Note:** In order to expand/collapse an item, you must add a click listener to the Adapter or alternatively implement the click listener to a specific inner view of the item and call toggleExpansion() method in the ExpandableViewHolder as done in the overridden onClick.
