### ISSUE TITLE
Divider not shown in RC3

### ISSUE THREAD

**Issue by litrik** [davideas/FlexibleAdapter#480]
I have the following code

`recyclerView.addItemDecoration(new FlexibleItemDecoration(getContext())
                .withDivider(R.drawable.divider_white)
                .withDrawOver(true)
                .addItemViewType(R.layout.event_item));`

where divider_white.xml contains

`<shape xmlns:android="http://schemas.android.com/apk/res/android">
    <size
        android:height="1dp"/>
    <solid
        android:color="@color/white"/>
</shape>`

In RC2 there was a thin white divider drawn between item of the type R.layout.event_item. In RC3 there's no more divider.

This looks a lot like #475 but that issue was about a default divider. And as a workaround it mentions that addItemViewType() should be used. My code already does that so there must be something else going wrong.

RC2
![rc2](https://user-images.githubusercontent.com/688765/32158814-dd485f02-bd4a-11e7-88c4-80267720a210.png)

RC3
![rc3](https://user-images.githubusercontent.com/688765/32158817-dff85284-bd4a-11e7-9850-2fae84db0841.png)

**Comment by davideas** [comment]
Hi @litrik, sorry for the delay, `addItemViewType()` method serie is for **offset only**, for the divider as Drawable you need to pass the viewTypes as **parameters** in the same function.

Now, you made confusion probably caused by the "ViewType" name, but how should I name those methods then? However, the javaDoc is well clear.

**Comment by litrik** [comment]
Thanks for the clarification. To be honest I didn't notice the withDivider() with the argument list. I based my code on https://github.com/davideas/FlexibleAdapter/wiki/5.x-%7C-Flexible-Item-Decoration Maybe that page could use an extra example of withDivider(R.drawable.divider_white, R.layout.event_item)

**Comment by davideas** [comment]
Thanks @litrik, now wiki page is clearer, however in another version i might separate the 2 item decorations since they don't fit together, they can anyway be added to the RecyclerView as we know.
This will be part of the work for the UI extensions later in months.
