### ISSUE TITLE
Adapter is not attached to RecyclerView. Enable sticky headers after setting adapter to RecyclerView.

### ISSUE THREAD

**Issue by YashMaharshi** [davideas/FlexibleAdapter#483]
Used FlexibleAdapter with recyclerview for displaying the header & Section item with Sticky header. I have a search option where when user type any text, the result get filter on basis of the text entered. 
I am not used the in-built search filter, I have customized it as per the my requirement. But when user try to type or delete text rapidly the app crashes with following exception

"java.lang.IllegalStateException: Adapter is not attached to RecyclerView. Enable sticky headers after setting adapter to RecyclerView."

Please let me know how to get rid of this app crash

**Comment by davideas** [comment]
@YashMaharshi, well I do not know your code for the search, but the exception is saying that RecyclerView is `null` in the Adapter, sticky header helper needs it.

**Comment by YashMaharshi** [comment]
Yeah you are right, but I don't know why, where and how the RecyclerView is getting null. I am attaching my code file which will help you to understand the problem 
line:309 => afterTextChanged() = use type the alphabet, and the code do the filtering of data
line:348 => displayMessageInfoSectionWithStickyHeader() = this method is called once we get the filtered data in the list, within this method I am assigning the new adapter to the RecyclerView
- But when user type or delete the record at speed, the app show the exception and crashes
PFA
[MessagesInfoFragment.txt](https://github.com/davideas/FlexibleAdapter/files/1448608/MessagesInfoFragment.txt)

**Comment by davideas** [comment]
@YashMaharshi, I see you use the same variable reference for adapter, first check your logs you should have a detach followed by an attach. Please also remove the last invocation `.showAllHeaders()`.

Alternatively, you can try to use swapAdapter from RV.
Alternatively, you can try to use another adapter instance for search only.
Alternatively, you can also update the list instead of creating a new instance.

**Comment by Quarx2k** [comment]
I have same problem. "Adapter is not attached to RecyclerView. Enable sticky headers after setting adapter to RecyclerView."
Randomly happens when open fragment. https://pastebin.com/40gVAFRB code
Version: Latest snapshot

**Comment by davideas** [comment]
@Quarx2k, I've seen your code and you are not doing it, Just do what the exception states: "_Enable sticky headers after setting adapter to RecyclerView_".
The sticky layout needs the RecyclerView instance that is taken from the Adapter.

**Comment by Quarx2k** [comment]
@davideas, Thanks. Anyway it's not helps
It was my fault while using Moxy. SetAdapter called twice sometimes and second call cause this exception.
