### ISSUE TITLE
bindViewHolder method is causing a problem with greendao

### ISSUE THREAD

**Issue by nordanfors** [davideas/FlexibleAdapter#484]
I am using GreenDao for persistence in my project and I am getting some error when trying to implement Flexible adapter:

Error:Execution failed for task ':app:greendao'.
> Found 1 problem(s) parsing 
  Pb(572) List is a raw type. References to generic type List<E> should be parameterized (16777788 at line 248).

Line 248 in my code is this method:
public void bindViewHolder(FlexibleAdapter adapter, MyViewHolder holder, int position,
                               List payloads) {...}

It seems greendao is not happy with the payload List being typeless. I have not been able to figure out a solution or workaround so any help would be very welcome.

**Comment by davideas** [comment]
@nordanfors, I can only put this: `List<Object>` in the Snapshot version so you can try and tell me.
I will try to publish it this evening CET timezone.

**Comment by davideas** [comment]
@nordanfors, can you try to verify with the Snapshot version?
