### ISSUE TITLE
How to create multi-level grouped item？

### ISSUE THREAD

**Issue by TCQQ** [davideas/FlexibleAdapter#486]
How to create multi-level grouped item, like a development tool
![qq 20171107163208](https://user-images.githubusercontent.com/10644057/32484068-8867e0ee-c3d9-11e7-8d16-a1a2ceae4a13.png)
![image](https://user-images.githubusercontent.com/10644057/32484573-49b1159e-c3db-11e7-8b56-e6addb535a56.png)

**Comment by davideas** [comment]
@TCQQ, this library is not very good for "tree view", however it has multilevel and you need to override `getExpansionLevel()` in `AbstractExpandableItem` carefully. In the demoApp there's a sample of multilevel you just need to extend it for your use case.

**Comment by TCQQ** [comment]
thank you I will to try, tree view function is commonly used, hope after can be add the tree view example in the demo

**Comment by davideas** [comment]
@TCQQ, in the wiki there's also a section for multi level.

**Comment by TCQQ** [comment]
ok thanks, I will check
