### ISSUE TITLE
error: duplicate value for resource 'attr/tint' with config ''.

### ISSUE THREAD

**Issue by Verichev** [davideas/FlexibleAdapter#487]
I  compile dependency this way
`    compile ('eu.davidea:flexible-adapter:5.0.0-rc3') {
        exclude module: 'appcompat-v7'
    }`
I can't import library in the project, when compiling I get this error:
`error: duplicate value for resource 'attr/tint' with config ''.`
I tried to cut out all appcompat-v7 dependencies, but it doesn't help.
I can build the project only if my own appcompat dependency is 26.0.0-alpha1
How can I fix it?

**Comment by davideas** [comment]
@Verichev, inside **recyclerView** is declared _provided_ and **design** is _compiled_.
Version is "26.1.0", try to use the same or "27.0.0".

**Comment by Verichev** [comment]
I tried all versions after 26.0.0-alpha1
Even 27.0.0
I get the same result, can't figure out why

**Comment by davideas** [comment]
In my other lab project here in GitHub: [AndroidBlueprints](https://github.com/davideas/AndroidBlueprints) everything works, please compare your build files with the ones in that project.

**Comment by davideas** [comment]
@Verichev, I've release a new SNAPSHOT version, can you try to verify if that problem has been resolved?

**Comment by Verichev** [comment]
Sorry, the problem wasn't related to the library.

**Comment by thasafarian** [comment]
i find the same issue. please help!!

**Comment by Verichev** [comment]
This library uses 26 sdk. So my using this library concinded with migration from 25 to 26 sdk
In a new sdk many new resources appeared such as attr/tint. But I had the same custom resource in my project allready. When I deleted it, the project has compiled

**Comment by thasafarian** [comment]
yeah i tried to delete it and the error was gone. but it gave me another error  because i need the file with the name 'tint' in it

**Comment by Katlaped** [comment]
Good day, i get the below error: Please assist, i checked the libraries but same error!

![image](https://user-images.githubusercontent.com/34712841/35151939-f656dd7a-fd28-11e7-966f-3f5064749ed4.png)

**Comment by MNGsulochana** [comment]
apply plugin: 'com.android.application'

android {
    compileSdkVersion 27
    buildToolsVersion '27.0.3'
    defaultConfig {
        applicationId "com.oriondigi.sia"
        minSdkVersion 19
        targetSdkVersion 27
        versionCode 10
        versionName "DEMO-NEW-VERSION"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true
        flavorDimensions "versionCode"
        // Enabling multidex support.
      //  multiDexEnabled true
    }

    signingConfigs {
        dexOptions {
            // incremental true
            javaMaxHeapSize "4g"
        }
    }

    buildTypes {

        debug {
            debuggable true
            minifyEnabled false
            useProguard true
            /* applicationIdSuffix ".debug"*/
            //  buildConfigField 'boolean', 'ENABLE_CRASH', 'false'
            //  proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        release {
            debuggable false

            shrinkResources true
            minifyEnabled true
            /* applicationIdSuffix ".release"*/

            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'

            //  proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            //  proguardFiles fileTree('proguard').asList().toArray()
        }
    }

    productFlavors {
        noExtensions
        withExtensions
    }
    lintOptions {
        disable 'MissingTranslation'
    }

  

}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    //noinspection GradleCompatible
  //  implementation 'com.android.support:appcompat-v7:27.0.2'

    withExtensionsCompile project(path: ':extension-ffmpeg')
    implementation 'com.google.android.exoplayer:exoplayer-hls:2.6.1'
    implementation 'com.google.android.exoplayer:exoplayer:2.6.1'
    implementation files('src/main/jniLibs/wasabi.jar')
    //noinspection GradleCompatible
    implementation 'com.android.support:leanback-v17:27.0.2'

    implementation 'com.squareup.picasso:picasso:2.5.2'
    implementation 'jp.wasabeef:glide-transformations:3.0.1'
    implementation 'com.github.bumptech.glide:glide:4.3.1'

    implementation 'com.squareup.retrofit2:converter-gson:2.3.0'

    implementation 'org.apache.directory.studio:org.apache.commons.io:2.4'
    implementation 'com.squareup.retrofit2:retrofit:2.3.0'
    implementation 'com.google.code.gson:gson:2.8.1'
    //noinspection GradleCompatible
//   implementation 'com.android.support:support-v4:27.0.2'
//    compile 'com.android.support:cardview-v7:27.0.2'

    testImplementation 'junit:junit:4.12'

   // compile 'com.android.support:multidex:1.0.2'
    implementation 'com.squareup.okhttp3:okhttp:3.9.1'
    implementation 'com.squareup.okhttp3:logging-interceptor:3.9.1'
//    annotationProcessor 'com.github.bumptech.glide:compiler:4.1.1'
/*    annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'*/

    implementation ('com.payumoney.sdkui:plug-n-play:1.0.0'){
        transitive = true;
        exclude module: 'payumoney-sdk'
    }

    implementation 'com.payumoney.core:payumoney-sdk:7.0.1'
}

***********************************************************************************************************
This is my gradle file for the project after adding payumoney dependency I am getting the error like
**************************************************************************
Information:Gradle tasks [clean, :sia:generateNoExtensionsDebugSources, :sia:generateNoExtensionsDebugAndroidTestSources, :sia:mockableAndroidJar, :extension-ffmpeg:generateDebugSources, :extension-ffmpeg:generateDebugAndroidTestSources, :extension-ffmpeg:mockableAndroidJar]
/home/sulochana/.gradle/caches/transforms-1/files-1.1/appcompat-v7-23.2.1.aar/881e020b641477421beb618a0a79354a/res/values/values.xml
Error:(102, 5) error: duplicate value for resource 'attr/rowHeight' with config ''.
Error:(102, 5) error: resource previously defined here.
Error:java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Information:BUILD FAILED in 34s
Information:3 errors
Information:0 warnings
Information:See complete output in console

if any idea please help me
