### ISSUE TITLE
AutoFitGridLayoutManager?

### ISSUE THREAD

**Issue by 10erlosh** [davideas/FlexibleAdapter#488]
Hi,
do you plan to integrate a GridLayoutManager that calculates the spanCount using a specified columnWidth like for example the one below?
If not, can you tell me please how to use it with your library? I tried it like this:

```
recyclerView.setLayoutManager(new AutoFitGridLayoutManager(activity, 200));
recyclerView.addItemDecoration(new FlexibleItemDecoration(activity).withOffset(16));
```
but when changing orientation I don't get the desired output (see second screenshot below).
Without ItemDecoration everything is fine.

Many thanks in advance!

good:
![good](https://user-images.githubusercontent.com/1727351/32656166-033b516e-c611-11e7-8926-b49cc6c38034.png)

after orientation changed:
![not good](https://user-images.githubusercontent.com/1727351/32656173-0b5e7d26-c611-11e7-95ad-df8a44106a0b.png)

```
public class AutoFitGridLayoutManager extends GridLayoutManager {

    private int columnWidth;
    private boolean columnWidthChanged = true;

    private boolean mWidthChanged = true;
    private int mWidth;

    public AutoFitGridLayoutManager(Context context, int columnWidth) {
        super(context, 1);

        setColumnWidth(columnWidth);
    }

    public void setColumnWidth(int newColumnWidth) {
        if (newColumnWidth > 0 && newColumnWidth != columnWidth) {
            columnWidth = newColumnWidth;
            columnWidthChanged = true;
        }
    }

    @Override
    public void onLayoutChildren(RecyclerView.Recycler recycler, RecyclerView.State state) {

        int width = getWidth();
        int height = getHeight();

        if (width != mWidth) {
            mWidthChanged = true;
            mWidth = width;
        }

        if (columnWidthChanged && columnWidth > 0 && width > 0 && height > 0
                || mWidthChanged) {
            int totalSpace;
            if (getOrientation() == VERTICAL) {
                totalSpace = width - getPaddingRight() - getPaddingLeft();
            } else {
                totalSpace = height - getPaddingTop() - getPaddingBottom();
            }
            int spanCount = Math.max(1, totalSpace / columnWidth);
            setSpanCount(spanCount);
            columnWidthChanged = false;
            mWidthChanged = false;
        }
        super.onLayoutChildren(recycler, state);
    }
}
```

**Comment by 10erlosh** [comment]
As a workaround I call `adapter.invalidateItemDecorations(100L);` on orientation change. Perhaps there is a better way?

**Comment by davideas** [comment]
@10erlosh, `invalidateItemDecorations()` is there for that reason, since RV can't recalculate the decoration when it changes layout position to the items. That behavior occurs also after dragging an item, but for you it's transparent because I can intercept the event internally. For orientation change I can't and the user must call it.
I couldn't find a better way.

This is explained in the wiki page of that component.
I will add also configuration change for completeness.

**Comment by 10erlosh** [comment]
Thank you. I'm happy with it!
