### ISSUE TITLE
StackOverflowError Exeption when lots of items inserted

### ISSUE THREAD

**Issue by meness** [davideas/FlexibleAdapter#489]
> FATAL EXCEPTION: main
>                                                               java.lang.StackOverflowError
>                                                                   at eu.davidea.flexibleadapter.FlexibleAdapter.getMainItemCount(FlexibleAdapter.java:663)
>                                                                   at eu.davidea.flexibleadapter.FlexibleAdapter.onLoadMoreComplete(FlexibleAdapter.java:2026)
>                                                                   at eu.davidea.flexibleadapter.FlexibleAdapter.onLoadMoreComplete(FlexibleAdapter.java:2002)
>                                                                   at apadana.we.rio.ui.search.SearchFragment.noMoreLoad(SearchFragment.java:105)
>                                                                   at eu.davidea.flexibleadapter.FlexibleAdapter.noMoreLoad(FlexibleAdapter.java:2078)
>                                                                   at eu.davidea.flexibleadapter.FlexibleAdapter.onLoadMoreComplete(FlexibleAdapter.java:2050)
>                                                                   at eu.davidea.flexibleadapter.FlexibleAdapter.onLoadMoreComplete(FlexibleAdapter.java:2002)
>                                                                   at apadana.we.rio.ui.search.SearchFragment.noMoreLoad(SearchFragment.java:105)
>                                                                   at eu.davidea.flexibleadapter.FlexibleAdapter.noMoreLoad(FlexibleAdapter.java:2078)
>                                                                   at eu.davidea.flexibleadapter.FlexibleAdapter.onLoadMoreComplete(FlexibleAdapter.java:2050)
>                                                                   at eu.davidea.flexibleadapter.FlexibleAdapter.onLoadMoreComplete(FlexibleAdapter.java:2002)
>                                                                   at apadana.we.rio.ui.search.SearchFragment.noMoreLoad(SearchFragment.java:105)
>                                                                   at eu.davidea.flexibleadapter.FlexibleAdapter.noMoreLoad(FlexibleAdapter.java:2078)
>                                                                   at eu.davidea.flexibleadapter.FlexibleAdapter.onLoadMoreComplete(FlexibleAdapter.java:2050)
>                                                                   at eu.davidea.flexibleadapter.FlexibleAdapter.onLoadMoreComplete(FlexibleAdapter.java:2002)
>                                                                   at apadana.we.rio.ui.search.SearchFragment.noMoreLoad(SearchFragment.java:105)
>                                                                   at eu.davidea.flexibleadapter.FlexibleAdapter.noMoreLoad(FlexibleAdapter.java:2078)
>                                                                   at eu.davidea.flexibleadapter.FlexibleAdapter.onLoadMoreComplete(FlexibleAdapter.java:2050)
>                                                                   at eu.davidea.flexibleadapter.FlexibleAdapter.onLoadMoreComplete(FlexibleAdapter.java:2002)
>                                                                   at apadana.we.rio.ui.search.SearchFragment.noMoreLoad(SearchFragment.java:105)
>                                                                   at eu.davidea.flexibleadapter.FlexibleAdapter.noMoreLoad(FlexibleAdapter.java:2078)
>                                                                   at eu.davidea.flexibleadapter.FlexibleAdapter.onLoadMoreComplete(FlexibleAdapter.java:2050)
>                                                                   at eu.davidea.flexibleadapter.FlexibleAdapter.onLoadMoreComplete(FlexibleAdapter.java:2002)
>                                                                   at apadana.we.rio.ui.search.SearchFragment.noMoreLoad(SearchFragment.java:105)
>                                                                   at eu.davidea.flexibleadapter.FlexibleAdapter.noMoreLoad(FlexibleAdapter.java:2078)
>                                                                   at eu.davidea.flexibleadapter.FlexibleAdapter.onLoadMoreComplete(FlexibleAdapter.java:2050)
>                                                                   at eu.davidea.flexibleadapter.FlexibleAdapter.onLoadMoreComplete(FlexibleAdapter.java:2002)
>                                                                   at apadana.we.rio.ui.search.SearchFragment.noMoreLoad(SearchFragment.java:105)
>                                                                   at eu.davidea.flexibleadapter.FlexibleAdapter.noMoreLoad(FlexibleAdapter.java:2078)
>                                                                   at eu.davidea.flexibleadapter.FlexibleAdapter.onLoadMoreComplete(FlexibleAdapter.java:2050)
>                                                                   at eu.davidea.flexibleadapter.FlexibleAdapter.onLoadMoreComplete(FlexibleAdapter.java:2002)
>                                                                   at apadana.we.rio.ui.search.SearchFragment.noMoreLoad(SearchFragment.java:105)
>                                                                   at eu.davidea.flexibleadapter.FlexibleAdapter.noMoreLoad(FlexibleAdapter.java:2078)
>                                                                   at eu.davidea.flexibleadapter.FlexibleAdapter.onLoadMoreComplete(FlexibleAdapter.java:2050)
>                                                                   at eu.davidea.flexibleadapter.FlexibleAdapter.onLoadMoreComplete(FlexibleAdapter.java:2002)
>                                                                   at apadana.we.rio.ui.search.SearchFragment.noMoreLoad(SearchFragment.java:105)
>                                                                   at eu.davidea.flexibleadapter.FlexibleAdapter.noMoreLoad(FlexibleAdapter.java:2078)
>                                                                   at eu.davidea.flexibleadapter.FlexibleAdapter.onLoadMoreComplete(FlexibleAdapter.java:2050)
>                                                                   at eu.davidea.flexibleadapter.FlexibleAdapter.onLoadMoreComplete(FlexibleAdapter.java:2002)
>                                                                   at apadana.we.rio.ui.search.SearchFragment.noMoreLoad(SearchFragment.java:105)
>                                                                   at eu.davidea.flexibleadapter.FlexibleAdapter.noMoreLoad(FlexibleAdapter.java:2078)
>                                                                   at eu.davidea.flexibleadapter.FlexibleAdapter.onLoadMoreComplete(FlexibleAdapter.java:2050)
>                                                                   at eu.davidea.flexibleadapter.FlexibleAdapter.onLoadMoreComplete(FlexibleAdapter.java:2002)
>                                                                   at apadana.we.rio.ui.search.SearchFragment.noMoreLoad(SearchFragment.java:105)
>                                                                   at eu.davidea.flexibleadapter.FlexibleAdapter.noMoreLoad(FlexibleAdapter.java:2078)
>                                                               	at eu.davidea.flexibleadapter.FlexibleAdapter.onLoadMore

```
  @Override
    public void noMoreLoad(int newItemsSize) {
        // empty
        adapter.onLoadMoreComplete(null);
    }
```

**Comment by davideas** [comment]
Why are you calling `onLoadMoreComplete()` if no more to load? Can you
please read the javaDoc of those methods?

Thanks

**Comment by meness** [comment]
@davideas [you wrote here](https://github.com/davideas/FlexibleAdapter/wiki/5.x-%7C-On-Load-More#4-implement-the-endlessscrolllistener)

**Comment by davideas** [comment]
@meness, actually you found a mistake of copy/paste in the documentation! If you notice carefully, my internal comment for `noMoreLoad` is equal to the `onLoadMore` implementation, so I'm going to remove that part inside `noMoreLoad`.
