### ISSUE TITLE
Automatically fetch first result on load more, scrolls the RecyclerView

### ISSUE THREAD

**Issue by meness** [davideas/FlexibleAdapter#490]
Hi,

There's a method to fetch first result on load more automatically, I tested it and I found it scrolls the `RecyclerView` but it shouldn't.

**Comment by davideas** [comment]
@meness, what do you mean, how many items are loaded, and why you think that it scrolls? I don't see this in the demoApp. I think I really need a video and a way to reproduce it.
Thanks.

**Comment by meness** [comment]
```java
adapter = new FlexibleAdapter<>(null);
adapter.setEndlessScrollListener(this, new ProgressItem()).setLoadingMoreAtStartUp(true);
```

```java
@Override
    public void onLoadMore(int lastPosition, int currentPage) {
        presenter.fetchOffProducts(adapter.getItemCount(), 25);
    }

public void productsFetched(List<Product> products) {
        List<IFlexible> items = new ArrayList<>();
        for (Product product : products) {
            items.add(new ProductItem(product));
        }

        adapter.onLoadMoreComplete(items);
    }
```

**Comment by NamingException** [comment]
Hi @davideas , 

You can reproduce this in the sample app in the FragmentInstagramHeaders class.

Just replace initializeRecyclerView code with 

```
private void initializeRecyclerView() {
        // Initialize Adapter and RecyclerView
        // true = it makes use of stableIds, I strongly suggest to implement 'item.hashCode()'
        FlexibleAdapter.useTag("InstagramHeadersAdapter");
        mAdapter = new FlexibleAdapter<>(new ArrayList<>(), getActivity(), true);
        mAdapter.addListener(getActivity())
                .setAnimationOnScrolling(true)
                .setAnimationOnReverseScrolling(true);
        mRecyclerView = getView().findViewById(R.id.recycler_view);
        mRecyclerView.setLayoutManager(createNewLinearLayoutManager());
        mRecyclerView.setAdapter(mAdapter);
        mRecyclerView.setHasFixedSize(true); //Size of RV will not change
        // NOTE: Use default item animator 'canReuseUpdatedViewHolder()' will return true if
        // a Payload is provided. FlexibleAdapter is actually sending Payloads onItemChange.
        mRecyclerView.setItemAnimator(new DefaultItemAnimator());
        // Custom divider item decorator with 24dpi as empty space between sections
        mRecyclerView.addItemDecoration(new FlexibleItemDecoration(getActivity()).withDefaultDivider());

        mAdapter.setDisplayHeadersAtStartUp(true) //Show Headers at startUp!
                .setStickyHeaders(true) //Make headers sticky
                // Endless scroll with 1 item threshold
                .setEndlessScrollListener(this, new ProgressItem())
				.setLoadingMoreAtStartUp(true)
                .setEndlessScrollThreshold(1); //Default=1

        SwipeRefreshLayout swipeRefreshLayout = getView().findViewById(R.id.swipeRefreshLayout);
        swipeRefreshLayout.setEnabled(true);
        mListener.onFragmentChange(swipeRefreshLayout, mRecyclerView, Mode.IDLE);
    }
```

You init the recycler with 0 items, and setLoadingMoreAtStartUp to true. After the items are loaded the recycler is scrolled a bit down and is not at the first item.

**Comment by davideas** [comment]
Ok, thanks, I will try to investigate why.

**Comment by davideas** [comment]
An update about the not easy investigation. In `onLoadMoreComplete`, adding the new items and then hiding the progressItem seems to cause the scroll from RecyclerView, but if I hide before the progressItem, then it seems the scroll doesn't occur. I do not understand why...

You can reproduce the behavior by doing (which are the key calls in the `onLoadMoreComplete`):
``` java
mAdapter.addItems(0, newItems);
mAdapter.removeScrollableFooter(mProgressItem);
//mAdapter.onLoadMoreComplete(newItems, 1000L);
```
This occurs in main example in endless fragment too, I followed the execution flow, but there's nothing I could identify the cause. But if you invert by the removing the progress item before the adding, then it seems to work as expected.

Now, I need to evaluate the impact of this change. I will come later for a new update.

**Comment by davideas** [comment]
I moved the adding after the removal of the progressItem, this preserves also the feature to delay the removal to display a message in the progressItem.

I release this fix in the new SNAPSHOT in few moments...
