### ISSUE TITLE
How to scroll to sub item in header

### ISSUE THREAD

**Issue by krupalagile** [davideas/FlexibleAdapter#494]
I have a recycled view with expandable items and headers. What to do if I want to scroll to the particular item in some expandable header? 

`recyclerReadingSection.smoothScrollToPosition(position)` will not work when dataset contains header items.

**Comment by davideas** [comment]
@krupalagile, you first need to find the correct position with `getGlobalPositionOf(item)` then you call `smoothScrollToPosition(position)`, this technique works only if the item is visible, if not, you have to probably expand the parent.

Finally I guess, you will want to make it visible after the scroll, I suggest to trigger a delayed slow ripple animation.

**Comment by krupalagile** [comment]
Thanks for quick reply. My issue has been solved but now `smoothScrollToPosition `to `globalPosition ` is scrolling to 2 more items than actual. Do you have any solution for that?

**Comment by davideas** [comment]
If you are using the layout manager of this library, that works. I use it in many points.

**Comment by krupalagile** [comment]
I am using `SmoothScrollLinearLayoutManager`.

`mSmoothScrollLinearLayoutManager.smoothScrollToPosition(recyclerview, null, position);`

is scrolling two more items in the case of expandable sticky headers

**Comment by davideas** [comment]
Did you consider the space took by the sticky item covering the item scrolled to?
Sorry man, it works, you have to subtract 1 from the position if sticky is enabled, just tried with demoApp.

**Comment by krupalagile** [comment]
Ok Thanks. Is there a way to calculate count of all sticky headers above some item?

**Comment by davideas** [comment]
Your rule is "-1", it's wrong to subtract the previous headers.

**Comment by krupalagile** [comment]
But it does not work when the header is larger than the child in terms of height.

**Comment by krupalagile** [comment]
Hi, can you please help me?

**Comment by davideas** [comment]
Sorry @krupalagile, the scroll height is your business. Please check some functions of _RecyclerView_.

**Comment by krupalagile** [comment]
I'll appreciate if you give some hints. Thanks.
