### ISSUE TITLE
Sticky headers strange behaviour

### ISSUE THREAD

**Issue by PingForward** [davideas/FlexibleAdapter#495]
Sticky headers strange behaviour when display already created fragment (replace from cache)

1. If fragment starts at first time all is working fine
I init adapter with empty list and then update dataset with items loaded from network also I save this list globally in the fragment
```
adapter = FlexibleAdapter(listOf(), this)
        adapter.setStickyHeaders(true)
                .setDisplayHeadersAtStartUp(true)
                .stickyHeaderElevation = 2
// after items loaded
adapter.updateDataSet(getConvertedList(items))
```
when I display this fragment again (replace some other fragment in activity) it already contains list of items and I pass it in constructor
` adapter = FlexibleAdapter(getConvertedList(items), this)`
and get this
![screenshot_1511251200](https://user-images.githubusercontent.com/17492722/33062472-79369e80-ceb0-11e7-89b6-4ce484b5d81d.png)

I have two types of header (upcoming and past)
```
private fun getConvertedList(items: List<Appointment>): List<AppointmentModelView> =
            items.map { AppointmentModelView(it, AppointmentHeaderItem(it.status)) }
```
**AppointmentHeaderItem**
```
    private val headerId: Int
        get() = when (status) {
            Appointment.Status.APPROVED -> HEADER_UPCOMING
            else -> HEADER_OTHER
        }

    init {
        isSelectable = false
        isEnabled = false
    }

    override fun equals(other: Any?): Boolean {
        if (other is AppointmentHeaderItem) {
            return this.headerId == other.headerId
        }
        return false
    }

    override fun hashCode(): Int = headerId.hashCode()

    companion object {
        private const val HEADER_UPCOMING = 1
        private const val HEADER_OTHER = 2
    }
```
2. Another case. I created adapter globally in fragment. 
`private val adapter: FlexibleAdapter<AppointmentModelView>= FlexibleAdapter(listOf(), this)`
When fragment added onCreate and other lifecycle methods called but adapter with items already exists in global variables and it contains items.
The problem is in sticky headers they stoped working. All headers except first one become not sticky and first one is visible if scroll position at 0 but if I start scrolling it disappear and left only empty space.
![screenshot_1511251115](https://user-images.githubusercontent.com/17492722/33062482-7f29cfba-ceb0-11e7-99a7-e7e6e7793104.png)

Am I doing something wrong?

**Comment by davideas** [comment]
@PingForward, yes, don't keep the adapter or any others UI objects in permanent memory.
Regarding your first problem (related to my previous sentence), please check your `equals` method in the items. Only the business objects (the original list).

But I think that, all your problems seem not related to the Adapter itself, but the way you manage the objects in lifecycle.

**Comment by davideas** [comment]
@PingForward, If you don't have any update, I will close this issue.
