### ISSUE TITLE
How to handle configuration change easily?

### ISSUE THREAD

**Issue by krupalagile** [davideas/FlexibleAdapter#498]
How to handle configuration changes? Is there any other way without implementing parcelable for all header and child models?

**Comment by krupalagile** [comment]
There is no  way to parcel child  of parent headers as IFlexible does not extend Parcelable interface.

**Comment by davideas** [comment]
@krupalagile, configuration is applied only in case of selection, filter, and you need to call `adapter.onSaveInstanceState(outState);` as well as `adapter.onRestoreInstanceState(savedInstanceState);`

**Comment by krupalagile** [comment]
ok Thanks. close #498
