### ISSUE TITLE
Sticky Header can only be updated once

### ISSUE THREAD

**Issue by superandroidgirl** [davideas/FlexibleAdapter#499]
@davideas  It's worked when first update. But second time doesn't work.
Only got into bindViewHolder once. Cause I want to update stickyheader's UI per second.

Question: #496 

Any solution?
Thanks.

**Comment by davideas** [comment]
The issue occurs only if the update occurs on the same sticky header. If the sticky header changes then it receives the update.
I will try to identify the cause in the coming days.

**Comment by superandroidgirl** [comment]
Thanks for your reply.

**Comment by krupalagile** [comment]
Any update on this? I am stuck because of issue in production.

**Comment by superandroidgirl** [comment]
@krupalagile the updateOrClearHeader method in FlexibleAdapter 
when the sticky header updated once, thw position will store in lastHeaderUpdate. so it won't go inside twice.
just waiting for fixed by davideas .
private void updateOrClearHeader() {
           ...
                if (lastHeaderUpdate != mStickyHeaderHelper.getStickyPosition()) {
                    lastHeaderUpdate = mStickyHeaderHelper.getStickyPosition();
                    // #320 - To include adapter changes just notified we need a new layout pass:
                    // We must give time to LayoutManager otherwise the findFirstVisibleItemPosition()
                    // will return wrong position!
                    mRecyclerView.postDelayed(new Runnable() {
                        @Override
                        public void run() {
                            if (areHeadersSticky()) mStickyHeaderHelper.updateOrClearHeader(true);
                        }
                    }, 100L);
                }
            }
}

**Comment by davideas** [comment]
@superandroidgirl @krupalagile, thanks for the messages, indeed the part of the code not working well is in `updateOrClearHeader`, but not only! Others parts of code (remove/insert) have an impact and need to be adapted and I am still thinking how exactly.

I'm sorry that you have an urgency but being open source, I have my free time available and of course nobody commissioned me for this library. I thought that this was clear.

There's a fixed delay to update the sticky layout (now at 100ms which is a compromise) it is very important as from issue #320.

**Comment by krupalagile** [comment]
@davideas Thanks for replies. No worries. It is a very good library so we are dependent on it for many projects. Can you provide any temporary solution? It will be very useful for us.

**Comment by davideas** [comment]
A new snapshot that includes this fix has been published.
