### ISSUE TITLE
error with orientation change: mUserLearnedSelection doesn't work with selected items...

### ISSUE THREAD

**Issue by Rainer-Lang** [davideas/FlexibleAdapter#5]

**Comment by davideas** [comment]
Hello, thanks to have notified it. I knew it already.
This is my evaluation: the demo app is indeed a *demo*, therefore, in a real app `mUserLearnedSelection` is initialized reading the value from the settings. If user learned it by dismissing that row, settings value is different and you will not have the row again even after a rotation.

In this demo, the value must be always `false` to show always that row.
