### ISSUE TITLE
Sticky Header is not updating when updateDataSet.

### ISSUE THREAD

**Issue by krupalagile** [davideas/FlexibleAdapter#500]
Version : 5.0.0-SNAPSHOT 
Sticky Header is not updating when `updateDataSet `is called.
`onBindViewHolder `is not called.
After scrolling some items, it gets called.

**Comment by davideas** [comment]
@krupalagile, do you use stableIds and correctly implemented equals? it might depends by that.

**Comment by krupalagile** [comment]
I have passed false in hasStaleIds in FlexibleAdapter constructor.

**Comment by krupalagile** [comment]
The problem occurs when headers are expandable and sticky at the same time.

**Comment by davideas** [comment]
Duplicate of #499.
