### ISSUE TITLE
Any way to have sticky header without shadow (elevation)

### ISSUE THREAD

**Issue by ryc16** [davideas/FlexibleAdapter#502]
I am using 5.0.0-rc3. 

The header seems always to have the shadow (elevation). Is there a way to make the header flat?

mRecyclerView.addItemDecoration(new FlexibleItemDecoration(getActivity())
                .withDefaultDivider(R.layout.recycler_simple_item));

mAdapter.setLongPressDragEnabled(false)
                .setHandleDragEnabled(false)
                .setSwipeEnabled(false)
                .setStickyHeaderElevation(0)
                .setUnlinkAllItemsOnRemoveHeaders(true)
                .setDisplayHeadersAtStartUp(true)
                .setStickyHeaders(true);

![image](https://user-images.githubusercontent.com/5568006/33526888-60abd444-d882-11e7-892b-fff6c595bd04.png)

I created the adapter with item decorator for divider only and I also tied different value on HeaderElevation, for example, setStickyHeaderElevation(0) or commented out // setStickyHeaderElevation(0) but all looks the same.

Any idea?

Thanks

**Comment by davideas** [comment]
From my wiki page [Headers-and-Sections #Transparency-elevation-and-offset](https://github.com/davideas/FlexibleAdapter/wiki/5.x-%7C-Headers-and-Sections#transparency-elevation-and-offset).

**Comment by IstrateAndrei** [comment]
In the wiki page it says that you can either set the value from the layout file or call `setStickyHeaderElevation()`. 
I did both but nothing changed, the header shadow is still there

**Comment by davideas** [comment]
@IstrateAndrei, try to set both to 0. As per now, the logic of removing elevation requires both 0.
