### ISSUE TITLE
Dragging items has inconsistent and buggy behavior

### ISSUE THREAD

**Issue by SZenglein** [davideas/FlexibleAdapter#504]
Dragging items (via long press) is extremely buggy (especially) when the first item is involved. This can be reproduced in the demo app after closing the header.

I want to use this feature and I don't know if I can wait long enough for a fix. If you have any idea on how to fix this in my app I would appreciate it.

I've attached a video demonstrating the issue. It should be clear this is no minor issue.
![flexible-adapter-demo](https://user-images.githubusercontent.com/13049685/33627165-f00d989a-d9fc-11e7-9b46-ca5079a3d5d2.gif)

**Comment by davideas** [comment]
Sorry @SZenglein, the implementation of the drag and swipe features in this library is _not more nor less_ the one you could do, plus new sub-functionality related to the Adapter. Unfortunately, that behavior doesn't come from this library, but from the RecyclerView itself, I believe.
I also believe that behavior occurs _only_ with Staggered Layout, I agree with you that is not perfect but I disagree that is unusable.

You can try to fine tune some parameters, for that, I provide the internal callback implementation with `getItemTouchHelperCallback()` OR you can try to set one completely yours with the setter.
