### ISSUE TITLE
notifyDataSetChanged Adapter not work when one item in the list

### ISSUE THREAD

**Issue by majdirabeh** [davideas/FlexibleAdapter#505]
private List<AbstractFlexibleItem> abstractFlexibleItems = new ArrayList<>();
if (abstractFlexibleItems.size() != 0) {
            mAdapter = new FlexibleAdapter<>(abstractFlexibleItems);
            mRecyclerView.setLayoutManager(new SmoothScrollStaggeredLayoutManager(mContext, 2));
            mRecyclerView.setAdapter(mAdapter);
            mRecyclerView.setHasFixedSize(true);
            mRecyclerView.setItemAnimator(new DefaultItemAnimator());
            mAdapter.setDisplayHeadersAtStartUp(true).enableStickyHeaders();
            mAdapter.notifyDataSetChanged();
        } else {
            //configVisibilityInstant(true);
        }

if (mAdapter != null)
                    mAdapter.notifyDataSetChanged();

notifyDataSetChanged Not work when list contain one Item in the abstractFlexibleItems .

**Comment by davideas** [comment]
I'm sorry for you but it works, that is RecyclerView code.
However in phase of startup, probably there's no need to update since the items are still not rendered.
