### ISSUE TITLE
Improvement: Add method to IFlexible/AbstractFlexibleItem which is invoked by the adapter when RecyclerView.Adapter.onViewAttachedToWindow() is called

### ISSUE THREAD

**Issue by sandeep-voxer** [davideas/FlexibleAdapter#506]
When `RecyclerView.Adapter.onViewAttachedToWindow()` is invoked, it's guaranteed that the view was actually attached to the Window and most likely shown to the user. And correspondingly when `onViewDetachedFromWindow()` we know for sure that the user can no longer see the View.

There are some cases where we want to take action for individual items when these events happen  - (e.g) stop playing GIFs/videos so that they don't continue playing unnecessarily while the View is offscreen (this happens when using _Glide_).

Could you please add some callbacks to `IFlexible` that are called when these adapter methods are called?

**Comment by davideas** [comment]
@sandeep-voxer, what's the difference with `unbindViewHolder()` already in `IFlexible`?

**Comment by sandeep-voxer** [comment]
bind/unbind don't indicate that the View/Viewholder were scrolled in/out of
the RecyclerView - they are called when the view needs to be created and
bound. RecyclerView precreates and binds some adapter positions even if
they will not be shown.

**Comment by davideas** [comment]
If I understood well, you will use this callbacks only for audio/video, so they can be stopped if not visible, for images, they can stay in the view until unbound.

**Comment by sandeep-voxer** [comment]
Yes, audio/video/GIFs or any dynamic content whose state needs to be
changed based on when they are actually become visible/invisible to the
user.

**Comment by sandeep-voxer** [comment]
Awesome, thank you!
