### ISSUE TITLE
Sticky headers not shown after calling setLoadingMoreAtStartUp(true)

### ISSUE THREAD

**Issue by rmunk** [davideas/FlexibleAdapter#509]
#### FlexibleAdapter version: RC4

I am using endless scrolling to load some data for different _measurement sites_ from the server. I am using sticky headers to group the data by months into sections implementing [use case 1](https://github.com/davideas/FlexibleAdapter/wiki/5.x-%7C-Headers-and-Sections#1-use-case-similar-to-instagram-or-contacts) method.

User can switch the current _measurement site_ using a spinner. When user switches to a different _measurement site_ I call `adapter.clear()` to clear the old site data and then `adapter.setLoadingMoreAtStartUp(true)` to fetch the data for the newly selected site.

When `adapter.setLoadingMoreAtStartUp(true)` is called for the first time for some site sticky headers are shown normally. But when user later returns to previously selected site, data for the site is loaded but no sticky headers are shown for items that were previously displayed. If I scroll further down to get new items that weren't perviously loaded from the server headers are shown for them and all following items.

I have traced the reason to `getPendingRemovedItem(item)` in `FlexibleAdapter.showHeaderOf()` method not returning `null`, but this is as far as my understanding goes:
```
    private boolean showHeaderOf(int position, T item, boolean init) {
        // Take the header
        IHeader header = getHeaderOf(item);
        // Check header existence
        if (header == null || getPendingRemovedItem(item) != null) return false;
        if (header.isHidden()) {
            log.v("Showing header position=%s header=%s", position, header);
            header.setHidden(false);
            // Insert header, but skip notifyItemInserted when init=true!
            // We are adding headers to the provided list at startup (no need to notify)
            performInsert(position, Collections.singletonList((T) header), !init);
            return true;
        }
        return false;
    }
```

Should I do something more when I clear the adapter data to also clear this `mRestoreList` in the adapter?

**Comment by davideas** [comment]
@rmunk, if you were not recreating the headers, they keep the old hidden flag, so they appear shown. Try to reset the flag hidden to `true` for the headers.
When the previously selected site items are displayed the items will have their header too.

**Comment by davideas** [comment]
I guess you have the previously selected site saved somewhere, so their headers the flag to be shown. Or you recreate the adapter items from the original items or you save the adapter current list. Somewhere, you must have saved something.

**Comment by rmunk** [comment]
@davideas I abandoned this approach in favor of expandable sticky headers which I populate manually in `onLoadMore()`. But you were right, I tried resetting the hidden flag and it seemed to solve the problem. 
I think headers were being reused because they were in fact the same regardless of the site, they had year-month based `equals()` method so adapter was trying to reuse the items.
