### ISSUE TITLE
setHidden not working for sticky header

### ISSUE THREAD

**Issue by kagile** [davideas/FlexibleAdapter#510]
Library version : Snapshot

setHidden(true) is still showing headers in the case of sticky header recycler view.

**Comment by davideas** [comment]
@krupalagile, that setter only modifies the hidden flag.
If you want one particular header to not be shown anymore, you have to remove it from the adapter with others means, and coherently if you keep it in memory alive, reset the hidden flag to `true`.

Normally the headers are shown or hidden all together, so you should use the adapter functions.
