### ISSUE TITLE
Endless scroll with expandable headers

### ISSUE THREAD

**Issue by rmunk** [davideas/FlexibleAdapter#511]
Is it possible to implement endless scrolling behavior with expandable headers?

I have created adapter containing expandable header items with sub items following [use case 2](https://github.com/davideas/FlexibleAdapter/wiki/5.x-%7C-Headers-and-Sections#2-use-case-to-extendcollapse-a-section) method but I am not sure how to implement `onLoadMore` method. 

When I get the response with data from the server I create subitems and add them to corresponding headers. If header doesn't already exists I create a new one, otherwise I add the subitem to existing header:
```
final List<IFlexible> newHeaders = new ArrayList<>();
for (Measurement measurement : measurements) {
    MeasurementsHeaderItem header = new MeasurementsHeaderItem(measurement);
    int i = adapter.getHeaderItems().indexOf(header);
    if (i >= 0) header = adapter.getHeaderItems().get(i);
    else newHeaders.add(header);

    final MeasurementItem item = new MeasurementItem(measurement, header);
    header.addSubItem(item);
    adapter.addSubItem(adapter.getGlobalPositionOf(header), header.getSubItemPosition(item), item, true, null);
}
adapter.onLoadMoreComplete(newHeaders, 5000);
```
The problem is that I need to call `onLoadMoreComplete(newItems)` to complete the action of loading more items. I pass the new header items as newItems to the method and it works. But if all subitems belong to already existing headers then I call `onLoadMoreComplete` with an empty list and adapter concludes there are no more items to load which may not be the case.

**Comment by rmunk** [comment]
So this turned out to be RTFM issue :)

As stated in the [docs code example](https://github.com/davideas/FlexibleAdapter/wiki/5.x-%7C-On-Load-More#4-implement-the-endlessscrolllistener) I needed to call `adapter.setEndlessProgressItem(progressItem)` before calling `onLoadMoreComplete` to enable endless scrolling again.

@davideas this hint is currently in the example code comments so it is easy to miss. Maybe you could also write it down as a note in the docs.

**Comment by davideas** [comment]
@rmunk, Ok great you found it, I will try to make it more visible in the docs and java docs.
There is another way to keep it always enabled, but I would prefer to keep this way, so no further calls will be requested if not necessary. If necessary we just need to reset the item.
