### ISSUE TITLE
addListener has a @NonNull notation, but takes @Nullable listeners from constructor

### ISSUE THREAD

**Issue by jlwatkins** [davideas/FlexibleAdapter#514]
The addListener method says it takes a @NonNull, but handles the Null case. This makes it very hard to override this method when extending FlexibleAdapter.

**Comment by rusxakep** [comment]
Hi, you need check nullable too:

public FlexibleAdapter(@Nullable List<T> items, @Nullable Object listeners, boolean stableIds) {
        super(stableIds);
        // Copy of the original list
        if (items == null) mItems = new ArrayList<>();
        else mItems = new ArrayList<>(items);
        // Initialize internal lists
        mScrollableHeaders = new ArrayList<>();
        mScrollableFooters = new ArrayList<>();
        mRestoreList = new ArrayList<>();
        mUndoPositions = new ArrayList<>();

        // Create listeners instances
        if (listeners != null) addListener(listeners);

        // Get notified when items are inserted or removed (it adjusts selected positions)
        registerAdapterDataObserver(new AdapterDataObserver());
}
