### ISSUE TITLE
Improve documentation for Sticky Headers

### ISSUE THREAD

**Issue by skimarxall** [davideas/FlexibleAdapter#515]
While implementing sticky header it took me some time to figure out why the holder for the sticky header was causing a null pointer. It was called twice when updating it and on the second call the itemView is just a FrameLayout, thus the findView was null, instead, contentView should be used. 

I could not find this in the documentation. Also worth to mention that if contentView is not used the sticky header won't update.

**Comment by davideas** [comment]
@skimarxall, I added another sentence to the point 3 of [Sticky Header](https://github.com/davideas/FlexibleAdapter/wiki/5.x-%7C-Headers-and-Sections#sticky-headers) wiki.
