### ISSUE TITLE
Section gap is gone when expand the last item of section

### ISSUE THREAD

**Issue by steventxc** [davideas/FlexibleAdapter#516]
as above describe, when the section contains a expandable item at last, expand it, the gap is gone, but collapse it, the gap is visible as normal. it's weird. any suggestion for it ? thx.

**Comment by steventxc** [comment]
collapsed
![104245](https://user-images.githubusercontent.com/1559916/34806337-4d772d8e-f6bd-11e7-8835-8ad6c9d7ac49.png)

expanded:
![104310](https://user-images.githubusercontent.com/1559916/34806338-4f8b0dd4-f6bd-11e7-8a03-9b93dfaa3cf8.png)

**Comment by steventxc** [comment]
collapsed:
![104245](https://user-images.githubusercontent.com/1559916/34806399-97186a16-f6bd-11e7-9992-78c62595f132.png)

expanded:
![104310](https://user-images.githubusercontent.com/1559916/34806405-9ea44674-f6bd-11e7-83b8-264e8ab32e0f.png)

**Comment by davideas** [comment]
Could you call `invalidateItemDecorations(delay)` when expanding?
The RV should apply the decoration to the current view, but is calculated and applied if the next item is a header. So we insert a new view type the decoration is lost.

**Comment by steventxc** [comment]
@davideas I'm not sure where to insert ```invalidateItemDecorations(delay) ``` method.
i try insert code these place:

1.  in ```ExpandableViewHolder```:

        @Override
        protected boolean shouldNotifyParentOnClick() {
            return true;
        }

        @Override
        protected void expandView(int position) {
            mAdapter.invalidateItemDecorations(100);
            super.expandView(position);
        }

2. in ```AbstractExpandableItem``` :

		@Override
    	public void bindViewHolder(FlexibleAdapter adapter, ES_ViewHolder holder, int position, List<Object> payloads) {
        	holder.tv_userName.setText(userName);
        	holder.tv_suggestion.setText(suggestion);
        	holder.iv_status.setImageResource(iconRes);
        
        	adapter.invalidateItemDecorations(100);
    	}
    	
3. in ```Fragment``` when init adapter:
		
		
	```
	List<ISectionable> list = new ArrayList<>();

	// section 1
	FDHeader header1 = new FDHeader(1, "Header 1");
	FDEatableSection section1 = new FDEatableSection(header1, "section1_1",
                        null, R.drawable.ic_eat_half);
	section1.addSubItem(new FDEatableSubItem(0, "section sub 1_1_1"));
	list.add(section1);

	// section 2
	FDHeader header2 = new FDHeader(2, "Header 2");

	FDEatableSection section2_1 = new FDEatableSection(header2, "section2_1", 
                        null, R.drawable.ic_eat_half);
	section2_1.addSubItem(new FDEatableSubItem(1, "section sub 2_1_1"));
	section2_1.addSubItem(new FDEatableSubItem(2, "section sub 2_1_2"));
	list.add(section2_1);

	// ....

	mAdapter = new FlexibleAdapter<ISectionable>(list,
                        FoodDetailFragment1.this, true);

	mAdapter.setDisplayHeadersAtStartUp(true)
        .setMinCollapsibleLevel(1) 
        .setAutoCollapseOnExpand(true)
        .expandAll(0); 


	recyclerView.setAdapter(mAdapter);
	recyclerView.addItemDecoration(new FlexibleItemDecoration(_mActivity)
                        .withSectionGapOffset(24));
   
   // i'm not sure this is necessary             
	mAdapter.invalidateItemDecorations(100);
                
	```
	
	
but all above are not work. :(

especially the third point, some items will expand at the beginning, how could i handle the gap?

**Comment by davideas** [comment]
@steventxc, try 1st point after the super() call since the expand occurs inside there.

**Comment by steventxc** [comment]
@davideas i followed your instruction, but it was not work. 
so i put my code in this [address](https://github.com/steventxc/FlexibleAdapterTest), am i do something wrong?

**Comment by davideas** [comment]
@steventxc, the `FDSubItem` is not a `ISectionable` type, when I created the gap, it was only for 1 level of section with items of type ISectionable.
But now I need more time, I'm too busy in these days.

**Comment by steventxc** [comment]
@davideas Thanks your time and help.
 It's work when I implement the `ISectionable` interface.

**Comment by davideas** [comment]
@steventxc, but which header do you assign? I tried and when no header is assigned it works, but it will have an impact for your sticky header if activated, it won't work as expected.
I will have to find another way to create the gap. please keep this issue opened.

**Comment by davideas** [comment]
This will be the condition to apply section gap from the next version:
``` java
// IMPORTANT: the check must be done on the BOTTOM of the section,
// otherwise the sticky header will jump!
if (flexibleAdapter.isHeader(nextItem)) {
    Log.v("applySectionGap position=%s", position);
    if (orientation == RecyclerView.VERTICAL) {
        outRect.bottom += mSectionOffset;
    } else {
        outRect.right += mSectionOffset;
    }
}
if (position >= adapter.getItemCount() - mSectionGapOnLastItem) {
    Log.v("applySectionGapOnLastPosition position=%s", position);
    if (orientation == RecyclerView.VERTICAL) {
        outRect.bottom += mSectionOffset;
    } else {
        outRect.right += mSectionOffset;
    }
}
```

But for `IExpandable`, we will have always to invalidate the item decoration when expanding and collapsing, if the expandable is the last item of the section!

**Comment by davideas** [comment]
I was smarter and I was able to identify the header of the section anyway. That's why sticky header works if you don't apply any header. However, i think is not good to implement `ISectionable` just to have the gap, the interface covers another purpose.

**Comment by steventxc** [comment]
@davideas  as you said above, in my project, i never assign any header for subitem, just implement `ISectionable`,  it works fine :)
thanks for your excellent and also SMART job! 😁
