### ISSUE TITLE
[Support] Add item to sticker expandable recyclerview ?

### ISSUE THREAD

**Issue by mdtuyen** [davideas/FlexibleAdapter#518]
I want to add more item to sticker expandable recyclerview with follow.
1. Check if header item exist (use for check all header of adapter)
2. Add Item into that header
3. Expandable

=> Dupplicate item (problem with function adapter.expand(item, true))
Solution: 
Add 
3': collape item then expand

That follow make more code and complex. 
Do you have an other flow for that ?

**Comment by davideas** [comment]
@mdtuyen, for subItems you have to insert with `addSubItem()` method, so it will be inserted. Unfortunately you need to calculate the position with `calculatePosition()`.

**Comment by mdtuyen** [comment]
@davideas 
As you said I must collape and expand to update header item ?

**Comment by davideas** [comment]
`addSubItem()` will automatically notify the parent about the change of its sub list.
So you will receive another call in `bindViewHolder` of the parent item.
