### ISSUE TITLE
Feedback flexibleadapter gradle problem

### ISSUE THREAD

**Issue by tcqq** [davideas/FlexibleAdapter#520]
Hi davidea, i was trying to submit a project to bintray using gradle in FlexibleAdapter, but when I ran the "gradlew install" code, an exception occurred and what am I doing wrong? How should I modify?
![image](https://user-images.githubusercontent.com/10644057/35078344-cfdd5580-fc3c-11e7-9783-e26b7d5b6b88.png)
![image](https://user-images.githubusercontent.com/10644057/35078350-d60c1e0a-fc3c-11e7-8e72-10ecfde668aa.png)
![image](https://user-images.githubusercontent.com/10644057/35078351-d9edb5f6-fc3c-11e7-93c1-01c3fa726560.png)

**Comment by davideas** [comment]
@tcqqm, you have to run `gradlew install -P ` with property `adapter` if you want only the adapter to be in the maven repository. Possible options are:
```
-P all
-P adapter
-P ui
-P livedata
-P databinding
```

**Comment by tcqq** [comment]
I run: gradlew install -P adapter, but have error

![image](https://user-images.githubusercontent.com/10644057/35101207-a75aa4b6-fc99-11e7-99d9-9a0f60803eb8.png)

**Comment by tcqq** [comment]
__error log__

> Task :flexible-adapter:javadoc
Unable to find the 'javadoc' executable. Tried the java home: C:\Program Files (x86)\Java\jre1.8.0_131 and the PATH. We will assume the executable can be ran in the current working folder.


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flexible-adapter:javadoc'.
> Javadoc generation failed. Generated Javadoc options file (useful for troubleshooting): 'H:\AndroidProject\FlexibleAdapter\flexible-adapter\build\tmp\javadoc\javadoc.options'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 20s
19 actionable tasks: 19 executed

**Comment by davideas** [comment]
@tcqq did you resolve the javadoc execution?
That is part of Java/bin folder, you should have in the PATH.

**Comment by tcqq** [comment]
"did you resolve the javadoc execution?"
-No, I tried for a long time, but always have javadoc error
“That is part of Java/bin folder, you should have in the PATH.”
-What should I do now?
