### ISSUE TITLE
Example  of how to implement a staggered layout with sticky headers

### ISSUE THREAD

**Issue by jrcacd** [davideas/FlexibleAdapter#521]
Is there an example of how to implement a staggered layout with sticky headers as showed in your [screenshot](https://github.com/davideas/FlexibleAdapter/blob/master/screenshots/demo20_dynamic_staggered_layout.png)?

**Comment by davideas** [comment]
@jrcacd, the difference from grid and linear is of course the LayoutManager and the full span support for the item identified as header.
``` java
// In the ViewHolder constructor
setFullSpan(true);
```
Which perform this code in `FlexibleViewHolder`:
``` java
/**
 * Support for StaggeredGridLayoutManager.
 *
 * @param enabled true to enable full span size, false to disable
 */
public void setFullSpan(boolean enabled) {
    if (itemView.getLayoutParams() instanceof StaggeredGridLayoutManager.LayoutParams) {
        ((StaggeredGridLayoutManager.LayoutParams) itemView.getLayoutParams())
            .setFullSpan(enabled);
    }
}
```

**Comment by jrcacd** [comment]
My header must inherit from which one: FlexibleViewHolder, AbstractHeaderItem, AbstractSectionableItem?

**Comment by davideas** [comment]
The item form `AbstractHeaderItem`, and the Holder from `FlexibleViewHolder` as the documentation paying attention at the constructor parameters (see docs).

**Comment by jrcacd** [comment]
Apparently I've make. But I seem to have found a mistake.

When I scroll and the last item before the next heading is in the left column, it works fine, meaning the next heading hinges on the previous one and pushes it up.

When I scroll and the last item before the next heading is in the right column (I only have 2 columns) the next heading disappears from where it is and jumps to the top (to the place where the previous heading was)

**Comment by davideas** [comment]
@jrcacd, yes I see it also in the demoApp.
I will have to investigate what is the cause, probably the `findFirstVisibleItemPositions(null)[0]` is not good.
Is that array referring to the column span?

**Comment by jrcacd** [comment]
Yes

**Comment by jrcacd** [comment]
Great!!!
