### ISSUE TITLE
How to implement ActionModeHelper multiselect in a fragment?

### ISSUE THREAD

**Issue by jrcacd** [davideas/FlexibleAdapter#522]
I followed [5.x | ActionModeHelper](https://github.com/davideas/FlexibleAdapter/wiki/5.x-%7C-ActionModeHelper) but I didn't get it working.

**Comment by davideas** [comment]
@jrcacd, normally I've implemented the ActionMode only in Activities, for Fragments it should works as well, just implement the callback `ActionMode.Callback`.
