### ISSUE TITLE
"getCardinalPositionOf" issue when using sticky headers

### ISSUE THREAD

**Issue by iskugor** [davideas/FlexibleAdapter#524]
Hello. :)

I'm using latest RC4 version of FlexibleAdapter.
I'm trying to get position of clicked item without taking sticky header items into account. I registered "OnItemClickListener" listener in which I get global position as callback function parameter. To get item position without taking header items into account I used "getCardinalPositionOf":

`
int cardinalPosition = adapter.getCardinalPositionOf(adapter.getItem(position));
`

but that doesn't seems to work with sticky headers?
(I get the same value as position)

I can get that position manually, but it would be nice if it worked with FlexibleAdapter.

Also, it would be really great if we could define if header are clickable and if not we would get item position in click event callback without taking header items into account.

Thanks!

**Comment by davideas** [comment]
@iskugor, easy to answer: `getSubPositionOf(item)`.
But always read the javaDoc of the methods.

**Comment by iskugor** [comment]
@davideas thanks for your answer, but I think you misunderstood the question. "getSubPositionOf" will return position of item in section, but what I want to get is position of item as if no sections were there.

For example:

> Section1
> Item1
> Section2
> Item2
> Item3

If I click on Item3, in callback as position I'll get 4, "getSubPositionOf" will return 1, but what I need is 2.
So, Section1 and Section2 are just ignored.


I checked JavaDoc and I assumed "getCardinalPositionOf" does that:

> Retrieves the position of the Main item in the Adapter list excluding the scrollable Headers.

But I checked code and it seems it just take scrollable headers into account and not sticky headers.


This is my function I use to get correct position:

`
protected int getFixedPosition(int position) {

	if (mAdapter.getItemCount() > position) {

		IFlexible item = mAdapter.getItem(position);

		List<IHeader> headerItems = mAdapter.getHeaderItems();

		IHeader itemHeader = mAdapter.getHeaderOf(item);

		return position - (headerItems.indexOf(itemHeader) + 1);

	}

	return position;
}
`


Hope you understand now. :)

**Comment by davideas** [comment]
@iskugor, yes I see it now, but I don't think I will add it in the Adapter.

**Comment by iskugor** [comment]
@davideas sorry to hear that. :( I think this has some applications in real world, in lots of cases you don't want sections / sticky headers to be clickable and without having this functionality you need to manually check what received click event and calculate correct position in list. The best example is contact list with first letters as sections / sticky headers.

**Comment by davideas** [comment]
@iskugor, the item must have an unique identifier, adapter position is relative to the view.
