### ISSUE TITLE
FlexibleAdapter setLayoutManager use FlexboxLayoutManager Error

### ISSUE THREAD

**Issue by tcqq** [davideas/FlexibleAdapter#525]
In FlexibleAdapter setLayoutManager use FlexboxLayoutManager have error.

# Error:
java.lang.ClassCastException: android.support.v7.widget.RecyclerView$LayoutParams cannot be cast to com.google.android.flexbox.FlexItem
                                                                   at com.google.android.flexbox.FlexboxHelper.calculateFlexLines(FlexboxHelper.java:438)
                                                                   at com.google.android.flexbox.FlexboxHelper.calculateVerticalFlexLines(FlexboxHelper.java:316)
                                                                   at com.google.android.flexbox.FlexboxLayoutManager.updateFlexLines(FlexboxLayoutManager.java:957)
                                                                   at com.google.android.flexbox.FlexboxLayoutManager.onLayoutChildren(FlexboxLayoutManager.java:716)
                                                                   at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3719)
                                                                   at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3436)
                                                                   at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3988)

# Activity.java:
``` java
private void initRecyclerView() {
    mAdapter = new PublishChooseSkillsAdapter(getDatabaseList(), this);
    mAdapter.setNotifyMoveOfFilteredItems(true)
            .setAnimationOnForwardScrolling(true);
    mRecyclerView = findViewById(R.id.recycler_view);
    mRecyclerView.setAdapter(mAdapter);

    FlexibleFlexboxLayoutManager layoutManager = new FlexibleFlexboxLayoutManager(getContext());
    layoutManager.setFlexDirection(FlexDirection.COLUMN);
    layoutManager.setJustifyContent(JustifyContent.FLEX_END);
    mRecyclerView.setLayoutManager(layoutManager);

    mRecyclerView.setHasFixedSize(true); //Size of RV will not change
    mRecyclerView.setItemAnimator(new DefaultItemAnimator());

    // More settings
    mAdapter
            // Show Headers at startUp, 1st call, correctly executed, no warning log message!
            .setDisplayHeadersAtStartUp(true)
            .setStickyHeaders(true);
}
```
# FlexibleFlexboxLayoutManager.java
``` java
public class FlexibleFlexboxLayoutManager extends FlexboxLayoutManager implements IFlexibleLayoutManager {

    public FlexibleFlexboxLayoutManager(Context context) {
        super(context);
    }

    public FlexibleFlexboxLayoutManager(Context context, int flexDirection) {
        super(context, flexDirection);
    }

    public FlexibleFlexboxLayoutManager(Context context, int flexDirection, int flexWrap) {
        super(context, flexDirection, flexWrap);
    }

    public FlexibleFlexboxLayoutManager(Context context, AttributeSet attrs, int defStyleAttr, int defStyleRes) {
        super(context, attrs, defStyleAttr, defStyleRes);
    }

    @Override
    public int getOrientation() {
        return OrientationHelper.VERTICAL;
    }

    @Override
    public int getSpanCount() {
        return 1;
    }
}
```

**Comment by tcqq** [comment]
I think you should use an
`<addr>` element here instead.

**Comment by davideas** [comment]
@tcqq, I've investigated the reason of the possible incompatibility, the `FlexboxLayoutManager` extends _only_ `generateLayoutParams(Context c, AttributeSet attrs)` and not `generateLayoutParams(ViewGroup.LayoutParams lp)` which I'm calling from ContentViewHolder when item is a sticky header. So the LayoutParams are not of the same type.

But it's impossible to get the AttributeSet to pass there! Isn't it?
Could you implement / override `LayoutParams generateLayoutParams(ViewGroup.LayoutParams lp)` in your `FlexibleFlexboxLayoutManager`? basically, doing this we take the new type `LayoutParams` declared by that specific LayoutManager and not the super type.

Copied from the super type:
``` java
public RecyclerView.LayoutParams generateLayoutParams(ViewGroup.LayoutParams lp) {
    if (lp instanceof RecyclerView.LayoutParams) {
        return new RecyclerView.LayoutParams((RecyclerView.LayoutParams) lp);
    } else if (lp instanceof ViewGroup.MarginLayoutParams) {
        return new RecyclerView.LayoutParams((ViewGroup.MarginLayoutParams) lp);
    } else {
        return new RecyclerView.LayoutParams(lp);
    }
}
```
If it works, Android team should officially override that method, I guess. We will open a ticket on their side.

**Comment by tcqq** [comment]
I tried for a long time, but still error, how should I modify "FlexibleFlexboxLayoutManager.java" is correct?

**Comment by davideas** [comment]
@tcqq, paste here that class.

I think, with that method it should work.

**Comment by tcqq** [comment]
**MainActivity.java** 
    /**
     * Init recycler view.
     */
    private void initRecyclerView() {
        mAdapter = new PublishChooseSkillsAdapter(mItems, this);
        mAdapter.setNotifyMoveOfFilteredItems(true);
        mRecyclerView = findViewById(R.id.recycler_view);
        mRecyclerView.setAdapter(mAdapter);
        mRecyclerView.setLayoutManager(new FlexibleFlexboxLayoutManager(getContext(), FlexDirection.ROW, FlexWrap.WRAP));
        mRecyclerView.setHasFixedSize(true);
        mRecyclerView.setItemAnimator(new DefaultItemAnimator());

        // More settings
        mAdapter
                // Show Headers at startUp, 1st call, correctly executed, no warning log message!
                .setDisplayHeadersAtStartUp(true)
                .setStickyHeaders(true);
    }

    /**
     * Init skills data.
     */
    private void initSkillsData() {
        // 获取并解析 Json
        String testData = "{\"result\":{\"message\":\"success\",\"code\":200},\"data\":{\"skills\":[{\"name\":\"Header 0\",\"id\":0,\"abilities\":[{\"name\":\"Simple Item 0\",\"id\":0},{\"name\":\"Simple Item 1\",\"id\":1}]},{\"name\":\"Header 1\",\"id\":1,\"abilities\":[{\"name\":\"Simple Item 2\",\"id\":2}]}]}}";

        PublishChooseSkillsModel publishChooseSkills = DataUtil.toModel(testData, PublishChooseSkillsModel.class);

        Observable
                .just(publishChooseSkills)
                .flatMap(skills -> Observable.fromIterable(skills.getData().getSkills()))
                .doOnNext(skills -> mHeaderItem = newSkillsHeaderItem(skills.getId(), skills.getName()))
                .flatMap(skills -> Observable.fromIterable(skills.getAbilities()))
                .subscribe(new Observer<PublishChooseSkillsModel.Data.Skills.Abilities>() {
                    @Override
                    public void onSubscribe(Disposable d) {
                        mItems.clear();
                    }

                    @Override
                    public void onNext(PublishChooseSkillsModel.Data.Skills.Abilities abilities) {
                        mItems.add(newAbilitiesItem(abilities.getName(), abilities.getId(), mHeaderItem));
                    }

                    @Override
                    public void onError(Throwable e) {
                        LogKit.error(e.getMessage());
                    }

                    @Override
                    public void onComplete() {

                    }
                });
    }

    /**
     * New skills header item.
     *
     * @param id   The id of skills
     * @param name The name of skills
     * @return The skills header item
     */
    public PublishChooseSkillsHeaderItem newSkillsHeaderItem(int id, String name) {
        PublishChooseSkillsHeaderItem headerItem = new PublishChooseSkillsHeaderItem("skills" + id);
        headerItem.setSkillName(name);
        return headerItem;
    }


    /**
     * New abilities item.
     *
     * @param name   The name of abilities
     * @param id     The id of abilities
     * @param header The header of abilities
     * @return The abilities item
     */
    public PublishChooseSkillsItem newAbilitiesItem(String name, int id, IHeader header) {
        PublishChooseSkillsItem item = new PublishChooseSkillsItem("abilities" + id, (PublishChooseSkillsHeaderItem) header);
        item.setAbilitiesName(name);
        return item;
    }

**FlexibleFlexboxLayoutManager.java**
public class FlexibleFlexboxLayoutManager extends FlexboxLayoutManager implements IFlexibleLayoutManager {

    public FlexibleFlexboxLayoutManager(Context context) {
        super(context);
    }

    public FlexibleFlexboxLayoutManager(Context context, int flexDirection) {
        super(context, flexDirection);
    }

    public FlexibleFlexboxLayoutManager(Context context, int flexDirection, int flexWrap) {
        super(context, flexDirection, flexWrap);
    }

    public FlexibleFlexboxLayoutManager(Context context, AttributeSet attrs, int defStyleAttr, int defStyleRes) {
        super(context, attrs, defStyleAttr, defStyleRes);
    }

    public RecyclerView.LayoutParams generateLayoutParams(ViewGroup.LayoutParams lp) {
        if (lp instanceof RecyclerView.LayoutParams) {
            return new FlexboxLayoutManager.LayoutParams((RecyclerView.LayoutParams) lp);
        } else if (lp instanceof ViewGroup.MarginLayoutParams) {
            return new FlexboxLayoutManager.LayoutParams((ViewGroup.MarginLayoutParams) lp);
        } else {
            return new FlexboxLayoutManager.LayoutParams(lp);
        }
    }

    @Override
    public int getOrientation() {
        return OrientationHelper.VERTICAL;
    }

    @Override
    public int getSpanCount() {
        return 1;
    }
}

**Comment by tcqq** [comment]
@davideas I follow the above code changes after, the "Simple Item" has not happen change, what is the reason? What did i do wrong?

**Comment by davideas** [comment]
@tcqq, sorry but I can't look into details in any issues, it's your layout, your code. Please investigate or ask question in stackoverflow website, eventually.
If something is wrong in the library we will fix it.

**Comment by tcqq** [comment]
Yes, but my code used is the code provided in this library document：https://github.com/davideas/FlexibleAdapter/wiki/5.x-%7C-Thirds-Layout-Managers 
It took me a long time to check my own code, but I did not in my code check out problem, however, the displayed effect is not the same as described in the document.
