### ISSUE TITLE
How to Add OnSubItemClickListeners?

### ISSUE THREAD

**Issue by shahzi8285** [davideas/FlexibleAdapter#527]
There is a problem with me that I do some operations on Subitem Click and when Operation has done,Item moves in another Expendable Header..I have Wasted two day..Please Help

Newbie Programmer :(

**Comment by davideas** [comment]
@shahzi8285, question is a unclear, however I try to answer:
- Current version: the click listener callback has the position only, you take the item from the adapter and check which type is: `instanceof Parent` or `instanceof Child` based on that you do the operation you need.
- Next version (I am already on working on it): in the callback you'll also receive the View object, so you can check the ViewId directly to distinguish which itemView OR which sub view in the item received the click event.

The click listener on itemView is already registered, you only need to implement the Adapter `OnItemClickListener` in your fragment/activity. Read the methods javaDoc, always.
