### ISSUE TITLE
Filter using interface rather than just a string

### ISSUE THREAD

**Issue by andrewlord1990** [davideas/FlexibleAdapter#53]
Rather than just passing a String constraint to the filter method, it would be nice if you could pass an interface along the lines of:

`boolean isAllowed(T item)`

The item would be passed to the `isAllowed` method and allow you to filter items with different conditions.

I am happy to work on a PR for this. Just wanted to check if this was something you were interested in supporting.

**Comment by davideas** [comment]
@andrewlord1990, thanks for the message.
In the Item that implements _IFilterable_ you already have access to its fields to evaluate different conditions relative to that item. Even more, you can still override the _filterObject(T item, String constraint)_, so you have 2 solutions, we don't need _isAllowed()_.

**Comment by andrewlord1990** [comment]
Ahh. Sorry, I was looking on the master branch which is the default branch when you open the repo page. This functionality doesn't exist there.

**Comment by davideas** [comment]
np, I have to work more to put it on master :-)
