### ISSUE TITLE
[Enhancement] Add left/right margin for dividerDecorator

### ISSUE THREAD

**Issue by AngeloAvv** [davideas/FlexibleAdapter#531]
Hi,
when using cards, the better way to keep their layout good is to adding left/right margins to these items instead of using padding inside recyclerView. But when using margin, the dividers overlap the card. 

Could it be possible as enhancement to configure a margin for the dividers, or is it better to create a custom divider with margins?

Could it also be an enhancement to decide where to put dividers at runtime, especially when using sections/headers items?

**Comment by davideas** [comment]
@AngeloAvv, thanks for the message.
Probably is better to create a custom divider with margins, because I don't have free time to dedicate on the decorator now.

**Comment by AngeloAvv** [comment]
I solved the problem inheriting the decorator class and adding a custom method to put left/right margins to the divider. If you want I can create a pull request so you can merge the snippet inside the original decorator.

**Comment by davideas** [comment]
Ok, why not I will check it out. Grazie Angelo.
