### ISSUE TITLE
Conditional placement of items in gridlayout

### ISSUE THREAD

**Issue by jcuypers** [davideas/FlexibleAdapter#532]
Hi, I'm looking for ideas on how I could customize or extend gridlayout to behave in the following way: I would like to have vertical, 2 (n) column gridlayout with 2 item types of which one is a header and the other a plain item. this is still standard, and I understand I can play with the getspansize to arrange things a bit. What i would like to achieve is that I could arrange the plain items (non-header) according to some kind of category. let's say: each item (of same type) is span size=1 and can be in a category A/B. if an item is in category A it should only be layout on the left side , if category B it should be layout on the right side. the number of items can be in-equal. 3 left. 7 right.
```
Header item  (2 span)
 Cat A (1sp)     Cat B(1sp)
 Cat A (1sp)     Cat B(1sp)
 Cat A (1sp)     Cat B(1sp)
 (empty)           Cat B(1sp)
 (empty)                  ....
```
I general I think i can achieve this behavior in two ways. adding empty/dummy items as many as any category is long or extend the grid layoutmanager to perform this behavior.

any ideas are welcome.

**Comment by davideas** [comment]
I would suggest to write your own GridLayoutManager or overriding some key functions of the official one or looking for something existent. I can't help more since I need to investigate on it.

Thanks for the question by the way.
