### ISSUE TITLE
setAutoScrollOnExpand(true) should try to make all expanded subitems totally visible if possible

### ISSUE THREAD

**Issue by Shikou** [davideas/FlexibleAdapter#533]
Especially when you only have one single big SubItem. It will be nice if auto scroll on expand tried to scroll enough (without hiding the parent item) to make the entire SubItem visible.

**Comment by davideas** [comment]
The auto scroll is calculated in this private function: `autoScrollWithDelay()`. it is a complex calculation that works well. I never tried with one big subitem bigger than the screen, but it takes into account the first and last completely visible item positions that could _possibly_ hide the parent in that particular situation.
By making sticky the parent item you should resolve your issue. I believe.
You might also disable the internal auto scroll and make your own simpler to manage the big item as per your specific use case.
