### ISSUE TITLE
setHasStableIds has exception

### ISSUE THREAD

**Issue by meness** [davideas/FlexibleAdapter#535]
Please check off the following points BEFORE submitting a new issue / asking support.
- [x] Write a self explanatory Subject.
- [x] Check if the issue has already been raised by someone else (see closed issue).

Calling `setHasStableIds(true)` throws `Cannot change whether this adapter has stable IDs while the adapter has registered observers`

```java
public ContactAdapter(@Nullable List<ContactItem> items) {
        super(items);
        setHasStableIds(true);
        setStickyHeaders(true);
    }
```

**Comment by davideas** [comment]
@meness, if you really need a custom adapter, please use the correct `super()` constructor.
