### ISSUE TITLE
Filtering doesn't work properly

### ISSUE THREAD

**Issue by meness** [davideas/FlexibleAdapter#536]
Please check off the following points BEFORE submitting a new issue / asking support.
- [x] Write a self explanatory Subject.
- [x] Check if the issue has already been raised by someone else (see closed issue).

```java
@Override
    public boolean onQueryTextChange(String query) {
        contactAdapter.setSearchText(query);
        contactAdapter.filterItems(400);
        return true;
    }
```

```java
contactAdapter = new ContactAdapter(null);

        rvList.setHasFixedSize(true);
        rvList.setAdapter(contactAdapter);

for (Pair<ContactEntity, List<ContactEntity>> contactEntity : ContactUtils.fetchGroups(getApplicationContext())) {
            contactAdapter.addItem(new ContactItem(contactEntity.first, new ContactHeaderItem(R.string.title_contacts_groups)));
        }
        for (ContactEntity contactEntity : ContactUtils.getContacts(getApplicationContext())) {
            contactAdapter.addItem(new ContactItem(contactEntity, new ContactHeaderItem(R.string.title_contacts)));
        }

        contactAdapter.setDisplayHeadersAtStartUp(true);
```

```java
@Override
    public boolean filter(String constraint) {
        return entity.getName().toLowerCase().contains(constraint);
    }
```

Filtering has two problems, it shows **duplicate items** and after clearing the search query, some items would be disappeared and theirs positions would be wrong.

**Comment by meness** [comment]
Setting unique hash codes and enabling stable ids fixed the problem.

**Comment by davideas** [comment]
@meness Good you resolved. JavaDoc and online Wiki can help you a lot in many situations.
I'm going to change the filter object. It will be of any type, so you will have to adapt it when I will release the final version.
