### ISSUE TITLE
[5.0.0-rc4] updateDataSet calls animation when 'animate' parameter is 'false'

### ISSUE THREAD

**Issue by Str4tocaster** [davideas/FlexibleAdapter#541]
Hello. I try to use FlexibleAdapter in our XMPP-client app - Xabber.
I have: compileSdkVersion 26, test on API 25
I enjoy to work with this adapter, but i also have one trouble.

When i call adapter.updateDataSet(items, false) - recyclerView always start update animation, although i set animate: false. Update animation do not start only if i called recyclerVIew.setItemAnimator(null). But in this case recyclerView do not have all animations. 

I need to have all standard animations except update animation. How can I achieve this behavior?Thanks.

**Comment by Str4tocaster** [comment]
I found information about it in https://github.com/davideas/FlexibleAdapter/issues/230. So i just set stableids = false in FlexibleAdapter constructor and this works like i need.
But i have one question - if i set stableids = false, is it reduce list performance? Thanks.

**Comment by davideas** [comment]
@Str4tocaster, Thank you for your choice.
In issue #230 I talked about setting stableIds `true`, so only the newly added/removed items will animate. Indeed having `false` it is like to call directly `notifyDataSetChanged()` (`updateDataSet()` calls it) that will bound again _all_ items, so performance are reduced.

With stableIds = true, the RecyclerView will be responsible to find the new items and will animate only them.
To know more I invite you to make some combination experiments with these 2 flags: _stableIds_ (constructor) and _animate_ (updateDataSet).
