### ISSUE TITLE
[5.0.0-rc4] List with EndlessScroll does not maintain scroll position in orientation change

### ISSUE THREAD

**Issue by pmellaaho** [davideas/FlexibleAdapter#542]
Hello, Thanks for the great work!

I have been playing with your library a little. I managed to get the EndlessScrolling to work but It seems like the scroll position is not maintained correctly if the user has scrolled down from the first page items. 

I tried calling these but it didn't help
adapter.onSaveInstanceState(outState);
adapter.onRestoreInstanceState(savedInstanceState);

I suppose library could call onLoadMore automatically after orientation change to restore all the adapter items. I also tried returning all the items with the updateDataSet after orientation change but that didn't help either.

**Comment by davideas** [comment]
@pmellaaho, configuration changes is supported for selection, filter and sticky header, but when we rotate, all code is performed again, so you need to switch mode by checking if `savedInstanceState != null` you take the existent list from your service/database and you initialize the adapter with it.
Endless scrolling won't be triggered from beginning.

If you use ViewModels and LiveData, then, the existent list is provided auto-magically.

**Comment by pmellaaho** [comment]
Ok, I see what you mean. In my case it's easier to store the adapter in the presenter and when orientation change happens I just fetch the adapter and set it to RecyclerView. This way I can maintain the scroll position but for some reason the headers are not sticky anymore?  

I can see that in the fresh start the order of events is a bit different, because setStickyHeaders(true) is being called before items are added to adapter (updateDataSet()) and in orientation change case I'm not sure if I should call setStickyHeaders() at all, does not seem to make difference.

**Comment by davideas** [comment]
You forgot that the reference of RV will change, so don't save the adapter, recreate it, just keep the original list.
