### ISSUE TITLE
ActionModeHelper: double longclick on same item crashes!

### ISSUE THREAD

**Issue by jrcacd** [davideas/FlexibleAdapter#545]
If longclick to selecd one item and then long click on the same item gives error.

**Comment by davideas** [comment]
@jrcacd, demoApp selection modes example doesn't crash if 2 consecutive long clicks.

**Comment by jrcacd** [comment]
If we long click on item, and then long click the same item it breaks.

I think it is because the second long click, its closing the actionMode and then onLongClick method is returning a null
```
override fun onLongClick(activity: AppCompatActivity?, position: Int): ActionMode {
...
return super.onLongClick(activity, position)
}
```

**Comment by davideas** [comment]
I do not see any crash. If you have, you have to describe it.
