### ISSUE TITLE
Why is ActionModeHelper above the main bar?

### ISSUE THREAD

**Issue by jrcacd** [davideas/FlexibleAdapter#546]
![sem nome](https://user-images.githubusercontent.com/26005662/36266167-c3a94926-1268-11e8-9d5a-1ad045ac11d0.png)

**Comment by davideas** [comment]
@jrcacd, read this: https://chris.banes.me/2014/11/12/theme-vs-style/
Also check the demoApp styles and toolbar layout.

**Comment by jrcacd** [comment]
Ok, fixed
