### ISSUE TITLE
FlexibleAdapter Search Have BUG

### ISSUE THREAD

**Issue by tcqq** [davideas/FlexibleAdapter#548]
__Check the location of the red arrow in the screenshot.__

### Screenshots
![image](https://user-images.githubusercontent.com/10644057/36532807-b7b8ff50-17fc-11e8-9961-5a731f76a85f.png)
![image](https://user-images.githubusercontent.com/10644057/36532815-ba9d8f74-17fc-11e8-8ac1-cbf628daa6cc.png)
![image](https://user-images.githubusercontent.com/10644057/36532833-c6a03a74-17fc-11e8-82ff-6f8a005b087d.png)

### Simple
https://github.com/tcqq/SimpleAdapter

**Comment by davideas** [comment]
@tcqq, I do not know what's that. You should enableLogs for the Adapter and discover.
DemoApp filter works with no bugs since very long time already.

**Comment by tcqq** [comment]
View the picture above the arrow point to the location, item there is a gap, I feel this is because the "FlexibleAdapter" library  not notification.
![image](https://user-images.githubusercontent.com/10644057/36533743-7fdccabe-17ff-11e8-978d-00676c3cce36.png)

**Comment by tcqq** [comment]
I tried to delay notification of the FlexibleAdapter when the text changed, and as a result the problem was solved but the delay notification was not a real solution

**Comment by davideas** [comment]
@tcqq, you already have a delay as parameter for fitlerItems, which is ok to have because user is typing and the human time is different from cpu time.
However, you can only discover by enabling logs and see how many items are removed and inserted.

**Comment by tcqq** [comment]
Yes, but the solution to the above code is not elegant, whether the library can fundamentally solve this problem?

**Comment by tcqq** [comment]
This is a serious problem, the gaps in the layout were due to the fact that no notice was given when the data changed.

**Comment by davideas** [comment]
@tcqq, i do not know from here what is that gap, demoApp works perfectly with no delay. So once again, enable logs and check the execution flow. I can't help from here in this case.

**Comment by tcqq** [comment]
"gap" is the distance the "item" and "item" between, I will do the same test on your demoApp and tell you the result.

**Comment by davideas** [comment]
@tcqq, check your logs first.

**Comment by tcqq** [comment]
I conducted the test, but I didn't find anything unusual in the logs.

**Comment by tcqq** [comment]
I conducted the same test on your demoApp, This is a screenshot after running
![image](https://user-images.githubusercontent.com/10644057/36538927-15957cc6-1810-11e8-88bd-8beba0ae2d36.png)

**Comment by davideas** [comment]
Check FlexboxLayoutManager.
Adapter Logs are perfect with 2 items (header+item filtered).

**Comment by tcqq** [comment]
I did a lot of checks and tests, but the problem still exists. This question is certainly easier for you. I want to know where I was doing something wrong. Thank you very much.

**Comment by davideas** [comment]
@tcqq, when we put another LayoutManager the gap disappears, and from adapter logs, everything corresponds to the filter result expected.
It is not related to the adapter since this component manages the items not the layout. So my suspect is related to that.
Work on the layout, add more elements, you can't work with 1 element only in the section: you might see more clues. Add your logs, and try to debug of course. Try to change the item layout. Try to use the new adapter snapshot version which I restored the DiffUtil (However the notifications are ok with both methods).
Do investigation like this.

**Comment by tcqq** [comment]
Feel the reply, I will hard try.
