### ISSUE TITLE
How to enable sticky headers?

### ISSUE THREAD

**Issue by BoldijarPaul** [davideas/FlexibleAdapter#55]
My header model

` */
public class MyNewsBigItem extends AbstractFlexibleItem<MyNewsBigItem.ViewHolder> implements ISectionable<MyNewsBigItem.ViewHolder, MyNewsHeaderItem> {

    private MyNewsHeaderItem mHeader;

    @Override
    public MyNewsHeaderItem getHeader() {
        return mHeader;
    }

    @Override
    public MyNewsHeaderItem setHeader(MyNewsHeaderItem header) {
        mHeader = header;
        return header;
    }
`
And my adapter looks like this:

`public class MyNewsFlexibleAdapter extends FlexibleAdapter<AbstractFlexibleItem> {

    public MyNewsFlexibleAdapter(List<AbstractFlexibleItem> items) {
        super(items);
        enableStickyHeaders(3);
        MyNewsHeaderItem h1 = createHeaderItem();
        MyNewsHeaderItem h2 = createHeaderItem();
        MyNewsHeaderItem h3 = createHeaderItem();
        MyNewsHeaderItem h4 = createHeaderItem();

        addItem(getItemCount(), h1);
        addItem(getItemCount(), createbigItem(h1));
        addItem(getItemCount(), createbigItem(h1));
        addItem(getItemCount(), createbigItem(h1));
        addItem(getItemCount(), createbigItem(h1));
        addItem(getItemCount(), h2);
        addItem(getItemCount(), createbigItem(h2));
        addItem(getItemCount(), createbigItem(h2));
        addItem(getItemCount(), createbigItem(h2));
        addItem(getItemCount(), createbigItem(h2));
        addItem(getItemCount(), createbigItem(h2));
        addItem(getItemCount(), h3);
        addItem(getItemCount(), createbigItem(h3));
        addItem(getItemCount(), h4);
        addItem(getItemCount(), createbigItem(h4));
        addItem(getItemCount(), createbigItem(h4));
        addItem(getItemCount(), createbigItem(h4));
        addItem(getItemCount(), createbigItem(h4));
    }
`

Everything is shown correctly on the app, but the headers are not sticky. Where I'm wrong?
I've also tried to call the enableStickyHeaders after I set the adapter to the recyclerview. no success.

**Comment by davideas** [comment]
Hi @BoldijarPaul, the headers are part of the ISectionable objects, they are handled by show/hideAllHeaders(), so you don't need to add the header item to the list, instead call the show method. Once they have the flag set as shown, the enableStickyHeader() method works, reading the comment of this method might help as well.

**Comment by BoldijarPaul** [comment]
Thanks!

**Comment by BoldijarPaul** [comment]
@davideas  do you know why                 adapter.getItem(position).setHidden(true);
 won't hide my item ?

Thanks :+1:

**Comment by davideas** [comment]
Items are not aware of the adapter, that flag is used internally especially during the filter, so if you want hide an item, basically you want to remove that item from the adapter but not from your database. You should have a logic behind to not add these hidden items list once you change that flag.
I hope I've answered your question.
