### ISSUE TITLE
Horizontal scrolling (with SnapHelper)

### ISSUE THREAD

**Issue by tcqq** [davideas/FlexibleAdapter#550]
How to use FlexibleAdapter to create horizontal item list? Is now supported create? 
### Like this picture:
![image](https://user-images.githubusercontent.com/10644057/36600069-3c21bfe4-18ec-11e8-8fd4-6620b1f679f5.png)

**Comment by davideas** [comment]
https://github.com/rubensousa/RecyclerViewSnap

**Comment by davideas** [comment]
You can check also this one.

https://github.com/TakuSemba/MultiSnapRecyclerView
