### ISSUE TITLE
Quick way to use different layout resource while switching different layout manager

### ISSUE THREAD

**Issue by ryc16** [davideas/FlexibleAdapter#553]
When switching from LinearLayout to GridLayout, would like to use different grid layout. Is there any quick way to do so? I think it can be done by recreate the component but want to find a quick way. For example, return different layout res based on linear layout or grid layout and perform binding accordingly.

@Override
    public int getLayoutRes() {
        return R.layout.recycler_simple_item;
    }

Couldn't find relative information from your docs and your demo.

Thanks

**Comment by davideas** [comment]
@ryc16, in demoApp check method [`AbstractFragment.onOptionsItemSelected()`](https://github.com/davideas/FlexibleAdapter/blob/master/flexible-adapter-app/src/main/java/eu/davidea/samples/flexibleadapter/fragments/AbstractFragment.java#L88). The items _should_ be bound again. Does it answer to your question?

**Comment by mecoFarid** [comment]
@davideas You're changing the layout manager and they all use the same layout res. The question was `different` layout res for different layout managers which seems quite impossible with library's current design.
