### ISSUE TITLE
RecyclerView ItemDecoration

### ISSUE THREAD

**Issue by meness** [davideas/FlexibleAdapter#554]
Please check off the following points BEFORE submitting a new issue / asking support.
- [x] Write a self explanatory Subject.
- [x] Check if the issue has already been raised by someone else (see closed issue).

I add an item decoration to the `RecyclerView`, everything is fine, but the divider shown after each header item and this is not what I want.

```java
public class ContactItemDivider extends RecyclerView.ItemDecoration {

    private static final int[] ATTRS = new int[]{android.R.attr.listDivider};

    private Drawable divider;

    public ContactItemDivider(Context context) {
        final TypedArray styledAttributes = context.obtainStyledAttributes(ATTRS);
        divider = styledAttributes.getDrawable(0);
        styledAttributes.recycle();
    }

    public ContactItemDivider(Context context, int resId) {
        divider = ContextCompat.getDrawable(context, resId);
    }

    @Override
    public void onDraw(Canvas c, RecyclerView parent, RecyclerView.State state) {
        int padding = 140;
        int left = parent.getPaddingLeft() + padding;
        int right = parent.getWidth() - (parent.getPaddingRight() + padding);

        int childCount = parent.getChildCount();
        for (int i = 0; i < childCount; i++) {
            View child = parent.getChildAt(i);

            RecyclerView.LayoutParams params = (RecyclerView.LayoutParams) child.getLayoutParams();

            int top = child.getBottom() + params.bottomMargin;
            int bottom = top + divider.getIntrinsicHeight();

            divider.setBounds(left, top, right, bottom);
            divider.draw(c);
        }
    }
}
```

**Comment by meness** [comment]
`FlexibleItemDecoration` helped a lot, but how to customize the divider's width, it is completely visible from left to the right now

**Comment by davideas** [comment]
@meness, this seems similar to the question in 531. Where I answer that if you need something specific, you should implement your own ItemDecoration.
However, to me is not clear the result you are getting and the result you desire.

**Comment by meness** [comment]
@davideas look at the above code, I use `padding` on the left and the right, is it possible with `FlexibleItemDecoration` ?

**Comment by davideas** [comment]
`int padding = 140;` is custom so you need to override that function or to create your own ItemDecoration.
