### ISSUE TITLE
ViewType instance not found for viewType 0. You should implement the AutoMap properly

### ISSUE THREAD

**Issue by HunterCZE** [davideas/FlexibleAdapter#555]
During application using we've got this exception:

```
java.lang.IllegalStateException: ViewType instance not found for viewType 0. You should implement the AutoMap properly.
	at eu.davidea.flexibleadapter.FlexibleAdapter.onCreateViewHolder(FlexibleAdapter.java:1679)
	at cz.programm.mibsale.solvent.mvp.models.adapters.base.MibsaleFlexibleAdapter.onCreateViewHolder(MibsaleFlexibleAdapter.java:56)
	at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6493)
```
Do you have any idea what can cause it?

**Comment by davideas** [comment]
@HunterCZE, yes, you need to specify the layout for `getLayoutRes()` that automatically will give the itemType for the item: the number will be chosen by Android as you know.

Alternatively for a custom itemType that requires same layout, you can additionally implement `getItemViewType()`, but this is superfluous in all others use cases.

Everything is in the Wiki documentation and javaDoc too.

**Comment by HunterCZE** [comment]
Hello, thank you for the quick respone.

We have implemented the getLayouRes()
`
    @Override
    public int getLayoutRes()
    {
        return R.layout.item_article;
    }

    @Override
    public ArticleListItemModelViewHolder createViewHolder(View view, FlexibleAdapter adapter)
    {
        return new ArticleListItemModelViewHolder(view, adapter);
    }
`

We have activity which has 8 fragments tabs and each tab contains RecyclerView using the FlexibleAdapter.

Most of the time everything is OK, but sometimes we got the ViewType instance not found for viewType 0. You should implement the AutoMap properly. So far we do not have steps to reproduce.
I think it is somehow related to the destroying activity, like the activity is beeing destroyed and the recycler view want to draw another item. Is that possible ?

Best Regards Jaromir

**Comment by davideas** [comment]
The only way that can be `0` is because the item is not found in the adapter list and therefore is `null`, an exception is raised.

I've checked that StickyHeaders asks for ViewHolder creation, but that occurs from a scrolling down AND if the requested and existent position >= 0. Therefore it can't be the cause.

Another cause is when the item is not found in the adapter list because the `equals` method called by Java during the list scan doesn't satisfies any match. Could you please check it out?
