### ISSUE TITLE
DefaultDivider with IExpandable

### ISSUE THREAD

**Issue by 10erlosh** [davideas/FlexibleAdapter#556]
I'm using `AbstractExpandableItem` as mainItems together with `AbstractFlexibleItem` as subItems.
ItemDecoraion ist set that way:
`recyclerView.addItemDecoration(new FlexibleItemDecoration(activity)
.withDefaultDivider(R.layout.item_list_xxx))`

In collapsed state everything is fine. But in expanded state the divider is still drawn below mainItems not respecting the fact that subItems are present.

How can i achieve that in expanded state dividers will be drawn below the last subItem instead of mainItem?

Thanks in advance!

P.S.: lib version is 5.0.0-rc3

**Comment by davideas** [comment]
Could you call `invalidateItemDecorations(delay)` when expanding/collapsing?

For the other question, you will have to implement your own Decoration doing something similar to what I do with sectionGap: I check if **next** item is a Header and I apply the decoration to the **current** item.
