### ISSUE TITLE
How to use live data

### ISSUE THREAD

**Issue by AlexisQapa** [davideas/FlexibleAdapter#559]
Hi, I've built a FlexibleViewModel following your wiki page on live data but I can't find a way to connect it to the adapter. Can you give me some tips ?

**Comment by davideas** [comment]
Linked to #529: Be aware that how it is, it's not good enough, however you need to observe the LiveData produced by `getLiveItems()` and you trigger the loading with `loadSource(identifier)`. The identifier can be your object as well as String/Long.

**Comment by AlexisQapa** [comment]
That's what I did, I was thinking LiveData support was more advanced i.e. you pass an lifecycle owner and some livedata and the adapter do the magic. Anyway that's working nice for basics cases. 

I have one question thought, what would be the recommended strategy to handle infinite scroll with livedata. I would like to have a repository serving resources. One resource know how to fetch initial and then load more data and expose a livedata with actual data for adapter. My goal is to have this : 

onCreate -> adapter(viewModel.getData (repository.getResource.data))
onInfiniteScroll -> viewModel.loadMore()

**Comment by davideas** [comment]
I think you should start to fill the adapter with the same function to load more items.
You start with adapter setup and trigger the first call with `setLoadingMoreAtStartUp()`.
Your solution is also acceptable and will have the initial items already visible at startup, I think.
