### ISSUE TITLE
Headers are shown multiple times

### ISSUE THREAD

**Issue by BoldijarPaul** [davideas/FlexibleAdapter#56]
How I initialize my adapter:

```javascript
mAdapter = new MyNewsFlexibleAdapter(new ArrayList<AbstractFlexibleItem>());
        mAdapter.setDisplayHeadersAtStartUp(true);//Show Headers at startUp!`

// And after I get my recycler view
mRecycler.setAdapter(mAdapter);
        mAdapter.enableStickyHeaders(3);

```

I have this method in my adapter

```javascript
 public void addNews(List<News> newsList) {
        // create header
        int categoryId = newsList.get(0).categoryId;
        MyNewsHeaderItem header = new MyNewsHeaderItem(categoryId);
        // add items for header
        for (News news : newsList) {
            MyNewsSmallItem newsSmallItem = new MyNewsSmallItem(news, header);
            addItem(getItemCount(), newsSmallItem);
        }
        showAllHeaders();
    }
```
 
And this method is called multiple times, if I call this method for 2 times I would like to have something like this

* header
* item
* item
* header
* item
* item

And instead the first header is added twice!
* header
* header
* item
* item
* header
* item
* item

If this method gets called 3 times, the first header would be added 3 times, the second one twice...

How can I fix this ? If I don't call showAllHeaders() the headers won't show up, and this method can be called any time..

EDIT :
I found a solution
```javascript
 hideAllHeaders();
        showAllHeaders();
```
EDIT 2: this will cause a NPE at FlexibleAdapter 827

And another question, how can I completely clear the list? Without creating a new adapter of course..

**Comment by davideas** [comment]
One moment, calling `addNews()` you create everytime a new header object which starts with the flag `hidden=true`, so at the next call of showAllHeaders it displays a new different header object (even if you think it is the same content category). You should keep the reference of the same header you already have in memory, the header object must be the same for all the items under that section.

However, I've improved a little bit the displaying of the header when adding a new item with header, maybe you can use 5.0.0-SNAPSHOT, read my comment release and check the code of  `addItem()` & `addItems()`: https://github.com/davideas/FlexibleAdapter/issues/39#issuecomment-187941634

So in the end you should call once `setDisplayHeadersAtStartUp()` which internally calls `showAllHeaders()`, do this when you create the Adapter/RecyclerView after you fill the items to the adapter.

**Comment by davideas** [comment]
To clear/remove all items you can use `removeRange(positionStart, itemCount)` or `removeItemsOfType(Integer... viewTypes)` the last method is available only in SNAPSHOT release and it will be also in the next beta release: beta5. it takes care to remove/hide also the header only if all items of that section are removed, so you don't need to remove the header type!
Or you can implement your own clear() method which internally calls removeRange(...)

**Comment by BoldijarPaul** [comment]
@davideas about the first issue. 

>  calling addNews() you create everytime a new header object 

I want to do this, because everytime I call addNews, i'm adding a list of news of a type, and I want a different header all the time.
I don't need to reuse headers now. How can I fix this?

**Comment by davideas** [comment]
Ok I understood, I was doing the same in my project, you need to calculate where to insert the new item keeping in the calculation all the previous displayed header, it is a bit more complicated of what you think because you might add an item at the end of the section or at the beginning of the section.

**Comment by BoldijarPaul** [comment]
Hey! I changed a bit my logic and now.

1) I'm creating all possible headers (header = type of news), and put it into an array.
2) I'm fetching news from server 
3) I'm getting more responses, each is a list of news for a category type.
4) I'm adding the items along with the correct headers.

How I create my adapter:
```javascript
  mAdapter = new MyNewsFlexibleAdapter(new ArrayList<AbstractFlexibleItem>());
        mAdapter.setDisplayHeadersAtStartUp(true);//Show Headers at startUp!
```

And no header is shown.
If I do showAllHeaders() after each time I add new news I will have the same problem as above (multiple headers).
Is there a solution for this problem on beta 4?

Thank you for your support.

**Comment by davideas** [comment]
@BoldijarPaul, do you initialize the list after you create new ArrayList?
Remember that the headers are attached to the items, so initialize your list and only after pass the list to the Adapter constructor.

**Comment by BoldijarPaul** [comment]
@davideas 
```javascript
 private List<AbstractFlexibleItem> mItems;

    public MyNewsFlexibleAdapter(List<AbstractFlexibleItem> items) {
        super(items);
        mItems = items;
    }
```

And how I initialize my adapter
```javascript
 mAdapter = new MyNewsFlexibleAdapter(new ArrayList<AbstractFlexibleItem>());
        mAdapter.setDisplayHeadersAtStartUp(true);//Show Headers at startUp!
```
And where i'm adding news
```javascript
public void addNews(List<ProTvNewsModel> news) {
        if (news.isEmpty()) {
            return;
        }
        int categoryId = news.get(0).categoryId;
        // add first item
        MyNewsBigItem newsBigItem = new MyNewsBigItem(news.get(0), mHeaders.get(categoryId));
        mItems.add(newsBigItem);
        // add next items
        news.remove(0);
        for (ProTvNewsModel newsModel : news) {
            MyNewsSmallItem newsSmallItem = new MyNewsSmallItem(newsModel, mHeaders.get(categoryId));
            mItems.add(newsSmallItem);
        }
        mItems.add(new MyNewsAdItem(mHeaders.get(categoryId), categoryId));
        notifyDataSetChanged();
    }
```
And again, i'm seeing duplicate headers..

**Comment by davideas** [comment]
Where is `addNews` in the Adapter or in the Activity? also when is it called?

If it is in the Adapter, you should use `addItem()` as you wrote before. Also what is `mItems`? I mean is it yours? because i-m sure it should be set as private in my Adapter so you should not have one in the adapter but in your "database service".
Summarizing, you have to change version to 5.0.0-SNAPSHOT as I said previously, otherwise when adding items with `addItem()` will not show the headers using beta4.

notifyDataSetChanged() indeed shows what is already in the mItems of the Adapter without animations, if the headers were not present in mItems then it continues to Not display any header.

**Comment by davideas** [comment]
Basically you should have 1 list of news as database where you fetch news from the server and rely on it as original list and without headers because headers are linked inside each item.
Then you need to synchronize the list of the adapter.
Why 2? because if you filter or remove an item with undo, the adapter list is modified with removals and these deletion don't have to be your database list but only in the displayed list.

**Comment by BoldijarPaul** [comment]
I'm now using the SNAPSHOT version and I have this issue

```javascript
 public void addNews(List<NewsModel> news) {
        if (news.isEmpty()) {
            return;
        }
        //  header
        int categoryId = news.get(0).categoryId;
        List<AbstractFlexibleItem> items = new ArrayList<>();
        // add first item
        MyNewsBigItem newsBigItem = new MyNewsBigItem(news.get(0), mHeaders.get(categoryId));
        items.add(newsBigItem);
        // add next items
        news.remove(0);
        for (ProTvNewsModel newsModel : news) {
            MyNewsSmallItem newsSmallItem = new MyNewsSmallItem(newsModel, mHeaders.get(categoryId));
            items.add(newsSmallItem);
        }
        items.add(new MyNewsAdItem(mHeaders.get(categoryId), categoryId));
        addItems(getItemCount(), items);

    }
```

I'm getting out of memory error.
Throwing OutOfMemoryError "Failed to allocate a 44479330 byte allocation with 10427408 free bytes and 9MB until OOM"

` java.lang.OutOfMemoryError: Failed to allocate a 44479330 byte allocation with 10427408 free bytes and 9MB until OOM
03-21 13:16:33.595 20700-20700/com.appsrise.protv E/AndroidRuntime:     at java.lang.StringFactory.newStringFromChars(Native Method)
03-21 13:16:33.595 20700-20700/com.appsrise.protv E/AndroidRuntime:     at java.lang.AbstractStringBuilder.toString(AbstractStringBuilder.java:629)
03-21 13:16:33.595 20700-20700/com.appsrise.protv E/AndroidRuntime:     at java.lang.StringBuilder.toString(StringBuilder.java:663)
03-21 13:16:33.595 20700-20700/com.appsrise.protv E/AndroidRuntime:     at com.android.internal.os.RuntimeInit.Clog_e(RuntimeInit.java:60)
03-21 13:16:33.595 20700-20700/com.appsrise.protv E/AndroidRuntime:     at com.android.internal.os.RuntimeInit.access$200(RuntimeInit.java:44)
03-21 13:16:33.595 20700-20700/com.appsrise.protv E/AndroidRuntime:     at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(R`

addNews is in the adapter, and gets called in the fragment.

My constructor:
```javascript
public MyNewsFlexibleAdapter(List<AbstractFlexibleItem> items) {
        super(items);
    }
```

**Comment by davideas** [comment]
About the OOM I don't know, please check the caused by and you will found the cause. Is the adapter involved in the stack trace? StringBuilder object is not used in my adapter library.

About the `addNews()`, if I understand correctly: You initialize the adapter with empty non null list and then you call addItems, it should be fine I think.

**Comment by BoldijarPaul** [comment]
I'm trying to make another project with as few lines of code as possible, maybe later it can be an example project.

https://github.com/BoldijarPaul/flexible-adapter-test

Currently i'm having 2 problems

- headers are not being shown
- adding items later, will add them to the last header instead of at the desired header. (check [addItems](https://github.com/BoldijarPaul/flexible-adapter-test/blob/master/app/src/main/java/com/boldijar/flexibleadapter/MyFlexibleAdapter.java#L32) in adapter)

**Comment by davideas** [comment]
@BoldijarPaul, I've analyzed your code, basically all items are sticky headers that's why you don't see the colored ones sticky. Yours `NormalItem extends AbstractHeaderItem` while it should extends `AbstractSectionableItem` for example...

``` java
public class NormalItem extends AbstractSectionableItem<NormalItem.ViewHolder, HeaderItem> {

    private int mId;

    public NormalItem(int id, HeaderItem headerItem) {
        mId = id;
        header = headerItem;
    }
    ...
}
```

**Comment by BoldijarPaul** [comment]
@davideas Thanks for your help!
Whenever the project will have a stable version, If you want, I could fork the repo, and add a separate example just for sticky headers. :+1:
