### ISSUE TITLE
Update data binding compiler version

### ISSUE THREAD

**Issue by AlexisQapa** [davideas/FlexibleAdapter#560]
Hi,

I'm using the data binding compiler V2 in my project but it's not compatible with the V1 according to:
https://developer.android.com/topic/libraries/data-binding/index.html#enable_v2

I have a compile time error due to this. Is there any plan to move on to v2 ?

**Comment by davideas** [comment]
Waiting the official release.

**Comment by davideas** [comment]
Should I **only** rebuild the library with `android.databinding.enableV2=true` ? There's not other change to make?

**Comment by AlexisQapa** [comment]
Well the thing is lib built with V2 aren't compatible with V1. V2 is obviously better and save some checks notably with kotlin. But upgrading would force users to upgrade too.

**Comment by wankey** [comment]
put a flexible-adapter-databinding-v2 version.users can choose which they need

**Comment by fvermeulen** [comment]
would be cool to have the option to upgrade to the second version. I would change to v2

**Comment by davideas** [comment]
I can always increase the version and create the beta3 compatible with databinding v2.
Who needs databinding v1 will stick with beta2.

**Comment by davideas** [comment]
**beta3** is published.
