### ISSUE TITLE
Search through only not expandable items

### ISSUE THREAD

**Issue by meness** [davideas/FlexibleAdapter#561]
Please check off the following points BEFORE submitting a new issue / asking support.
- [x] Write a self explanatory Subject.
- [x] Check if the issue has already been raised by someone else (see closed issue).

Hi,

I need to search and filter items through only not expandable items, how can I do this?

**Comment by davideas** [comment]
@meness, as you will do for all items, implement `IFilterable<Type>` to that class for subitems.

**Comment by meness** [comment]
@davideas The sub item and the item class is the same
