### ISSUE TITLE
Infinite scroll pagination

### ISSUE THREAD

**Issue by AlexisQapa** [davideas/FlexibleAdapter#563]
Hi,

Context: I've evaluated the new Google paging library and while it's nice it is very hard to customise / insert items arbitrarily.

Disclaimer: I don't want a complete answer or demo I'd rather start a discussion about functionality/limitation of flexible adapter. 😄

I need to build the following : 
- Infinite scroll of X + every 10 X a Y element.
- Y is a banner like element, not returned by API
- Scroll bar reflect the total elements and not loaded elements are placeholders so user can jump to any part of the data.
- When user scroll over a chuck of placeholder, load data and replace placeholders
- Place holder can be FlexibleItems with bind(null)

What I have : 
- Total count is known
- Api is positional (load item at page X is independent of previous or next page) and flexible

Is this possible to have this kind of behaviour with flexible adapter ? (the important part for me is the placeholder thing and scroll). If so, what strategy would you use to represent the chucks of data (I'm think about sections but is this really the way to go ?)  ?

**Comment by davideas** [comment]
@AlexisQapa, regarding the infinite scroll, it does a specific work: it loads new items from repository to append to the list, so the adapter doesn't know them!
To show the content in the items you have to manage the binding, but that is automatic as soon as the item is going to be shown.
Placeholders for text you need to do something similar for images when you download them, you need to link the repository to the items if the text isn't already loaded. But as said before you need to know the item identification first, so the item as placeholder must be added to the list.

You know that as soon as you scroll and the item is partially or temporarily visible, it loads everything in that item.

Y element as banner is your problem _only_.

**Comment by AlexisQapa** [comment]
Ok after thinking about it another time it's not infinite scroll as I already know the items count.
What I want is to pass a list with nullable items to the adapter and to get a callback when a null item will be requested so I can lazy load it. My list won't grow and user can scroll to the end before any item is loaded.

**Comment by davideas** [comment]
Items themselves can't be null! As said they must have an unique identifier (non null as well) otherwise you don't know what are you going to load and show.
The others fields can be null.

The bindView method is already a callback, you just need to pass the repository instance to each item at the creation. It's a bit strange however.

**Comment by AlexisQapa** [comment]
This means that if I have a list of 40k items I need to initialise a list of 40k placeholders. Even if they are minimalistic it's a memory cost. I made an abstract list that work the way I want. It works with a classic DiffUtil adapter + a updateCallback which reload loaded rows.

Here is a simpler version of my list : 

class MyPagedList(val service: QapaAPI, private val updateCallBack: (from: Int, to: Int) -> Unit) : AbstractList<Recyclable>() {

    init {
        launch(UI) {
            delay(2)    // Delai after init so vars are initialized
            loadPage(0) // force load the first page so we get the total items count
        }
    }

    private val pageSize = 30
    private var itemsCount = 0
    private var pageCount = 0
    private var storage: MutableMap<Int, Page> = emptyMap<Int, Page>().toMutableMap()

    // List implementation :
    override val size: Int get() = itemsCount

    override fun get(index: Int): Recyclable {
        val pageIndex = index / pageSize 
        val itemIndex = index % pageSize
        val storedPage = storage[pageIndex]
        loadAround(index)
        return when (storedPage) {
            is LoadedPage -> storedPage.data[itemIndex]
            is LoadingPage -> PlaceHolderItem()
            else -> {
                loadPage(pageIndex)
                PlaceHolderItem()
            }
        }
    }

    // Helpers
    private fun loadAround(index: Int) {
        val indexWithOffset = index + pageSize / 2
        val pageIndex = indexWithOffset / pageSize
        loadPage(pageIndex)
    }

    private fun loadPage(pageIndex: Int) {
        if (pageIndex in 0..pageCount && storage[pageIndex] !is LoadedPage && storage[pageIndex] !is LoadingPage) {
            storage[pageIndex] = LoadingPage()
            launch(CommonPool) {
                try {
                    val response = with(search) {
                        service.getData(pageIndex * pageSize, pageSize).execute()
                    }
                    val model = response.body()?.toModel()
                    if (response.isSuccessful && model != null) {
                        if (pageIndex == 0) {
                            itemsCount = model.metadata.totalItems
                            pageCount = model.metadata.pageCount
                        }
                        storage[pageIndex] = LoadedPage(model.results)
                        val startIndex = pageIndex * pageSize
                        updateCallBack(startIndex, startIndex + pageSize)
                    } else {
                        throw Error(response.message())
                    }
                } catch (t: Throwable) {
                    storage[pageIndex] = ErrorPage()
                    Timber.e(t)
                }
            }
        }
    }
}

Here is the page definition : 
sealed class Page
class LoadingPage : Page()
class ErrorPage : Page()
class LoadedPage(val data: List<MyObject>) : Page()

You said with FlexibleAdapter I can't have nullable items so I made my list not nullable (I return a placeholder item), but I present a list that seems to be of the size of the complete data without loading in memory placeholder nor data. Could this work with your adapter ?

**Comment by AlexisQapa** [comment]
@davideas the whole goal of this is to have a perfect smooth scroll all the way to the bottom of the data and / or be able to jump to the middle with a fastscroller.

**Comment by davideas** [comment]
40K items in a small device? you need a filter and / or endless scrolling.
That number is not manageable by human eyes, which we all have to deal with, anyway.

I would put a local database, and if the element is not available you load it from remote. The repository should do that logic.

I didn't read the code, sorry. I can't help more: we are asking architecture consultancy.

**Comment by AlexisQapa** [comment]
I am sorry, I didn't wanted to take too much of your time. I wasn't asking for architecture help. The issue with the load more pattern is that user doesn't know where he is in the data as the data grows as the user scroll. Etsy engineering team wrote a nice article about cons of this pattern.

My lazy list is working with another adapter and I think the issue is that FlexibleAdapter use a copy of the list and not the one given in the init. I'll continue working on this and provide a working example if you are interested. This would enable using fastscroller and so on paginated data.

Again sorry I asked much
