### ISSUE TITLE
Removing range of expandable items and re-adding them makes them still hidden.

### ISSUE THREAD

**Issue by Marc1510** [davideas/FlexibleAdapter#566]
I've created a list of AbstractExpandableItems and removed them using removeRange(index, itemCount) on the adapter. The problem I have is that after removing the list of items I want to re-add them after clicking on for example a button. Because the the sub-items are marked as hidden on the removeItem (FlexibleAdapter.java line 3489) they do not appear after re-adding the AbstractExpandableItems with the sub-items attached.
Also after calling expand on the adapter with the correct index, the return value is 0 which means that it couldn't expand the item.
I've tried resetting isHidden to false, however that does not fix it.

As a temporary workaround I recreated the objects at the time I need to add them to the adapter once again, however this isn't my preferred way of re-adding them.
Is there anything I'm missing?

My expandable item is like this:
`public class ProductGroupItem
        extends AbstractExpandableItem<ProductGroupItem.ViewHolder, AbstractFlexibleItem>
        implements ISectionable<ProductGroupItem.ViewHolder, IHeader> {`

**Comment by davideas** [comment]
@Marc1510, I'm confused by the manual removal and addition of subItems, I don't see what you are trying to achieve.
Expanding and collapsing is internal shouldn't be touched.
If you want reacting with a button, well just invoke the expand and collapsing from the click listener.

**Comment by davideas** [comment]
@Marc1510, please use `updateDataSet()` or switch adapter, removing items does extra operations for other purposes (Undo, Header unlinking, and no indication about collapsing concept): it does a remove.

**Comment by Marc1510** [comment]
@davideas awesome thanks, that does the trick. Perhaps it would be an idea to mention that removed items shouldn't be re-used as for example the headers can break.
