### ISSUE TITLE
Problem when selecting sections (Randomly section headers are hidden)

### ISSUE THREAD

**Issue by afzalzy** [davideas/FlexibleAdapter#567]
In this sample, I have used the flexible adapter with an expandable sticky header. 

- The first issue is when changing section using position it changes correctly, but section header goes hidden when we are using the smooth scroll. 

- The second issue is when scrolling up and down via physical keyboard the cursor jumps to the top as soon as it reaches the end of the screen. 

The source code is below:
- https://github.com/afzalzy/FlexibleAdapterWithEditText

**Comment by davideas** [comment]
@afzalzy, Let's try to make some order in the code.
- It's important that you implement the equals method correctly. Or you will have unexpected behaviors the most dangerous (not the most visible) is a memory leak for the boundViewHolders (I will make this cleared in the docs). Maybe you wanted to do this instead:
``` java
Override
public boolean equals(Object inObject) {
    if (inObject instanceof OrderHolder) {
        OrderHolder that = (OrderHolder) inObject;
        return (that.getModel().getId() + "_" + that.header.getId()).equals(modelData.getId() + "_" + header.getId());
    }
    return false;
}
```
- You don't need to clear selection when you use toggleSelection.
- Enable Logs for adapter in Debug level and you will see much more.
- Don't use log.error for debug values.
- it seems laggy, to discover the cause...

I will continue to investigate, but it seems related to the way you call the clear selection and add selection.
