### ISSUE TITLE
FlexibleItemDecoration getItemOffsets withBottomEdge

### ISSUE THREAD

**Issue by zhangz89** [davideas/FlexibleAdapter#569]
class `FlexibleItemDecoration`  `public void getItemOffsets(final Rect outRect, View view, RecyclerView recyclerView, RecyclerView.State state)`
`            if (isLastRowOrColumn) {
                if (withBottomEdge) {
                    bottom = deco.bottom;
                }
            } else {
                bottom = deco.bottom;
            }`
i think this code is not correct, if the item is not last row ,it has bottom too. i think need to delete the `else`

**Comment by davideas** [comment]
The elements need that offset anyway, otherwise all elements result attached to each others at the bottom.
