### ISSUE TITLE
Sorting items?

### ISSUE THREAD

**Issue by BoldijarPaul** [davideas/FlexibleAdapter#57]
Is there a way to sort items without inserting them at the correct position?

Thanks!

**Comment by davideas** [comment]
It's a nice idea, but in my opinion sorting depends by the specific use case that only the developer knows.
Basically, you can apply your sort logic to your list and then call `updateDataSet(sorted list)` OR you can call `animateTo(sorted list)` to have inserting and removal animations (this method is called in the filter, so it should work also for any new list).
