### ISSUE TITLE
ActionMode overlay

### ISSUE THREAD

**Issue by meness** [davideas/FlexibleAdapter#571]
Please check off the following points BEFORE submitting a new issue / asking support.
- [x] Write a self explanatory Subject.
- [x] Check if the issue has already been raised by someone else (see closed issue).

Hi,

How can I make the action mode overlay on the toolbar?

```xml
<item name="android:windowActionModeOverlay">true</item>
<item name="windowActionModeOverlay">true</item>
```

above workaround does't work.

**Comment by davideas** [comment]
In the article I posted in #546 there's the ActionMode overlay and theme as well.
