### ISSUE TITLE
Multiple Sticky Header. How to implement it?

### ISSUE THREAD

**Issue by lnarv** [davideas/FlexibleAdapter#573]
I need to implement multiple header which are sticky. How i will be able to achieve same?
Possible example is below.
[Multiple Sticky Header](https://github.com/edubarr/header-decor)

**Comment by davideas** [comment]
@lnarv, not possible in this implementation. It requires months of works in freetime and possibly change completely the solution with a special LayoutManager.

**Comment by davideas** [comment]
I'm sorry @lnarv, but I'm sincere, I can't follow you on your use case.
