### ISSUE TITLE
Item is on the right

### ISSUE THREAD

**Issue by jrcacd** [davideas/FlexibleAdapter#574]
If I clear a recyclerView adapter list and an list with only one Item it appears on the right and not on the left.

```
recyclerView.layoutManager = StaggeredGridLayoutManager(...)
recyclerView.setHasFixedSize(true)
....
recyclerView.adapter.clear()
recyclerView.adapter.addItems(0, carts) 
```

**Comment by davideas** [comment]
@jrcacd, it's not the adapter, it's StaggeredGridLayoutManager.

**Comment by jrcacd** [comment]
I dont know if I can ask, but it there a way to solve it?
