### ISSUE TITLE
RecyclerView — More Animations with Less Code using Support Library ListAdapter

### ISSUE THREAD

**Issue by meness** [davideas/FlexibleAdapter#576]
[Read this](https://medium.com/@trionkidnapper/recyclerview-more-animations-with-less-code-using-support-library-listadapter-62e65126acdb), it might be helpful.

**Comment by davideas** [comment]
Thank you @meness, but everything was already covered more than 2 years ago in this Adapter. DiffUtil was also implemented 1 year ago.
