### ISSUE TITLE
Items with ConstraintLayout slow in sticky headers

### ISSUE THREAD

**Issue by java2men** [davideas/FlexibleAdapter#577]
I use the items with ConstraintLayout in sticky headers. This is slow.
I replaced ConstraintLayout with LinearLayout, it helped.
Who can confirm problems with ConstraintLayout?

**Comment by davideas** [comment]
@java2men, I didn't try to have elements with ConstraintLayout.
Good that LinearLayout you have no issues.

**Comment by davideas** [comment]
@java2men, we are talking of, how many items? However, could you try to follow these guide lines?

- Enable stable ids (unique ids)? you need `equals` and `hashCode` well implemented for the items!
- If your item layouts have the same size, you can enable `recyclerView.setHasFixedSize(true)`;
- You can possibly enable cache `recyclerView.setItemViewCacheSize(20)` and others options for cache.
- Try to reduce the code inside `bindViewHolder()`: put the listener creation in the constructor of ViewHolder.
- Do not refresh everything at each single change, but use the _internal calculation_ or the `DiffUtil` class.
- Simplify the item layouts.

**Comment by java2men** [comment]
@davideas, thanks for the recommendation.
The problem of freezing is in the complexity of the item layout(ConstraintLayout).

**Comment by jrcacd** [comment]
The same is hapening with my code.

**Comment by davideas** [comment]
People talks: https://www.reddit.com/r/androiddev/comments/7ylbz3/is_constraintlayout_that_slow/

**Comment by java2men** [comment]
New version released:
https://androidstudio.googleblog.com/2018/04/constraintlayout-110.html

I have not tested yet.
