### ISSUE TITLE
Sticky headers inside section

### ISSUE THREAD

**Issue by fess89** [davideas/FlexibleAdapter#58]
Is it possible to configure the FlexibleAdapter to have sticky headers _inside_ a section, not above it?
What I mean is to have items look like so:

=== section name ===
== sticky header 1 ==
= item 1.1 =
= item 1.2 =
== sticky header 2 ==
= item 2.1 =
= item 2.2 =

The point is that the section names do not stick to the top of the screen but the sticky headers which are inside the sections do.

**Comment by davideas** [comment]
@fess89, that's not possible, header is meant to be a section already. I've seen something in Github with double sticky sections/header, you may want to see it but I really don't remember the project name.
