### ISSUE TITLE
selected item positions mistakenly adjusted when view state restored

### ISSUE THREAD

**Issue by technicalflaw** [davideas/FlexibleAdapter#581]
In the case where the adapter's view state is restored, and that restoration includes the selected item positions, and if this happens *before* the adapter's data set is updated, then when the actual data is updated *with an animation* (i.e. it causes insertion notifications, not just a single change notification which a non-animated update would do), then the selected item positions are adjusted as if they were inserted before that update (which, until now, there were not).

For example
* an adapter that had 2 items, both selected, has its state restored (e.g. after a rotation).
* state restoration happens (via `Fragment#onViewStateRestored()`) before the adapter's data set is populated 
* the adapter's data set is populated with animation (e.g. via `LoaderManager.LoaderCallback#onLoaderFinished()`)
* this causes `AdapterDataObserver#onItemRangeInserted()` calls for all items (because the adapter was previously empty)
* the adapter's internal observer observes this, and calls `adjustPositions()` for the selected item positions
* selected item positions (0 & 1) are offset to (2 & 3), but the data set only contains 2 items (at positions 0 & 1)

Workarounds include making sure your initial `updateDataSet()` is not animated, delaying view state restoration until after the initial update, or perhaps just handling the selection restoration logic yourself. You could also (if it's the initial update), take incorrect selection before `updateDataSet()`, and apply it after the update. But remember that an animated update is multithreaded, so it'll have to be done probably via an overload to `FlexibleAdapter#onPostUpdate`

(FWIW I would suggest that if the adapter is null when the state is restored it should be cached until the adapter is set non-null)

**Comment by davideas** [comment]
@technicalflaw, I think you already understood to do the restoration after adapter has been filled.
1. `Fragment.onCreate()`.
2. `Fragment.onActivityCreated()`.
3. `Fragment.onViewStateRestored()`.
4. `Activity.onRestoreInstanceState()`.
5. I suppose the async update occurs here.
6. Call here `mAdapter.onRestoreInstanceState()`.

In the demoApp the items are taken synchronously from memory, passed to the constructor and selection restored synchronously from the Activity.
Animation is not important here, the thing important is to have the items in the adapter list!
Also, the logic for rotation has to be done only if the `Bundle savedInstanceState` is not null.

In the future versions, I might move the selection state in the adapter items and remove the `adjustSelection`.
