### ISSUE TITLE
How to create seperate layout for Sticky Header with Zooming and Slide in from Bottom animation

### ISSUE THREAD

**Issue by athul131** [davideas/FlexibleAdapter#582]
Im trying to create an app with header and expandable multilevel item in recycler view.
Current requirement is to make the **sticky header display with a different layout unlike the normal header using animation** when the header(sticky) changes.
Animation should be  zooming text size compared to normal header text size and with slide in from bottom when scrolled up and vice versa when scrolled down.

Please help me configure this. I haven't been able to do it yet.

**Comment by davideas** [comment]
@athul131, at the moment I am not providing the ViewHolder in the listener callback, but only positions.
If you retrieve the ViewHolder from the RecyclerView starting from the position doesn't it work?

**Comment by athul131** [comment]
But creates problem during the fling scroll of recycler view ( up scroll ).
Background change take time to be hidden for normal header hence there would be that background shown for while after turning sticky header to a normal header and creates bad UI due to this.
Could we do something about it?

**Comment by davideas** [comment]
Fling + Animations? no sense.

**Comment by athul131** [comment]
How can we access the sticky header layout which is generated when sticky header is enabled.
How to handle the background in . sticky header layout rather than in normal header.

**Comment by athul131** [comment]
Could the background of sticky header be changed by anyway, without using the Header layout for changing each time

**Comment by davideas** [comment]
@athul131, if it can help, you can also provide a custom sticky layout, as you can see from javaDoc.
At the moment the only way to know about the swapping is that listener.

**Comment by athul131** [comment]
How can I add a custom layout can u show an example?
