### ISSUE TITLE
New feature request: FastScroll by Sections

### ISSUE THREAD

**Issue by janbolat** [davideas/FlexibleAdapter#584]
Please add an ability to fast scroll by sections...
So that when a user drags FastScroller back and forth, it scrolls by Sections but not by every single item in the list.
Thank you.

**Comment by davideas** [comment]
@janbolat, I do not see how this could be useful at feasible too.
You can return the section info for each item in the callback, by overriding the function `getBubbleText` in the "flexible" items.

**Comment by janbolat** [comment]
No problem. Thank you anyway. Found a solution for myself: https://github.com/myinnos/AlphabetIndex-Fast-Scroll-RecyclerView

**Comment by davideas** [comment]
@janbolat, I had a look, but look that is the same as I explained just above. You return always the same section.
