### ISSUE TITLE
why is the Datamodel impelented in the Viewholder?

### ISSUE THREAD

**Issue by MohammadNsr** [davideas/FlexibleAdapter#590]
i look at the wiki and i am trying to use the felxibleadapter in my app.
but i notice that constructor of felxibleadapter needs always item-set which is not only model. the items must be of type  List<AbstractFlexibleItem>,which means, that i must merge my datamodell-items (objects) with the view (here the viewholder) to creat the items.
is there another way to use the datamodel separately from the view?

**Comment by davideas** [comment]
@MohammadNsr, thanks for the message.
For serious and structured applications, the items are adapter items and not model items. You need to "convert" the model to the view items. You can use the Holder pattern to hold the model item in the adapter Item.

For simple apps as the demoApp the model item coincides with the adapter item.

The Adapter at the moment is not generic in the way that accepts a custom object with all elements, but is generic in the way that items exposes basic delegation functions so it allows me to provide functionalities based on that known interface.
