### ISSUE TITLE
Position must be increased by value returned from "expand" method. 

### ISSUE THREAD

**Issue by AlexandreGorobets** [davideas/FlexibleAdapter#592]
https://github.com/davideas/FlexibleAdapter/blob/131ac64a6bb7a9e4fa2182b63714753ddd890715/flexible-adapter/src/main/java/eu/davidea/flexibleadapter/FlexibleAdapter.java#L435

Currently in case of multilevel expanded items, they will be added more then one time to the mItems list.

**Comment by davideas** [comment]
Already worked on it. No duplication.
It is similar to a recursive function, having and sub-item that is **expandable** will expand also its children. If **not expandable** the if `isExpanded(item)` returns `false`, and it goes to the next position without appending items. So no duplication.

**Comment by AlexandreGorobets** [comment]
Examlple:
level0 1
level1  1_1 
level2  1_1_1
level0 2

All items 1, 1_1 and 1_1_1 wil be marked as Expanded on adapter fill
When I call method 
At first iteration ("position" == 0) after processing item 1 you will add all expanded items (1_1 and 1_1_1) to mItems list.
On next loop iteration ("position" == 1) item 1_1 will be processed and item 1_1_1 will be added to mItems again.
And this is error. "position" must be increased on size on new item that was added to mItems, because we already processed all child items recursively.

**Comment by davideas** [comment]
@AlexandreGorobets, I will check again, it might that after I added the recursive function I didn't modify the `expandItemsAtStartUp()` function.

**Comment by davideas** [comment]
@AlexandreGorobets, thanks to have insisted because the function was modified initially to expand all subItems. Then I added the recursive expand function without modifying the start up function.
I will try to add also a UnitTest on it now.

_Time is always limited for this open library, unfortunately._

**Comment by AlexandreGorobets** [comment]
Hice job!)
Thank you for fast response!
