### ISSUE TITLE
Access to the custom object item in ViewHolder

### ISSUE THREAD

**Issue by NLLAPPS** [davideas/FlexibleAdapter#595]
Hi, I have
``` java
public class ViewHolder extends FlexibleViewHolder {
        public TextView recordingNameText;
        public ImageView likeImage
        ViewHolder(View view, FlexibleAdapter adapter) {
}
```
``` java
public class Recording
public Recording(String name)

public class RecordingItemHolder
public RecordingItemHolder(Recording item)
```

Adapters data is list of RecordingItemHolders. I need to get access to Recording item in RecordingItemHolder when likeImage in my Viewholder is clicked.
Currently I have a click listener in the viewholder for likeImage and am casting as

``` java 
Recording rf = ((RecordingItemHolder) adapter.getItem(getFlexibleAdapterPosition()))
                    .getRecording();
````

Is there a better way to access to the Recording that RecordingItemHolder  holds on this particular position?

**Comment by davideas** [comment]
@NLLAPPS, the Recording object, _normally_, is accessed on the lower level, so you can save and maintain the state in your App (Local DB / Server).

If now you have the state in Memory, that is the only way.
Alternatively you move the click listener in the binding.

**Comment by NLLAPPS** [comment]
To bindViewHolder ? I thought it would be quite costly to create it there. 

It is in the DB, but there is no reason to use more resources by accessing the database while it is already available in the memory
Thank you
