### ISSUE TITLE
FlexibleAdapter.onLoadMoreComplete(list,-1) not work

### ISSUE THREAD

**Issue by steventxc** [davideas/FlexibleAdapter#597]
``` java
public void onLoadMoreComplete(@Nullable List<T> newItems, @IntRange(from = -1) long delay) {
    // ......
    // Remove the progressItem if needed
    if (delay > 0 && (newItemsSize == 0 || !isEndlessScrollEnabled())) {
        log.v("onLoadMore     enqueued removing progressItem (%sms)", delay);
        mHandler.sendEmptyMessageDelayed(LOAD_MORE_COMPLETE, delay);
    } else {
        hideProgressItem();
    }
   // ......
}
```

above codes from `FlexibleAdapter.onLoadMoreComplete`, and the doc says :
```
@param delay    the delay used to remove the progress item or 
                -1 to disable the loading forever and to keep the progress item visible.
```

when I passed `-1`, it is not work, actually the above method not handle this situation.
I want to know, how can i keep the progress item when nothing returned to show some tips, any suggestion?  thanks.

**Comment by davideas** [comment]
@steventxc, the idea was that, then some modifications led to miss that part.
However, I need to verify few things. For example, what to do if the user refreshes with the progressItem already visible?

**Comment by steventxc** [comment]
@davideas I wonder how can i pause  the endless scroll mechanism, I found when add footer in the `noMoreLoad` method would trigger `noMoreLoad` method again, so I wanna pause the mechanism and then restart it.  Looking forward to your suggestion, thanks

**Comment by davideas** [comment]
Please try with 5.0.4-SNAPSHOT and let me know if it works now.
You need an `if` to pass delay of `-1` when empty and `0` or more seconds to remove the `progressItem`.
A simple refresh will trigger the loading more automatically.
```
allprojects {
    repositories {
        // For SNAPSHOT
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
    }
}
```
```
dependencies {
    implementation ('eu.davidea:flexible-adapter:5.0.4-SNAPSHOT') {
        changing = true;
    }
}
```

**Comment by steventxc** [comment]
@davideas that's fine, i test it in my code, and work fine. thanks for your work!
