### ISSUE TITLE
Apps that use this thing :)

### ISSUE THREAD

**Issue by mario** [davideas/FlexibleAdapter#598]
Nextcloud Talk
https://play.google.com/store/apps/details?id=com.nextcloud.talk2&hl=en
https://nextcloud.com/talk/

**Comment by mario** [comment]
Thanks for the awesome work!

**Comment by davideas** [comment]
@mario, great work! I'm pleased to have contributed to the idea of yours App.
What did you use for settings?

**Comment by mario** [comment]
@davideas thanks for the compliments!

For settings, I used a combination of https://github.com/yarolegovich/MaterialPreferences for the UI and Storebox for persistence magic.

In the future, I'll change it to use a bottom sheet for selections and inputs, but step-by-step :)
