### ISSUE TITLE
The adapter is highlighting text but not filtering

### ISSUE THREAD

**Issue by root1** [davideas/FlexibleAdapter#6]
I have copied the two classes and extended the Flexible adapter class in my adapter. My problem now is when i enter text in search view the text gets highlighted but it does not get filtered. I know im going wrong somewhere but i cant figure out where. Below is the code of my adapter class.

``` java
    public class FertilizerListAdapter extends FlexibleAdapter<FertilizerListAdapter.FertilizerViewHolder, Fertilizer> {
    List<Fertilizer> items;
    Context context;
    LayoutInflater mInflater;
    public FertilizerListAdapter(Context context, List<Fertilizer> items, String param) {
        this.items = items;
        this.context = context;
        mInflater = LayoutInflater.from(context);
        updateDataSet(param);
    }
    @Override
    public void updateDataSet(String param) {
        
    }
    @Override
    public FertilizerViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        View productItem = LayoutInflater.from(parent.getContext()).inflate(R.layout.fertilizer_list_item, parent, false);
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.HONEYCOMB)
            productItem.setLayerType(View.LAYER_TYPE_HARDWARE, null);
        FertilizerViewHolder productItemVH = new FertilizerViewHolder(productItem);
        return productItemVH;

    }

    @Override
    public void onBindViewHolder(FertilizerViewHolder holder, final int position) {
        Fertilizer item = items.get(position);
        Typeface custom_font = Typeface.createFromAsset(context.getAssets(), "fonts/RobotoSlab-Light.ttf");
        holder.mProductName.setText(items.get(position).sProductName);
        holder.mProductPrice.setText(items.get(position).sProductPrice);
        holder.mShortDesc.setText(items.get(position).sShortDesc);
        ColorGenerator generator = ColorGenerator.DEFAULT;
        int color = generator.getRandomColor();
        TextDrawable drawable = TextDrawable.builder()
                .beginConfig()
                .textColor(Color.WHITE)
                .toUpperCase()
                .useFont(custom_font)
                .fontSize(30)
                .endConfig()
                .buildRound(String.valueOf(items.get(position).sProductName.charAt(0)), color);

        Picasso.with(context)
                .load(items.get(position).sProductImage)
                .placeholder(drawable)
                .error(drawable)
                .into(holder.mProductImage);


        holder.itemView.setTag(item);
        if (hasSearchText()) {
            setHighlightText(holder.mProductName, item.sProductName, mSearchText);
            setHighlightText(holder.mShortDesc, item.sShortDesc, mSearchText);
        } else {
            holder.mProductName.setText(item.sProductName);
            holder.mShortDesc.setText(item.sShortDesc);
        }
        holder.mView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Intent i = new Intent(context, FertilizerView.class);
                i.putExtra("ProductApplication", (items.get(position).sApplication));
                i.putExtra("ProductAvailability", (items.get(position).sAvailability));
                i.putExtra("ProductBenefits", (items.get(position).sBenefits));
                i.putExtra("ProductChemicalContent", (items.get(position).sChemicalContent));
                i.putExtra("ProductCrops", (items.get(position).sCrops));
                i.putExtra("ProductBacgroundImage", (items.get(position).sProductBackground));
                i.putExtra("ProductImage", (items.get(position).sProductImage));
                i.putExtra("ProductName", (items.get(position).sProductName));
                i.putExtra("ProductPrice", (items.get(position).sProductPrice));
                i.putExtra("ProductDescription", (items.get(position).sShortDesc));
                context.startActivity(i);
            }
        });
    }





    @Override
    public int getItemCount() {
        return items.size();
    }


    public static class FertilizerViewHolder extends RecyclerView.ViewHolder {
        ImageView mProductImage;
        TextView mProductName;
        TextView mShortDesc, mProductPrice;
        View mView;

        public FertilizerViewHolder(View itemView) {
            super(itemView);
            mView = itemView;
            mProductImage = (ImageView) itemView.findViewById(R.id.product_image);
            mProductName = (TextView) itemView.findViewById(R.id.product_name);
            mProductPrice = (TextView) itemView.findViewById(R.id.price);
            mShortDesc = (TextView) itemView.findViewById(R.id.shortDesc);

        }
    }
    private void setHighlightText(TextView textView, String text, String searchText) {
        Spannable spanText = Spannable.Factory.getInstance().newSpannable(text);
        int i = text.toLowerCase(Locale.getDefault()).indexOf(searchText);
        if (i != -1) {
            spanText.setSpan(new ForegroundColorSpan(Utils.getColorAccent(context)), i,
                    i + searchText.length(), Spannable.SPAN_EXCLUSIVE_EXCLUSIVE);
            spanText.setSpan(new StyleSpan(Typeface.BOLD), i,
                    i + searchText.length(), Spannable.SPAN_EXCLUSIVE_EXCLUSIVE);
            textView.setText(spanText, TextView.BufferType.SPANNABLE);
        } else {
            textView.setText(text, TextView.BufferType.NORMAL);
        }
    }
    @Override
    protected boolean filterObject(Fertilizer fertilizer, String constraint) {
        String valueText = fertilizer.sProductName;
        //Filter on Title
        if (valueText != null && valueText.toLowerCase().contains(constraint)) {
            return true;
        }
        //Filter on Subtitle
        valueText = fertilizer.sShortDesc;
        return valueText != null && valueText.toLowerCase().contains(constraint);
    }
    }
```

**Comment by davideas** [comment]
Hi, did you take the Adapter from **dev** branch?
If yes, method *filterObject* is called by the inner class FlexibleFilter of the FlexibleAdapter of dev branch. It should work. Also MainActivity should use the class Filter: `mAdapter.getFilter().filter(newText);`

I have to advise you that only filtering should work, but don't allow the user to delete or add rows. 
*Reason*: When changing/removing the searchText and after add/remove rows, the filter is applied always from the untouched original list. I tried to have both lists synchronized (filtered list and the original list) but it has some bugs.
*My suggestion*: In one of my project the filter is not in the adapter (it contains only 1 list). Now at every new text I recalculate the original list and I use *updateDataSet*. It's simplier and the user can perform all actions on original list.

**Comment by root1** [comment]
Yes i took the adapter from the dev branch and this is how my MainActivity looks looks like

    public class FertilizersActivity extends AppCompatActivity implements SearchView.OnQueryTextListener{
    SwipeRefreshLayout mSwipeRefreshLayout;
    FertilizerListAdapter mAdapter;
    RecyclerView recyclerView;
    public static final String TAG = FertilizersActivity.class.getSimpleName();
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_fertilizers);
        mSwipeRefreshLayout = (SwipeRefreshLayout) findViewById(R.id.swipeRefreshLayout);
        setupToolbar();
        List<Fertilizer> items = new ArrayList<>();
        items.add(new Fertilizer("image", "image", "ZFC MaizeForcefert",
                "This is the short description of the product", "$20.00", "Available",
                "crops", "chemical content", "application", ""));
        items.add(new Fertilizer("image", "image", "Ground Nuts",
                "This is the short description of the product", "$20.00", "Available",
                "crops", "chemical content", "application", ""));
        items.add(new Fertilizer("image", "image", "Tobacco",
                "This is the short description of the product", "$20.00", "Available",
                "crops", "chemical content", "application", ""));
        items.add(new Fertilizer("image", "image", "Soyabeans",
                "This is the short description of the product", "$20.00", "Available",
                "crops", "chemical content", "application", ""));
        items.add(new Fertilizer("image", "image", "ZFC MaizeForcefert",
                "This is the short description of the product", "$20.00", "Available",
                "crops", "chemical content", "application", ""));
        recyclerView = (RecyclerView) findViewById(R.id.feed_recyclerview);
        recyclerView.addItemDecoration(new GridSpacingItemDecoration(1, 5, true));
        recyclerView.setHasFixedSize(true);
        recyclerView.setLayoutManager(new LinearLayoutManager(getApplicationContext(), LinearLayoutManager.VERTICAL, false));
        recyclerView.addItemDecoration(new SimpleDividerItemDecoration(this));
        mAdapter = new FertilizerListAdapter(FertilizersActivity.this, items , "example parameter for List1");
        recyclerView.setAdapter(mAdapter);
        mSwipeRefreshLayout.setOnRefreshListener(new SwipeRefreshLayout.OnRefreshListener() {
            @Override
            public void onRefresh() {
                refresh();
            }
        });
        updateEmptyView();
    }

    private void refresh() {
        try {
            Thread.sleep(2000);

            mSwipeRefreshLayout.setRefreshing(false);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        getMenuInflater().inflate(R.menu.menu_main, menu);
        initSearchView(menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        int id = item.getItemId();

        if (id == R.id.action_settings) {
            return true;
        }

        return super.onOptionsItemSelected(item);
    }

    private void setupToolbar() {
        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);
        ActionBar ab = getSupportActionBar();
        ab.setDisplayShowHomeEnabled(true);
        ab.setDisplayHomeAsUpEnabled(true);
    }

    @Override
    public boolean onQueryTextSubmit(String query) {
        return onQueryTextChange(query);
    }

    @Override
    public boolean onQueryTextChange(String newText) {
        if (!FertilizerListAdapter.getSearchText().equalsIgnoreCase(newText)) {
            Log.d(TAG, "onQueryTextChange newText: " + newText);
            FertilizerListAdapter.setSearchText(newText);
            mAdapter.getFilter().filter(newText);
        }
        //Due to Filter background Thread, give some short time to finish filtering
        //Otherwise Adapter could not be synchronized with the new content
        new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                updateEmptyView();
            }
        }, 100L);
        return true;
    }
    private void updateEmptyView() {
        //TextView emptyView = (TextView) findViewById(R.id.empty);
        //emptyView.setText(getString(R.string.no_items));
        if (mAdapter.getItemCount() > 0) {
            recyclerView.setVisibility(View.VISIBLE);
            //emptyView.setVisibility(View.GONE);
        } else {
            recyclerView.setVisibility(View.GONE);
            //emptyView.setVisibility(View.VISIBLE);
        }
    }
    private void initSearchView(final Menu menu) {
        //Associate searchable configuration with the SearchView
        Log.d("onCreateOptions", "onCreateOptionsMenu setup SearchView!");
        SearchManager searchManager = (SearchManager) getSystemService(Context.SEARCH_SERVICE);
        final SearchView searchView = (SearchView) MenuItemCompat
                .getActionView(menu.findItem(R.id.search));
        searchView.setInputType(InputType.TYPE_TEXT_VARIATION_FILTER);
        searchView.setImeOptions(EditorInfo.IME_ACTION_DONE | EditorInfo.IME_FLAG_NO_FULLSCREEN);
        searchView.setQueryHint(getString(R.string.search));
        searchView.setSearchableInfo(searchManager.getSearchableInfo(getComponentName()));
        searchView.setOnQueryTextListener(this);
        searchView.setOnSearchClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                menu.findItem(R.id.action_settings).setVisible(false);
            }
        });
        searchView.setOnCloseListener(new SearchView.OnCloseListener() {
            @Override
            public boolean onClose() {
                menu.findItem(R.id.action_settings).setVisible(true);
                return false;
            }
        });
    }
    @TargetApi(Build.VERSION_CODES.HONEYCOMB)
    @Override
    public boolean onPrepareOptionsMenu(Menu menu) {
        Log.v(TAG, "onPrepareOptionsMenu called!");
        SearchView searchView = (SearchView) menu.findItem(R.id.search).getActionView();
        if (!mAdapter.hasSearchText()) {
            Log.d(TAG, "onPrepareOptionsMenu Clearing SearchView!");
            searchView.setIconified(true);// This also clears the text in SearchView widget
        } else {
            searchView.setQuery(mAdapter.getSearchText(), false);
            searchView.setIconified(false);
        }
        return super.onPrepareOptionsMenu(menu);
    }

    }


i guess my issues is here
"method filterObject is called by the inner class FlexibleFilter of the FlexibleAdapter"
I cant figure it out from the example app. How should i implement it?

**Comment by root1** [comment]
i can see notifyDataSetChanged() is getting called onTextChange but its just the filter which is not working

**Comment by davideas** [comment]
Try to put some logs while filtering, especially in the Filter inner class.
Highlight works because is independent from the filter.

**Comment by davideas** [comment]
Maybe it could be that you didn't enabled the search in the manifest, have a look at others files & differences.

**Comment by root1** [comment]
Ok let me do as that

**Comment by root1** [comment]
I think i finally pin pointed the error and here it is

     java.lang.NullPointerException
            at java.util.ArrayList.<init>(ArrayList.java:93)
            at com.greencrunch.utils.FlexibleAdapter$FlexibleFilter.performFiltering(FlexibleAdapter.java:371)
            at android.widget.Filter$RequestHandler.handleMessage(Filter.java:234)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.os.HandlerThread.run(HandlerThread.java:60)

And this is the line of code on line 371

    					mOriginalValues = new ArrayList<T>(mItems);

**Comment by davideas** [comment]
Yes, I see now. In the first message you use a custom list `items` while you should use `mItems` already part of the adapter, and so `mItems` cannot be that null while filtering.

Instead of passing the list to the adapter create it inside the FertilizerListAdapter, you should implement this method:
``` java
public void updateDataSet(String param) {
	//Fill mItems with your custom list
	this.mItems = Database.getItems(param); //or the way you do
}
```
If you really can't do it (and I suggest to do it), you have to initialize `mItems` with your list: in your constructor `this.mItems = items;`
The list is already in the FlexibleAdapter, remove it from FertilizerListAdapter.

**Comment by root1** [comment]
Thanks man it work. So in case someone else may get the same issue you can just write on the main project page that they should initialize    mItems with their data in the constructor. Anyway, great work, thanks a lot

**Comment by davideas** [comment]
Well, I'm happy for you. I will add it the project page. Thanks.
