### ISSUE TITLE
Find out if row after is headerview

### ISSUE THREAD

**Issue by NLLAPPS** [davideas/FlexibleAdapter#600]
Excuse my ignorance but, Is there any easy way to know if the row/item after is (sticky or otherwise) a header-view?

**Comment by davideas** [comment]
@NLLAPPS, use `getStickyPosition()` and you evaluate this position with yours position.

**Comment by NLLAPPS** [comment]
Thanks, while at it, could you please point me to a sample where it shows how to add headers as bulk?

Currently I am creating header per item in the list which seems to work but also means I am creating a many header ls as items. I want to simplify push headers with unique ids where adapter would then  group items according to item and header ID.

This would allow me to create only needed header.

**Comment by davideas** [comment]
@NLLAPPS, so did you read the wiki page for [initialization](https://github.com/davideas/FlexibleAdapter/wiki/5.x-%7C-Headers-and-Sections#initialization)?

Not clear if you want:
- header1
- item1
- header2
- item2

or 

- header1
- item11
- item12
- header2
- item21
- item22

In any case, you only link a the same header of a section to the `ISectionable` items part of that section.
In demoApp, I create the demo lists in DatabaseService, check there.

**Comment by NLLAPPS** [comment]
I have items in headers. For example, list of recordings grouped by day, Day i header where there might be 1,2,3... recordings on each day
