### ISSUE TITLE
How to disable manual/onClick collapsing of an ExpandableViewHolder?

### ISSUE THREAD

**Issue by r-elbouhi** [davideas/FlexibleAdapter#601]
How to disable manual/onClick collapsing of an `ExpandableViewHolder` to be enable to expand item only
But should keep auto collapsing from `setAutoCollapseOnExpand` method.

**Comment by davideas** [comment]
@r-elbouhi, I do not understand your question.

**Comment by r-elbouhi** [comment]
thanks for replay

**Comment by r-elbouhi** [comment]
thanks for reply
i am asking for a way to do like this overriding function do "isViewCollapsibleOnLongClick() { return false;}"
but in the normal click not in the long click.
the purpose of my question to make the user unable to collapse Expandable list manually.

**Comment by davideas** [comment]
@r-elbouhi, at the moment you still need to override some key functions, unfortunately all of them have `@CallSuper` that you need to ignore. You can override for example the function `toggleExpansion()` to skip the collapse when called from `onClick` or to extend from `FlexibleViewHolder` and to copy everything.

I'm ok to improve the series of calls, by inserting a new check with `isViewCollapsibleOnClick`.

**Comment by r-elbouhi** [comment]
thanks for your effort @davideas
