### ISSUE TITLE
getCurrentItems but headers

### ISSUE THREAD

**Issue by NLLAPPS** [davideas/FlexibleAdapter#603]
Hi again,I seem to be keep bothering you :)

I have below routine to get certain data from Model held by Holder in the adapter

` flexibleAdapter = new RecordingAdapter(null, new RecordingAdapter.Listener() {
            @Override
            public void onPostFilter() {
                if (mRecordingListFragmentViewModel != null) {
                    mRecordingListFragmentViewModel.updateRecordingStatsFromHolder(flexibleAdapter.getCurrentItems());
                }
            }`

getCurrentItems() returns all items including headers. 

I know I can do

` for (IFlexible holder : holderItems) {
                if (holder instanceof RecordingHolder) {
                    recordingFiles.add(((RecordingHolder)holder).getRecordingFile());
                }
            }`

But, is there a helper method to get items excluding hder items similar to getHeaderItems()?

**Comment by davideas** [comment]
@NLLAPPS, there isn't a function for that, I would do the same as you do with the _for-loop_.
However, I guess that in `updateRecordingStatsFromHolder` you have a sort of loop to manage all items, well, if you do there, we save the for-loop done in the Adapter.
