### ISSUE TITLE
Remove section not working as I expect

### ISSUE THREAD

**Issue by steventxc** [davideas/FlexibleAdapter#607]
As document says
 `To remove a section: 
You can delete the header item with removeItem(getGlobalPositionOf(header));`

but when i want to remove a section, followed above instruction, just removed the header item only, not removed the section items belong to the header,.
do i need to remove the section items manually?

**Comment by davideas** [comment]
@steventxc, no indeed the documentation is a bit wrong. it deletes only the section header.
I can add a shortcut function to remove all the items of the sections, with `removeSection()`. In the meantime you have to remove yourself the items.

**Comment by steventxc** [comment]
```
List<Integer> ids = mAdapter.getSectionItemPositions(mHeaderItem);
mAdapter.removeItems(ids);
```

@davideas I used this code solve my problem, thanks

**Comment by davideas** [comment]
@steventxc, very good, indeed, the new `removeSection` will do something similar to that, but I will have to make it working also for expandable headers. I will publish this in 5.0.5.
