### ISSUE TITLE
Request to upgrade Android X

### ISSUE THREAD

**Issue by tcqq** [davideas/FlexibleAdapter#608]
@davideas Request to upgrade FlexibleAdapter to Android X

Because the support library and the androidx library are incompatible, This will lead to multiple errors.
Because support is about to be replaced by androidx. 
![image](https://user-images.githubusercontent.com/10644057/40062547-0b670fc6-588e-11e8-88e0-3082771bacf2.png)

![image](https://user-images.githubusercontent.com/10644057/40062064-e7b4bc00-588c-11e8-9077-886cbbe96764.png)
![image](https://user-images.githubusercontent.com/10644057/40063114-2d043518-588f-11e8-908d-b6d36b526ddb.png)

### Refactor AndroidX URL:
https://android-developers.googleblog.com/2018/05/hello-world-androidx.html
https://developer.android.com/studio/preview/features/#androidx_refactoring
https://dl.google.com/dl/android/maven2/index.html

![image](https://user-images.githubusercontent.com/10644057/40062432-c985eadc-588d-11e8-9012-7db9d0fb493d.png)

**Comment by tcqq** [comment]
Because over time, more and more libraries will use Android X instead of support, However, Android X and support are not compatible.  This will cause the current project can't to use the library that has been imported into Android X. At the same time Android X adds a variety of useful widgets, so you do not need to re-create in use time.

So I suggest updating 5.05 now, thank you very much. @davideas

**Comment by tcqq** [comment]
@davideas I upgraded the FlexibleAdapter to Android X and it now works. #609

**Comment by magneticflux-** [comment]
As an addendum, I just ran into an issue involving AndroidX, DataBinding, and your FlexibleAdapter-databinding companion library. After sorting through dozens of cryptic errors and trying random things to fix it, I eventually found that using a `@BindingAdapter` from your library while also using AndroidX dependencies causes about a million random other errors about completely unrelated things.

These were just a few of the errors produced:
```
e: C:\Users\username\StudioProjects\MyAppName\app\build\generated\data_binding_base_class_source_out\debug\dataBindingGenBaseClassesDebug\out\com\github\magneticflux\MyAppName\databinding\MenuFragmentBinding.java:25: error: cannot find symbol
  protected MenuFragmentBinding(DataBindingComponent _bindingComponent, View _root,
                                ^
  symbol:   class DataBindingComponent
  location: class MenuFragmentBinding
e: C:\Users\username\StudioProjects\MyAppName\app\build\generated\data_binding_base_class_source_out\debug\dataBindingGenBaseClassesDebug\out\com\github\magneticflux\MyAppName\databinding\MenuFragmentBinding.java:47: error: cannot find symbol
      @Nullable ViewGroup root, boolean attachToRoot, @Nullable DataBindingComponent component) {
                                                                ^
  symbol:   class DataBindingComponent
  location: class MenuFragmentBinding
e: C:\Users\username\StudioProjects\MyAppName\app\build\generated\data_binding_base_class_source_out\debug\dataBindingGenBaseClassesDebug\out\com\github\magneticflux\MyAppName\databinding\MenuFragmentBinding.java:58: error: cannot find symbol
      @Nullable DataBindingComponent component) {
                ^
  symbol:   class DataBindingComponent
  location: class MenuFragmentBinding
e: C:\Users\username\StudioProjects\MyAppName\app\build\generated\data_binding_base_class_source_out\debug\dataBindingGenBaseClassesDebug\out\com\github\magneticflux\MyAppName\databinding\MenuFragmentBinding.java:67: error: cannot find symbol
      @Nullable DataBindingComponent component) {
                ^
  symbol:   class DataBindingComponent
  location: class MenuFragmentBinding
```

FYI, Android Studio 3.2 is on Beta 1 right now, so I'll be a while until a full release of Android Jetpack.

**Comment by jrcacd** [comment]
As android studio 3.2 is getting stable, this is an must have.

**Comment by NLLAPPS** [comment]
I am too using it on a project with Android Xabd it works fine without changing anything.

Android studio should already be jettifiying it.

**Comment by jrcacd** [comment]
Android Studio 3.2 is stable and androidx is stable too

**Comment by davideas** [comment]
Please update to [release 5.1.0](https://github.com/davideas/FlexibleAdapter/releases/tag/5.1.0).
