### ISSUE TITLE
Sticky headers are not pushing one another from screen when using grid layout manager.

### ISSUE THREAD

**Issue by MartinRajniak** [davideas/FlexibleAdapter#61]
Hi,
I am testing 5.0.0-b5 and found a bug in StickyHeaderHelper#translateHeader() on row 151. You are expecting next potential header on position 1. But if for example I use 3 columns in my grid, you will always get current header until all items in section are off the screen. 

So you won't get this nice pushing of one header off the screen by another header. 

I was able to reproduce this in your demo app, when I changed span count of grid to 3 and span size of all items except header to 1.

Anyway, thanks for great work.

**Comment by davideas** [comment]
Hello @MartinRajniak, I've reproduced the issue using the fragment ExpandableSection using 3 for span count and size for non header items.

Indeed, it should enter in the `if` at line 155 to calculate the translation, but it doesn't.
Logging the item cotent with adapterPos it shows:

SubItem[id=E1S1, title=Sub Item 1 in expandable section]
SubItem[id=E1S2, title=Sub Item 2 in expandable section]
_but not the sub Item 3, then it swap the header, so it doesn't see where the section ends_
swapHeader newPosition=5
SubItem[id=E2S2, title=Sub Item 2 in expandable section]

I will try to fix it.
Thanks.

**Comment by davideas** [comment]
I think this issue should be resolved, available with the SNAPSHOT of 2017-04-17.
