### ISSUE TITLE
Sticky expandable header disappears

### ISSUE THREAD

**Issue by interblitz** [davideas/FlexibleAdapter#612]
Hi, thank you for the great library.

There is an issue with sticky expandable header on 5.0.4. When I scroll recycle view **a little** the header becomes sticky and hides. Screen dump from the UI Automator Viewer shows that header and it's widgets are not disappeared really but invisible or transparent.

When scroll **much** header is ok.Tested on Android 5 and 7.

How can I fix an issue?

**Comment by davideas** [comment]
@interblitz, please describe how to reproduce. Describe details on your list.
From the only indication "a little" the demoApp works well.

**Comment by interblitz** [comment]
Yes, you are right, demo works fine. Found out the difference. Changing

`recyclerView.setLayoutManager(new LinearLayoutManager(getContext()));`
to
`recyclerView.setLayoutManager(new SmoothScrollLinearLayoutManager(getContext()));`

is the solution. Thank you for the quick reply. Have a nice day :)

**Comment by davideas** [comment]
If I remove the 2 scrollable headers, the sticky header starts sticky and there remains: this occurs with CardView. With the 2 scrollable headers, the item disappears, but I do not know why, because if we continue to scroll it works. The issue is only for the first time as described.

**Comment by interblitz** [comment]
I've noticed also, when Cardview is surrounded with the Frame layout sticky headers doesn't disappear (see layout below). But in this case sticky header elevation is not drawn correctly.

There is something wrong with CardView may be...

```xml
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"

    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    >

<android.support.v7.widget.CardView xmlns:android="http://schemas.android.com/apk/res/android"
	xmlns:app="http://schemas.android.com/apk/res-auto"

	android:layout_width="match_parent"
	android:layout_height="wrap_content"
	>

<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
	xmlns:tools="http://schemas.android.com/tools"
	android:layout_width="match_parent"
	android:layout_height="?android:attr/listPreferredItemHeightSmall"
	android:background="#FF1B5E20"
	android:elevation="5dp">

	<LinearLayout
		android:id="@+id/title_container"
		android:layout_width="match_parent"
		android:layout_height="wrap_content"
		android:layout_marginLeft="@dimen/margin_left"
		android:layout_marginStart="@dimen/margin_left"
		android:layout_marginRight="@dimen/margin_right"
		android:layout_marginEnd="@dimen/margin_right"
		android:layout_centerInParent="true"
		android:orientation="vertical">

		<TextView
			android:id="@+id/title"
			android:layout_width="match_parent"
			android:layout_height="wrap_content"
			android:ellipsize="end"
			android:maxLines="1"
			android:textAppearance="@style/TextAppearance.AppCompat.Widget.Button.Inverse"
			tools:text="Header"/>

		<TextView
			android:id="@+id/subtitle"
			android:layout_marginTop="2dp"
			android:layout_width="match_parent"
			android:layout_height="wrap_content"
			android:ellipsize="end"
			android:maxLines="1"
			android:textAppearance="@style/TextAppearance.AppCompat.Caption"
			android:textColor="@color/material_text_color_white_text"
			tools:text="Header Subtitle"/>

	</LinearLayout>

	<ImageView
		android:id="@+id/row_handle"
		android:layout_width="wrap_content"
		android:layout_height="wrap_content"
		android:layout_alignParentEnd="true"
		android:layout_alignParentRight="true"
		android:layout_centerInParent="true"
		android:layout_marginEnd="@dimen/margin_right_handle"
		android:layout_marginLeft="@dimen/margin_left"
		android:layout_marginRight="@dimen/margin_right_handle"
		android:layout_marginStart="@dimen/margin_left"
		android:src="@drawable/ic_drag_handle_white_24dp"/>

</RelativeLayout>
</android.support.v7.widget.CardView>
</FrameLayout>
```

**Comment by davideas** [comment]
@interblitz, at line [191](https://github.com/davideas/FlexibleAdapter/blob/master/flexible-adapter/src/main/java/eu/davidea/flexibleadapter/helpers/StickyHeaderHelper.java#L191) I do `setBackground` as precondition for elevation, otherwise elevation won't be applied. CardView does not work well with backgrounds.
Which is your use case, to use cardVview as header?

**Comment by davideas** [comment]
@interblitz, I do not have an explanation, but we need a fixed height, **not** `wrap_content`!
Try with `android:layout_height="?android:attr/listPreferredItemHeightSmall"`.

It still doesn't explain why it becomes visible again as soon as the view holder is regenerated.  Are you sure you want to use CardView?

**Comment by interblitz** [comment]
@davideas, CardView just has preset options so it was the first choice to use. Moving from CardView to FrameLayout fixed all problems with disappearing and elevations.

Thank you for quick responses and have a nice weekend :)
