### ISSUE TITLE
FastScroller leave artifacts on the screen when language is RTL such as Hebrew

### ISSUE THREAD

**Issue by NLLAPPS** [davideas/FlexibleAdapter#613]
See the video from [https://imgur.com/a/CQeVuQH](https://imgur.com/a/CQeVuQH)

Layout:
``` xml
<android.support.constraint.ConstraintLayout 
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
        <include layout="@layout/flexible_adapter_fast_scroller" />
</android.support.constraint.ConstraintLayout>
```

FastScroller:
``` xml
<eu.davidea.fastscroller.FastScroller
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/fast_scroller"
    android:layout_width="wrap_content"
    android:layout_height="match_parent"
    android:layout_centerHorizontal="true"
    android:layout_alignParentEnd="true"
    app:fastScrollerAutoHideEnabled="true"
    app:fastScrollerAutoHideDelayInMillis="1000"
    app:fastScrollerBubblePosition="adjacent"
    app:fastScrollerBubbleEnabled="false"
    app:fastScrollerIgnoreTouchesOutsideHandle="false"
    tools:visibility="visible"/>
```

**Comment by davideas** [comment]
Hello @NLLAPPS, you should create custom drawables and custom views with the new drawables, take inspiration from the library ([library_fast_scroller_layout.xml](library_fast_scroller_layout.xml)). Then in your code, pass the views to the FastScroller before assigning it to the Adapter:
``` java
fastScroller.setViewsToUse(
                R.layout.library_fast_scroller_layout,
                R.id.fast_scroller_bubble,
                R.id.fast_scroller_handle);
mAdapter.setFastScroller(fastScroller);
```
Once done this, could you share them here?

**Comment by davideas** [comment]
You see will need to change the attributes of the view and of the 2 drawables, that I cannot modify.
There might be also a modification for the animation, if you want it. In this case you need to implement/override `FastScroller`. `bubbleAnimator` and `scrollbarAnimator` are `protected` so you can access them.

**Comment by NLLAPPS** [comment]
Sorry for my ignorance but I am still not clear.
From what I understand documentation at [https://github.com/davideas/FlexibleAdapter/wiki/5.x-%7C-FastScroller](https://github.com/davideas/FlexibleAdapter/wiki/5.x-%7C-FastScroller) shows xml or java implementation.

Does fast scroll require to be set with mAdapter.setFastScroller(fastScroller); even if you just add xml? It does work fine without mAdapter.setFastScroller(fastScroller);

**Comment by NLLAPPS** [comment]
Excuse my ignoranc. But, I already use mAdapter.setFastScroller(fastScroller) without setViewsToUse. Do I have to add them even if my FastScroller layout is like above?

**Comment by davideas** [comment]
@NLLAPPS, please read the documentation, then if you make the RTL layouts and drawables, please share them here.

**Comment by NLLAPPS** [comment]
I am not usually this daft but I haven't got a clue which documentation you are talking about.

I am nit using any bubble drawables at all. I am simply using fast scroller and as you cna see from the video, there is an odd affect when it is first drawn.

Do you mean it is due to my layout?

**Comment by davideas** [comment]
@NLLAPPS, Wiki pages? there's FastScroller page.

**Comment by NLLAPPS** [comment]
Of course I have gone through with it. But anyways. Thanks for your help.

**Comment by mattlaabs** [comment]
I just ran into the same issue. It's easy to fix.
This prevents the fastscroller from taking over all events:
FastScroller.java
```
            case MotionEvent.ACTION_DOWN:
                if (event.getX() < handle.getX() - handle.getWidth()) return false; // padding start should be 0 for rtl
                if (event.getX() > handle.getX() + 2 * handle.getWidth()) return false; // fix RTL

```
also remove padding for handle ImageView in library_fast_scroller_layout.xml

This fixes the bubble design
drawable-ldrtl/fast_scroller_bubble.xml (NEW)
```
...
android:bottomRightRadius="38dp"
android:bottomLeftRadius="0px"
...
```

This fixes animations:
```
ScrollbarAnimator.java
    protected AnimatorSet createAnimator(View bar, View handle, boolean showFlag) {
        boolean rtl = bar.getContext().getResources().getConfiguration().getLayoutDirection() == View.LAYOUT_DIRECTION_RTL;
        int barWidth = bar.getWidth() * (rtl ? -1 : 1);
        ObjectAnimator barAnimator = ObjectAnimator.ofFloat(bar, TRANSLATION_X, showFlag ? 0 : barWidth);
        AnimatorSet animator = new AnimatorSet();
        if (handleAlwaysVisible) {
            animator.play(barAnimator);
        } else {
            int handleWidth = handle.getWidth() * (rtl ? -1 : 1);
            ObjectAnimator handleAnimator = ObjectAnimator.ofFloat(handle, TRANSLATION_X, showFlag ? 0 : handleWidth);
            animator.playTogether(barAnimator, handleAnimator);
        }
...
```
