### ISSUE TITLE
Different item sizes cause visualization problems

### ISSUE THREAD

**Issue by angelgutlop** [davideas/FlexibleAdapter#614]
Hello,
I have created a simple chat app that shows the messages sent by the users, so each item in recycler view has a different size. The error occurred when you scroll down because sometimes an undesired spacing appears between elements, as you can see in this image. Is there any solution for this?

Thank you

![image](https://user-images.githubusercontent.com/26769581/40501093-29ffc7c0-5f87-11e8-8436-ab1c630c6ffe.png)

[https://github.com/angelgutlop/SQawker](url)

**Comment by davideas** [comment]
@angelgutlop, it's strange. To start, remove from the SqwakAdapter `this.notifyDataSetChanged();`.
Then I see you use FlexibleItemDecoration with withDefaultDivider(), this accepts **nothing** or the **item layout** (not the divider id, it's already android default divider!) to which you want to apply the divider, possibly with drawOver.

**Comment by angelgutlop** [comment]
Thanks for answering!! However, these changes that you have proposed to me have not solved the problem. Can the problem be related to the layout of the item? To help investigate the cause I have initialized the app database with random messages of different sizes. You can download it from the previous url
 
![image](https://user-images.githubusercontent.com/26769581/40545484-45f93038-602c-11e8-9659-2fe2ac94ab75.png)

**Comment by davideas** [comment]
@angelgutlop, I see you removed the decorator, so it's not anymore involved. Do other extremely important modifications in `SqwakItem` which generally help your code:

- Use `public static class SqwakViewHolver`;
- Move `private final ViewBinderHelper viewBinderHelper = new ViewBinderHelper();` to your custom adapter. Then in order to have a unique reference to that helper, you can cast the adapter: a) at the creation; b) in the viewholder; c) in the binding.

I never got this issue in my apps, going for exclusion, I would say it might be something related to the layout or constraintLayout and not from the Adapter. Try change/play with the layout a bit.

**Comment by davideas** [comment]
@angelgutlop, You can use also **Layout Inspector** from the menu _tools_ in Android Studio.

**Comment by angelgutlop** [comment]
Hi. Thank you very much for your advices. I did not know the tool to inspect layouts. I have been checking the problem and it has to do with the sliding layout of the FrameLayout type of the SwipeRevealLayout. From time to time, this layout changes height and takes up more screen space as it has no limitations on its size. I am trying to solve this problem.

![image](https://user-images.githubusercontent.com/26769581/40620289-9246db2a-6298-11e8-94fa-d7470243ac13.png)

<com.chauthai.swipereveallayout.SwipeRevealLayout 
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    app:dragEdge="right"
    app:mode="same_level">
   

    <FrameLayout
        android:layout_width="wrap_content"
        android:layout_height="match_parent">

        <ImageView
            android:id="@+id/imagen_unfollow"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="center_vertical|center_horizontal"
            app:srcCompat="@drawable/ic_visibility_off_white_24dp" />

    </FrameLayout>

    <android.support.constraint.ConstraintLayout
        android:id="@+id/vista_frontal"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="@android:color/background_light"
        android:padding="8dp">
        .  .  .

</com.chauthai.swipereveallayout.SwipeRevealLayout>`

**Comment by angelgutlop** [comment]
Hi. I have been investigating the causes of this problem and it turns out that it is a problem in the library https://github.com/chthai64/SwipeRevealLayout to make the swipe. With this one, I have not had any problems. https://github.com/daimajia/AndroidSwipeLayout
Thanks for the help!!

**Comment by davideas** [comment]
@angelgutlop, thanks for your investigation.
