### ISSUE TITLE
Stable Ids break the initial animation

### ISSUE THREAD

**Issue by de-Stan** [davideas/FlexibleAdapter#616]
The initial animation of the items is "broken" while having enabled stable ids. Meaning you can see the items inside the recyclerView and then the animation will start flashing all the items. The rest of the items that are off screen yet are not affected and scrolling will animate them nicely.

If i disable the stable ids, passing false to the constructor then the initial animation is totally smooth. The recyclerview is empty and you can see the items animate from the bottom of the recyclerview. I'm using `slideInFromBottomAnimator`

I'm using the latest version of the library. Also i have a `GridLayoutManager` with two columns  but i tested it with with a `LinearLayoutManager` and got the same behavior.

**Comment by davideas** [comment]
@de-Stan, I've made several tries, with and without stableId.
Initially, in my demoApp there was scrollable header inserted _with no_ delay, changing stable ids had a difference, as you said, but when scrollable header is inserted _with_ a delay, stable ids had no impact.

Then, when I change layout, stable Ids seems not have an impact as well and always animate items (with an exception of staggered layout, which has different behavior and preconditions).

Have a case study with `FragmentOverall`.
