### ISSUE TITLE
EmptyViewHelper - Empty view is always shown for a few milliseconds after start

### ISSUE THREAD

**Issue by chrisonline** [davideas/FlexibleAdapter#617]
I use the EmptyViewHelper and it is working good except that it is shown for a few milliseconds before the data will be displayed.

How can I prevent this or is this "works as designed"?

It should be a white screen if it is loading and after loading show the empty view or the list.

**Comment by chrisonline** [comment]
Fixed it by myself.
If you set the emptyView in the layout to alpha=0.0 it is hidden at start.
The EmptyViewHelper set the alpha=1 if no data otherwise it will set alpha=0!

**Comment by davideas** [comment]
@chrisonline yes, it must start with `android:alpha="0.0"` and also I fixed the flashing in the beta4. I use the alpha animation to fade it in/out, which is nicer to see.
