### ISSUE TITLE
Sticky Header item disapere when recycler view scroll down

### ISSUE THREAD

**Issue by raiytu4** [davideas/FlexibleAdapter#619]
First of all, thank for the library, I have been using it for a long time, it's wonderful. Great job!

Recently I have been encountered a problem with the sticky header. It disappears when recycler view scrolling up. I have been using the sticky header for several times, it's work fine even when I combine it with Expandable. Not sure what is the problem with this project, I have tried to switch back to many version from 5.0.0 to 5.0.5, not thing work sadly. I have checked all the condition to make sticky header work like put recycler view in frame layout, set the condition to the adapter, equally method and so on. I have no Idea why this is happening.

Really need some help :(

Ps: The source code to demonstrate this issues can be found here:
https://github.com/raiytu4/StickyHeader

**Comment by davideas** [comment]
@raiytu4, it seems you are not following at all the steps in the documentation.
There are several mistakes, so please fix them getting help from the wiki.
`AbstractSectionableItems`, the parameter for `ViewHolder`, the fact you add header yourself to the list and ask to display them at startup, etc...

**Comment by raiytu4** [comment]
Thank, it's working great now, my bad.
