### ISSUE TITLE
About Listener

### ISSUE THREAD

**Issue by Joslyn-Chen** [davideas/FlexibleAdapter#620]
How Custom listeners？
https://github.com/davideas/FlexibleAdapter/wiki/5.x-%7C-Callbacks
I do not quite understand the description here.
Is there a simple example?

**Comment by davideas** [comment]
@Joslyn-Chen, here you can find one of the possible examples of a custom adapter. More specifically the points 1-2 of the wiki point you linked:
``` java
public class OrderItemsAdapter extends FlexibleAdapter<HolderOrderItem> {

    private OnQuantityClickListener mQuantityListener;

    public OrderItemsAdapter(@Nullable List<HolderOrderItem> items,
                             @NonNull Object listener) {
        super(items, listener);
        if (listener instanceof OnQuantityClickListener) {
            this.mQuantityListener = (OnQuantityClickListener) listener;
        }
    }

    public void increaseQuantity(int position) {
        mQuantityListener.onQuantityAdded(position);
    }

    public void decreaseQuantity(int position) {
        mQuantityListener.onQuantitySubtracted(position);
    }

    public interface OnQuantityClickListener {
        void onQuantityAdded(int position);
        void onQuantitySubtracted(int position);
    }

}
```
In the Views of the ViewHolder you trigger the call to the casted adapter and in the activity you implement the Listener so the adapter can forward again the call.
Once again, this is one way to do it, there are many ways. But the trigger comes from the event of the view.

**Comment by Joslyn-Chen** [comment]
@davideas Thank you very much for your answer.
I still have a question.An interface in Samples. 
[FragmentHeadersSections](https://github.com/davideas/FlexibleAdapter/blob/2b8a6a428a66dcd36784aa840357560cd57735bb/flexible-adapter-app/src/main/java/eu/davidea/samples/flexibleadapter/fragments/FragmentHeadersSections.java)
Both Headers and Sections,I can get a header-only list via mAdapter.getHeaderItems(), so how do I get a list of only the Section?

**Comment by davideas** [comment]
@Joslyn-Chen, well just check the available methods: `getSectionItems()`, `getSectionItemPositions()`.
However, normally, you have them already from your original source.
