### ISSUE TITLE
Possible bug in endless scroll feature

### ISSUE THREAD

**Issue by unveloper** [davideas/FlexibleAdapter#621]
Hi there!
First of all thanks for this library, I think it's amazing and very well done!

I'm not sure if I found a bug or I'm doing something wrong...
I think the endless scroll feature doesn't work when a threshold greater than 1 is set.
I have 1000 rows on my db and I retrieve them by a page size of 200.

Before adding them to the adapter I add headers if I need them, so if i retrieve 200 rows is possible that in the adapter the added elements on every "onLoadMoreComplete" will be more than 200 (I say this just to explain my situation but the fact that I add section elements it's not relevant).

This is what I get when I use the **default threshold** (logged inside the "onLoadMore" method of my EndlessScrollListener):

- offset = 0 itemcount = 1
- offset = 200 itemcount = 208 (this is the situazione when I've add 8 headers)
- offset = 400 itemcount = 408
- offset = 600 itemcount = 608
- offset = 800 itemcount = 808
- offset = 1000 itemcount = 1008

The offset it's **always correct, a multiple of my page size**.

This is what I get when i use a threshold of 10 or 50 (I'll put more result just to show that the loading become incorrect and random)

First try:

- offset = 0 itemcount = 1
- offset = 200 itemcount = 208
- offset = 200 itemcount = 208
- offset = 200 itemcount = 208
- offset = 200 itemcount = 208
- offset = 200 itemcount = 208
- offset = 400 itemcount = 408
- offset = 1400 itemcount = 1408

Second try:

- offset = 200 itemcount = 208
- offset = 200 itemcount = 208
- offset = 200 itemcount = 208
- offset = 400 itemcount = 408
- offset = 600 itemcount = 608
- offset = 1000 itemcount = 1008
- offset = 1200 itemcount = 1208

Third try:

- offset = 200, currentPage = 2, itemcount = 208
- offset = 200, currentPage = 2, itemcount = 208
- offset = 200, currentPage = 2, itemcount = 208
- offset = 400, currentPage = 3, itemcount = 408
- offset = 600, currentPage = 4, itemcount = 608
- offset = 800, currentPage = 5, itemcount = 808
- offset = 1400, currentPage = 8, itemcount = 1408

Can you help me?
Thanks

**Comment by davideas** [comment]
@unveloper, sorry but I do not get your case.
