### ISSUE TITLE
Basic Examples

### ISSUE THREAD

**Issue by hammadzz** [davideas/FlexibleAdapter#624]
Are there not any tutorials or basic examples? I went through the wiki which is quite useful but I am still quite stuck. Trying to implement a basic RecyclerView to use FlexibleAdapter is a simple example that could be done in good detail. Perhaps the learning on top of using Kotlin is making it far harder for me.

I just want sticky headers...

**Comment by davideas** [comment]
@hammadzz, the new demoApp is far to be ready, however if you follow the [Setting Up](https://github.com/davideas/FlexibleAdapter/wiki/5.x-%7C-Setting-Up) wiki page should be enough for basic list.
