### ISSUE TITLE
Add a Scrollable Header to the Sticky headers list.

### ISSUE THREAD

**Issue by Joslyn-Chen** [davideas/FlexibleAdapter#627]
Sticky headers list is displayed normally, but adding the ScrollableHeader results in the following error:

addScrollableHeader (adapter.Shop2GoodsSectionItem) in FlexibleAdapter cannot be applied to (Shop2GoodsCouponItem)

In this code:
`Shop2GoodsCouponItem couponItem = new Shop2GoodsCouponItem(entity, shop_id);
        sectionAdapter.addScrollableHeader(couponItem);`
My Shop2GoodsCouponItem:
`public class Shop2GoodsCouponItem
    extends AbstractFlexibleItem<Shop2GoodsCouponItem.GoodsCouponViewHolder> {
……
}`
My sectionAdapter：
`
Shop2GoodsSectionAdapter<Shop2GoodsSectionItem> sectionAdapter;
sectionAdapter = new Shop2GoodsSectionAdapter<>(null, this);
`
My AbstractSectionableItem：
`public class Shop2GoodsSectionItem extends
    AbstractSectionableItem<Shop2GoodsSectionItem.GoodsSectionViewHolder, Shop2GoodsHeaderItem> {
……
}
`
My Shop2GoodsHeaderItem：
`public class Shop2GoodsHeaderItem
    extends AbstractHeaderItem<Shop2GoodsHeaderItem.GoodsHeaderViewHolder> {
……
}`
My Shop2GoodsSectionAdapter：
`public class Shop2GoodsSectionAdapter<T extends IFlexible> extends FlexibleAdapter<T> {

  private OnGoodsSectionClickListener mListener;

  public Shop2GoodsSectionAdapter(@Nullable List<T> items, OnGoodsSectionClickListener listener) {
    super(items);
    this.mListener = listener;
  }
}`

**Comment by davideas** [comment]
Unsupported.
