### ISSUE TITLE
Implementing  IHolder Need Help!!!

### ISSUE THREAD

**Issue by dineshmm23** [davideas/FlexibleAdapter#628]
I have two fragments in a tab. One of them implement `Model holder functionality with header `and another implement `Model holder functionality without header`.
 **Note:** Both model are not same.   

> Model holder functionality to any previous item | ... + IHolder

Q1. How to implement selection mode differently for each fragment.
Q2. On Implementing , Event methods: `onClick()`
- How do i handle click event for slelction mode and other purposes like starting new activity
```
 @Override
        public void onClick(View view) {
            Toast.makeText(mContext, "Click on " + mTitle.getText() + " position " + getAdapterPosition(), Toast.LENGTH_SHORT).show();
           mcontext.startActivity(new Intent(mcontext,SomeClass.class);
            super.onClick(view);
        }
```

Q3. On Implementing  IHolder ,how to get the `model of selected position in click events or selection modes`

**Comment by davideas** [comment]
@dineshmm23.

A1. ActionMode can be unique for each screen (let's say), if you have 2 fragments shown at the same time (you didn't explain well), only one per time can be active! to implement check the wiki page and demoApp.

A2. The click event is handled in the Fragment/Activity by implementing the relative listener from FlexibleAdapter and initializing it with the listener object. The `onClick` in ViewHolder already provides the callback to the Fragment/Activity! Open that `super.onClick`, read the javaDoc+Wiki and study the code!!

A3. In the implementation of the click listener in Fragment, you receive the position necessary to get the item from the Adapter, you cast it and you have your Model inside with `getModel`.

**Comment by dineshmm23** [comment]
Sorry i am new to implementation of ur libarary...i'm trying my best to understand the wiki..

> A3. In the implementation of the click listener in Fragment, you receive the position necessary to get the item from the Adapter, you cast it and you have your Model inside with getModel.

```
for (AbstractFlexibleItem adapterItem : mAdapter.getDeletedItems()) {
            // NEW! You can take advantage of AutoMap and differentiate logic by viewType using "switch" statement
            switch (adapterItem.getLayoutRes()) {
                case R.layout.comm_member_adapter:
                    break;
                case R.layout.fragment_comm_roles_adapter:
                    // mItems.removeItem(adapterItem);
                    
**adapterItem**  is AbstractFlexibleItem how can these

                    break;
            }
```

How do i get model obj from these item in `selection mode(mActionModeHelper`)?
