### ISSUE TITLE
Having trouble with checkboxes in subItems updating on checkChanged and holding state after scroll

### ISSUE THREAD

**Issue by james-nicholas** [davideas/FlexibleAdapter#629]
I've implemented an expandable and sticky header with a subItem. It collapses and sticks as I would expect when I've added items. However, when the subItem contains a checkbox(and I'm assuming I'd have the same problem with a button) I can't get the checkbox to save state after a scroll. I also am not sure what's the proper way to set the checkbox item or what to check against in the bindViewHolder. I believe I've set up my equals/hash correctly(generated).

1. How can I set the checkbox item properly? Via the subItem ViewHolder and have a setOnCheckedChangeListener? Then what does the listener actually set?

2. In the bind, I can't seem to get access to the actual dataList to see if the dataList(position).checkBox is set. How can I see if the actual subItem checkbox is set such that I can set the viewHolder's checkbox?

Thanks.

Edit: I think i have it working, but still would like to know best practices. In the subItem's viewHolder, for the onCheckedChangedListener, I'm doing:

 ((SubItem) adapter.getItem(getAdapterPosition))).getCheckBox().setSelected(isChecked);

And in the bind, I'm doing:

holder.mCheckBox.setChecked(((SubItem) adapter.getItem(position).getCheckBox().isSelected());

**Comment by davideas** [comment]
@james-nicholas, yes, that is the solution to set and get the value for an item. Do you need something else?

**Comment by james-nicholas** [comment]
Thank you.

If you'll allow me one more:

1. What's the desired way to get that checkedChanged callback to the parent fragment? I have the itemView onClick callback working fine and get notified in the fragment. Would I somehow make use of the addListener feature I've read about here? I only want to be notified when the checkbox is clicked.

**Comment by davideas** [comment]
@james-nicholas, in your case checkBox onChange is equivalent to the onClick of the item.
However, to answer at your question as general rule, you can extend the adapter and add inside there a public field as interface for the new listener. Then you implement the methods of this interface in the fragment; next add this fragment to the listeners. The custom listener callback will be triggered from the inside of the view callback.
I think you can check the Wiki about this customization (see [Setting-Up Advanced](https://github.com/davideas/FlexibleAdapter/wiki/5.x-%7C-Setting-Up-Advanced)).
