### ISSUE TITLE
Remove fade animation for sticky headers

### ISSUE THREAD

**Issue by volser** [davideas/FlexibleAdapter#632]
Is it possible to remove fade animation for sticky headers?
I didn't find in code

When I'm calling updateDataSet and there are sticky headers I see fade animations,
I didn't see such behavior on 5.0.3

**Comment by davideas** [comment]
Not wanted.

**Comment by volser** [comment]
ok, but why Fade animation when call updateDataSet?

appeared only in 5.0.5... reverted to 5.0.4 all ok

**Comment by davideas** [comment]
@volser, fade animation is now better displayed as it meant to be, at the initialization (enabling) and at the removal (disabling) of the feature. I just tried locally that using `updateDataSet` (with or without animate flag) has no glitch of the current sticky view (at least in my demoApp).
