### ISSUE TITLE
How to change subitems of expandable sticky header dynamically?

### ISSUE THREAD

**Issue by saipsa** [davideas/FlexibleAdapter#633]
My database consists of `AbstractExpandableHeaderItem`s with subitems.

So only list of `AbstractExpandableHeaderItem`s are passed to the adapter.

Now I want to fetch items from the network and the local cache based on the user input to `EditText`, which is expandable sticky header.

My requirements are

1. to clear the subitems of the expandable sticky header

1. add items from local cache

1. append items from network

Directly creating the subitem and adding it to the adapter leads to duplication of the sticky header.

what is the proper way to do it?

Thanks.

**Comment by davideas** [comment]
Everything is up to you, you will invoke same methods as you do for normal items. Of course useless to say that everything must be in sync.
If you are not sure of something, read documentations and JavaDoc!
