### ISSUE TITLE
Sticky Section Header Disappears on scrollToPositionWithOffset called inside onResume()

### ISSUE THREAD

**Issue by hammadzz** [davideas/FlexibleAdapter#634]
When using this adapter the stick section header disappears if called from onResume() of a fragment. Otherwise it works fine when called such as on button click. What is expected is for the stick header not to disappear and perform the same if called from within onResume lifecycle method.

```
override fun onResume() {
            (recyclerView.layoutManager as LinearLayoutManager).scrollToPositionWithOffset(10, 0)
}
```

**Comment by davideas** [comment]
@hammadzz, nope, just tried in demoApp.

**Comment by hammadzz** [comment]
Could this be due to me having a toolbar/view on top of the recyclerview?

**Comment by davideas** [comment]
@hammadzz, I have idea. Screenshot?

**Comment by hammadzz** [comment]
```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
    <RelativeLayout
        android:id="@+id/bar"
        android:background="@color/colorSerpiaDark"
        android:layout_width="match_parent"
        android:layout_height="36dp"
        android:paddingLeft="@dimen/default_margin"
        android:paddingRight="@dimen/default_margin">
        <Button
            android:id="@+id/verseBtn"
            android:layout_width="70dp"
            android:layout_height="28dp"
            android:layout_centerVertical="true"
            android:background="@drawable/hollow_button"
            android:textColor="@color/colorPrimaryDark"
            android:textSize="13sp"
            android:textAllCaps="false"
            android:text="@string/btn_verse_title"/>
    </RelativeLayout>
    <View
        android:id="@+id/divider"
        android:layout_width="match_parent"
        android:layout_height="1dp"
        android:background="@color/colorAccent"
        android:layout_below="@id/bar"
        />
    <FrameLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_below="@id/divider">
        <android.support.v7.widget.RecyclerView xmlns:android="http://schemas.android.com/apk/res/android"
            xmlns:tools="http://schemas.android.com/tools"
            android:id="@+id/recyclerView"
            android:name="app.example.example.VersesFragment"
            android:background="@color/colorSerpia"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            tools:context=".VersesFragment"
            tools:listitem="@layout/verse_item" />
        </FrameLayout>
</RelativeLayout>
```

<img src="https://user-images.githubusercontent.com/6963295/42902037-4005bedc-8a9b-11e8-816c-9374ca5f1a9b.png" data-canonical-src="https://user-images.githubusercontent.com/6963295/42902037-4005bedc-8a9b-11e8-816c-9374ca5f1a9b.png" width="200" />

**Comment by hammadzz** [comment]
I persist where the recyclerview position was and scroll to that position after and it hides the sticky header as shown here:

<img src="https://user-images.githubusercontent.com/6963295/42902385-754ac604-8a9c-11e8-9279-2d4bfaa7d627.png" data-canonical-src="https://user-images.githubusercontent.com/6963295/42902385-754ac604-8a9c-11e8-9279-2d4bfaa7d627.png" width="200" height="400" />

**Comment by davideas** [comment]
@hammadzz, I don't think is caused by that, however you can try to remove the top view just to try. If you normally scroll and header doesn't disappear that's ok.
Question, why do you need to scroll when user comes back to this page? normally this alter the status of the app when user left the page/app and might disorient the user.

And still, it works. You can try by applying the resume-scroll in the demoApp. It should be something else, but the code is yours, I cannot dig in it.

**Comment by hammadzz** [comment]
@davideas which code in the demo app are you referring to? I need to save the scroll position as the user would want to continue reading where they left off.

**Comment by davideas** [comment]
@hammadzz, add the resume in the `SectionHeaderFragment`.

**Comment by hammadzz** [comment]
@davideas do you mean to add the save last position and return to it in the FragmentHeadersSections example?

**Comment by davideas** [comment]
@hammadzz, yes: you save it `onStop` and you read it in `onResume`. maybe you should use the `savedInstanceState`.
