### ISSUE TITLE
Sticky expandable header - background disappears

### ISSUE THREAD

**Issue by interblitz** [davideas/FlexibleAdapter#635]
Hello,

I have the followed issue with sticky expandable header that don't know how to reproduce on demo.

1. PagerView contains three pages with flexible adapter. All three pages have sticky expandable header option on as well.
2.1. One adapter scrolled up so much as header becomes sticky and scrolled back down so sticky header replaced with its original layout. 
2.2 Then PagerView swiped left and right. After that **sometimes but often** header's  background is lost and becomes as window's background (deep black or white depends on theme).
2.3. If PagerView swiped left and right without step 2.1. background always remains.
2.4. Very seldom after step 2.1. background is lost just after refreshing adapter without step 2.2.

I have tried:
1. Manual set background to viewHolder.getContentView() in bindViewHolder, for example
contentView.setBackgroundColor();
2. Add a listener on page scrolled and called updateItem for header.

It brings strange results. Background still sometimes lost. But after that one left-right swipe restores original background and next one removes.

I have tried to put breakpoints into original code to find out background replacement but without any success. It seems that RecycleView do the job but not sure.

May be you have any clue to dig in?
May be clearHeader() doesn't completely restore header as before?

PS. I understand that you have a lot of work so just a hint to start with will be enough.

**Comment by interblitz** [comment]
Finally found out the cause. Having layout below for expandable item for coloring and ripple effect at the same time gives an issue.

```XML
<?xml version="1.0" encoding="utf-8"?>

<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"

    android:background="?attr/colorBackgroundFloating"
   >

    <LinearLayout

        android:id="@+id/item_layout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:minHeight="@dimen/dropdownListPreferredItemHeight"
        android:orientation="horizontal"

        android:background="?attr/selectableItemBackground"

        android:padding="@dimen/image_button_padding"
        >

        <ImageButton
            android:id="@+id/item_button_expand_collapse"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="center_vertical"

            android:background="?attr/selectableItemBackgroundBorderless"

            android:padding="@dimen/image_button_padding"
            android:src="@drawable/ic_action_navigation_expand_more" />

        <FrameLayout
            android:id="@+id/content_place_holder"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_gravity="center_vertical"

            android:orientation="vertical">

        </FrameLayout>

    </LinearLayout>

</FrameLayout>
```

Changing android:background="?attr/selectableItemBackground" to android:background="?attr/colorBackgroundFloating" for LinearLayput brings background color always stable.

**Comment by interblitz** [comment]
@davideas, 

Adding android:foreground="?attr/selectableItemBackground" to the linear layout works good. But will keep in mind your suggestion. Thank you very much.

**Comment by tcqq** [comment]
> @interblitz thank you.
> You can try to use the ripple and background at runtime with the `DrawableUtils`.

I tried to create a ripple on the **Expandable Item** using `DrawableUtils`, but when I swipe the sublist and then click on the **Header Item**, the ripple will have a dithering problem.
