### ISSUE TITLE
Adapter is not attached to RecyclerView. Enable sticky headers after setting adapter to RecyclerView.

### ISSUE THREAD

**Issue by saipsa** [davideas/FlexibleAdapter#637]
Steps to reproduce

1. make a new adapter, set it to recyclerview, enable stickyheader in adapter

repeat step 1, 2-3 times in succession.

Since `setStickyheaders` uses `post` to handler to set the sticky, by the time the runnanble of step 1 is scheduled to be run, the recyclerview has another adapter. When adapter1 tries, it gets null recyclerview, resulting in crash. Cannot catch it , as it is posted to handler.

Why set adapters in succession?

The adapters are set in response to callbacks.

**Comment by saipsa** [comment]
Proposed fix, fail silently if recyclerview is null

**Comment by davideas** [comment]
@saipsa, well that exception is there for a reason.
Try to change the way you display information, maybe reusing the same adapter OR use 3 fragments with one RV and its adapter OR not providing so many callbacks at the same time if you know the last is the one will be finally displayed!

I close this case.
