### ISSUE TITLE
[Dev Branch] - Demo app doesn't work on 23+ devices

### ISSUE THREAD

**Issue by tikimcfee** [davideas/FlexibleAdapter#64]
Hey there!

First off, gotta say, this seems like quite the library. I've been looking around for something like what you're putting together for 5.0 and I'm quite excited to play around with it! Unfortunately, I'm not able to actually run what's up on the current dev branch. The app immediately crashes on open.

I'm sitting at commit 175edaa7465ad3739d58e074f54fc012a7cdf6f8 right now, and I'm testing on a **Nexus 4** running **5.1.1** . On a fresh install, I get this exception:

```
FATAL EXCEPTION: main
Process: eu.davidea.examples.flexibleadapter, PID: 22437
        java.lang.RuntimeException: Unable to start activity ComponentInfo{eu.davidea.examples.flexibleadapter/eu.davidea.examples.flexibleadapter.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void eu.davidea.examples.flexibleadapter.OnListFragmentInteractionListener.onAdapterChange(android.support.v4.widget.SwipeRefreshLayout, android.support.v7.widget.RecyclerView, eu.davidea.examples.flexibleadapter.ExampleAdapter)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
        
        <..... Standard zygote activity stuff ..... >

Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void eu.davidea.examples.flexibleadapter.OnListFragmentInteractionListener.onAdapterChange(android.support.v4.widget.SwipeRefreshLayout, android.support.v7.widget.RecyclerView, eu.davidea.examples.flexibleadapter.ExampleAdapter)' on a null object reference
        at eu.davidea.examples.flexibleadapter.FragmentOverall.initializeRecyclerView(FragmentOverall.java:118)
        at eu.davidea.examples.flexibleadapter.FragmentOverall.onActivityCreated(FragmentOverall.java:78)
        at android.app.Fragment.performActivityCreated(Fragment.java:2061)
        <..... Standard fragment lifecycle stuff ..... >
```

Looks like the current lifecycle flow doesn't set 'mListener' on **FragmentOverall**. Commenting that out, I then get:

```
FATAL EXCEPTION: main
Process: eu.davidea.examples.flexibleadapter, PID: 25148
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean eu.davidea.examples.flexibleadapter.ExampleAdapter.hasSearchText()' on a null object reference
        at eu.davidea.examples.flexibleadapter.MainActivity.onPrepareOptionsMenu(MainActivity.java:369)
        at android.app.Activity.onPreparePanel(Activity.java:2841)
        at android.support.v4.app.FragmentActivity.onPrepareOptionsPanel(FragmentActivity.java:530)
```

Which makes sense, as there's a nice big block of code commented out where 'mAdapter' (seems to be) set. Commenting **that** out, I can get the app to open up and scroll around (looks awesome - love the slide in animations!), but beyond that, I can't navigate around to get to the different samples.

Any idea what commit I might be able to pull to test out your latest and greatest? Also, I'd be interested to help you test some samples out as you make them - I have a number of devices from API 19 through to 23 (no 24 yet), and know it can be painful to test the Recycler support library across the different versions. Also also, let me know if I can help provide any more info about the above errors, device stats, etc.

Anyway, thanks much for your time, and look forward to your next commits!

~ Ivan

**Comment by Yoshi3003** [comment]
Not sure if this is related but the apk file that is posted at https://github.com/davideas/FlexibleAdapter/releases/download/5.0.0-b5/flexible-adapter-v5.0.0-b5.apk cannot be launched, it crashed immediately (Android version 5.1.1, Samsung Galaxy S6).

**Comment by davideas** [comment]
@tikimcfee, thanks to report it.
I just discovered that `onAttach(Activity)` was deprecated in API 23. I implemented `onAttach(Context)` instead and so it is called by Android API  23 only. I used `android.app.Fragment` instead of the Support Fragment, because in the past support fragment didn't work on something specific that now I don't remember by heart.

The method `onAdapterChange()` of the listeners must be called to initialize the Adapter in the MainActivity, that's why you will get others NPE.
Regarding the big commented block, it was the old demo with only the MainActivity without fragments, but I'm trying to differentiate the examples with fragments.

But at this point I have to review the entire demo app. In the mean time, you have to use the a device or an emulator with API 23. Sorry for that.

**Comment by tikimcfee** [comment]
Ahh, I didn't realize they were standard Fragments and not AppCompat versions - totally overlooked!

Hopefully whatever issue you're trying to get around can be done in a way to handle SupportFragments, and in turn give a good base for older API supporting apps to run.

I don't recommend a full transition to it specifically, but you _could_ try to use something like Mosby (https://github.com/sockeqwe/mosby) to streamline the usage of support fragments and help give some well-known MVP structure to the setup of the demo app. **Take this with a grain of salt** as I have never used Mosby myself, but I think you get my drift. Perhaps you can find some other library that has abstracted away support fragments enough for you to quickly swap them out?

Anyway, don't worry about it. As I said, I have plenty of older devices to test with, and I look forward to running the sample on them to at least get a feel for it all.

Thanks much for the time!

P.S. - Should we close this ticket out and make a new one for "Demo app doesn't work on 23+ devices", or just rename this one?

**Comment by davideas** [comment]
Demo app should be fixed, I've committed the change and uploaded the new Apk.

Actually, the demo app already includes the new feature of multi-level expansions... but still does't work well when restoring deleted child items to the original position, I'm working on it and it will be available initially for the next SNAPSHOT library.

@tikimcfee
Rename and close, we can still continue to write here.
I will look the Mosby project, but there are several interesting architecture already in Github, some are in my _starred_ list.

Testing on different devices would be cool!
I will need some help for some special tests, and some extensions. For example a nice test would be to check how this library behaves when loading images from internet (for instance) with _Glide_; To see horizontal layout manager and grid with spanned rows and sticky headers (there's already an open bug on this). And so to create more examples in the demo.

Regarding the development, I don't know if you want to help: ToDo list is long, for example I'm looking a simple way to configure the `ViewHolder` to swipe items and show a real view below and not only a background painted, there's already something around (I can give references to others projects); To not create conflicts with custom item animators and adapter animation if both are active; etc...
