### ISSUE TITLE
Multi Selection in Recyclerview

### ISSUE THREAD

**Issue by Hemant0408** [davideas/FlexibleAdapter#642]
I have used multi selection in recyclerview, when i selects all using selectAll() method it selects all items and shows counter in toolbar. 

Issue is in this above case selection colour of some items not changing to selected colour.

my library version is:
compile 'eu.davidea:flexible-adapter:5.0.5'
compile 'eu.davidea:flexible-adapter-ui:1.0.0-b5'

**Comment by davideas** [comment]
@Hemant0408, insufficient information!! by the way demoApp works very well for selection state.
