### ISSUE TITLE
onRestoreInstanceState

### ISSUE THREAD

**Issue by de-Stan** [davideas/FlexibleAdapter#643]
I am getting some crashes in Firebase pointing at the onRestoreInstanceState method.

> Fatal Exception: java.lang.NullPointerException
> Attempt to invoke interface method 'java.util.Iterator java.util.Collection.iterator()' on a null object reference
> java.util.AbstractCollection.addAll (AbstractCollection.java:74)
> java.util.TreeSet.addAll (TreeSet.java:132)
> java.util.Collections$SynchronizedCollection.addAll (Collections.java:390)
> eu.davidea.flexibleadapter.SelectableAdapter.onRestoreInstanceState (SelectableAdapter.java:577)
> eu.davidea.flexibleadapter.FlexibleAdapter.onRestoreInstanceState (FlexibleAdapter.java:5106)

my code:
```
adapter = new FlexibleAdapter<>(stuff, this, true);
recyclerView.addItemDecoration(newFlexibleItemDecoration(this)
.withDefaultDivider()
.withDrawOver(true));
recyclerView.setAdapter(adapter);
adapter.setMode(SelectableAdapter.Mode.SINGLE);
adapter.onRestoreInstanceState(state);
```
This is a simple activity with no fragments involved. I am trying to reproduce the issue but i had no luck so far. I thought to check if the the state might be null but i see that you do check for this, first thing in the method.
Android versions from firebase listing with the crash are from 5 up to 8.

I don't know if i missed something, any suggestions on this?

**Comment by davideas** [comment]
@de-Stan, Yes you must check `savedInstanceState` is not null. I can also add a check for non null, but not publishing soon.

**Comment by davideas** [comment]
@de-Stan, `savedInstanceState` is already checked non null! The content is null. Do you call `onSaveInstanceState` ??

**Comment by davideas** [comment]
@de-Stan, can you check if outState is null? (I do not think it is). If you follow the flow in the code, your exception cannot happen, theoretically. Because the list object is created in `onSaveInstanceState` and taken in `onRestoreInstanceState` with the same TAG.

**Comment by de-Stan** [comment]
I do not think that **outstate** is null either but i will do some more testing. Until now i was not able to reproduce the crash.

**Comment by davideas** [comment]
@de-Stan, can you please read the conversation of issue #611 ? maybe there's something useful for you as well.

**Comment by de-Stan** [comment]
I will close this since i was not able to reproduce the crash on my phone and on the emulator. I will post here if i find anything at another time.

Thank you
