### ISSUE TITLE
Random crash when we update dataset with animate = true

### ISSUE THREAD

**Issue by longht89** [davideas/FlexibleAdapter#644]
Hello guys, we have an problem about animation in FlexibleAdapter.
It crashes when we push or pop a fragment, which has RecyclerView.

This is crash log:
https://drive.google.com/file/d/1dh4NR3DpmWT8k4UIiejDB0TpcQn2H918/view?usp=sharing

Thank you

**Comment by davideas** [comment]
@longht89, it might be that async task is not finished (long op) and fragment is popped. Some references might be null. I can't identify the line guilty, but if you have logs you can check it out the moment.

**Comment by davideas** [comment]
@longht89, in general not enough information to elaborate more this issue.
