### ISSUE TITLE
Divider shown between item and next header

### ISSUE THREAD

**Issue by Marvosg** [davideas/FlexibleAdapter#645]
When using the Flexible Adapter to display a list with multiple headers, there is an option to add a FlexibleItemDecoration to the recyclerview and show dividers only between specified view types (or all if no view types specified). I am using this part as such:
```
recyclerView.addItemDecoration( new FlexibleItemDecoration(context)
    .withDivider( R.drawable.list_divider, R.layout.friend_recycler_item )
    .withDrawOver(true));
```
I am displaying a `List<T extends AbstractSectionableItem>`. In this list I am only adding the items themselves, the headers are referenced in each item, as specified in the wiki. 

However, a divider is shown between the last item of a section and the next section's header:

<img width="540" alt="screenshot" src="https://user-images.githubusercontent.com/3502880/43617149-a2749288-96c0-11e8-8624-f9299d91b400.png">

Which is not expected behaviour, as these are two different view types, but a divider is still shown between them. Is there something missing or configured wrong?

**Comment by davideas** [comment]
@Marvosg, everthing works as expected for basic use cases. Yours is evident a special use case. Use different solution for dividers... :ok_hand:

**Comment by Marvosg** [comment]
Solved it by removing `FlexibleItemDecoration` and styling the background drawable of certain items to contain the divider graphic in themselves.
