### ISSUE TITLE
Collapse Header When Query not found and When user has finished searching 

### ISSUE THREAD

**Issue by shahzi8285** [davideas/FlexibleAdapter#653]
Hello,
Thank you for making this wonderful library.
but there is a issue which is creating a big hurdle in maintaining good UX in App that is 

**What I want to acheive**
1.Auto Collapse header item if searched item  does not exists in that group/parent
2. when user press back button of search view(Means he/She has completed search) auto collapse all parent items

**What I have tried**
I tried CollapseAll();but it does not work
I have tried with my custom code in FlexibleAdapter class but did not work
I have tried and wasted 7-8hours 

**What I have noticed**
this is log 
I have apply this log in 
``` java
@Override
public void setExpanded(boolean expanded) {
    Log.i(TAG, title+ " setExpanded: "+expanded);
    mExpanded = expanded;
}
```
GroupItem: Friends setExpanded: true
GroupItem: Contacts setExpanded: false
GroupItem: Friends setExpanded: true
GroupItem: Friends setExpanded: true
             
Please Help @davideas  As soon As possible it will be very thankful :)

**Comment by shahzi8285** [comment]
Just check sample of this library 
now these are steps for finding that problem

1.Open Library sample app
2.Go to Expendable Sections Tab
3.Search anything in search view and press back
Now notice that headers subtitle with will be like this "4 subitems Expended"

I hope that You understand that

**Comment by shahzi8285** [comment]
Is there anyone?

**Comment by davideas** [comment]
@shahzi8285, "4 subitems Expended" is just a text I've put for expand/collapse feature.
The adapter doesn't trigger a new update for the found items, it cannot do! So, if you really want it you have to bind yourself in the corresponding header the number of the items found.
I think you receive automatically the callback for the binding of the search.

The logic to retrieve that number is your duty. You have all the methods to reach that.
