### ISSUE TITLE
RestoreInstanceState does not work

### ISSUE THREAD

**Issue by tcqq** [davideas/FlexibleAdapter#658]
@davideas I found that MainActivity.java in AndroidManifest.xml contains the restriction activity reset code `android:configChanges="orientation|screenSize"`. I correctly added the `mAdapter.onSaveInstanceState(outState);` and `mAdapter.onRestoreInstanceState(savedInstanceState);` code. However, if you delete `android:configChanges="orientation|screenSize"` code, when the screen is rotated, the status of expanded/selection will not be restored normally. 

When I remove the `mAdapter.onSaveInstanceState(outState);` and `mAdapter.onRestoreInstanceState(savedInstanceState);` code, then I only add the `android:configChanges="orientation|screenSize"` code, when the screen is rotated, the state will resume normally. Because the activity does not reset when the screen is rotated.

Because the example was created in Fragment, the Fragment will not be affected when the Activity is reset, but if I create it on the Activity, how can I make the state not be lost after the activity is reset? But I don't want to use "configuration" to limit the activity reset because it is not officially recommended. What should I do to make the status not lost use in Activity?
![image](https://user-images.githubusercontent.com/10644057/44630103-3b957900-a98b-11e8-9192-7687bed052d1.png)

**I delete the red box code in the image, and  `android:configChanges="orientation|screenSize"` code, then I changed the items state and rotated the screen, but found that the items state is still correct.**
![image](https://user-images.githubusercontent.com/10644057/44630395-58cc4680-a98f-11e8-8f22-fed8fa465708.png)

So the following code doesn't work?
```
    @Override
    public void onSaveInstanceState(Bundle outState) {
        Log.v("onSaveInstanceState!");
        mAdapter.onSaveInstanceState(outState);
        super.onSaveInstanceState(outState);
    }

    @Override
    protected void onRestoreInstanceState(Bundle savedInstanceState) {
        super.onRestoreInstanceState(savedInstanceState);
        // Restore previous state
        if (savedInstanceState != null && mAdapter != null) {
            // Selection
            mAdapter.onRestoreInstanceState(savedInstanceState);
            mActionModeHelper.restoreSelection(this);
        }
    }
```

**Comment by ShahoodulHassan** [comment]
True, as soon as we delete android:configChanges="orientation|screenSize" and do a screen rotation, things go south.
@davideas please address that! Do we all have to declare android:configChanges="orientation|screenSize" in the manifest files of our apps if we use this library.

**Comment by davideas** [comment]
@tcqq @ShahoodulHassan Uhm.. not true at least in demoApp... I programmed correctly for both situations. DemoApp initializes the adapter on creation phase, then, the callback for restoration occurs. If you have delay due to asynchronous callback to initialize the adapter, then your restoration must occur after the adapter has been initialized(filled with previous items), to correctly assign the selected position on an existent item for same positions.
