### ISSUE TITLE
Collapsed feature does  not work

### ISSUE THREAD

**Issue by tcqq** [davideas/FlexibleAdapter#659]
@davideas Cannot be collapsed when Item is selected.
![image](https://user-images.githubusercontent.com/10644057/44669640-ffc5e680-aa52-11e8-9893-565a63396d52.png)

**Comment by davideas** [comment]
Clearly a wanted feature as stated everywhere.

**Comment by bogdanzurac** [comment]
I've just updated from v5.0.0-b7 to v5.0.5 and collapsing an expandable header item (or clicking any item for that matter) is not working anymore. Is this issue related?
