### ISSUE TITLE
Dev branch - null pointer exception on fastscroller setrecylcerview

### ISSUE THREAD

**Issue by zosocanuck** [davideas/FlexibleAdapter#66]
Hi,

I"m using dev branch and following your sample code (from FragmentExpandableSections.java), and running in an API 23 simulator:

`java.lang.NullPointerException: Attempt to invoke virtual method 'void eu.davidea.fastscroller.FastScroller.setRecyclerView(android.support.v7.widget.RecyclerView)' on a null object reference`

This is the relevant code in initializeRecyclerView():

> FastScroller fastScroller = (FastScroller) getActivity().findViewById(R.id.fast_scroller);
>         fastScroller.setRecyclerView(mRecyclerView);
>         //Add FastScroll to the RecyclerView, after the Adapter has been attached the RecyclerView!!!
>         mAdapter.setFastScroller(fastScroller,
>                 R.color.colorAccent, (HomeScreen) getActivity());

Any ideas?

**Comment by davideas** [comment]
@zosocanuck, probably it doesn't find the FastScroller with id R.id.fast_scroller;
I'll add a check on the FastScroller object.

Thanks to report it, I will fix it on next SNAPSHOT release.
However, be sure to set a non-null object when `mAdapter.setFastScroller()` is invoked.
