### ISSUE TITLE
Update StickyHeader Layout

### ISSUE THREAD

**Issue by athul131** [davideas/FlexibleAdapter#660]
Task:
I have to change the sticky header view alpha to 0.2f when a field/item is expanded and to 1.0f alpha 
 when a field is collapsed in the RecyclerView Items.
Question:
How can i update the sticky header layout  in recycler view list?

**Comment by davideas** [comment]
@athul131, in the binding you check if the header item position corresponds to the current sticky position. To update any item you can invoke the `updateItem()` function.
