### ISSUE TITLE
updateItem() on scrollable footer scrolls the recycler down

### ISSUE THREAD

**Issue by jakejanson** [davideas/FlexibleAdapter#661]
I have a code that displays a progress indicator at the end of a Recycler View using FlexibleAdapterʼs scrollable footer. After the loading is finished, the progress indicator turns into a message that all data have been loaded. To achieve this, I change the _loading state_ property of the `IFlexible` (Iʼm using the same adapter item instance for the indicator and the message – `bindViewHolder()` decides based on the _loading state_ which one to show) and then invoke `updateItem(indicator, Payload.CHANGE)`.

However, invoking the `updateItem()` causes the whole Recycler View to scroll down to the updated scrollable footer. I couldnʼt find anything in the documentation about this kind of behavior, so I donʼt know whether it is a bug, or a feature – in that case, can it be disabled somehow?

Right now Iʼm using a combination of `removeScrollableFooter()` followed by `addScrollableFooter()`, as those two methods do not invoke the unwanted scrolling behavior.

Iʼm using the adapter in combination with the Support Library and this issue occurs on all Android versions from API 14 to 28.

Thanks for any advice.

_`flexible-adapter` version: 5.0.5_
_`flexible-adapter-ui` version: 1.0.0-b5_
_`recyclerview-v7` version: 28.0.0-rc01_

**Comment by davideas** [comment]
@jakejanson, I'm sorry for you but what you say isn't true. Compile demoApp with the current code (modified Fab action for you); enter in _Headers and Sections_ example and wait for the initialization; check the footer title; go to any other positon (middle/top); press Fab button; check again the footer.
