### ISSUE TITLE
ActionModeHelper selects the wrong position

### ISSUE THREAD

**Issue by tcqq** [davideas/FlexibleAdapter#665]
@davideas First use "ActionModeHelper" or "toggleSelection" to select **"Simple Item 1"**, then I enter "2" in the search box, after Item is filtered, **"Simple Item 2"** is displayed in the position of **"Simple Item 1"**, causing it to be selected incorrectly.
![tim 20180904014514](https://user-images.githubusercontent.com/10644057/44998021-d70a9780-afe4-11e8-8e54-d162264d40d4.png)![tim 20180904014524](https://user-images.githubusercontent.com/10644057/44998022-d7a32e00-afe4-11e8-8561-add067aeea15.png)![tim 20180904014528](https://user-images.githubusercontent.com/10644057/44998026-d8d45b00-afe4-11e8-8497-1f5ca93d1172.png)

**Comment by davideas** [comment]
@tcqq, I tell you, selection how is made now, is a temporary state and is handled separated from the item status. You have item which have selected status inside as property, you cannot mix/confuse the 2 concepts.
The current item interface doesn't support selection property, the selection keeps tracks of the position.
So, this and others issues you opened have some preconditions not met.
You should bind correctly the item you display and filter, which are not "selected" for the adapter.

**Comment by tcqq** [comment]
@davideas I need to add a value for the selection state to the item?

**Comment by tcqq** [comment]
@davideas Any method?

**Comment by davideas** [comment]
Again, the search should not be used with selection. As said, the selection tracks the positions which won't correspond if you change the list by filtering it. This until I will move the selection inside the item as property: Create a Boolean as property in your item. Don't use selection in this specific use case.

**Comment by tcqq** [comment]
Thank you for your suggestion, I will try.
