### ISSUE TITLE
Some Simple Example

### ISSUE THREAD

**Issue by rajivenator** [davideas/FlexibleAdapter#67]
Hi Can you post a simple example Like loading contact list from contacts database and make them multi selectable with same animation as you have in your v5 branch for selection,

Your library though extremely useful is a bit too technical for a  newbie to understand,
Or it may be the case I am not reading the correct code base.

**Comment by davideas** [comment]
@rajivenator, I think it's possible, but keep in mind that the demo will be reviewed, as it is I don't like too :-) just that, I don't have time.

**Comment by davideas** [comment]
@rajivenator, what exactly is not clear: item interfaces? animators? methods to call?
I can try to create a better wiki page.

**Comment by rajivenator** [comment]
Hi may be the wiki needs a proper step by step.. In current documentation I am not able to understand where do i write View holders and how do i pass the collection of Items to be shown in recycler view.

Thanks in advance.

**Comment by davideas** [comment]
Ok, I will try to make something similar, however the `ExampleAdapter` (or the newest `OverallAdapter`) has my comments and you can see 2 ways to implement/bind ViewHolders. the normal way and with item interfaces.

**Comment by davideas** [comment]
I've added [How to use](https://github.com/davideas/FlexibleAdapter/wiki/5.x-%7C-How-to-use) wiki page.
You can you give some suggestions.

**Comment by hari2109** [comment]
Thanks for this great library. You've really demonstrated how powerful the RecyclerView can be with this. But I'm afraid you've highlighted how complex it can be too.

I've been trying to implement a simple sectioned recycler view with sticky headers for half a day, and I'm afraid I'm not quite able to figure out what needs to be done. The multiple levels of abstractions and inheritances in the examples have left me doing my head in and some of the documentation seems to be related to the code of the master branch instead of the dev branch code which I think you've used to build the beta5 apk. I'm gonna take another crack at it after clearing my head for a bit.

**Comment by davideas** [comment]
@hari2109, thanks for your message, but if you can be more specific maybe I can help you. The demo is under heavy development, and if you compare the one in _dev_ today for the last SNAPSHOT with the b5, much is changed and will continue to change to better separate single examples in fragments.

Regarding the levels of abstraction, there are wiki pages for 5.0 that explain the library structure and how the class signatures can be done.
However, I've studied others similar libraries and they are more or less on the same level, some even more complex.

**Comment by hari2109** [comment]
@davideas Yes, I can see that it is still undergoing lots of significant changes. I am waiting for the final stable version. In the meanwhile, I've gone ahead and tested an implementation of the b5 and used an implementation similar to the _FragmentHeadersSections_ from the example.I added the JCenter b5 dependency, and I am able to get a simple list without any headers working now.

After making my data model implement the _ISectionable_ interface, I tried to display the headers. But this call in the `bindViewHolder` method,
 `List<ISectionable> sectionableList = adapter.getSectionItems(this);` 
is causing an ANR in my application and after checking the implementation of this method, I can see that it is different in the dev branch and the added library. Could that be what is causing the issue?

**Comment by davideas** [comment]
@hari2109, indeed I changed that function (it was completely wrong), I trust you if it was causing an ANR, but I can't verify it.
If you really need it, please use the new SNAPSHOT release.
I still have to modify the demo app for the fab button, it will show a little dialog or a bottom sheet to customize the item to add depending the fragment in use, so I will also test all the new functions as well.

PS. For specific question like this, it is better to create another issue, next time.

**Comment by hari2109** [comment]
@davideas Sure, I will try with the SNAPSHOT release. I will report as separate issues if I find any as I keep exploring the different options. Initially the major difference in implementation of the example for the dev and master was what confused me. I have a clearer understanding of how to use it now. Thanks. Keep up the great work :+1:
