### ISSUE TITLE
Section headers are not visible

### ISSUE THREAD

**Issue by bogdanzurac** [davideas/FlexibleAdapter#671]
I've tried to implement sticky section headers using the first use case provided in the documentation at https://github.com/davideas/FlexibleAdapter/wiki/5.x-%7C-Headers-and-Sections.
I'm adding only AppointmentItems to the list and calling updateDataSet(list). In the fragment I'm calling  adapter.setDisplayHeadersAtStartUp(true).

As far sa I can tell, I think everything seems ok. However, headers are not showing up, only the items. Am I missing something?

```
class MyAdapter: FlexibleAdapter<AbstractFlexibleItem<FlexibleViewHolder>>(ArrayList())
{
    inner class AppointmentItem(
        private var sectionItem: SectionItem?,
        var appointment: AppointmentViewModel) : AbstractFlexibleItem<AppointmentViewHolder>(),
                                                 ISectionable<AppointmentViewHolder, SectionItem>
{
override fun getHeader(): SectionItem?
        {
            return sectionItem
        }
        
        override fun setHeader(header: SectionItem?)
        {
            this.sectionItem = header
        }

override fun equals(other: Any?): Boolean
        {
            return other is AppointmentItem && other === this
        }
        
        override fun hashCode(): Int
        {
            var result = sectionItem?.hashCode() ?: 0
            result = 31 * result + appointment.hashCode()
            return result
        }
}
  inner class SectionItem(
        var startDate: Date?,
        var endDate: Date?) :
        AbstractExpandableHeaderItem<SectionViewHolder, AppointmentItem>()
{
 override fun equals(other: Any?): Boolean
        {
            return other is SectionItem && other === this
        }
        
        override fun hashCode(): Int
        {
            var result = startDate?.hashCode() ?: 0
            result = 31 * result + (endDate?.hashCode() ?: 0)
            return result
        }
}
}
```

**Comment by tcqq** [comment]
@bogdanzurac This is an example that supports displaying sticky titles, you can take a look.
https://github.com/tcqq/FlexibleAdapterStickyHeaderExample

**Comment by bogdanzurac** [comment]
But that example from that link shows adding the list of **headers** as items of the adapter, each header containing a list of children. I wanted to add the list of **children** to the adapter, each child containing the associated header. It's the 1st use case from the documentation, not the 2nd one. I can confirm that inside another app we used the use case from your example and it worked. However, we need to implement the other solution.

**Comment by ShahoodulHassan** [comment]
@bogdanzurac have u tried using AbstractHeaderItem instead of AbstractExpandableHeaderItem?

**Comment by bogdanzurac** [comment]
But I need the headers to be expandable. However, I've got the 2nd use case working, like the demo @tcqq mentioned. Now that it works even with this approach, I'm wondering, why have 2 use cases? What's the advantage of adding the children to the adapter instead of the headers?

**Comment by ShahoodulHassan** [comment]
@bogdanzurac
As far as I understood, 1st use case is where u want section header only without the feature of expanding these to show their children. That's why in 1st approach, u just have to add the children to the adapter with rather dumb headers used as separators for each section.
I've tried both approaches and I can confirm both work as intended.

**Comment by bogdanzurac** [comment]
Then I suppose we should use the 2nd solution in our use case, which indeed works perfectly. Thanks for clearing things up!

**Comment by androidovshchik** [comment]
> @bogdanzurac This is an example that supports displaying sticky titles, you can take a look.
> https://github.com/tcqq/FlexibleAdapterStickyHeaderExample

Yes, its recyclerview is also expandable
