### ISSUE TITLE
Build qus/problems from a novice

### ISSUE THREAD

**Issue by jastewart** [davideas/FlexibleAdapter#678]
I am desperate to use something like FlexibleAdapter (FA) and it seems attractive cf. others.
First, my target device is Android 8.1. 
Am I right to assume that the AndroidX build of FA is therefore n/a? 
I have downloaded 5.0.6 and this builds and runs on an 8.1 emulator.
But, I can not work out what to include in my own project to make use of FA. I copied the given dependencies (trying both 5.0.6 and 5.1.0) but still get a number of build errors such as:
>resource android:attr/ttcIndex not found

I get these errors after adding only the given dependencies to an otherwise fully working project. I guess there must be some conflict, or something...
Reverting to v5.1.0, when I build the downloaded files, I get this:

> Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:8:2-45:16 to override.

1. How can I get v5.1.0 (as downloaded) to build?
2. When built, what do I need in some new project to use the adapter? - the given list of dependencies and jcenter does not seem to provide all that is needed.

Hoping to make progress....

TIA

**Comment by davideas** [comment]
@jastewart, clean project?

**Comment by mpt212** [comment]
@jastewart i have this problem too, can you resolve that?

**Comment by jastewart** [comment]
Sorry, I have only just discovered this in a spam folder.
I'm afraid that I jacked the whole thing in and went with Xamarin, with 
which I did more in an afternoon, from scratch, that I had done in two 
weeks with AS etc.

jas
