### ISSUE TITLE
FlexibleAdapter.OnItemClickListener and onItemClick position

### ISSUE THREAD

**Issue by zosocanuck** [davideas/FlexibleAdapter#68]
Hi,

I have implemented an AbstractFlexibleItem item with a ParentViewHolder that handles the onClick event:

```
@Override
        public void onClick(View view) {
            Toast.makeText(mContext, "Click on " + mNameView.getText() + " position " + getAdapterPosition(), Toast.LENGTH_SHORT).show();
            super.onClick(view);

        }
```

Now in my main activity I also implement `onClickItem `via` FlexibleAdapter.OnItemClickListener` implements, and notice that the position does not match up to what is obtained from the adapter.`getItem(position)`.  Any ideas?

I compared to your sample code but could not see anything wrong.

**Comment by davideas** [comment]
"Does not match up" what does it means exactly? Can you check if you are in this situation?
If yes, please use `getFlexibleAdapterPosition()`.

``` java
public abstract class FlexibleViewHolder extends ...

/**
 * Overcomes the situation of returning an unknown position (-1) of ViewHolders created out of
 * the LayoutManager (ex. StickyHeaders).
 * <p><b>NOTE:</b> Always call this method, instead of {@code getAdapterPosition()}, in case
 * of StickyHeaders use case.</p>
 *
 * @return the Adapter position result of {@link #getAdapterPosition()} OR the backup position
 *         preset and known, if the previous result was {@link RecyclerView#NO_POSITION}.
 * @see #setBackupPosition(int)
 */
public int getFlexibleAdapterPosition() {
	int position = getAdapterPosition();
	if (position == RecyclerView.NO_POSITION) {
		position = mBackupPosition;
	}
	return position;
}
```

**Comment by zosocanuck** [comment]
This is a different situation

onClick in the parentviewholder does this:

            Toast.makeText(mContext, "Click on " + mNameView.getText() + " position " + getAdapterPosition(), Toast.LENGTH_SHORT).show();

In my MainActivity I register  public boolean onItemClick(int position) { ...}
from within this i run mAdapter.getItem(position), and this produces an AbstractFlexibleItem that is different than the one shown via Toast in the parentviewholder.

Am I using mAdapter.getItem(position) correctly?

**Comment by davideas** [comment]
Sure it is correct, but it seems impossible what you say... because if you check implementation of `getItem(position)` it's just `List.get(index)`. I am not able to reproduce it.

Can you try to debug it? Display your item with getItem() inside the onClick before and after calling super() and check if the item is the same, also put a breakpoint in getItem and check the content of the `mList` inside the Adapter.

Finally read the comment of `getAdapterPosition()`.

**Comment by davideas** [comment]
I would say also, check the implementation of `equals` because get(index) returns the first item with equals() = true. So, if you have more items with same ID, that it is the issue.

**Comment by zosocanuck** [comment]
So I ended up debugging and at position = 1 from the onItemClick(int position) in MainActivity.java.

mItems has a list of 6 items (internally index as 0-5).  List.get(1) therefore returns the 2nd item instead of what I believe should be the first item in the list that was selected.

ProductLine header = new ProductLine("Section 1");
        mItems.clear();
        Product p1 = new Product("Test1", "Test1", 4.50, "Test1", header);
        Product p2 = new Product("Test2", "Test2", 5.50, "Test2", header);
        Product p3 = new Product("Test3", "Test3", 6.50, "Test3", header);
        mItems.add(p1);
        mItems.add(p2);
        mItems.add(p3);
        ProductLine header2 = new ProductLine("Section 2");
        Product p4 = new Product("Test4", "Test4", 7.50, "Test4", header2);
        Product p5 = new Product("Test5", "Test5", 8.50, "Test5", header2);
        Product p6 = new Product("Test6", "Test6", 9.50, "Test6", header2);
        mItems.add(p4);
        mItems.add(p5);
        mItems.add(p6);

**Comment by davideas** [comment]
The `mItems` you wrote, do you pass as it is, to the Adapter or you make a copy?
If you pass the the list as copy, keep in mind that the Adapter manipulates the list to display the extra items like headers for example, or to make the undo.

If the item "Test4" is at position 3 in your list, in the adapter list with headers shown it's 5.

**Comment by zosocanuck** [comment]
Well originally I ended up creating a 2nd adapter for the activity to reference but that seemed to causing problems with the list, so ended up referencing the fragment adapter, and list indexing is now working fine. I will close this ticket for now.
