### ISSUE TITLE
Scrollable headers/footers behavior when filtering

### ISSUE THREAD

**Issue by shymmq** [davideas/FlexibleAdapter#681]
[5.x | Scrollable Headers and Footers](https://github.com/davideas/FlexibleAdapter/wiki/5.x-%7C-Scrollable-Headers-and-Footers)
> Cannot be filtered because they are not part of the main list, but added separately at the initialization phase (basically, implementing IFilterable will be useless).

What does this mean exactly? Will the headers/footers remain in the list after filtering or not? Is it possible to modify this behavior? I'm trying to apply a search filter to main items, but leave the scrollable header untouched. Unfortunately, the header always disappears when i use filterItems().

I tried overriding filterObject() with this:
`override fun filterObject(item: GenericItem?, constraint: Serializable?) = if (isScrollableHeaderOrFooter(item)) true else super.filterObject(item, constraint)`
but it doesn't seem to affect the behavior.

Is there any way around this?

**Comment by davideas** [comment]
@shymmq, I'm sorry but it is not possible for how it is designed. It is in more parts of the code.
It could be done in the future, but I have no plan/time for it now.
