### ISSUE TITLE
Layout property fastScrollerIgnoreTouchesOutsideHandle does not work

### ISSUE THREAD

**Issue by Fanda36** [davideas/FlexibleAdapter#685]
Hi,

I tried this layout property from doc in layout XML `app:fastScrollerIgnoreTouchesOutsideHandle="true"`. But it was ignored. When I set it programmatically `fastScroller.setIgnoreTouchesOutsideHandle(true);` then it works fine.

I use last version of FlexibleAdapter - 5.1.0

Thank you for really nice adapter.

**Comment by davideas** [comment]
@Fanda36, just verified that it works.
