### ISSUE TITLE
How to change the status of header item when it expand or collapse?

### ISSUE THREAD

**Issue by hayukleung** [davideas/FlexibleAdapter#69]
I try to change the status of header item when it expand or collapse:

`eu.davidea.examples.models.ExpandableHeaderItem.java`

`@Override`
`public void bindViewHolder(FlexibleAdapter adapter, ExpandableHeaderViewHolder holder, int position, List payloads) {`
`    if (payloads.size() > 0) {`
`        Log.i(this.getClass().getSimpleName(), "ExpandableHeaderItem Payload " + payloads);`
`    } else {`
`        holder.mTitle.setText(getTitle());`
`    }`
`    setSubtitle(adapter.getCurrentChildren(this).size() + " subItems");`
`    holder.mSubtitle.setText(getSubtitle());`
`    // my code -------------------------------------------------------------------------------------`
`    if (isExpanded()) {`
`        holder.mSubtitle.setText("expanded");`
`    } else {`
`        holder.mSubtitle.setText("collapse");`
`    }`
`    // my code --------------------------------------------------------------------------------------`
`}`

thank you!

**Comment by hayukleung** [comment]
`
eu.davidea.examples.models.ExpandableHeaderItem.java
public static class ExpandableHeaderViewHolder extends ExpandableViewHolder {

		public TextView mTitle;
		public TextView mSubtitle;

        private FlexibleAdapter mFlexibleAdapter;

		public ExpandableHeaderViewHolder(View view, FlexibleAdapter adapter) {
			super(view, adapter);
            mFlexibleAdapter = adapter;
			mTitle = (TextView) view.findViewById(R.id.title);
			mSubtitle = (TextView) view.findViewById(R.id.subtitle);
		}

		@Override
		protected boolean isViewExpandableOnClick() {
			return true;
		}

        @Override
        public void onClick(View view) {
            super.onClick(view);
            mFlexibleAdapter.notifyDataSetChanged();
        }
    }`
it works!

**Comment by davideas** [comment]
@hayukleung, yes it works but I give you the correct lines and command. if you use `notifyDataSetChanged()` you are going to bind again **all** items! And `onClick()` is not at all the good place to add it, because the `expand()` and `collapse()` methods are called under some conditions, override the 2 methods like this in `ExpandableHeaderViewHolder`:

``` java
@Override
protected void expandView(int position) {
	super.expandView(position);
	//Let's notify the item has been expanded
	if (mAdapter.isExpanded(position)) mAdapter.notifyItemChanged(position, true);
}

@Override
protected void collapseView(int position) {
	super.collapseView(position);
	//Let's notify the item has been collapsed
	if (!mAdapter.isExpanded(position)) mAdapter.notifyItemChanged(position, true);
}
```

Basically you notify **only** that item and also you send a payload object that you will check in the bind method to even optimize the single view binding:

``` java
@Override
public void bindViewHolder(FlexibleAdapter adapter, ExpandableHeaderViewHolder holder, int position, List payloads) {
	if (payloads.size() > 0) {
		Log.i(this.getClass().getSimpleName(), "ExpandableHeaderItem Payload " + payloads);
	} else {
		holder.mTitle.setText(getTitle());
	}
	setSubtitle(String.valueOf(adapter.getCurrentChildren(this).size()) +
			" subItems (" + (isExpanded() ? "expanded" : "collapsed") + ")");
	holder.mSubtitle.setText(getSubtitle());
}
```

I added this code to the example app. I will commit soon with many others changes for the demo app, keep watched my commits :-)

**Comment by hayukleung** [comment]
I got it, thanks for your help!
