### ISSUE TITLE
loading more `currentPage` values will not be restored

### ISSUE THREAD

**Issue by tcqq** [davideas/FlexibleAdapter#693]
@davideas When the activity is reset, loading more `currentPage` values will not be restored. I can recreate a "currentPage" to recover, but this means I can't load more of the other features in the framework, ex: setEndlessPageSize, setEndlessTargetCount. Is it possible to add an option to set whether support for recovery?

**Comment by davideas** [comment]
@tcqq, what do you mean with "activity is reset" and with "support for recovery"?
The `currentPage` is calculated as `getMainItemCount() / mEndlessPageSize`.

**Comment by tcqq** [comment]
@davideas After the activity is reset, if the data is not saved, the data will be restored to the default value. Save and restore data like this.

```
    override fun onSaveInstanceState(outState: Bundle?) {
        outState?.run {
            putInt(STATE_PAGE_NUMBER, pageNumber)
        }
        super.onSaveInstanceState(outState)
    }
```

```
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        if (savedInstanceState != null) {
            with(savedInstanceState) {
                pageNumber = getInt(STATE_PAGE_NUMBER)
            }
        }
```

**Comment by davideas** [comment]
@tcqq, I think you can take/read again the correct `pageNumber` after the adapter has been initialized with all its configuration for endless feature and with all the items loaded with "loading more" OR use the configuration change property.

**Comment by tcqq** [comment]
@davideas Yes, I am using the above method, because `currentPage` in **FlexibleAdapter** will not save and restore state after the activity is re-created  so I created a `pageNumber` in the activity that supports saving and restoring state after the activity is recreated. I mean the currentPage in the FlexibleAdapter will not save its value after the activity is reset, it will be restored to the default value.

**Comment by davideas** [comment]
@tcqq, currentPage is a function is not a variable inside the adapter, so it cannot be restored.

**Comment by tcqq** [comment]
Ok, I understand, thank you for your reply.
