### ISSUE TITLE
fastScroller does not save and restore scroll position

### ISSUE THREAD

**Issue by tcqq** [davideas/FlexibleAdapter#694]
@davideas The fastScroller scroll position will not be saved and restored when the activity is reset.

The state of the example is not lost because this line of code: `android:configChanges="orientation|screenSize`

**Comment by tcqq** [comment]
The same code. If directly use the [RecyclerView-FastScroll](https://github.com/timusus/RecyclerView-FastScroll) library, the above problem will be fixed. However, when the scroll bar is swiped. Drop frame is obvious.

**Comment by davideas** [comment]
Duplicate of #686
