### ISSUE TITLE
5.0.6 does not update after updateDataSet()

### ISSUE THREAD

**Issue by chrisonline** [davideas/FlexibleAdapter#699]
On version 5.0.6 the updateDataSet does not update the data.
I have 3 headers with 50 elements in sum.

No I add 3 elements to the last header item and call updateDataSet().
The data is not updated and I see only the 50 elements on the screen.

Changed version back to 5.0.5 and it is working again.
Can you please check this?

**Comment by davideas** [comment]
@chrisonline, it can be many things. Check if your equals method of the items is well implemented or if you didn't have `setNotifyChangeOfUnfilteredItems` to `false`.
You can also `enableLogs(Level.DEBUG/VERBOSE)` to verify what the adapter is doing.

Items get update!
