### ISSUE TITLE
Any news about development?

### ISSUE THREAD

**Issue by Rainer-Lang** [davideas/FlexibleAdapter#7]

**Comment by davideas** [comment]
Hi, do you mean the search functionality?
I have to advise you that only the filter works. Deleting/modify/add rows when filter is active it doesn't have the expected result. For the moment I keep it in Dev. Probably I will remove it.

*Reason*: Every time when changing/removing the searchText and just after add/mod/delete rows, the filter generates a new list from the untouched original list. I tried to have both lists synchronized (filtered list and the original list) but it is not practical at all...

*My suggestion*: In one of my project the filter is not in the adapter (it contains only 1 list). Now at every new searchText I recalculate the original list and I use updateDataSet. It's **simplier** and the user can perform **all actions** on original list.

**Comment by Rainer-Lang** [comment]
Thanks for your answer.
