### ISSUE TITLE
Fragments using FlexibleAdapter only works with the first fragment when inside a ViewPager

### ISSUE THREAD

**Issue by jonathanyee** [davideas/FlexibleAdapter#70]
So I found a weird bug.  I have 2 different fragments that I want stickyheaders enabled and another fragment that doesn't use this library inside of a ViewPager.  However, only the first fragment with stickyheaders enabled that I add to the ViewPager has sticky headers working.  I have these settings set on my view pager.

```
viewPager.setIsSwipeable(false);
viewPager.setOffscreenPageLimit(3);
```

Do you know what could be causing this? Maybe some static variable?  Even if I create multiple instances of one fragment, only the first one will work.

**Comment by davideas** [comment]
@jonathanyee, I didn't understood if the different fragments are simultaneously visible or they are in the ViewPager.
If you added 2 RV, 2 Adapters and 2 FrameLayouts that host the itemView for sticky headers, one for each RecyclerView. These 2 FrameLayouts have the same `id=sticky_header_container` , maybe you can _Override_ the method `getStickySectionHeadersHolder()` in each of the Adapter and customize the FrameLayout with different `id`.

Or maybe you should put the FrameLayout where the RV is declared, so that each fragment inflates only the same FrameLayout as I did in my demo in `fragment_recycler_view.xml`.

**Comment by jonathanyee** [comment]
Only one fragment is visible at a time as the VIewPager takes up most of the screen.  Both fragments are different, but use the same layout file with the same `sticky_header_container`.

```
<?xml version="1.0" encoding="utf-8"?>
<!--- used by recent contacts and address book -->
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <android.support.v4.widget.SwipeRefreshLayout
        android:id="@+id/swipeContainer"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <android.support.v7.widget.RecyclerView
            android:id="@+id/list"
            android:background="@color/white"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />

    </android.support.v4.widget.SwipeRefreshLayout>

    <!-- needed for FlexibleAdapter sticky headers -->
    <include layout="@layout/sticky_header_layout"/>

    <include
        android:id="@android:id/empty"
        android:visibility="gone"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        layout="@layout/empty_layout" />

    <ProgressBar
        android:id="@+id/progressBar"
        style="?android:attr/progressBarStyleSmall"
        android:layout_width="50dp"
        android:layout_height="50dp"
        android:layout_centerInParent="true"
        android:visibility="gone"/>

    <spokeo.com.spokeomobile.views.OpenSansTextView
        android:id="@+id/progressText"
        android:layout_below="@id/progressBar"
        android:layout_marginTop="10dp"
        android:gravity="center"
        android:layout_centerHorizontal="true"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:textSize="14sp"
        android:text="Loading Connections"
        android:textColor="@color/dark_gray"
        android:visibility="gone"/>

</RelativeLayout>
```

**Comment by jonathanyee** [comment]
So I was able to fix it by adding another frame layout with another id for the sticky header.
