### ISSUE TITLE
Enabling sticky headers may cause illegal state

### ISSUE THREAD

**Issue by masc3d** [davideas/FlexibleAdapter#709]
When adapter is attached and detached quickly in succession, the way sticky headers are initialized may cause (depending on timings)
 ```
IllegalStateException("Adapter is not attached to RecyclerView. Enable sticky headers after setting adapter to RecyclerView.");
```

one resolution would be to synchronize sticky header helper initialization with recycler view attachment / detachment and remove unstable `post` workaround in `setStickyHeaders`.

will you accept PR for this?

**Comment by davideas** [comment]
@masc3d, ok try to create the PR. I will try to find time to check it out. Thanks :-)
