### ISSUE TITLE
Gradle Sync Issue

### ISSUE THREAD

**Issue by Morgazmo** [davideas/FlexibleAdapter#710]
Just trying to build the project and it is falling apart with this error:

Gradle Sync Issues:
ERROR: Cause: de/mannodermaus/gradle/plugins/junit5/tasks/AndroidJUnit5UnitTest$ConfigAction

**Comment by davideas** [comment]
@Morgazmo, which Gradle and Gradle plugin version are you using?

**Comment by davideas** [comment]
I do not have that error. Closing issue.
