### ISSUE TITLE
Footers and Sections and Sticky Footers as a feature?

### ISSUE THREAD

**Issue by droidluv** [davideas/FlexibleAdapter#718]
This is a library I cannot live without but the above mentioned is a feature I sorely miss and have no idea how to implement with the existing sections and headers, it would be great if footers can behave just like headers but in the reverse direction, capability to add footers to sections, expandable footer(items being inserted upwards), sticky footers and I daresay capability to make a header or footer item behave sticky towards to the top and bottom.

Is there anything that I can do to guide myself to extend on this amazing library and add these kind of features?

**Comment by davideas** [comment]
@droidluv, as written in #717 it is enough interesting, but exceeds my effort for this project.
Moreover, the solution applied for sticky headers is just enough for simple use cases: a real layout manager is THE solution.
