### ISSUE TITLE
Support for AsyncLayoutInflater ?

### ISSUE THREAD

**Issue by tomblenz** [davideas/FlexibleAdapter#719]
Please check off the following points BEFORE submitting a new issue / asking support.
- [x] Write a self explanatory Subject.
- [x] Check if the issue has already been raised by someone else (see closed issue).

-------

I've got some heavy layout items in my recyclerview and it'd be really cool if I could do [asynchronous layout inflation](asynclayoutinflater).  Is this something that could reasonably added to the road map for this project?

**Comment by davideas** [comment]
@tomblenz, thank you for your request, but it exceeds the scope of this project and the effort from my side.
