### ISSUE TITLE
Is there some way to get the relative index of a child item within the section?

### ISSUE THREAD

**Issue by hari2109** [davideas/FlexibleAdapter#72]
I want to detect if a current child of a sectioned list is the last item in the section and take some action based on that. 

I was looking for something like `getSectionableIndexOf(position)`

**Comment by davideas** [comment]
@hari2109, maybe you can get the list of section items with `getSectionItems(header)` and then you can retrieve the index of that sectionable item.

Which is your use case because you would take the last item? maybe it could be useful to others as well.

**Comment by hari2109** [comment]
I will initially have a limited set of items in each of my sections, and the last item will have a "View All" button which will load more items in to the section. 

I tried using `getSectionItems(header)` from the `bindViewHolder` method of my sectionable model but it is giving me_OutOfMemoryError_, probably because it's calling a `do...while` loop internally.

**Comment by davideas** [comment]
Sorry, it is my fault, I've reviewed that method now, it was completely wrong, please use the latest SNAPSHOT release for the fixed `getSectionItems()`. I've added also `addItemToSection()` `addSection()` but not tested yet.

But did you consider to use Expandable as a section? it holds subItems maybe you can handle better with addSubItems.

**Comment by hari2109** [comment]
Yeah, I tried with the SNAPSHOT version and it is working fine with the approach you had suggested initially. 
I did consider using an Expandable as a section as it gives more control over children. But I don't need the expandable behaviour, I need all the items visible at all times.
