### ISSUE TITLE
Possibility to unswipe an item

### ISSUE THREAD

**Issue by christophehenry** [davideas/FlexibleAdapter#726]
Unless I'm wrong, there's currently no easy way to unswipe an item after is has been swiped. This limits usages to swipe to dismiss only. There should be a method to reset the item to initial poisition.

Meanwhile, can you indicate me a way to achive this?

**Comment by davideas** [comment]
@christophehenry, this is a know limitation of the Android classes in use, I can't do anything.

**Comment by christophehenry** [comment]
I don't get it. It is possible to manually unswipe the item with the gesture. So it may be possible to control the animate the item, right?

**Comment by christophehenry** [comment]
Ok, I looked at the code. I get where the problem lies. I also found [this solution](https://stackoverflow.com/a/48057827), which looks like a hack but does the trick. Would you consider this solution as a temporary patch?

**Comment by davideas** [comment]
@christophehenry, do you mean `adapter.notifyItemChanged(viewHolder.getAdapterPosition());` ?
I think I've tried, but I do not remember well if the solution was acceptable.
However, yes, you can.

**Comment by christophehenry** [comment]
Yes. I mean that exactly. Even though it feels hacky, it solves my problem. Ok if I add it as a solution to the documentation until that part is rewritten using another class?

**Comment by davideas** [comment]
@christophehenry, no problem, go ahead.

**Comment by christophehenry** [comment]
[Done](https://github.com/davideas/FlexibleAdapter/wiki/5.x-%7C-Drag&Drop-and-Swipe#limitations-1).
