### ISSUE TITLE
Utilisation of IHolder

### ISSUE THREAD

**Issue by maxoreli** [davideas/FlexibleAdapter#75]
Hi,guys.  I found there are about 3 methods for Create/Binding ViewHolders.  
In my implementation i dont want use ViewHolder in model objects because my model class can be used by multiple RecyclerView. I remarked that Method(IHolder) is most suitable case.

So i dont know how to adapt it to my case. Anyone can share me an example of using IHolder.

Thanks in Advance

**Comment by davideas** [comment]
Hello @maxoreli, did you have a look at the Wiki page?
Alternatively you can find an implementation of IHolder item under the package `eu.davidea.samples.flexibleadapter.showcase`. The item is not used yet in the sample, it is just declared.

**Comment by maxoreli** [comment]
yes, I looked at this.  I would know where do I must declare  FlexibleItemHolder ?  Is it in Model or in my Adapter. In this case, onCreatedView and onBindViewHolder of my adapter should be implemented?
And How can I transfer my objects list to FlexibleItemHolder. just a little basic usage of that.

Thanks in Advance. Your help is very appreciated.

**Comment by davideas** [comment]
The Adapter signature is ok.
To answer at your question, you can add the Model object to the Holder item using a custom constructor, basically you don't need a set method, so in that case the model object inside will be never null.

The creation and binding of the view in the Adapter remain an option. I suggest to use this classic style method if you have 1 type of view.
