### ISSUE TITLE
Disable swipe by row type

### ISSUE THREAD

**Issue by mdtuyen** [davideas/FlexibleAdapter#80]
I enabled swipe to delete item, but with some row on a head or expanable header I don't want wipe for it. Please help me a solution.

**Comment by davideas** [comment]
Hello, I have already checked that this is possible, and it was already planned to implement. I will try to add this new feature on next util build.
Thanks for the comment.

**Comment by davideas** [comment]
There are 2 ways to make an item Draggable or Swipeable:
- Using the item interface: call `setDraggable()` and `setSwipeable()`, in the constructor or in the binding depends by yours use case.
- Alternatively, override the 2 methods `isDraggable()`, `isSwipeable()` inside the `FlexibleViewHolder` to return always true.

By default items are NOT Draggable nor Swipeable.

This feature will be published in the next SNAPSHOT and next release.

**Comment by mdtuyen** [comment]
Thanks for your help,

I need a power recyclerview for my project. FlexibleAdapter is a best for me.
Thanks a gain.
