### ISSUE TITLE
SwipeRefreshLayout position is under stickerheader

### ISSUE THREAD

**Issue by mdtuyen** [davideas/FlexibleAdapter#83]
When I enable swipe to refresh SwipeRefreshLayout showed but It is under StickerHeader. It should be    front of StickerHeader.

**Comment by davideas** [comment]
This has a drawback on dragging, they are not compatible!!! Dragging down, it start the refresh...
I added a comment, in the layout, that imported Layout for StickyHeader cannot be inserted in the SwipeToRefresh if ALSO user wants dragging feature.
