### ISSUE TITLE
Bug onLoadMore InstagramItem layout changes

### ISSUE THREAD

**Issue by yilzer** [davideas/FlexibleAdapter#84]
![screenshot_2016-05-16-10-45-11](https://cloud.githubusercontent.com/assets/7904887/15287218/a6822048-1b61-11e6-846e-1ba7ae0609f2.png)

When I want to load more items and scroll down the layout changes, look at image above, as a result of this the sticky headers won't work at this moment. Sometimes i get this when i load more images in the feed and sometimes when i refresh the sticky headers don't work anymore. 

It looks like there is a layout behind the feed that hangs there while you scroll in the feed. It's not that the instagram item changes but the background behind the items changes with one item that sticks there and gives a look like the image above. You see this one item in the background only at the comments area.

**Comment by davideas** [comment]
@yilzer, it happened to me only once, I can say that it is (very) rare, but I can't find a way to reproduce it systematically and I don't find the single cause. I used emulator and real phone as well, but nothing.

So, I don't know where to look into, however it is related to the technique used for the sticky headers.

**Comment by davideas** [comment]
@yilzer, actually this issue should be resolved with the solution provided in #92.
