### ISSUE TITLE
Do you have a plan to implement Index for this library ?

### ISSUE THREAD

**Issue by mdtuyen** [davideas/FlexibleAdapter#89]
I see that Index is a special feature use for recyclerview, it could be implement to adapter. Do you have a plan for that ?

**Comment by davideas** [comment]
Hello @mdtuyen, what is "Index" special feature in RV?

**Comment by mdtuyen** [comment]
yes, indexablerecyclerview. That is a vertical bar contain index for each group item by first character of string item in recyclerview. You can see it in contact list of android or ios.

**Comment by davideas** [comment]
I made a research, _IndexableRecyclerView_ is a custom RV. There are several implementations.
You are referring to this implementation? https://github.com/xhnwsw520/IndexableRecyclerView

I think it should be compatible, you can extend `FlexibleAdapter` and add that feature.
I will check later if I can add an example with the `SectionIndexer` interface as it was for ListView. Or if you want you can pull request a new example for the demo app.
