### ISSUE TITLE
[5.0.0-b6] Sticky headers become not sticky when soft keyboard is visible

### ISSUE THREAD

**Issue by vverbitskyy** [davideas/FlexibleAdapter#90]
Hi.
I tried to use yours library and it's pretty good.
But i had an issue with sticky header at the next situation:
I have adapter with items
[view_type1]
[sticky header]
[view_type2]
[view_type2]
[view_type2]
etc [view_type2]
When i set android:windowSoftInputMode="adjustPan" and work with keyboard, if i scroll content
above keyboard, sticky header is scrolling too with the rest of content.

Maybe I am doing smth. wrong?

**Comment by davideas** [comment]
Hello @vverbitskyy, SoftInputMode is not in the scope of this library.
I never tried using adjustPan, so don't know how it behaves.
I think you don't need sticky functionality when using keyboard, there's very limited space, also in tablet.

**Comment by davideas** [comment]
Hello @vverbitskyy, now I remember, it's not the `adjustPan`: I explicitly disable the sticky functionality to avoid the crash, as from the bugs you see currently opened. The technique used for the sticky functionality is not fully compatible when removing items, and filtering is one of the case.

**Comment by vverbitskyy** [comment]
@davideas u are not right. I have test it with a version, where sticky functionality is available.
It works, but when keyboard appear in adjustPan, sticky become inactive, but when keyboard become
hidden, sticky header continue work.

**Comment by davideas** [comment]
In my example I use fragment, if I set `adjustPan` to the mainActivity, nothing changes to the sticky headers, I use _Headers and Sections_ fragment example.
How can I reproduce it?

**Comment by mdtuyen** [comment]
Yes, your example use fragment however you make all delegate in main activity. I think it is better if you put them in a abstract fragment as AbstractFragment in your example. Because in activity we can use many type fragment ( with recyclerview or not)

**Comment by vverbitskyy** [comment]
@davideas i will provide you an exemaple today

**Comment by vverbitskyy** [comment]
Here are some changes. Just install it and you will see.

[flexible-adapter-app.zip](https://github.com/davideas/FlexibleAdapter/files/291922/flexible-adapter-app.zip)

**Comment by davideas** [comment]
@vverbitskyy, I've tried, I see at the moment I found only this possible solution, can you try and see if you like the effect and sticky header remains? http://stackoverflow.com/a/18923547/3397345

We can't do much because the `adjustPan` move the content until the focused editText is visible on the top of the keyboard.
Maybe you can put the edit text on the top of the RV?

**Comment by vverbitskyy** [comment]
@davideas I will try solution that you attached and give you an answer.

"Maybe you can put the edit text on the top of the RV?" unfortunately no, cause my screen is some kind of chat, so i can't put it at the top of RV
