### ISSUE TITLE
Is there a possibility to set available swipe type?

### ISSUE THREAD

**Issue by vverbitskyy** [davideas/FlexibleAdapter#91]
For example, I need my adapter item can swipe right only, but I can't set it to ItemTouchHelperCallback, cause it's private. So can I do it in another way?

**Comment by davideas** [comment]
From the current SNAPSHOT only (I forgot to mention the new function I do it now).
Call `getItemTouchHelperCallback().setSwipeFlags(int flags)`. See the method comment for more details.

**Comment by vverbitskyy** [comment]
@davideas good job. thanks
