### ISSUE TITLE
Disable item animation

### ISSUE THREAD

**Issue by carmas123** [davideas/FlexibleAdapter#93]
There is method to disable all item adding or removing animation?

**Comment by davideas** [comment]
@carmas123, do you mean disable it at runtime?
Call `setAnimationOnScrolling()` to enable/disable all scrolling directions or `setAnimationOnReverseScrolling()` to animate also backward scrolling.

At design time, don't call the method `animateView()`.

**Comment by davideas** [comment]
@carmas123, can we close this issue?

**Comment by davideas** [comment]
All item change animations are done with ItemAnimators, however that must be customized and improved to be coherent with scrolling animation, a change request to improve this behavior was opened by me months ago (issue 27).
