### ISSUE TITLE
[5.0.0-b6] Item does not updated after updateDataSet()

### ISSUE THREAD

**Issue by vverbitskyy** [davideas/FlexibleAdapter#94]
Think there is an issue at the method 
``` java
protected void applyAndAnimateAdditions(List<T> from, List<T> newItems) {
		int out = 0;
		for (int i = 0, count = newItems.size(); i < count; i++) {
			final T item = newItems.get(i);
			if (!from.contains(item)) {
				if (DEBUG) Log.v(TAG, "animateAdditions  add position=" + i + " item=" + item);
				from.add(i, item);
				notifyItemInserted(i);
			} else if (mNotifyChangeOfUnfilteredItems) {
				out++;
				notifyItemChanged(i, mNotifyChangeOfUnfilteredItems);
				if (DEBUG) Log.v(TAG, "animateAdditions keep position=" + i + " item=" + item);
			}
		}
		if (DEBUG) Log.v(TAG, "animateAdditions total out=" + out + " in=" + newItems.size());
}
```

so if old array does not contains item, you add it and notify adapter, otherwise you just notifying that item was updated, but from list does not receive that updated item. Think needs to call smth. like from.set(i, item) before calling notifyItemChanged(i, mNotifyChangeOfUnfilteredItems);

**Comment by davideas** [comment]
@vverbitskyy, at the beginning this method was used only for filtering purpose, than I saw that could be used also for any update, but I think you could be right. To be sincere I did not test `updateDataSet()` when items are modified from code.
I will check and eventually modify it.
