### ISSUE TITLE
Ability to remove endless scrolling

### ISSUE THREAD

**Issue by vverbitskyy** [davideas/FlexibleAdapter#97]
Please, add an ability to disable endless scrolling, when it's need.
I have an issue, when I call adapter.updateItem(...) element with last position,
RV automatically scrolls up on 1 element (element that was updated becomes invisible).
I have investigate this. Think that the reason is that after updating, onLoadMore called and
I need to load more data. At that moment there are no more data at the server, so i just calling
onLoadMoreCompleted(null) and at that moment, RV scrolls up by 1 element

**Comment by vverbitskyy** [comment]
Sry. I have done it at my subclass of FlexibleAdapter

**Comment by davideas** [comment]
@vverbytskyi, Please be aware that, Endless Scrolling is going to be changed very soon. In order to support the new features and a better logic, the behaviors and callbacks methods will be refactored.

Please check issue #233 for the latest developments.
