### ISSUE TITLE
Custom swipe layout 

### ISSUE THREAD

**Issue by mdtuyen** [davideas/FlexibleAdapter#98]
I want to custom swipe layout as this library [SwipeMenu](https://github.com/TUBB/SwipeMenu)

That mean, I can swipe lef, right, top, bottom and still show a part of frontview when swipe. How to implement it ?

**Comment by davideas** [comment]
@mdtuyen, I tried, it is not technically possible with the `ItemTouchHelper` at our disposal.
This is a point to review and improve, but not soon. It must be something custom as that library.
Difficult to say that it can be part of an Adapter.

**Comment by davideas** [comment]
Another nice alternative could be https://github.com/chthai64/SwipeRevealLayout.

**Comment by tspoke** [comment]
I was looking for a way to implement swipe with FlexibleAdapter. I tried your solution (SwipeRevealLayout), but I needed 2 sides swipe. 

I found a cool library, with no adapter change : https://github.com/rambler-digital-solutions/swipe-layout-android
