### ISSUE TITLE
setEndlessScrollListener problem

### ISSUE THREAD

**Issue by carmas123** [davideas/FlexibleAdapter#99]
I've a custom FlexibleAdapter and I need to use endless scroll, but using setEndlessScrollListener I see that it need same Item type.
Because this is a particulat element into RecyclerView please can you handle the ProgressItem as special and not inheriting it from Adapter Item type?

**Comment by davideas** [comment]
@carmas123, can you explain better? because progressItem is a different type treated as "footerView" with different layout, so it also must be added and removed from the list as item. This is done automatically by the Adapter.

**Comment by carmas123** [comment]
I've an advanced Flexible Item with some properties and I don't want repliacete it on Progress Item

**Comment by davideas** [comment]
@carmas123, sorry, can you explain better your idea?
What do you mean with "not inheriting it from Adapter Item type"? "I don't want replace it on Progress Item"?

**Comment by carmas123** [comment]
ok.
The proble is that if I've adapters like this (I wrote in Kotlin):

class MyAdapter1(context: Context, list: MutableList<TtemGeneric1>) : FlexibleAdapter(context: Context, list)

class MyAdapter2(context: Context, list: MutableList<TtemGeneric2>) : FlexibleAdapter(context: Context, list)

class MyAdapter3(context: Context, list: MutableList<TtemGeneric3>) : FlexibleAdapter(context: Context, list)

To use endless functionality I need to create a progress item for each adapter who do nothing because are all equals.

**Comment by davideas** [comment]
@carmas123, I think you can pass the same progress item for each of them. Why you have to create different items? I continue to not understand :-)

**Comment by carmas123** [comment]
Because my Adapter use Generics  FlexibleAdapter<TMyClassItem> and when I call method setEndlessScrollListener(myFragment, !!! here is needed an item with TMyClassItem !!! )

**Comment by davideas** [comment]
`mItems` is declared to accept type **T**, what you are asking is not possible.
I cannot treat ProgressItem as special and it must be part of Adapter Item type **T**

So you want that `mItems` accepts `IFlexible` types? I don't know if I can, it has a big impact in theory.

**Comment by carmas123** [comment]
I imagined :)
So, thank you so much for all you replies.

A few days ago I ask you to separate InitilizeItems, do you have some news about it?

**Comment by davideas** [comment]
Separating the expand initialization can be done, but then user has to explicitly call the initialization and it's not automatic anymore. I reopened the other issue.

**Comment by davideas** [comment]
@carmas123, please be aware that, Endless Scrolling is going to be changed very soon. In order to support the new features and a better logic, the behaviors and callbacks methods will be refactored.

Please check issue #233 for the latest developments.
